from typing import Dict, List, Optional, Protocol, Tuple

from digital_twin.modules.accounts.contracts import WatchlistAccount
from digital_twin.shared_kernel.events import DomainEvent


class AccountWatchlistRepository(Protocol):
    def load_saved(self) -> List[WatchlistAccount]: ...
    def load_all(self) -> List[WatchlistAccount]: ...
    def watchlist_items(self, account_id: str) -> List[Dict[str, object]]: ...
    def mutate_watchlist(self, account_id: str, action: str, symbols: List[str]) -> Tuple[List[str], Optional[DomainEvent]]: ...
