"""Explicit, lazy contracts surface for the decisions module."""

from digital_twin.modules._exports import resolve_export


_EXPORTS = {'compact_decision_continuity_packet': ('digital_twin.modules.decisions.domain.decision_continuity',
                                        'compact_decision_continuity_packet')}

_EXPORTS['DecisionEpisodeRepository'] = ('digital_twin.modules.decisions.domain.repositories', 'DecisionEpisodeRepository')


_EXPORTS.update({
    'ABSTAIN': ('digital_twin.modules.decisions.domain.investment_reasoning.subject_case', 'ABSTAIN'),
    'ACTION_LABELS': ('digital_twin.modules.decisions.domain.notification_ai_gate_contracts', 'ACTION_LABELS'),
    'AIJudgmentResult': ('digital_twin.modules.decisions.domain.investment_reasoning.contracts', 'AIJudgmentResult'),
    'AI_DECISION_CONTRACT_VERSION': ('digital_twin.modules.decisions.domain.notification_ai_prompt_release', 'AI_DECISION_CONTRACT_VERSION'),
    'AI_DECISION_PROMPT_VERSION': ('digital_twin.modules.decisions.domain.notification_ai_prompt_release', 'AI_DECISION_PROMPT_VERSION'),
    'ARCHIVE': ('digital_twin.modules.decisions.domain.investment_reasoning.dispatch', 'ARCHIVE'),
    'CASE_AI_COMPLETED': ('digital_twin.modules.decisions.domain.investment_reasoning.case', 'CASE_AI_COMPLETED'),
    'CASE_AI_PENDING': ('digital_twin.modules.decisions.domain.investment_reasoning.case', 'CASE_AI_PENDING'),
    'CASE_BLOCKED': ('digital_twin.modules.decisions.domain.investment_reasoning.case', 'CASE_BLOCKED'),
    'CASE_COMPLETED': ('digital_twin.modules.decisions.domain.investment_reasoning.case', 'CASE_COMPLETED'),
    'CASE_CREATED': ('digital_twin.modules.decisions.domain.investment_reasoning.case', 'CASE_CREATED'),
    'CASE_DECISION_SYNTHESIZED': ('digital_twin.modules.decisions.domain.investment_reasoning.case', 'CASE_DECISION_SYNTHESIZED'),
    'CASE_DEFERRED': ('digital_twin.modules.decisions.domain.investment_reasoning.case', 'CASE_DEFERRED'),
    'CASE_EXPIRED': ('digital_twin.modules.decisions.domain.investment_reasoning.case', 'CASE_EXPIRED'),
    'CASE_FAILED': ('digital_twin.modules.decisions.domain.investment_reasoning.case', 'CASE_FAILED'),
    'CASE_HYPOTHESES_READY': ('digital_twin.modules.decisions.domain.investment_reasoning.case', 'CASE_HYPOTHESES_READY'),
    'CASE_INFERENCE_COMPLETED': ('digital_twin.modules.decisions.domain.investment_reasoning.case', 'CASE_INFERENCE_COMPLETED'),
    'CASE_INPUT_READY': ('digital_twin.modules.decisions.domain.investment_reasoning.case', 'CASE_INPUT_READY'),
    'CASE_PUBLISHED': ('digital_twin.modules.decisions.domain.investment_reasoning.case', 'CASE_PUBLISHED'),
    'CASE_SUPERSEDED': ('digital_twin.modules.decisions.domain.investment_reasoning.case', 'CASE_SUPERSEDED'),
    'CASE_SUPPRESSED': ('digital_twin.modules.decisions.domain.investment_reasoning.case', 'CASE_SUPPRESSED'),
    'CASE_TERMINAL_STAGES': ('digital_twin.modules.decisions.domain.investment_reasoning.case', 'CASE_TERMINAL_STAGES'),
    'CASE_VALIDATED': ('digital_twin.modules.decisions.domain.investment_reasoning.case', 'CASE_VALIDATED'),
    'CONTEXT_OBSERVATION': ('digital_twin.modules.decisions.domain.investment_reasoning.disposition', 'CONTEXT_OBSERVATION'),
    'DecisionAbstention': ('digital_twin.modules.decisions.domain.investment_reasoning.subject_case', 'DecisionAbstention'),
    'DecisionDelta': ('digital_twin.modules.decisions.domain.investment_reasoning.decision_delta', 'DecisionDelta'),
    'DecisionEpisode': ('digital_twin.modules.decisions.domain.investment_brain', 'DecisionEpisode'),
    'DecisionSynthesis': ('digital_twin.modules.decisions.domain.investment_reasoning.contracts', 'DecisionSynthesis'),
    'FINAL_DECISION': ('digital_twin.modules.decisions.domain.investment_reasoning.subject_case', 'FINAL_DECISION'),
    'FactDelta': ('digital_twin.modules.decisions.domain.investment_reasoning.contracts', 'FactDelta'),
    'FinalDecision': ('digital_twin.modules.decisions.domain.investment_reasoning.contracts', 'FinalDecision'),
    'GraphHypothesisManager': ('digital_twin.modules.decisions.domain.investment_reasoning.hypotheses', 'GraphHypothesisManager'),
    'HANDOFF_AI': ('digital_twin.modules.decisions.domain.investment_reasoning.dispatch', 'HANDOFF_AI'),
    'HYPOTHESIS_QUALIFICATION_PENDING': ('digital_twin.modules.decisions.domain.investment_reasoning.disposition', 'HYPOTHESIS_QUALIFICATION_PENDING'),
    'INVALID': ('digital_twin.modules.decisions.domain.investment_reasoning.dispatch', 'INVALID'),
    'InferenceDispatchDecision': ('digital_twin.modules.decisions.domain.investment_reasoning.dispatch', 'InferenceDispatchDecision'),
    'InferenceResult': ('digital_twin.modules.decisions.domain.investment_reasoning.contracts', 'InferenceResult'),
    'InvestmentQuestion': ('digital_twin.modules.decisions.domain.investment_brain', 'InvestmentQuestion'),
    'LearningProposal': ('digital_twin.modules.decisions.domain.investment_brain', 'LearningProposal'),
    'MESSAGE_START_BADGE': ('digital_twin.modules.decisions.domain.notification_ai_gate_contracts', 'MESSAGE_START_BADGE'),
    'NO_MATERIAL_PREDICTIVE_RULE_MATCH': ('digital_twin.modules.decisions.domain.investment_reasoning.disposition', 'NO_MATERIAL_PREDICTIVE_RULE_MATCH'),
    'NotificationAIValidatedResponse': ('digital_twin.modules.decisions.domain.notification_ai_gate_contracts', 'NotificationAIValidatedResponse'),
    'NovelHypothesisProposal': ('digital_twin.modules.decisions.domain.investment_brain', 'NovelHypothesisProposal'),
    'OBSERVATION': ('digital_twin.modules.decisions.domain.investment_reasoning.subject_case', 'OBSERVATION'),
    'PUBLISH_TYPEDB': ('digital_twin.modules.decisions.domain.investment_reasoning.dispatch', 'PUBLISH_TYPEDB'),
    'REVIEW_ONLY': ('digital_twin.modules.decisions.domain.investment_reasoning.subject_case', 'REVIEW_ONLY'),
    'RULE_COVERAGE_GAP_CANDIDATE': ('digital_twin.modules.decisions.domain.investment_reasoning.disposition', 'RULE_COVERAGE_GAP_CANDIDATE'),
    'ReasoningCase': ('digital_twin.modules.decisions.domain.investment_reasoning.case', 'ReasoningCase'),
    'RuleEvaluationRecord': ('digital_twin.modules.decisions.domain.investment_reasoning.contracts', 'RuleEvaluationRecord'),
    'RuleMatchProof': ('digital_twin.modules.decisions.domain.investment_reasoning.contracts', 'RuleMatchProof'),
    'SUBJECT_ABSTAINED': ('digital_twin.modules.decisions.domain.investment_reasoning.subject_case', 'SUBJECT_ABSTAINED'),
    'SUBJECT_AI_COMPLETED': ('digital_twin.modules.decisions.domain.investment_reasoning.subject_case', 'SUBJECT_AI_COMPLETED'),
    'SUBJECT_AI_PENDING': ('digital_twin.modules.decisions.domain.investment_reasoning.subject_case', 'SUBJECT_AI_PENDING'),
    'SUBJECT_BLOCKED': ('digital_twin.modules.decisions.domain.investment_reasoning.subject_case', 'SUBJECT_BLOCKED'),
    'SUBJECT_OBSERVATION': ('digital_twin.modules.decisions.domain.investment_reasoning.subject_case', 'SUBJECT_OBSERVATION'),
    'SUBJECT_PUBLISHED': ('digital_twin.modules.decisions.domain.investment_reasoning.subject_case', 'SUBJECT_PUBLISHED'),
    'SUBJECT_READY': ('digital_twin.modules.decisions.domain.investment_reasoning.subject_case', 'SUBJECT_READY'),
    'SUBJECT_REVIEW_ONLY': ('digital_twin.modules.decisions.domain.investment_reasoning.subject_case', 'SUBJECT_REVIEW_ONLY'),
    'SUBJECT_SUPPRESSED': ('digital_twin.modules.decisions.domain.investment_reasoning.subject_case', 'SUBJECT_SUPPRESSED'),
    'SUBJECT_VALIDATED': ('digital_twin.modules.decisions.domain.investment_reasoning.subject_case', 'SUBJECT_VALIDATED'),
    'SUPPRESSED': ('digital_twin.modules.decisions.domain.investment_reasoning.subject_case', 'SUPPRESSED'),
    'StrategyModel': ('digital_twin.modules.decisions.domain.strategy', 'StrategyModel'),
    'SubjectDecisionCase': ('digital_twin.modules.decisions.domain.investment_reasoning.subject_case', 'SubjectDecisionCase'),
    '_driver_rows': ('digital_twin.modules.decisions.domain.notification_ai_gate_validation', '_driver_rows'),
    '_line_after_colon': ('digital_twin.modules.decisions.domain.notification_ai_gate_text', '_line_after_colon'),
    '_number': ('digital_twin.modules.decisions.domain.notification_ai_gate_text', '_number'),
    '_raw_lines': ('digital_twin.modules.decisions.domain.notification_ai_gate_text', '_raw_lines'),
    '_text': ('digital_twin.modules.decisions.domain.notification_ai_gate_text', '_text'),
    'action_label_for_target': ('digital_twin.modules.decisions.domain.notification_ai_gate_validation', 'action_label_for_target'),
    'active_rule_items': ('digital_twin.modules.decisions.domain.notification_ai_context', 'active_rule_items'),
    'ai_gate_enabled_for_message_type': ('digital_twin.modules.decisions.domain.notification_ai_gate_contracts', 'ai_gate_enabled_for_message_type'),
    'ai_insight_handoff': ('digital_twin.modules.decisions.domain.investment_reasoning.ai_insight', 'ai_insight_handoff'),
    'all_source_urls_for_context': ('digital_twin.modules.decisions.domain.notification_ai_gate_sources', 'all_source_urls_for_context'),
    'append_unique_text': ('digital_twin.modules.decisions.domain.notification_ai_gate_text', 'append_unique_text'),
    'assess_prompt_evidence': ('digital_twin.modules.decisions.domain.prompt_evidence_admission', 'assess_prompt_evidence'),
    'attach_prompt_evidence_admission': ('digital_twin.modules.decisions.domain.prompt_evidence_admission', 'attach_prompt_evidence_admission'),
    'canonical_investment_timestamp': ('digital_twin.modules.decisions.domain.investment_brain', 'canonical_investment_timestamp'),
    'criterion_lines': ('digital_twin.modules.decisions.domain.notification_ai_context', 'criterion_lines'),
    'customer_visible_ai_text': ('digital_twin.modules.decisions.domain.notification_ai_gate_text', 'customer_visible_ai_text'),
    'decision_comparison_state': ('digital_twin.modules.decisions.domain.decision_integrity', 'decision_comparison_state'),
    'decision_data_gaps_from_relation_context': ('digital_twin.modules.decisions.domain.investment_reasoning.synthesis', 'decision_data_gaps_from_relation_context'),
    'decision_episode_from_context': ('digital_twin.modules.decisions.domain.investment_brain', 'decision_episode_from_context'),
    'decision_episode_ontology_context': ('digital_twin.modules.decisions.domain.investment_brain', 'decision_episode_ontology_context'),
    'decision_for_position': ('digital_twin.modules.decisions.domain.strategy', 'decision_for_position'),
    'decision_synthesis_from_relation_context': ('digital_twin.modules.decisions.domain.investment_reasoning.synthesis', 'decision_synthesis_from_relation_context'),
    'decisions_for_positions': ('digital_twin.modules.decisions.domain.strategy', 'decisions_for_positions'),
    'delivery_level_from_context': ('digital_twin.modules.decisions.domain.notification_ai_gate_validation', 'delivery_level_from_context'),
    'disposition_code_from_context': ('digital_twin.modules.decisions.domain.investment_reasoning.disposition', 'disposition_code_from_context'),
    'enrich_notification_ai_context': ('digital_twin.modules.decisions.domain.notification_ai', 'enrich_notification_ai_context'),
    'event_strategy_guidance': ('digital_twin.modules.decisions.domain.investment_strategy_guidance', 'event_strategy_guidance'),
    'event_type_guidance': ('digital_twin.modules.decisions.domain.investment_strategy_guidance', 'event_type_guidance'),
    'hypothesis_set_evidence_summary': ('digital_twin.modules.decisions.domain.decision_evidence_contract', 'hypothesis_set_evidence_summary'),
    'hypothesis_set_from_relation_context': ('digital_twin.modules.decisions.domain.investment_brain', 'hypothesis_set_from_relation_context'),
    'inference_evidence_assertions': ('digital_twin.modules.decisions.domain.decision_evidence_assertion', 'inference_evidence_assertions'),
    'inference_required_relation_context': ('digital_twin.modules.decisions.domain.strategy', 'inference_required_relation_context'),
    'investment_decision_actionability': ('digital_twin.modules.decisions.domain.investment_decision_actionability', 'investment_decision_actionability'),
    'is_concrete_observable_condition': ('digital_twin.modules.decisions.domain.investment_decision_actionability', 'is_concrete_observable_condition'),
    'is_graph_backed_relation_context': ('digital_twin.modules.decisions.domain.notification_ai_context', 'is_graph_backed_relation_context'),
    'is_watchlist_context': ('digital_twin.modules.decisions.domain.notification_ai_context', 'is_watchlist_context'),
    'local_validated_ai_response': ('digital_twin.modules.decisions.domain.notification_ai_gate_validation', 'local_validated_ai_response'),
    'merge_strategy_context': ('digital_twin.modules.decisions.domain.investment_strategy_guidance', 'merge_strategy_context'),
    'notification_ai_execution_profile': ('digital_twin.modules.decisions.domain.notification_ai_decision_brief', 'notification_ai_execution_profile'),
    'notification_ai_prompt_context': ('digital_twin.modules.decisions.domain.notification_ai', 'notification_ai_prompt_context'),
    'parse_investment_timestamp': ('digital_twin.modules.decisions.domain.investment_brain', 'parse_investment_timestamp'),
    'persisted_decision_authorization': ('digital_twin.modules.decisions.domain.investment_decision_actionability', 'persisted_decision_authorization'),
    'previous_decision_episode_value': ('digital_twin.modules.decisions.domain.investment_decision_history', 'previous_decision_episode_value'),
    'publication_for_subject_case': ('digital_twin.modules.decisions.domain.investment_reasoning.subject_case', 'publication_for_subject_case'),
    'reasoning_case_decision_episode_id': ('digital_twin.modules.decisions.domain.investment_brain', 'reasoning_case_decision_episode_id'),
    'reasoning_disposition_delivery': ('digital_twin.modules.decisions.domain.investment_reasoning.disposition', 'reasoning_disposition_delivery'),
    'reasoning_disposition_requires_ai': ('digital_twin.modules.decisions.domain.investment_reasoning.disposition', 'reasoning_disposition_requires_ai'),
    'reasoning_rule_inventory': ('digital_twin.modules.decisions.domain.investment_reasoning.rule_inventory', 'reasoning_rule_inventory'),
    'reconciliation_after_delivery': ('digital_twin.modules.decisions.domain.investment_reasoning.ai_insight', 'reconciliation_after_delivery'),
    'reference_date': ('digital_twin.modules.decisions.domain.notification_ai_gate_text', 'reference_date'),
    'relation_context_value': ('digital_twin.modules.decisions.domain.notification_ai_context', 'relation_context_value'),
    'relation_facts': ('digital_twin.modules.decisions.domain.notification_ai_context', 'relation_facts'),
    'rule_evaluation_records_from_projection_results': ('digital_twin.modules.decisions.domain.investment_reasoning.contracts', 'rule_evaluation_records_from_projection_results'),
    'scoped_decision_follow_ups': ('digital_twin.modules.decisions.domain.investment_brain', 'scoped_decision_follow_ups'),
    'source_detail_map': ('digital_twin.modules.decisions.domain.notification_ai_gate_sources', 'source_detail_map'),
    'source_detail_text': ('digital_twin.modules.decisions.domain.notification_ai_gate_sources', 'source_detail_text'),
    'stable_id': ('digital_twin.modules.decisions.domain.investment_brain', 'stable_id'),
    'strategy_message_lines': ('digital_twin.modules.decisions.domain.investment_strategy_guidance', 'strategy_message_lines'),
    'target_text': ('digital_twin.modules.decisions.domain.investment_strategy_guidance', 'target_text'),
    'ungrounded_narrative_numbers': ('digital_twin.modules.decisions.domain.narrative_numeric_grounding', 'ungrounded_narrative_numbers'),
    'user_friendly_ai_text': ('digital_twin.modules.decisions.domain.notification_ai_gate_text', 'user_friendly_ai_text'),
    'utc_now_iso': ('digital_twin.modules.decisions.domain.investment_brain', 'utc_now_iso'),
    'validate_decision_episode_integrity': ('digital_twin.modules.decisions.domain.decision_integrity', 'validate_decision_episode_integrity'),
    'watchlist_friendly_text': ('digital_twin.modules.decisions.domain.notification_ai_gate_validation', 'watchlist_friendly_text'),
})

__all__ = list(_EXPORTS)


def __getattr__(name):
    return resolve_export(__name__, _EXPORTS, name)
