from dataclasses import asdict, dataclass
from typing import Dict, List, Optional


@dataclass(frozen=True)
class TBoxBoundedContext:
    key: str
    label: str
    description: str


@dataclass(frozen=True)
class TBoxClassDef:
    name: str
    bounded_context: str
    label: str = ""
    parent: str = ""
    description: str = ""


@dataclass(frozen=True)
class TBoxRelationDef:
    name: str
    bounded_context: str
    source_context: str = ""
    target_context: str = ""
    description: str = ""


@dataclass(frozen=True)
class TBoxRuleDef:
    text: str
    bounded_context: str
    description: str = ""


BOUNDED_CONTEXTS: List[TBoxBoundedContext] = [
    TBoxBoundedContext(
        "investment-core",
        "투자 핵심",
        "계좌, 포트폴리오, 투자 대상, 보유/관심 상태, 현금과 노출을 정의합니다.",
    ),
    TBoxBoundedContext(
        "observation-data",
        "관측 데이터",
        "가격, 수급, 기술 지표, 외부 이벤트, 데이터 출처와 신선도를 정의합니다.",
    ),
    TBoxBoundedContext(
        "strategy-thesis",
        "전략 가설",
        "투자 가설, 진입/청산/리밸런싱/비중 규칙과 기존 모델 점수의 역할을 정의합니다.",
    ),
    TBoxBoundedContext(
        "risk-exposure",
        "리스크 노출",
        "시장, 유동성, 집중, 통화, 이벤트, 데이터 품질, 모델, 실행 리스크를 분류합니다.",
    ),
    TBoxBoundedContext(
        "reasoning-insight",
        "추론 인사이트",
        "신호, 근거, 판단 근거, 의견, 모순, 기회, 인사이트와 AI 리뷰를 정의합니다.",
    ),
    TBoxBoundedContext(
        "operations-dispatch",
        "운영과 알림",
        "데이터 수집, 분석 실행, 추론 주기, 알림 디스패치와 억제 정책을 정의합니다.",
    ),
]


CLASS_DEFS: List[TBoxClassDef] = [
    TBoxClassDef("Portfolio", "investment-core", "포트폴리오", description="투자 계좌의 전체 자산과 노출 집합입니다."),
    TBoxClassDef("Account", "investment-core", "계좌", description="데이터와 주문 권한이 연결되는 투자 계좌입니다."),
    TBoxClassDef("Instrument", "investment-core", "투자 대상", description="주식, ETF, 크립토, 현금성 자산 등 투자 가능한 대상입니다."),
    TBoxClassDef("Company", "investment-core", "회사", description="증권을 발행하고 뉴스·공시·실세계 노출의 주체가 되는 법인입니다."),
    TBoxClassDef("Security", "investment-core", "증권", parent="Instrument", description="회사가 발행한 거래 가능 증권입니다."),
    TBoxClassDef("Equity", "investment-core", "주식", parent="Instrument"),
    TBoxClassDef("ETF", "investment-core", "ETF", parent="Instrument"),
    TBoxClassDef("CryptoAsset", "investment-core", "크립토 자산", parent="Instrument"),
    TBoxClassDef("CashAsset", "investment-core", "현금성 자산", parent="Instrument"),
    TBoxClassDef("Derivative", "investment-core", "파생상품", parent="Instrument"),
    TBoxClassDef("Index", "investment-core", "지수", parent="Instrument"),
    TBoxClassDef("FXPair", "investment-core", "환율쌍", parent="Instrument"),
    TBoxClassDef("Stock", "investment-core", "종목", parent="Equity"),
    TBoxClassDef("Position", "investment-core", "포지션", description="보유 또는 관찰 중인 투자 대상의 계좌상 행입니다."),
    TBoxClassDef("Watchlist", "investment-core", "관심 목록"),
    TBoxClassDef("WatchlistCandidate", "investment-core", "관심 후보", parent="Position"),
    TBoxClassDef("Sector", "investment-core", "섹터"),
    TBoxClassDef("Industry", "investment-core", "산업"),
    TBoxClassDef("PeerGroup", "investment-core", "피어 그룹"),
    TBoxClassDef("Market", "investment-core", "시장"),
    TBoxClassDef("Currency", "investment-core", "통화"),
    TBoxClassDef("Cash", "investment-core", "대기 현금", parent="CashAsset"),
    TBoxClassDef("MarketExposure", "investment-core", "시장 노출"),
    TBoxClassDef("Observation", "observation-data", "관측값", description="특정 시점과 출처에서 들어온 사실입니다."),
    TBoxClassDef("FactChange", "observation-data", "사실 변경", parent="Observation"),
    TBoxClassDef("PriceObservation", "observation-data", "가격 관측", parent="Observation"),
    TBoxClassDef("VolumeObservation", "observation-data", "거래량 관측", parent="Observation"),
    TBoxClassDef("TechnicalObservation", "observation-data", "기술 지표 관측", parent="Observation"),
    TBoxClassDef("FlowObservation", "observation-data", "수급 관측", parent="Observation"),
    TBoxClassDef("FundamentalObservation", "observation-data", "펀더멘털 관측", parent="Observation"),
    TBoxClassDef("ExternalObservation", "observation-data", "외부 관측", parent="Observation"),
    TBoxClassDef("PriceMetric", "observation-data", "가격 지표", parent="PriceObservation"),
    TBoxClassDef("TechnicalIndicator", "observation-data", "기술 지표", parent="TechnicalObservation"),
    TBoxClassDef("TradeFlow", "observation-data", "거래/수급", parent="FlowObservation"),
    TBoxClassDef("DataQuality", "observation-data", "데이터 품질", parent="Observation"),
    TBoxClassDef("DataSource", "observation-data", "데이터 출처"),
    TBoxClassDef("DataFreshness", "observation-data", "데이터 신선도"),
    TBoxClassDef("DataLatency", "observation-data", "데이터 지연 특성", parent="DataQuality"),
    TBoxClassDef("MissingData", "observation-data", "부족 데이터"),
    TBoxClassDef("CoverageGap", "observation-data", "온톨로지 커버리지 부족", parent="DataQuality", description="투자 판단에 필요한 가격, 경로, 수급, 외부 근거, 밸류에이션, 매크로 같은 범주 중 현재 ABox가 채우지 못한 공백입니다."),
    TBoxClassDef("Provenance", "observation-data", "출처 이력"),
    TBoxClassDef("SourceReliability", "observation-data", "출처 신뢰도", parent="Provenance"),
    TBoxClassDef("ObservationConfidence", "observation-data", "관측 신뢰도", parent="DataQuality"),
    TBoxClassDef("TimeWindow", "observation-data", "시간 구간"),
    TBoxClassDef("ObservationTime", "observation-data", "관측 시점"),
    TBoxClassDef("SignalHorizon", "observation-data", "신호 기간"),
    TBoxClassDef("HoldingPeriod", "observation-data", "보유 기간"),
    TBoxClassDef("ValidityInterval", "observation-data", "유효 기간"),
    TBoxClassDef("Staleness", "observation-data", "노후화"),
    TBoxClassDef("ValidationRule", "observation-data", "검증 규칙"),
    TBoxClassDef("PriceBar", "observation-data", "가격 봉", parent="PriceObservation"),
    TBoxClassDef("PricePath", "observation-data", "가격 경로", parent="PriceObservation"),
    TBoxClassDef("VolumeProfile", "observation-data", "거래량 프로파일", parent="VolumeObservation"),
    TBoxClassDef("KeyLevel", "observation-data", "주요 가격대", parent="TechnicalObservation"),
    TBoxClassDef("SupportLevel", "observation-data", "지지선", parent="KeyLevel"),
    TBoxClassDef("ResistanceLevel", "observation-data", "저항선", parent="KeyLevel"),
    TBoxClassDef("Breakout", "observation-data", "돌파", parent="TechnicalObservation"),
    TBoxClassDef("FailedBreakout", "observation-data", "돌파 실패", parent="Breakout"),
    TBoxClassDef("Retest", "observation-data", "재시험", parent="TechnicalObservation"),
    TBoxClassDef("ResearchEvidence", "observation-data", "리서치 근거", parent="ExternalObservation"),
    TBoxClassDef("ExternalSignal", "observation-data", "외부 신호", parent="ExternalObservation"),
    TBoxClassDef("NewsEvent", "observation-data", "뉴스 이벤트", parent="ExternalSignal"),
    TBoxClassDef("NewsArticle", "observation-data", "뉴스 기사", parent="NewsEvent"),
    TBoxClassDef("ArticleAIAnalysis", "observation-data", "기사 AI 분석", parent="NewsEvent"),
    TBoxClassDef("NewsTopic", "observation-data", "뉴스 토픽", parent="NewsEvent"),
    TBoxClassDef("NewsEventType", "observation-data", "뉴스 이벤트 유형", parent="NewsEvent"),
    TBoxClassDef("PeerCompanyMention", "observation-data", "피어 회사 언급", parent="ExternalObservation"),
    TBoxClassDef("DisclosureEvent", "observation-data", "공시 이벤트", parent="ExternalSignal"),
    TBoxClassDef("DisclosureFiling", "observation-data", "공시 문서", parent="DisclosureEvent"),
    TBoxClassDef("MacroIndicator", "observation-data", "거시 지표", parent="ExternalSignal"),
    TBoxClassDef("MacroPrint", "observation-data", "거시 발표값", parent="MacroIndicator"),
    TBoxClassDef("MacroRegime", "observation-data", "거시 레짐", parent="MacroIndicator", description="금리 수준, 금리 변화, 수익률곡선, 환율 환경을 묶어 투자 대상에 전파하는 시장 환경입니다."),
    TBoxClassDef("RateSignal", "observation-data", "금리 신호", parent="ExternalSignal"),
    TBoxClassDef("InterestRate", "observation-data", "금리", parent="RateSignal"),
    TBoxClassDef("YieldCurve", "observation-data", "수익률곡선", parent="RateSignal"),
    TBoxClassDef("FXRateSignal", "observation-data", "환율 신호", parent="ExternalSignal"),
    TBoxClassDef("CreditSpreadSignal", "observation-data", "크레딧 스프레드 신호", parent="ExternalSignal"),
    TBoxClassDef("CryptoMarketSignal", "observation-data", "크립토 시장 신호", parent="ExternalSignal"),
    TBoxClassDef("EarningsEvent", "observation-data", "실적 이벤트", parent="ExternalSignal"),
    TBoxClassDef("EarningsCalendarEvent", "observation-data", "실적 일정 이벤트", parent="EarningsEvent"),
    TBoxClassDef("AnalystRevision", "observation-data", "애널리스트 추정 변경", parent="ExternalSignal"),
    TBoxClassDef("CorporateAction", "observation-data", "기업 액션", parent="ExternalSignal"),
    TBoxClassDef("RegulatoryEvent", "observation-data", "규제 이벤트", parent="ExternalSignal"),
    TBoxClassDef("ProductLine", "observation-data", "제품/서비스 라인", parent="ExternalObservation"),
    TBoxClassDef("SupplyChainExposure", "observation-data", "공급망 노출", parent="ExternalObservation"),
    TBoxClassDef("CustomerExposure", "observation-data", "고객 노출", parent="ExternalObservation"),
    TBoxClassDef("RevenueExposure", "observation-data", "매출 노출", parent="ExternalObservation"),
    TBoxClassDef("Factor", "strategy-thesis", "투자 팩터"),
    TBoxClassDef("FactorExposure", "strategy-thesis", "팩터 노출"),
    TBoxClassDef("BenchmarkIndex", "strategy-thesis", "벤치마크 지수"),
    TBoxClassDef("HedgeCandidate", "strategy-thesis", "헤지 후보"),
    TBoxClassDef("Strategy", "strategy-thesis", "투자전략"),
    TBoxClassDef("InvestorProfile", "strategy-thesis", "투자자 성향", description="계정별 손실 허용도, 수익 보호 기준, 비중 한도, 행동 범위를 정의합니다."),
    TBoxClassDef("InvestmentStrategyProfile", "strategy-thesis", "투자 전략 성향", parent="InvestorProfile"),
    TBoxClassDef("InstrumentProfile", "strategy-thesis", "종목 투자 타입 프로필", description="종목별 투자 성격, 민감도, 추가매수·축소 정책을 정의합니다."),
    TBoxClassDef("InvestmentArchetype", "strategy-thesis", "투자 타입", description="성장주, 우선주, 비트코인 프록시, 반도체 사이클처럼 종목별 판단 방식을 바꾸는 타입입니다."),
    TBoxClassDef("GrowthStock", "strategy-thesis", "성장주 타입", parent="InvestmentArchetype"),
    TBoxClassDef("AIGrowth", "strategy-thesis", "AI 성장 타입", parent="GrowthStock"),
    TBoxClassDef("HighVolatilityGrowth", "strategy-thesis", "고변동 성장 타입", parent="GrowthStock"),
    TBoxClassDef("MegaCapQuality", "strategy-thesis", "대형 우량 타입", parent="InvestmentArchetype"),
    TBoxClassDef("PlatformGrowth", "strategy-thesis", "플랫폼 성장 타입", parent="GrowthStock"),
    TBoxClassDef("DividendIncome", "strategy-thesis", "배당형 타입", parent="InvestmentArchetype"),
    TBoxClassDef("PreferredIncome", "strategy-thesis", "우선주/인컴 타입", parent="DividendIncome"),
    TBoxClassDef("BitcoinProxy", "strategy-thesis", "비트코인 프록시 타입", parent="InvestmentArchetype"),
    TBoxClassDef("BitcoinSensitiveIncome", "strategy-thesis", "비트코인 민감 인컴 타입", parent="PreferredIncome"),
    TBoxClassDef("CryptoAssetProfile", "strategy-thesis", "크립토 투자 타입", parent="InvestmentArchetype"),
    TBoxClassDef("SemiconductorCyclical", "strategy-thesis", "반도체 사이클 타입", parent="InvestmentArchetype"),
    TBoxClassDef("SemiconductorHBM", "strategy-thesis", "HBM 반도체 타입", parent="SemiconductorCyclical"),
    TBoxClassDef("CyclicalGrowth", "strategy-thesis", "경기민감 성장 타입", parent="GrowthStock"),
    TBoxClassDef("EquityGeneral", "strategy-thesis", "일반 주식 타입", parent="InvestmentArchetype"),
    TBoxClassDef("PositionIntent", "strategy-thesis", "포지션 의도", description="core, trading, income, market-signal처럼 종목을 계좌 안에서 어떤 역할로 볼지 정의합니다."),
    TBoxClassDef("FactorSensitivity", "strategy-thesis", "팩터 민감도", parent="FactorExposure", description="금리, 환율, 사이클, 비트코인, AI 같은 요인에 대한 종목별 민감도입니다."),
    TBoxClassDef("RiskBudget", "strategy-thesis", "손실 허용 기준", parent="RiskManagementRule"),
    TBoxClassDef("ProfitPolicy", "strategy-thesis", "수익 보호 기준", parent="RiskManagementRule"),
    TBoxClassDef("PositionRole", "strategy-thesis", "포지션 역할", parent="PositionSizingRule"),
    TBoxClassDef("InvestmentThesis", "strategy-thesis", "투자 가설"),
    TBoxClassDef("EntryCondition", "strategy-thesis", "진입 조건"),
    TBoxClassDef("ExitCondition", "strategy-thesis", "청산 조건"),
    TBoxClassDef("RiskManagementRule", "strategy-thesis", "위험 관리 규칙"),
    TBoxClassDef("RebalancingRule", "strategy-thesis", "리밸런싱 규칙"),
    TBoxClassDef("PositionSizingRule", "strategy-thesis", "비중 규칙"),
    TBoxClassDef("Scenario", "strategy-thesis", "시나리오"),
    TBoxClassDef("StrategyExperiment", "strategy-thesis", "전략 실험"),
    TBoxClassDef("StrategySignal", "strategy-thesis", "전략 신호"),
    TBoxClassDef("ModelScore", "strategy-thesis", "모델 점수", parent="StrategySignal"),
    TBoxClassDef("Threshold", "strategy-thesis", "기준값"),
    TBoxClassDef("RuntimeSetting", "strategy-thesis", "런타임 설정"),
    TBoxClassDef("AlertRule", "strategy-thesis", "알림 규칙", parent="RuntimeSetting"),
    TBoxClassDef("PromptTemplate", "strategy-thesis", "프롬프트 템플릿", parent="RuntimeSetting"),
    TBoxClassDef("ValuationAssumption", "strategy-thesis", "밸류에이션 가정"),
    TBoxClassDef("LegacyScoreModel", "strategy-thesis", "관계 규칙 점수 모델"),
    TBoxClassDef("Risk", "risk-exposure", "리스크"),
    TBoxClassDef("MarketRisk", "risk-exposure", "시장 리스크", parent="Risk"),
    TBoxClassDef("LiquidityRisk", "risk-exposure", "유동성 리스크", parent="Risk"),
    TBoxClassDef("LiquidityProfile", "risk-exposure", "유동성 프로파일", parent="LiquidityRisk"),
    TBoxClassDef("ExitCapacity", "risk-exposure", "청산 가능 용량", parent="LiquidityRisk"),
    TBoxClassDef("ExecutionMetric", "observation-data", "실행 지표", parent="FlowObservation", description="보유 규모, 거래대금, 호가잔량, 청산 일수처럼 주문 실행 가능성을 판단하는 원천 관측값입니다."),
    TBoxClassDef("ExecutionCapacity", "risk-exposure", "실행 가능 용량", parent="ExecutionRisk", description="현재 보유 수량을 실제 시장 유동성 안에서 실행할 수 있는 여유입니다."),
    TBoxClassDef("PositionExitExposure", "risk-exposure", "포지션 청산 노출", parent="LiquidityRisk", description="보유 규모가 거래량·거래대금·호가잔량 대비 얼마나 큰지 나타내는 노출입니다."),
    TBoxClassDef("SlippageEstimate", "risk-exposure", "슬리피지 추정", parent="ExecutionRisk"),
    TBoxClassDef("ConcentrationRisk", "risk-exposure", "집중 리스크", parent="Risk"),
    TBoxClassDef("CurrencyRisk", "risk-exposure", "통화 리스크", parent="Risk"),
    TBoxClassDef("VolatilityRisk", "risk-exposure", "변동성 리스크", parent="Risk"),
    TBoxClassDef("CryptoExposure", "risk-exposure", "크립토 노출", parent="VolatilityRisk", description="비트코인·이더리움 등 디지털 자산 가격 경로가 종목 또는 포트폴리오에 전달되는 노출입니다."),
    TBoxClassDef("EventRisk", "risk-exposure", "이벤트 리스크", parent="Risk"),
    TBoxClassDef("DataQualityRisk", "risk-exposure", "데이터 품질 리스크", parent="Risk"),
    TBoxClassDef("ArticleQualityRisk", "risk-exposure", "기사 품질 리스크", parent="DataQualityRisk", description="뉴스 본문 부재, 종목 직접성 미확인, 분석 충돌처럼 기사 근거의 판단 신뢰도를 낮추는 리스크입니다."),
    TBoxClassDef("ModelRisk", "risk-exposure", "모델 리스크", parent="Risk"),
    TBoxClassDef("ExecutionRisk", "risk-exposure", "실행 리스크", parent="Risk"),
    TBoxClassDef("CorrelationRisk", "risk-exposure", "상관 리스크", parent="Risk"),
    TBoxClassDef("RegimeRisk", "risk-exposure", "레짐 리스크", parent="Risk"),
    TBoxClassDef("Signal", "reasoning-insight", "신호"),
    TBoxClassDef("PriceSignal", "reasoning-insight", "가격 신호", parent="Signal"),
    TBoxClassDef("TrendSignal", "reasoning-insight", "추세 신호", parent="Signal"),
    TBoxClassDef("FlowSignal", "reasoning-insight", "수급 신호", parent="Signal"),
    TBoxClassDef("InvestorFlowSentiment", "reasoning-insight", "투자자별 수급 심리", parent="FlowSignal"),
    TBoxClassDef("SmartMoneyFlow", "reasoning-insight", "외국인·기관 수급", parent="FlowSignal"),
    TBoxClassDef("SmartMoneyJointInflow", "reasoning-insight", "외국인·기관 동반 순매수", parent="SmartMoneyFlow"),
    TBoxClassDef("SmartMoneyJointOutflow", "reasoning-insight", "외국인·기관 동반 순매도", parent="SmartMoneyFlow"),
    TBoxClassDef("SmartMoneyAccumulation", "reasoning-insight", "외국인·기관 매집", parent="SmartMoneyFlow"),
    TBoxClassDef("PartialSmartMoneySupport", "reasoning-insight", "외국인·기관 일부 순매수", parent="SmartMoneyFlow"),
    TBoxClassDef("PartialSmartMoneyRisk", "reasoning-insight", "외국인·기관 일부 순매도", parent="SmartMoneyFlow"),
    TBoxClassDef("RetailFlowPsychology", "reasoning-insight", "개인 수급 심리", parent="FlowSignal"),
    TBoxClassDef("RetailDipBuyingRisk", "reasoning-insight", "개인 저가매수 위험", parent="RetailFlowPsychology"),
    TBoxClassDef("ValuationSignal", "reasoning-insight", "밸류에이션 신호", parent="Signal"),
    TBoxClassDef("MacroSignal", "reasoning-insight", "거시 신호", parent="Signal"),
    TBoxClassDef("DisclosureSignal", "reasoning-insight", "공시 신호", parent="Signal"),
    TBoxClassDef("CryptoSignal", "reasoning-insight", "크립토 신호", parent="Signal"),
    TBoxClassDef("DataQualitySignal", "reasoning-insight", "데이터 품질 신호", parent="Signal"),
    TBoxClassDef("Evidence", "reasoning-insight", "근거"),
    TBoxClassDef("Belief", "reasoning-insight", "판단 근거"),
    TBoxClassDef("RelationStateSnapshot", "reasoning-insight", "관계 상태 스냅샷"),
    TBoxClassDef("SignalTransition", "reasoning-insight", "신호 상태 전이"),
    TBoxClassDef("TrendPhase", "reasoning-insight", "추세 국면", parent="Signal"),
    TBoxClassDef("TrendTransition", "reasoning-insight", "추세 국면 전이", parent="SignalTransition"),
    TBoxClassDef("ReversalSignal", "reasoning-insight", "반전 신호", parent="TrendTransition"),
    TBoxClassDef("ConsolidationBreak", "reasoning-insight", "횡보 이탈", parent="TrendTransition"),
    TBoxClassDef("AccelerationSignal", "reasoning-insight", "가속 신호", parent="TrendTransition"),
    TBoxClassDef("DecelerationSignal", "reasoning-insight", "둔화 신호", parent="TrendTransition"),
    TBoxClassDef("MaterialityAssessment", "reasoning-insight", "중요 변경 평가"),
    TBoxClassDef("ThresholdCrossing", "reasoning-insight", "기준선 통과"),
    TBoxClassDef("ExposureAssessment", "reasoning-insight", "노출 영향 평가"),
    TBoxClassDef("ConfidenceAssessment", "reasoning-insight", "신뢰도 평가"),
    TBoxClassDef("ActionabilityAssessment", "reasoning-insight", "행동 가능성 평가"),
    TBoxClassDef("LossDefenseEvidence", "reasoning-insight", "손실 구간 방어 근거", parent="ActionabilityAssessment"),
    TBoxClassDef("AddBuyEligibility", "reasoning-insight", "추가매수 검토 가능성", parent="ActionabilityAssessment"),
    TBoxClassDef("AveragingDownRisk", "reasoning-insight", "물타기 위험", parent="Risk"),
    TBoxClassDef("RecoveryConfirmation", "reasoning-insight", "회복 확인", parent="ActionabilityAssessment"),
    TBoxClassDef("ReboundFailureRisk", "risk-exposure", "반등 실패 위험", parent="Risk", description="단기 반등이 있지만 주요 평균 가격과 수급 확인이 부족해 회복으로 보기 어려운 위험입니다."),
    TBoxClassDef("MomentumConfirmation", "reasoning-insight", "상승 흐름 확인", parent="ActionabilityAssessment"),
    TBoxClassDef("FlowConfirmation", "reasoning-insight", "수급 확인", parent="ActionabilityAssessment", description="가격 신호가 거래량, 체결강도, 외국인·기관 수급과 같은 방향으로 확인된 상태입니다."),
    TBoxClassDef("ProfitProtection", "reasoning-insight", "수익 보호", parent="ActionabilityAssessment"),
    TBoxClassDef("InvestorFlowRisk", "risk-exposure", "투자자 수급 위험", parent="Risk"),
    TBoxClassDef("InvestorProfilePolicy", "strategy-thesis", "투자 성향 정책", parent="ActionPolicy"),
    TBoxClassDef("StrategyFitAssessment", "reasoning-insight", "투자 성향 적합 판단", parent="ActionabilityAssessment", description="종목 타입, 계정 성향, 비중 한도가 서로 맞는지 판단한 추론입니다."),
    TBoxClassDef("StrategyMismatchRisk", "risk-exposure", "투자 성향 부적합 위험", parent="Risk", description="종목 타입이나 현재 상태가 계정 성향, 손실 허용폭, 비중 정책과 맞지 않는 위험입니다."),
    TBoxClassDef("NewsImpactConfirmation", "reasoning-insight", "뉴스 영향 확인", parent="ActionabilityAssessment", description="뉴스·공시가 실제 가격, 거래량, 수급 반응으로 확인됐는지 나타내는 추론입니다."),
    TBoxClassDef("DisclosureDilutionRisk", "risk-exposure", "공시 희석/자금조달 위험", parent="EventRisk", description="증자, 전환사채, 자기주식 처분 등으로 주주 가치나 수급 부담을 확인해야 하는 공시 위험입니다."),
    TBoxClassDef("PreviousInsight", "reasoning-insight", "이전 인사이트", parent="Insight"),
    TBoxClassDef("Opinion", "reasoning-insight", "AI 의견"),
    TBoxClassDef("ActiveInvestmentOpinion", "reasoning-insight", "실행 투자 의견", parent="Opinion"),
    TBoxClassDef("ExecutionPlan", "reasoning-insight", "실행 계획"),
    TBoxClassDef("DecisionDriver", "reasoning-insight", "판단 근거 축"),
    TBoxClassDef("TargetRole", "reasoning-insight", "판단 대상 역할", description="보유종목과 관심종목처럼 실행 가능한 행동 범위를 나누는 역할입니다."),
    TBoxClassDef("ActionPolicy", "reasoning-insight", "행동 정책", description="대상 역할별로 허용되는 투자 행동과 차단되는 행동을 정의합니다."),
    TBoxClassDef("ActionCandidate", "reasoning-insight", "행동 후보"),
    TBoxClassDef("AllowedAction", "reasoning-insight", "허용 행동", parent="ActionCandidate"),
    TBoxClassDef("BlockedAction", "reasoning-insight", "보류 행동", parent="ActionCandidate"),
    TBoxClassDef("InvalidationCondition", "reasoning-insight", "무효화 조건"),
    TBoxClassDef("NextCheck", "reasoning-insight", "다음 확인"),
    TBoxClassDef("AIValidation", "reasoning-insight", "AI 판단 검증"),
    TBoxClassDef("ValidatedOpinion", "reasoning-insight", "AI 최종 의견", parent="Opinion"),
    TBoxClassDef("AIJudgmentAudit", "reasoning-insight", "AI 판단 감사 로그"),
    TBoxClassDef("AIContextPacket", "reasoning-insight", "AI 컨텍스트 패킷", parent="AIJudgmentAudit"),
    TBoxClassDef("EvidenceSubgraph", "reasoning-insight", "근거 서브그래프", parent="InferencePath"),
    TBoxClassDef("GraphNeighborhood", "reasoning-insight", "그래프 이웃 관계", parent="EvidenceSubgraph"),
    TBoxClassDef("Opportunity", "reasoning-insight", "기회"),
    TBoxClassDef("Contradiction", "reasoning-insight", "모순"),
    TBoxClassDef("Insight", "reasoning-insight", "인사이트"),
    TBoxClassDef("InsightType", "reasoning-insight", "인사이트 타입"),
    TBoxClassDef("InsightPolicy", "reasoning-insight", "인사이트 정책"),
    TBoxClassDef("MessageDeliveryProfile", "reasoning-insight", "메시지 전달 수준"),
    TBoxClassDef("ReasoningRule", "reasoning-insight", "추론 규칙"),
    TBoxClassDef("RuleRegistry", "reasoning-insight", "규칙 레지스트리"),
    TBoxClassDef("RelationRuleRegistry", "reasoning-insight", "투자 관계 규칙 레지스트리", parent="RuleRegistry"),
    TBoxClassDef("GraphInferenceRule", "reasoning-insight", "그래프 추론 규칙", parent="ReasoningRule"),
    TBoxClassDef("RelationReasoningRule", "reasoning-insight", "투자 관계 추론 규칙", parent="ReasoningRule"),
    TBoxClassDef("RuleCondition", "reasoning-insight", "규칙 조건", parent="ReasoningRule"),
    TBoxClassDef("RelationRuleCondition", "reasoning-insight", "투자 관계 규칙 조건", parent="RuleCondition"),
    TBoxClassDef("RelationTemplate", "reasoning-insight", "파생 관계 템플릿", parent="ReasoningRule"),
    TBoxClassDef("RelationRuleTemplate", "reasoning-insight", "투자 관계 파생 템플릿", parent="RelationTemplate"),
    TBoxClassDef("RuleDecisionPolicy", "reasoning-insight", "규칙 판단 단계 정책", parent="RelationTemplate"),
    TBoxClassDef("RulePriorityPolicy", "reasoning-insight", "규칙 우선순위 정책", parent="RelationTemplate"),
    TBoxClassDef("RuleBoxGovernance", "reasoning-insight", "RuleBox 운영 거버넌스"),
    TBoxClassDef("RuleBoxVersion", "reasoning-insight", "RuleBox 저장 버전", parent="RuleBoxGovernance"),
    TBoxClassDef("RuleChangeCandidate", "reasoning-insight", "규칙 변경 후보", parent="RuleBoxGovernance"),
    TBoxClassDef("DerivedAssertion", "reasoning-insight", "파생 어설션"),
    TBoxClassDef("InferenceTrace", "reasoning-insight", "추론 경로"),
    TBoxClassDef("InferencePath", "reasoning-insight", "추론 패스", parent="InferenceTrace"),
    TBoxClassDef("GraphReasoner", "reasoning-insight", "그래프 추론기"),
    TBoxClassDef("GraphStoreNativeReasoner", "reasoning-insight", "그래프 저장소 네이티브 추론기", parent="GraphReasoner"),
    TBoxClassDef("TypeDBNativeReasoner", "reasoning-insight", "TypeDB 네이티브 추론기", parent="GraphReasoner"),
    TBoxClassDef("ReasoningCard", "reasoning-insight", "추론 카드"),
    TBoxClassDef("ConfidenceScore", "reasoning-insight", "확신도"),
    TBoxClassDef("ReliabilityScore", "reasoning-insight", "신뢰도"),
    TBoxClassDef("AIReview", "reasoning-insight", "AI 리뷰"),
    TBoxClassDef("DataPipeline", "operations-dispatch", "데이터 파이프라인"),
    TBoxClassDef("CollectionSchedule", "operations-dispatch", "수집 주기"),
    TBoxClassDef("CollectionPolicy", "operations-dispatch", "수집 정책"),
    TBoxClassDef("MarketSnapshot", "operations-dispatch", "시장 스냅샷", parent="DataPipeline"),
    TBoxClassDef("WatchlistSnapshot", "operations-dispatch", "관심 스냅샷", parent="DataPipeline"),
    TBoxClassDef("ExternalSignalCollection", "operations-dispatch", "외부 신호 수집", parent="DataPipeline"),
    TBoxClassDef("AnalysisJob", "operations-dispatch", "분석 작업"),
    TBoxClassDef("ReasoningCycle", "operations-dispatch", "추론 주기"),
    TBoxClassDef("NotificationPolicy", "operations-dispatch", "알림 정책"),
    TBoxClassDef("NotificationDispatch", "operations-dispatch", "알림 디스패치"),
    TBoxClassDef("NotificationIntent", "operations-dispatch", "알림 의도"),
    TBoxClassDef("AlertCandidate", "operations-dispatch", "알림 후보", parent="NotificationIntent"),
    TBoxClassDef("ImportanceGate", "operations-dispatch", "중요도 게이트", parent="NotificationPolicy"),
    TBoxClassDef("CooldownPolicy", "operations-dispatch", "쿨다운 정책", parent="NotificationPolicy"),
    TBoxClassDef("NoveltyPolicy", "operations-dispatch", "신규성 정책", parent="NotificationPolicy"),
    TBoxClassDef("SuppressionPolicy", "operations-dispatch", "억제 정책", parent="NotificationPolicy"),
    TBoxClassDef("MarketSession", "operations-dispatch", "시장 세션"),
    TBoxClassDef("OperationalEvent", "operations-dispatch", "운영 이벤트"),
]


RELATION_DEFS: List[TBoxRelationDef] = [
    TBoxRelationDef("DEFINES_BOUNDED_CONTEXT", "operations-dispatch", "operations-dispatch", "operations-dispatch"),
    TBoxRelationDef("DEFINES_CLASS", "operations-dispatch", "operations-dispatch", "operations-dispatch"),
    TBoxRelationDef("DEFINES_RELATION", "operations-dispatch", "operations-dispatch", "operations-dispatch"),
    TBoxRelationDef("CONSTRAINS_ASSERTIONS", "operations-dispatch", "operations-dispatch", "operations-dispatch"),
    TBoxRelationDef("CONSTRAINS_RULES", "reasoning-insight", "operations-dispatch", "reasoning-insight"),
    TBoxRelationDef("DERIVES_ASSERTIONS", "reasoning-insight", "reasoning-insight", "reasoning-insight"),
    TBoxRelationDef("IS_A", "investment-core", "investment-core", "investment-core"),
    TBoxRelationDef("HOLDS", "investment-core", "investment-core", "investment-core"),
    TBoxRelationDef("WATCHES", "investment-core", "investment-core", "investment-core"),
    TBoxRelationDef("HOLDS_CASH", "investment-core", "investment-core", "investment-core"),
    TBoxRelationDef("MANAGES_PORTFOLIO", "investment-core", "investment-core", "investment-core"),
    TBoxRelationDef("HAS_POSITION", "investment-core", "investment-core", "investment-core"),
    TBoxRelationDef("HAS_WATCHLIST", "investment-core", "investment-core", "investment-core"),
    TBoxRelationDef("ISSUES", "investment-core", "investment-core", "investment-core"),
    TBoxRelationDef("COMPETES_WITH", "investment-core", "investment-core", "investment-core"),
    TBoxRelationDef("SUPPLIES_TO", "observation-data", "investment-core", "investment-core"),
    TBoxRelationDef("SELLS_TO", "observation-data", "investment-core", "investment-core"),
    TBoxRelationDef("HAS_PRODUCT_EXPOSURE", "observation-data", "investment-core", "observation-data"),
    TBoxRelationDef("HAS_SUPPLY_CHAIN_EXPOSURE", "observation-data", "investment-core", "observation-data"),
    TBoxRelationDef("HAS_CUSTOMER_EXPOSURE", "observation-data", "investment-core", "observation-data"),
    TBoxRelationDef("HAS_REVENUE_EXPOSURE", "observation-data", "investment-core", "observation-data"),
    TBoxRelationDef("REPRESENTS_STOCK", "investment-core", "investment-core", "investment-core"),
    TBoxRelationDef("REPRESENTS_INSTRUMENT", "investment-core", "investment-core", "investment-core"),
    TBoxRelationDef("HAS_MARKET_EXPOSURE", "investment-core", "investment-core", "investment-core"),
    TBoxRelationDef("BELONGS_TO", "investment-core", "investment-core", "investment-core"),
    TBoxRelationDef("TRADED_IN", "investment-core", "investment-core", "investment-core"),
    TBoxRelationDef("DENOMINATED_IN", "investment-core", "investment-core", "investment-core"),
    TBoxRelationDef("EXPOSED_TO", "risk-exposure", "investment-core", "risk-exposure"),
    TBoxRelationDef("HAS_FX_EXPOSURE", "risk-exposure", "investment-core", "risk-exposure"),
    TBoxRelationDef("HAS_RATE_SENSITIVITY", "risk-exposure", "investment-core", "risk-exposure"),
    TBoxRelationDef("HAS_MACRO_REGIME", "risk-exposure", "investment-core", "risk-exposure", "투자 대상이 현재 금리·환율·수익률곡선 레짐에 노출됩니다."),
    TBoxRelationDef("HAS_CRYPTO_EXPOSURE", "risk-exposure", "investment-core", "risk-exposure", "투자 대상이 크립토 가격 경로와 변동성에 노출됩니다."),
    TBoxRelationDef("HAS_OBSERVATION", "observation-data", "investment-core", "observation-data"),
    TBoxRelationDef("OBSERVED_FROM", "observation-data", "investment-core", "observation-data"),
    TBoxRelationDef("HAS_PRICE", "observation-data", "investment-core", "observation-data"),
    TBoxRelationDef("HAS_PRICE_PATH", "observation-data", "investment-core", "observation-data"),
    TBoxRelationDef("HAS_TECHNICAL_INDICATOR", "observation-data", "investment-core", "observation-data"),
    TBoxRelationDef("HAS_TRADE_FLOW", "observation-data", "investment-core", "observation-data"),
    TBoxRelationDef("HAS_INVESTOR_FLOW_SENTIMENT", "observation-data", "investment-core", "observation-data", "외국인·기관·개인 수급을 투자자 심리 관계로 해석합니다."),
    TBoxRelationDef("HAS_LIQUIDITY_PROFILE", "observation-data", "investment-core", "risk-exposure"),
    TBoxRelationDef("HAS_EXECUTION_METRIC", "observation-data", "investment-core", "observation-data"),
    TBoxRelationDef("HAS_DATA_QUALITY", "observation-data", "investment-core", "observation-data"),
    TBoxRelationDef("HAS_COVERAGE_GAP", "observation-data", "investment-core", "observation-data", "ABox가 투자 판단 필수 범주를 채우지 못한 공백을 명시합니다."),
    TBoxRelationDef("HAS_EXTERNAL_SIGNAL", "observation-data", "investment-core", "observation-data"),
    TBoxRelationDef("HAS_PROVENANCE", "observation-data", "observation-data", "observation-data"),
    TBoxRelationDef("HAS_ANALYSIS", "observation-data", "observation-data", "observation-data"),
    TBoxRelationDef("EXPLAINS", "observation-data", "observation-data", "observation-data"),
    TBoxRelationDef("HAS_SOURCE_RELIABILITY", "observation-data", "observation-data", "observation-data"),
    TBoxRelationDef("WEIGHTED_BY_CONFIDENCE", "observation-data", "observation-data", "reasoning-insight"),
    TBoxRelationDef("STALE_AFTER", "observation-data", "observation-data", "observation-data"),
    TBoxRelationDef("CONFLICTS_WITH_SOURCE", "observation-data", "observation-data", "observation-data"),
    TBoxRelationDef("PRODUCES_OBSERVATION", "observation-data", "operations-dispatch", "observation-data"),
    TBoxRelationDef("MEASURED_AT", "observation-data", "observation-data", "observation-data"),
    TBoxRelationDef("VALID_DURING", "observation-data", "observation-data", "observation-data"),
    TBoxRelationDef("PRECEDES", "observation-data", "observation-data", "observation-data"),
    TBoxRelationDef("CHANGED_FROM", "reasoning-insight", "reasoning-insight", "reasoning-insight"),
    TBoxRelationDef("CONFIRMED_OVER", "reasoning-insight", "observation-data", "reasoning-insight"),
    TBoxRelationDef("FAILED_AFTER", "reasoning-insight", "observation-data", "reasoning-insight"),
    TBoxRelationDef("HAS_TREND_PHASE", "reasoning-insight", "observation-data", "reasoning-insight"),
    TBoxRelationDef("HAS_TREND_TRANSITION", "reasoning-insight", "investment-core", "reasoning-insight"),
    TBoxRelationDef("INDICATES_REVERSAL", "reasoning-insight", "reasoning-insight", "reasoning-insight"),
    TBoxRelationDef("BREAKS_CONSOLIDATION", "reasoning-insight", "reasoning-insight", "reasoning-insight"),
    TBoxRelationDef("INDICATES_ACCELERATION", "reasoning-insight", "reasoning-insight", "reasoning-insight"),
    TBoxRelationDef("INDICATES_DECELERATION", "reasoning-insight", "reasoning-insight", "reasoning-insight"),
    TBoxRelationDef("INDICATES_WEAKENING", "reasoning-insight", "reasoning-insight", "reasoning-insight"),
    TBoxRelationDef("RETESTS_LEVEL", "observation-data", "investment-core", "observation-data"),
    TBoxRelationDef("BREAKS_LEVEL", "observation-data", "investment-core", "observation-data"),
    TBoxRelationDef("RECLAIMS_LEVEL", "observation-data", "investment-core", "observation-data"),
    TBoxRelationDef("MENTIONS_INSTRUMENT", "observation-data", "observation-data", "investment-core"),
    TBoxRelationDef("MENTIONS_PEER", "observation-data", "observation-data", "investment-core"),
    TBoxRelationDef("HAS_TOPIC", "observation-data", "observation-data", "observation-data"),
    TBoxRelationDef("HAS_EVENT_TYPE", "observation-data", "observation-data", "observation-data"),
    TBoxRelationDef("AFFECTS_SECTOR", "observation-data", "observation-data", "investment-core"),
    TBoxRelationDef(
        "NEWS_CONTEXT_FOR",
        "observation-data",
        "observation-data",
        "investment-core",
        "뉴스가 투자 대상의 직접/간접 맥락 근거로 연결됩니다.",
    ),
    TBoxRelationDef(
        "NEWS_RISK_FOR",
        "risk-exposure",
        "observation-data",
        "investment-core",
        "뉴스가 투자 대상의 이벤트 리스크 근거로 연결됩니다.",
    ),
    TBoxRelationDef(
        "NEWS_SUPPORTS_ENTRY",
        "strategy-thesis",
        "observation-data",
        "investment-core",
        "뉴스가 투자 대상의 진입/유지 가설을 지지하는 근거로 연결됩니다.",
    ),
    TBoxRelationDef(
        "NEWS_PROPAGATES_CONTEXT",
        "observation-data",
        "observation-data",
        "investment-core",
        "섹터, 피어, 시장 뉴스가 투자 대상에 간접 맥락으로 전파됩니다.",
    ),
    TBoxRelationDef("MATERIAL_TO", "observation-data", "observation-data", "strategy-thesis"),
    TBoxRelationDef("DECAYS_AFTER", "observation-data", "observation-data", "observation-data"),
    TBoxRelationDef("HAS_TIME_HORIZON", "observation-data", "investment-core", "observation-data"),
    TBoxRelationDef("APPLIES_TO_HORIZON", "observation-data", "strategy-thesis", "observation-data"),
    TBoxRelationDef("HAS_VALUATION", "strategy-thesis", "investment-core", "strategy-thesis"),
    TBoxRelationDef("HAS_MODEL_SCORE", "strategy-thesis", "investment-core", "strategy-thesis"),
    TBoxRelationDef("HAS_THRESHOLD", "strategy-thesis", "strategy-thesis", "strategy-thesis"),
    TBoxRelationDef("HAS_RUNTIME_SETTING", "strategy-thesis", "investment-core", "strategy-thesis"),
    TBoxRelationDef("HAS_ALERT_RULE", "strategy-thesis", "strategy-thesis", "strategy-thesis"),
    TBoxRelationDef("HAS_PROMPT_TEMPLATE", "strategy-thesis", "strategy-thesis", "strategy-thesis"),
    TBoxRelationDef("USES_STRATEGY", "strategy-thesis", "investment-core", "strategy-thesis"),
    TBoxRelationDef("HAS_INVESTOR_PROFILE", "strategy-thesis", "investment-core", "strategy-thesis"),
    TBoxRelationDef("USES_INVESTMENT_STRATEGY_PROFILE", "strategy-thesis", "investment-core", "strategy-thesis"),
    TBoxRelationDef("HAS_RISK_BUDGET", "strategy-thesis", "strategy-thesis", "strategy-thesis"),
    TBoxRelationDef("HAS_PROFIT_POLICY", "strategy-thesis", "strategy-thesis", "strategy-thesis"),
    TBoxRelationDef("HAS_POSITION_ROLE", "strategy-thesis", "investment-core", "strategy-thesis"),
    TBoxRelationDef("HAS_INSTRUMENT_PROFILE", "strategy-thesis", "investment-core", "strategy-thesis"),
    TBoxRelationDef("HAS_ARCHETYPE", "strategy-thesis", "strategy-thesis", "strategy-thesis"),
    TBoxRelationDef("HAS_FACTOR_SENSITIVITY", "strategy-thesis", "strategy-thesis", "strategy-thesis"),
    TBoxRelationDef("HAS_POSITION_INTENT", "strategy-thesis", "strategy-thesis", "strategy-thesis"),
    TBoxRelationDef("USES_INSTRUMENT_POLICY", "strategy-thesis", "strategy-thesis", "strategy-thesis"),
    TBoxRelationDef("EVALUATED_UNDER_STRATEGY", "strategy-thesis", "investment-core", "strategy-thesis"),
    TBoxRelationDef("BASED_ON_THESIS", "strategy-thesis", "investment-core", "strategy-thesis"),
    TBoxRelationDef("HAS_ENTRY_CONDITION", "strategy-thesis", "strategy-thesis", "strategy-thesis"),
    TBoxRelationDef("HAS_EXIT_CONDITION", "strategy-thesis", "strategy-thesis", "strategy-thesis"),
    TBoxRelationDef("HAS_RISK_MANAGEMENT_RULE", "strategy-thesis", "strategy-thesis", "strategy-thesis"),
    TBoxRelationDef("HAS_POSITION_SIZING_RULE", "strategy-thesis", "strategy-thesis", "strategy-thesis"),
    TBoxRelationDef("HAS_REBALANCING_RULE", "strategy-thesis", "strategy-thesis", "strategy-thesis"),
    TBoxRelationDef("HAS_FACTOR_EXPOSURE", "strategy-thesis", "investment-core", "strategy-thesis"),
    TBoxRelationDef("HAS_BETA_TO", "strategy-thesis", "investment-core", "strategy-thesis"),
    TBoxRelationDef("CORRELATED_WITH", "risk-exposure", "investment-core", "investment-core"),
    TBoxRelationDef("OFFSETS_RISK", "risk-exposure", "strategy-thesis", "risk-exposure"),
    TBoxRelationDef("SUPPORTS_THESIS", "strategy-thesis", "reasoning-insight", "strategy-thesis"),
    TBoxRelationDef("WEAKENS_THESIS", "strategy-thesis", "risk-exposure", "strategy-thesis"),
    TBoxRelationDef("INVALIDATES_THESIS", "strategy-thesis", "reasoning-insight", "strategy-thesis"),
    TBoxRelationDef("TRIGGERS_ENTRY", "strategy-thesis", "reasoning-insight", "strategy-thesis"),
    TBoxRelationDef("TRIGGERS_EXIT", "strategy-thesis", "risk-exposure", "strategy-thesis"),
    TBoxRelationDef("REQUIRES_CONFIRMATION", "strategy-thesis", "strategy-thesis", "observation-data"),
    TBoxRelationDef("CONFIGURES", "strategy-thesis", "investment-core", "strategy-thesis"),
    TBoxRelationDef("DERIVES_SIGNAL", "reasoning-insight", "observation-data", "reasoning-insight"),
    TBoxRelationDef("DEFINES_RULE", "reasoning-insight", "reasoning-insight", "reasoning-insight"),
    TBoxRelationDef("HAS_CONDITION", "reasoning-insight", "reasoning-insight", "reasoning-insight"),
    TBoxRelationDef("DERIVES_RELATION", "reasoning-insight", "reasoning-insight", "reasoning-insight"),
    TBoxRelationDef("HAS_RULEBOX_VERSION", "reasoning-insight", "reasoning-insight", "reasoning-insight"),
    TBoxRelationDef("HAS_RULE_CHANGE_CANDIDATE", "reasoning-insight", "reasoning-insight", "reasoning-insight"),
    TBoxRelationDef("TRIGGERED_INFERENCE", "reasoning-insight", "reasoning-insight", "reasoning-insight"),
    TBoxRelationDef("EXECUTES_RULEBOX", "reasoning-insight", "reasoning-insight", "reasoning-insight"),
    TBoxRelationDef("MATERIALIZES_INFERENCE", "reasoning-insight", "reasoning-insight", "reasoning-insight"),
    TBoxRelationDef("HAS_INFERENCE_TRACE", "reasoning-insight", "investment-core", "reasoning-insight"),
    TBoxRelationDef("EXPLAINED_BY_TRACE", "reasoning-insight", "reasoning-insight", "reasoning-insight"),
    TBoxRelationDef("HAS_INFERRED_RISK", "risk-exposure", "investment-core", "risk-exposure"),
    TBoxRelationDef("HAS_INFERRED_SUPPORT", "strategy-thesis", "investment-core", "reasoning-insight"),
    TBoxRelationDef("HAS_INFERRED_ENTRY_OPPORTUNITY", "strategy-thesis", "investment-core", "reasoning-insight"),
    TBoxRelationDef("MATCHES_INVESTOR_PROFILE", "strategy-thesis", "investment-core", "reasoning-insight", "종목 타입과 계정 투자 성향이 맞는지 추론합니다."),
    TBoxRelationDef("FITS_INVESTOR_RISK_PROFILE", "strategy-thesis", "investment-core", "reasoning-insight", "투자 성향의 손실·비중 허용 범위 안에서 행동 후보가 가능한지 추론합니다."),
    TBoxRelationDef("VIOLATES_STRATEGY_FIT", "risk-exposure", "investment-core", "risk-exposure", "종목 타입이나 현재 흐름이 계정 전략과 맞지 않는 위험을 추론합니다."),
    TBoxRelationDef("VIOLATES_RISK_TOLERANCE", "risk-exposure", "investment-core", "risk-exposure", "보유 손익과 비중이 계정 투자 성향의 손실 허용 기준을 넘었는지 추론합니다."),
    TBoxRelationDef("CONFIRMS_RECOVERY", "reasoning-insight", "investment-core", "reasoning-insight", "가격 회복이 거래·수급 확인으로 보강됐는지 추론합니다."),
    TBoxRelationDef("FAILS_RECOVERY", "risk-exposure", "investment-core", "risk-exposure", "단기 반등이 주요 평균 가격과 수급 확인을 통과하지 못했는지 추론합니다."),
    TBoxRelationDef("CONFIRMS_WITH_FLOW", "reasoning-insight", "investment-core", "reasoning-insight", "가격 신호가 투자자별 수급 심리와 같은 방향인지 추론합니다."),
    TBoxRelationDef("DIVERGES_FROM_FLOW", "risk-exposure", "investment-core", "risk-exposure", "가격 변화와 외국인·기관·개인 수급 심리가 어긋나는지 추론합니다."),
    TBoxRelationDef("CONFIRMS_EVENT_IMPACT", "reasoning-insight", "investment-core", "reasoning-insight", "뉴스·공시 영향이 가격·거래 반응으로 확인됐는지 추론합니다."),
    TBoxRelationDef("HAS_DILUTION_RISK", "risk-exposure", "investment-core", "risk-exposure", "공시가 자금조달, 지분 희석, 수급 부담 위험을 만들었는지 추론합니다."),
    TBoxRelationDef("HAS_ACTION_CANDIDATE", "reasoning-insight", "investment-core", "reasoning-insight"),
    TBoxRelationDef("USED_AS_EVIDENCE", "reasoning-insight", "reasoning-insight", "reasoning-insight"),
    TBoxRelationDef("CONFIRMS_SIGNAL", "reasoning-insight", "reasoning-insight", "reasoning-insight"),
    TBoxRelationDef("DIVERGES_FROM", "reasoning-insight", "reasoning-insight", "reasoning-insight"),
    TBoxRelationDef("DERIVES", "reasoning-insight", "reasoning-insight", "reasoning-insight"),
    TBoxRelationDef("AFFECTS", "reasoning-insight", "observation-data", "reasoning-insight"),
    TBoxRelationDef("IMPACTS_OPINION", "reasoning-insight", "reasoning-insight", "reasoning-insight"),
    TBoxRelationDef("CONTRIBUTES_TO", "reasoning-insight", "reasoning-insight", "strategy-thesis"),
    TBoxRelationDef("SUPPORTED_BY", "reasoning-insight", "investment-core", "reasoning-insight"),
    TBoxRelationDef("CONTRADICTS", "reasoning-insight", "reasoning-insight", "reasoning-insight"),
    TBoxRelationDef("USES_EVIDENCE_FROM", "reasoning-insight", "investment-core", "reasoning-insight"),
    TBoxRelationDef("REQUESTS_OPINION_FROM", "reasoning-insight", "investment-core", "reasoning-insight"),
    TBoxRelationDef("HAS_EVIDENCE", "reasoning-insight", "investment-core", "reasoning-insight"),
    TBoxRelationDef("HAS_BELIEF", "reasoning-insight", "investment-core", "reasoning-insight"),
    TBoxRelationDef("HAS_OPINION", "reasoning-insight", "investment-core", "reasoning-insight"),
    TBoxRelationDef("HAS_EXECUTION_PLAN", "reasoning-insight", "investment-core", "reasoning-insight"),
    TBoxRelationDef("HAS_MESSAGE_DELIVERY_PROFILE", "reasoning-insight", "investment-core", "reasoning-insight"),
    TBoxRelationDef("USES_MESSAGE_DELIVERY_PROFILE", "reasoning-insight", "investment-core", "reasoning-insight"),
    TBoxRelationDef("HAS_AI_CONTEXT_PACKET", "reasoning-insight", "reasoning-insight", "reasoning-insight"),
    TBoxRelationDef("HAS_EVIDENCE_SUBGRAPH", "reasoning-insight", "reasoning-insight", "reasoning-insight"),
    TBoxRelationDef("INCLUDES_EVIDENCE_RELATION", "reasoning-insight", "reasoning-insight", "reasoning-insight"),
    TBoxRelationDef("HAS_DECISION_DRIVER", "reasoning-insight", "reasoning-insight", "reasoning-insight"),
    TBoxRelationDef("HAS_TARGET_ROLE", "reasoning-insight", "investment-core", "reasoning-insight"),
    TBoxRelationDef("USES_ACTION_POLICY", "reasoning-insight", "investment-core", "reasoning-insight"),
    TBoxRelationDef("ALLOWS_ACTION", "reasoning-insight", "reasoning-insight", "reasoning-insight"),
    TBoxRelationDef("HAS_PRIMARY_ACTION", "reasoning-insight", "reasoning-insight", "reasoning-insight"),
    TBoxRelationDef("BLOCKS_ACTION", "reasoning-insight", "reasoning-insight", "reasoning-insight"),
    TBoxRelationDef("LIMITED_BY_LIQUIDITY", "risk-exposure", "reasoning-insight", "risk-exposure"),
    TBoxRelationDef("HAS_EXIT_CAPACITY", "risk-exposure", "reasoning-insight", "risk-exposure"),
    TBoxRelationDef("HAS_EXECUTION_CAPACITY", "risk-exposure", "reasoning-insight", "risk-exposure"),
    TBoxRelationDef("HAS_SLIPPAGE_RISK", "risk-exposure", "reasoning-insight", "risk-exposure"),
    TBoxRelationDef("STRENGTHENS_ACTION_IF", "reasoning-insight", "reasoning-insight", "reasoning-insight"),
    TBoxRelationDef("WEAKENS_ACTION_IF", "reasoning-insight", "reasoning-insight", "reasoning-insight"),
    TBoxRelationDef("REQUIRES_NEXT_CHECK", "reasoning-insight", "reasoning-insight", "reasoning-insight"),
    TBoxRelationDef("VALIDATES_OPINION", "reasoning-insight", "reasoning-insight", "reasoning-insight"),
    TBoxRelationDef("VALIDATES_DATA", "reasoning-insight", "reasoning-insight", "observation-data"),
    TBoxRelationDef("HAS_DECISION_AUDIT", "reasoning-insight", "reasoning-insight", "reasoning-insight"),
    TBoxRelationDef("PRODUCES_VALIDATED_MESSAGE", "operations-dispatch", "reasoning-insight", "operations-dispatch"),
    TBoxRelationDef("HAS_REASONING_CARD", "reasoning-insight", "investment-core", "reasoning-insight"),
    TBoxRelationDef("HAS_CONFIDENCE", "reasoning-insight", "reasoning-insight", "reasoning-insight"),
    TBoxRelationDef("CHANGES_FACT", "observation-data", "observation-data", "observation-data"),
    TBoxRelationDef("TRIGGERS_MATERIALITY_ASSESSMENT", "reasoning-insight", "observation-data", "reasoning-insight"),
    TBoxRelationDef("HAS_THRESHOLD_CROSSING", "reasoning-insight", "reasoning-insight", "reasoning-insight"),
    TBoxRelationDef("HAS_EXPOSURE_ASSESSMENT", "reasoning-insight", "reasoning-insight", "reasoning-insight"),
    TBoxRelationDef("HAS_CONFIDENCE_ASSESSMENT", "reasoning-insight", "reasoning-insight", "reasoning-insight"),
    TBoxRelationDef("HAS_ACTIONABILITY_ASSESSMENT", "reasoning-insight", "reasoning-insight", "reasoning-insight"),
    TBoxRelationDef("LOWERS_CONFIDENCE_OF", "reasoning-insight", "risk-exposure", "reasoning-insight"),
    TBoxRelationDef("AMPLIFIES_RISK", "risk-exposure", "reasoning-insight", "risk-exposure"),
    TBoxRelationDef("MITIGATES_RISK", "risk-exposure", "reasoning-insight", "risk-exposure"),
    TBoxRelationDef("HAS_PIPELINE", "operations-dispatch", "investment-core", "operations-dispatch"),
    TBoxRelationDef("COLLECTS_DATA_FROM", "operations-dispatch", "operations-dispatch", "observation-data"),
    TBoxRelationDef("RUNS_ON_SCHEDULE", "operations-dispatch", "operations-dispatch", "operations-dispatch"),
    TBoxRelationDef("RUNS_AFTER_EVENT", "operations-dispatch", "operations-dispatch", "operations-dispatch"),
    TBoxRelationDef("USES_COLLECTION_POLICY", "operations-dispatch", "operations-dispatch", "operations-dispatch"),
    TBoxRelationDef("HAS_DATA_FRESHNESS", "operations-dispatch", "operations-dispatch", "observation-data"),
    TBoxRelationDef("UPDATES_GRAPH", "operations-dispatch", "operations-dispatch", "investment-core"),
    TBoxRelationDef("TRIGGERS_REASONING", "operations-dispatch", "operations-dispatch", "operations-dispatch"),
    TBoxRelationDef("HAS_REASONING_CYCLE", "operations-dispatch", "investment-core", "operations-dispatch"),
    TBoxRelationDef("SCHEDULES_ANALYSIS", "operations-dispatch", "operations-dispatch", "operations-dispatch"),
    TBoxRelationDef("PRODUCES_INSIGHT", "operations-dispatch", "operations-dispatch", "reasoning-insight"),
    TBoxRelationDef("HAS_INSIGHT_TYPE", "reasoning-insight", "reasoning-insight", "reasoning-insight"),
    TBoxRelationDef("CREATED_FROM_RELATION", "reasoning-insight", "investment-core", "reasoning-insight"),
    TBoxRelationDef("EVALUATED_BY", "reasoning-insight", "reasoning-insight", "reasoning-insight"),
    TBoxRelationDef("USES_INSIGHT_POLICY", "operations-dispatch", "operations-dispatch", "reasoning-insight"),
    TBoxRelationDef("USES_IMPORTANCE_GATE", "operations-dispatch", "operations-dispatch", "operations-dispatch"),
    TBoxRelationDef("HAS_NOTIFICATION_POLICY", "operations-dispatch", "investment-core", "operations-dispatch"),
    TBoxRelationDef("HAS_NOTIFICATION_DISPATCH", "operations-dispatch", "investment-core", "operations-dispatch"),
    TBoxRelationDef("PASSES_IMPORTANCE_GATE", "operations-dispatch", "reasoning-insight", "operations-dispatch"),
    TBoxRelationDef("BLOCKED_BY_IMPORTANCE_GATE", "operations-dispatch", "reasoning-insight", "operations-dispatch"),
    TBoxRelationDef("CREATES_NOTIFICATION_INTENT", "operations-dispatch", "reasoning-insight", "operations-dispatch"),
    TBoxRelationDef("CREATES_ALERT_CANDIDATE", "operations-dispatch", "reasoning-insight", "operations-dispatch"),
    TBoxRelationDef("DISPATCHED_BY", "operations-dispatch", "reasoning-insight", "operations-dispatch"),
    TBoxRelationDef("SUPPRESSED_BY_POLICY", "operations-dispatch", "operations-dispatch", "operations-dispatch"),
    TBoxRelationDef("HAS_COOLDOWN_POLICY", "operations-dispatch", "operations-dispatch", "operations-dispatch"),
    TBoxRelationDef("HAS_NOVELTY_POLICY", "operations-dispatch", "operations-dispatch", "operations-dispatch"),
    TBoxRelationDef("OBSERVES_MARKET_SESSION", "operations-dispatch", "investment-core", "operations-dispatch"),
    TBoxRelationDef("TRIGGERS_ALERT", "operations-dispatch", "reasoning-insight", "operations-dispatch"),
]


RULE_DEFS: List[TBoxRuleDef] = [
    TBoxRuleDef("portfolio exposure, position weight, and sector concentration create risk beliefs", "risk-exposure"),
    TBoxRuleDef("price, trend, volume, and smart-money flow observations derive investable signals", "observation-data"),
    TBoxRuleDef("signals support, weaken, or invalidate an investment thesis before AI forms an opinion", "strategy-thesis"),
    TBoxRuleDef("legacy score model remains supporting evidence, not the primary decision model", "strategy-thesis"),
    TBoxRuleDef("legacy score disagreement with trend, flow, or risk creates contradiction beliefs", "reasoning-insight"),
    TBoxRuleDef("data quality, freshness, provenance, and missing data control AI opinion confidence", "observation-data"),
    TBoxRuleDef("watchlist candidates create observation assertions and entry checks, not sell decisions", "investment-core"),
    TBoxRuleDef("all runtime concepts become ABox nodes before AI receives an opinion packet", "operations-dispatch"),
    TBoxRuleDef("relations with opinionImpact, riskImpact, supportImpact, or polarity change AI opinion pressure", "reasoning-insight"),
    TBoxRuleDef("execution plans are ABox nodes derived from facts, active relation rules, counter signals, and missing data before notification rendering", "reasoning-insight"),
    TBoxRuleDef("AI validation validates an active investment opinion and execution plan before notification dispatch", "reasoning-insight"),
    TBoxRuleDef("data collection, analysis, reasoning, and notification dispatch are first-class ontology concepts", "operations-dispatch"),
    TBoxRuleDef("notification dispatch is driven by meaningful ontology insights, not by alert-type polling alone", "operations-dispatch"),
    TBoxRuleDef("fact changes must pass a materiality assessment before they trigger ontology reasoning or notification intent", "reasoning-insight"),
    TBoxRuleDef("materiality combines threshold crossings, novelty, exposure, confidence, and actionability before dispatch", "reasoning-insight"),
    TBoxRuleDef("collection schedules describe data freshness targets while cooldown, novelty, and suppression policies control delivery noise", "operations-dispatch"),
    TBoxRuleDef("price-bar sequence, key levels, and relation-state transitions distinguish confirmation, failure, and acceleration", "observation-data"),
    TBoxRuleDef("price path transitions such as falling-to-rebound, sideways breakout, sideways breakdown, and rising-to-distribution can change investment thesis confidence", "reasoning-insight"),
    TBoxRuleDef("individual news, disclosure, macro, earnings, and analyst events are ABox evidence objects that can support, weaken, or invalidate a thesis", "observation-data"),
    TBoxRuleDef("news relevance scope separates direct instrument evidence from peer, sector, market, and noise context before rules score it", "observation-data"),
    TBoxRuleDef("factor exposure, benchmark beta, and correlation clusters transmit market-regime risk across positions", "risk-exposure"),
    TBoxRuleDef("liquidity profile, exit capacity, and slippage risk constrain execution plans before alert dispatch", "risk-exposure"),
    TBoxRuleDef("source reliability and observation confidence weight evidence before AI receives the graph", "observation-data"),
    TBoxRuleDef("coverage gaps are ABox data-quality facts that lower confidence before an AI opinion is allowed to sound decisive", "observation-data"),
    TBoxRuleDef("crypto assets must carry price, price path, liquidity, data quality, and exposure relations before they can alter a stock thesis", "risk-exposure"),
    TBoxRuleDef("macro regimes combine rates, yield curve, FX, and rate-sensitive position context before deriving risk or support", "risk-exposure"),
    TBoxRuleDef("news body availability and subject confirmation are data-quality facts that can lower confidence independently from headline polarity", "observation-data"),
    TBoxRuleDef("fundamental and valuation evidence affects confidence only after provenance and coverage gates are visible in ABox", "strategy-thesis"),
    TBoxRuleDef("RuleBox stores executable graph inference rules as first-class ontology nodes linked to their conditions and derived relation templates", "reasoning-insight"),
    TBoxRuleDef("InferenceBox stores derived assertions, inference traces, matched conditions, and source relation ids so new ABox facts can immediately affect opinions", "reasoning-insight"),
    TBoxRuleDef("The active graph store projection preserves TBox, RuleBox, ABox, and InferenceBox as queryable ontology layers instead of flattening rule output into text", "operations-dispatch"),
    TBoxRuleDef("TypeDB executes RuleBox conditions and materializes InferenceBox facts, traces, evidence, beliefs, and derived relations after graph persistence", "reasoning-insight"),
    TBoxRuleDef("companies issue securities, securities represent tradable instruments, and peer groups transmit sector and competitive context before AI forms an opinion", "investment-core"),
    TBoxRuleDef("market-data changes become FactChange and MaterialityAssessment ABox nodes before any alert candidate is created", "observation-data"),
    TBoxRuleDef("trend transitions remain ABox facts in the active graph store even when local Python opinions are disabled for production projection", "reasoning-insight"),
    TBoxRuleDef("AI receives a compact evidence subgraph built from InferenceBox relations, traces, current facts, missing data, and source freshness instead of an undifferentiated raw dump", "reasoning-insight"),
    TBoxRuleDef("RuleBox graph conditions can filter ABox fact values such as trade strength, volume ratio, orderbook imbalance, materiality score, event type, and relation scope before deriving opinions", "reasoning-insight"),
    TBoxRuleDef("material direct news, disclosures, trade-flow pressure, trend transitions, and fact-change gates can each independently create InferenceBox relations that alter AI investment opinions", "reasoning-insight"),
    TBoxRuleDef("RuleBox relation templates own decisionStage and stagePriority so graph-store policy, not rule-id code maps, controls AI decision routing", "reasoning-insight"),
    TBoxRuleDef("RuleBox relation templates and InferenceBox assertions carry targetRole, actionPolicy, allowedActions, and blockedActions so watchlist candidates stay entry-only before AI validation", "reasoning-insight"),
    TBoxRuleDef("loss-position smart-money inflow first weakens sell pressure, and only investor-profile-gated recovery confirmation can open conditional add-buy review", "reasoning-insight"),
    TBoxRuleDef("foreign, institutional, and retail investor flow psychology derives accumulation, absorption, or retail-dip-buying risk before add-buy and trim opinions are formed", "reasoning-insight"),
    TBoxRuleDef("instrument profiles classify each security into archetypes, sensitivities, position intent, and action policies before RuleBox decides add, hold, trim, or sell", "strategy-thesis"),
    TBoxRuleDef("RuleBox changes must produce governance versions and reviewable rule-change candidates before candidate rules affect InferenceBox decisions", "reasoning-insight"),
]


TBOX_CLASSES = [item.name for item in CLASS_DEFS]
TBOX_RELATION_TYPES = [item.name for item in RELATION_DEFS]
TBOX_REASONING_RULES = [item.text for item in RULE_DEFS]

_CLASS_BY_NAME: Dict[str, TBoxClassDef] = {item.name: item for item in CLASS_DEFS}
_RELATION_BY_NAME: Dict[str, TBoxRelationDef] = {item.name: item for item in RELATION_DEFS}

_ABSTRACT_CLASS_NAMES = {
    "Instrument",
    "Security",
    "Equity",
    "Observation",
    "ExternalObservation",
    "ExternalSignal",
    "Risk",
    "Signal",
    "Evidence",
    "Belief",
    "Opinion",
    "ReasoningRule",
    "RuleRegistry",
    "RuleCondition",
    "RelationTemplate",
}

_SOURCE_BACKED_CLASS_NAMES = {
    "Portfolio",
    "Account",
    "Company",
    "Stock",
    "ETF",
    "CryptoAsset",
    "CashAsset",
    "Derivative",
    "Index",
    "FXPair",
    "Position",
    "Watchlist",
    "WatchlistCandidate",
    "Sector",
    "Industry",
    "PeerGroup",
    "Market",
    "Currency",
    "Cash",
    "MarketExposure",
    "FactChange",
    "PriceObservation",
    "VolumeObservation",
    "TechnicalObservation",
    "FlowObservation",
    "FundamentalObservation",
    "PriceMetric",
    "TechnicalIndicator",
    "TradeFlow",
    "DataQuality",
    "DataSource",
    "DataFreshness",
    "DataLatency",
    "MissingData",
    "CoverageGap",
    "Provenance",
    "SourceReliability",
    "ObservationConfidence",
    "TimeWindow",
    "ObservationTime",
    "SignalHorizon",
    "HoldingPeriod",
    "ValidityInterval",
    "Staleness",
    "ValidationRule",
    "PriceBar",
    "PricePath",
    "VolumeProfile",
    "KeyLevel",
    "SupportLevel",
    "ResistanceLevel",
    "Breakout",
    "FailedBreakout",
    "Retest",
    "ResearchEvidence",
    "NewsEvent",
    "NewsArticle",
    "ArticleAIAnalysis",
    "NewsTopic",
    "NewsEventType",
    "PeerCompanyMention",
    "DisclosureEvent",
    "DisclosureFiling",
    "MacroIndicator",
    "MacroPrint",
    "MacroRegime",
    "RateSignal",
    "InterestRate",
    "YieldCurve",
    "FXRateSignal",
    "CreditSpreadSignal",
    "CryptoMarketSignal",
    "EarningsEvent",
    "EarningsCalendarEvent",
    "AnalystRevision",
    "CorporateAction",
    "RegulatoryEvent",
    "ProductLine",
    "SupplyChainExposure",
    "CustomerExposure",
    "RevenueExposure",
    "Factor",
    "FactorExposure",
    "FactorSensitivity",
    "BenchmarkIndex",
    "HedgeCandidate",
    "Strategy",
    "InstrumentProfile",
    "InvestmentArchetype",
    "GrowthStock",
    "AIGrowth",
    "HighVolatilityGrowth",
    "MegaCapQuality",
    "PlatformGrowth",
    "DividendIncome",
    "PreferredIncome",
    "BitcoinProxy",
    "BitcoinSensitiveIncome",
    "CryptoAssetProfile",
    "SemiconductorCyclical",
    "SemiconductorHBM",
    "CyclicalGrowth",
    "EquityGeneral",
    "PositionIntent",
    "InvestmentThesis",
    "EntryCondition",
    "ExitCondition",
    "RiskManagementRule",
    "RebalancingRule",
    "PositionSizingRule",
    "Scenario",
    "StrategyExperiment",
    "StrategySignal",
    "ModelScore",
    "Threshold",
    "RuntimeSetting",
    "AlertRule",
    "PromptTemplate",
    "ValuationAssumption",
    "LegacyScoreModel",
    "MarketRisk",
    "LiquidityRisk",
    "LiquidityProfile",
    "ExitCapacity",
    "ExecutionMetric",
    "ExecutionCapacity",
    "PositionExitExposure",
    "SlippageEstimate",
    "ConcentrationRisk",
    "CurrencyRisk",
    "VolatilityRisk",
    "CryptoExposure",
    "EventRisk",
    "DataQualityRisk",
    "ArticleQualityRisk",
    "ModelRisk",
    "ExecutionRisk",
    "CorrelationRisk",
    "RegimeRisk",
}

_INFERRED_CLASS_NAMES = {
    "PriceSignal",
    "TrendSignal",
    "FlowSignal",
    "ValuationSignal",
    "MacroSignal",
    "DisclosureSignal",
    "CryptoSignal",
    "DataQualitySignal",
    "RelationStateSnapshot",
    "SignalTransition",
    "TrendPhase",
    "TrendTransition",
    "ReversalSignal",
    "ConsolidationBreak",
    "AccelerationSignal",
    "DecelerationSignal",
    "MaterialityAssessment",
    "ThresholdCrossing",
    "ExposureAssessment",
    "ConfidenceAssessment",
    "ActionabilityAssessment",
    "PreviousInsight",
    "ActiveInvestmentOpinion",
    "ExecutionPlan",
    "DecisionDriver",
    "ActionCandidate",
    "BlockedAction",
    "InvalidationCondition",
    "NextCheck",
    "AIValidation",
    "ValidatedOpinion",
    "AIJudgmentAudit",
    "AIContextPacket",
    "EvidenceSubgraph",
    "GraphNeighborhood",
    "Opportunity",
    "Contradiction",
    "Insight",
    "InsightType",
    "InsightPolicy",
    "MessageDeliveryProfile",
    "DerivedAssertion",
    "InferenceTrace",
    "InferencePath",
    "GraphReasoner",
    "GraphStoreNativeReasoner",
    "TypeDBNativeReasoner",
    "ReasoningCard",
    "ConfidenceScore",
    "ReliabilityScore",
    "AIReview",
}

_RULEBOX_CLASS_NAMES = {
    "RelationRuleRegistry",
    "GraphInferenceRule",
    "RelationReasoningRule",
    "RelationRuleCondition",
    "RelationRuleTemplate",
    "RuleDecisionPolicy",
    "RulePriorityPolicy",
}

_GOVERNANCE_CLASS_NAMES = {
    "RuleBoxGovernance",
    "RuleBoxVersion",
    "RuleChangeCandidate",
}

_OPERATIONAL_CLASS_NAMES = {
    "DataPipeline",
    "CollectionSchedule",
    "CollectionPolicy",
    "MarketSnapshot",
    "WatchlistSnapshot",
    "ExternalSignalCollection",
    "AnalysisJob",
    "ReasoningCycle",
    "NotificationPolicy",
    "NotificationDispatch",
    "NotificationIntent",
    "AlertCandidate",
    "ImportanceGate",
    "CooldownPolicy",
    "NoveltyPolicy",
    "SuppressionPolicy",
    "MarketSession",
    "OperationalEvent",
}

_SCHEMA_RELATION_NAMES = {
    "DEFINES_BOUNDED_CONTEXT",
    "DEFINES_CLASS",
    "DEFINES_RELATION",
    "CONSTRAINS_ASSERTIONS",
    "CONSTRAINS_RULES",
    "DERIVES_ASSERTIONS",
    "IS_A",
}

_RULEBOX_RELATION_NAMES = {
    "HAS_RULE_CONDITION",
    "USES_RULE_TEMPLATE",
    "MATCHES_CONDITION",
    "PRODUCES_DERIVED_ASSERTION",
    "DERIVES_RELATION",
    "GOVERNED_BY",
    "PROPOSES_RULE_CHANGE",
    "SUPERSEDES_RULE_VERSION",
}


def tbox_class_def(name: str) -> Optional[TBoxClassDef]:
    return _CLASS_BY_NAME.get(str(name or ""))


def tbox_relation_def(name: str) -> Optional[TBoxRelationDef]:
    return _RELATION_BY_NAME.get(str(name or "").upper())


def tbox_class_materialization_policy(name: str) -> str:
    value = str(name or "")
    if value in _GOVERNANCE_CLASS_NAMES:
        return "governance"
    if value in _RULEBOX_CLASS_NAMES:
        return "rulebox"
    if value in _INFERRED_CLASS_NAMES:
        return "inferred"
    if value in _OPERATIONAL_CLASS_NAMES:
        return "operational"
    if value in _SOURCE_BACKED_CLASS_NAMES:
        return "source-backed"
    if value in _ABSTRACT_CLASS_NAMES:
        return "abstract"
    return "source-backed"


def tbox_materialization_box(policy: str) -> str:
    value = str(policy or "")
    if value in {"abstract", "schema"}:
        return "TBox"
    if value == "rulebox":
        return "RuleBox"
    if value == "governance":
        return "RuleBoxGovernance"
    if value == "inferred":
        return "InferenceBox"
    return "ABox"


def tbox_relation_materialization_policy(name: str) -> str:
    value = str(name or "").upper()
    if value in _SCHEMA_RELATION_NAMES:
        return "schema"
    if value in _RULEBOX_RELATION_NAMES:
        return "rulebox"
    definition = tbox_relation_def(value)
    if definition and definition.bounded_context in {"reasoning-insight", "operations-dispatch"}:
        return "inferred-or-operational"
    return "source-backed"


def bounded_contexts_payload() -> List[Dict[str, object]]:
    return [asdict(item) for item in BOUNDED_CONTEXTS]


def class_definitions_payload() -> List[Dict[str, object]]:
    rows: List[Dict[str, object]] = []
    for item in CLASS_DEFS:
        payload = asdict(item)
        policy = tbox_class_materialization_policy(item.name)
        payload["materializationPolicy"] = policy
        payload["materializationBox"] = tbox_materialization_box(policy)
        rows.append(payload)
    return rows


def relation_definitions_payload() -> List[Dict[str, object]]:
    rows: List[Dict[str, object]] = []
    for item in RELATION_DEFS:
        payload = asdict(item)
        policy = tbox_relation_materialization_policy(item.name)
        payload["materializationPolicy"] = policy
        payload["materializationBox"] = tbox_materialization_box(policy)
        rows.append(payload)
    return rows


def rule_definitions_payload() -> List[Dict[str, object]]:
    return [asdict(item) for item in RULE_DEFS]
