"""Bootstrap ontology relation catalog.

Use active TypeDB schema-function RuleBox/InferenceBox output for runtime reasoning behavior.
The defaults here seed ontology/native-rule management views and prompt read models when no
graph-store rules have been saved yet; they are not a Python fallback reasoner.
"""

from .ontology_relation_contracts import (
    DecisionStageDefinition,
    RelationRuleDefinition,
    ScoreBandDefinition,
)


SCORE_BANDS = [
    ScoreBandDefinition("URGENT", "매우 강함", 85.0, "urgent", "즉시 재확인이 필요한 매우 강한 관계 신호", 0.0),
    ScoreBandDefinition("ACTION", "강함", 70.0, "action", "대응 기준을 확인할 만큼 강한 관계 신호", 85.0),
    ScoreBandDefinition("REVIEW", "주의", 55.0, "review", "관찰을 유지해야 하는 관계 신호", 70.0),
    ScoreBandDefinition("WATCH", "관찰", 35.0, "watch", "추적은 필요하지만 단독 판단 근거는 약한 관계 신호", 55.0),
    ScoreBandDefinition("LOW", "낮음", 0.0, "reference", "참고 수준의 약한 관계 신호", 35.0),
]


DECISION_STAGE_DEFINITIONS = {
    "RELATION_WATCH": DecisionStageDefinition("RELATION_WATCH", "holdWatch", "watch", "관계 규칙 관찰", "hold", 35.0, 55.0),
    "HOLD_KEEP": DecisionStageDefinition("HOLD_KEEP", "holdWatch", "watch", "보유 유지", "watch", 0.0, 35.0),
    "LOSS_WATCH": DecisionStageDefinition("LOSS_WATCH", "lossControl", "watch", "손실 방어 관망", "hold", 0.0, 55.0),
    "LOSS_REDUCE": DecisionStageDefinition("LOSS_REDUCE", "lossControl", "review", "손실 축소 권장", "caution", 55.0, 70.0),
    "LOSS_CUT": DecisionStageDefinition("LOSS_CUT", "lossControl", "action", "손절·분할축소 권장", "danger", 70.0, 85.0),
    "PROFIT_PARTIAL": DecisionStageDefinition("PROFIT_PARTIAL", "profitTake", "review", "일부 익절 권장", "caution", 55.0, 70.0),
    "PROFIT_SPLIT": DecisionStageDefinition("PROFIT_SPLIT", "profitTake", "action", "분할매도 권장", "caution", 70.0, 85.0),
    "REBALANCE_REVIEW": DecisionStageDefinition("REBALANCE_REVIEW", "rebalance", "review", "리밸런싱 점검", "caution", 55.0, 70.0),
    "REBALANCE_ACTION": DecisionStageDefinition("REBALANCE_ACTION", "rebalance", "action", "리밸런싱 권장", "caution", 70.0, 85.0),
    "BTC_REVIEW": DecisionStageDefinition("BTC_REVIEW", "cryptoSensitivity", "review", "비트코인 민감도 점검", "watch", 55.0, 70.0),
    "BTC_REDUCE": DecisionStageDefinition("BTC_REDUCE", "cryptoSensitivity", "action", "비트코인 민감도 축소 검토", "caution", 70.0, 85.0),
    "DISCLOSURE_REVIEW": DecisionStageDefinition("DISCLOSURE_REVIEW", "disclosure", "review", "공시 리스크 대응 검토", "caution", 55.0, 70.0),
    "NEWS_RISK": DecisionStageDefinition("NEWS_RISK", "eventRisk", "review", "뉴스 리스크 대응 검토", "caution", 55.0, 70.0),
    "NEWS_CONFIRMATION": DecisionStageDefinition("NEWS_CONFIRMATION", "eventConfirmation", "review", "뉴스·가격 동조 확인", "watch", 55.0, 70.0),
    "SECTOR_NEWS": DecisionStageDefinition("SECTOR_NEWS", "sectorContext", "watch", "섹터·피어 뉴스 영향 점검", "watch", 35.0, 55.0),
    "FLOW_WATCH": DecisionStageDefinition("FLOW_WATCH", "flowTrend", "watch", "수급·추세 관찰", "watch", 35.0, 55.0),
    "FLOW_DEFENSE": DecisionStageDefinition("FLOW_DEFENSE", "flowTrend", "review", "수급·추세 방어 권장", "caution", 55.0, 70.0),
    "SUPPORT_RETEST": DecisionStageDefinition("SUPPORT_RETEST", "trendReview", "review", "60일선 지지 재확인", "hold", 55.0, 70.0),
    "RECOVERY_CONFIRM": DecisionStageDefinition("RECOVERY_CONFIRM", "recovery", "review", "회복 시도 확인", "watch", 55.0, 70.0),
    "BREAKDOWN_ACCELERATION": DecisionStageDefinition("BREAKDOWN_ACCELERATION", "lossControl", "action", "하락 가속 대응 점검", "danger", 70.0, 85.0),
    "BREAKOUT_FAILURE": DecisionStageDefinition("BREAKOUT_FAILURE", "lossControl", "action", "돌파 실패 리스크 점검", "danger", 70.0, 85.0),
    "SUPPORT_RETEST_FAILED": DecisionStageDefinition("SUPPORT_RETEST_FAILED", "lossControl", "review", "지지선 실패 점검", "caution", 55.0, 70.0),
    "DISTRIBUTION_REVIEW": DecisionStageDefinition("DISTRIBUTION_REVIEW", "distributionRisk", "review", "분산매도 의심 점검", "caution", 55.0, 70.0),
    "EXECUTION_OK": DecisionStageDefinition("EXECUTION_OK", "executionRisk", "watch", "실행 가능 용량 확인", "watch", 0.0, 35.0),
    "LIQUIDITY_REVIEW": DecisionStageDefinition("LIQUIDITY_REVIEW", "executionRisk", "review", "유동성 실행 점검", "caution", 55.0, 70.0),
    "LIQUIDITY_ACTION": DecisionStageDefinition("LIQUIDITY_ACTION", "executionRisk", "action", "분할 실행 우선", "caution", 70.0, 85.0),
    "FACTOR_CROWDING": DecisionStageDefinition("FACTOR_CROWDING", "factorRisk", "review", "팩터 과밀 점검", "caution", 55.0, 70.0),
    "DATA_CONFLICT": DecisionStageDefinition("DATA_CONFLICT", "dataQuality", "review", "데이터 충돌 점검", "caution", 55.0, 70.0),
    "PROFIT_PROTECT": DecisionStageDefinition("PROFIT_PROTECT", "profitTake", "review", "수익 보호 점검", "caution", 55.0, 70.0),
    "MACRO_REGIME": DecisionStageDefinition("MACRO_REGIME", "macroRegime", "review", "거시 레짐 점검", "watch", 55.0, 70.0),
    "RATE_REVIEW": DecisionStageDefinition("RATE_REVIEW", "rateRegime", "review", "금리 민감도 점검", "watch", 55.0, 70.0),
    "RATE_ACTION": DecisionStageDefinition("RATE_ACTION", "rateRegime", "action", "금리 리스크 대응 점검", "caution", 70.0, 85.0),
    "FX_REVIEW": DecisionStageDefinition("FX_REVIEW", "fxRegime", "review", "환율 민감도 점검", "watch", 55.0, 70.0),
    "FX_ACTION": DecisionStageDefinition("FX_ACTION", "fxRegime", "action", "환율 리스크 대응 점검", "caution", 70.0, 85.0),
    "MARKET_STRUCTURE": DecisionStageDefinition("MARKET_STRUCTURE", "marketStructure", "review", "시장 구조 리스크 점검", "caution", 55.0, 70.0),
    "ENTRY_WATCH": DecisionStageDefinition("ENTRY_WATCH", "entryWait", "watch", "신규 진입 관찰", "watch", 35.0, 55.0),
    "ENTRY_WAIT": DecisionStageDefinition("ENTRY_WAIT", "entryWait", "review", "신규 진입 대기", "watch", 55.0, 70.0),
    "ENTRY_SPLIT_BUY": DecisionStageDefinition("ENTRY_SPLIT_BUY", "entry", "review", "소액 진입 검토", "watch", 55.0, 70.0),
    "ENTRY_READY": DecisionStageDefinition("ENTRY_READY", "entry", "action", "소액 분할매수 검토", "caution", 70.0, 85.0),
    "ADD_BUY_WATCH": DecisionStageDefinition("ADD_BUY_WATCH", "addBuy", "watch", "추가매수 관찰", "watch", 35.0, 55.0),
    "ADD_BUY_REVIEW": DecisionStageDefinition("ADD_BUY_REVIEW", "addBuy", "review", "조건부 추가매수 검토", "watch", 55.0, 70.0),
    "ADD_BUY_BLOCKED": DecisionStageDefinition("ADD_BUY_BLOCKED", "entryRisk", "review", "추가매수 보류", "caution", 55.0, 70.0),
}


DECISION_LABEL_ALIASES = {
    "조건부 보유": "HOLD_KEEP",
    "손절 기준 확인": "LOSS_CUT",
    "손실 관리 기준 확인": "LOSS_REDUCE",
    "손실 기준 근접 관찰": "LOSS_REDUCE",
    "분할 매도 기준 확인": "PROFIT_SPLIT",
    "익절 점검": "PROFIT_PARTIAL",
    "리밸런싱 점검": "REBALANCE_REVIEW",
    "60일선 지지 재확인": "SUPPORT_RETEST",
    "회복 시도 확인": "RECOVERY_CONFIRM",
    "하락 가속 대응 점검": "BREAKDOWN_ACCELERATION",
    "추가매수 관찰": "ADD_BUY_WATCH",
    "조건부 추가매수 검토": "ADD_BUY_REVIEW",
    "추가매수 보류": "ADD_BUY_BLOCKED",
}


DEFAULT_RELATION_RULES = [
    RelationRuleDefinition(
        "holding.profit_take.trend_weakness.v1",
        "수익 보유 + 추세 약화 -> 익절 점검",
        "v1",
        "PROFIT_TAKE_REVIEW",
        "exit_timing",
        "손익률이 +10% 이상이고 20일선 아래이거나 60일선 대비 약해질 때",
        "익절을 서두르라는 결론보다 분할 매도, 추세 회복 조건, 유지 조건을 함께 비교합니다.",
        ["profitLossRate", "currentPrice", "ma20", "ma60"],
    ),
    RelationRuleDefinition(
        "holding.loss_guard.breakdown.v1",
        "손실 보유 + 기준선 이탈 -> 손실 관리",
        "v1",
        "LOSS_GUARD",
        "risk_control",
        "손익률이 손실 기준 이하이거나 20일선보다 5% 이상 낮고, 60일선·거래량·수급 확인 강도로 점수를 조정할 때",
        "손절 여부만 묻지 말고 손실 확대 요인, 60일선 유지, 거래량 동반 여부, 회복 조건, 분할 대응 기준을 분리합니다.",
        ["profitLossRate", "currentPrice", "ma20", "ma60", "volumeRatio", "sellableQuantity"],
    ),
    RelationRuleDefinition(
        "holding.concentration.rebalance.v1",
        "업종 집중 + 보유 비중 과대 -> 리밸런싱 점검",
        "v1",
        "CONCENTRATION_RISK",
        "portfolio_risk",
        "업종 비중 50% 이상 또는 단일 종목 비중 30% 이상일 때",
        "개별 종목 판단과 포트폴리오 리스크를 분리해서 설명합니다.",
        ["sectorRatio", "positionWeight"],
    ),
    RelationRuleDefinition(
        "holding.trend_flow.confirmation.v1",
        "추세와 수급 방향 일치 -> 판단 신뢰도 보강",
        "v1",
        "EVIDENCE_SUPPORT",
        "confirmation",
        "20일/60일 추세와 외국인·기관 순매수 방향이 같은 쪽으로 움직일 때",
        "같은 방향 근거와 반대 근거를 나눠 AI에게 검토시킵니다.",
        ["ma20Distance", "ma60Distance", "foreignNetVolume", "institutionNetVolume"],
    ),
    RelationRuleDefinition(
        "holding.loss_smart_money.defense.v1",
        "손실 보유 + 외국인·기관 동반 순매수 -> 매도 강도 완화",
        "v1",
        "LOSS_DEFENSE_EVIDENCE",
        "flow_defense",
        "손실 보유 중이지만 외국인과 기관이 동시에 순매수할 때",
        "동반 순매수를 즉시 추가매수 신호로 보지 않고, 먼저 손실 방어·매도 강도를 낮추는 반대 근거로 설명합니다.",
        ["profitLossRate", "foreignNetVolume", "institutionNetVolume", "investorFlowScore", "investmentStrategyProfile"],
    ),
    RelationRuleDefinition(
        "holding.investor_flow.smart_money_accumulation.v1",
        "외국인·기관 매집 심리 -> 수급 방어",
        "v1",
        "LOSS_DEFENSE_EVIDENCE",
        "flow_psychology",
        "외국인과 기관이 순매수하고 개인이 순매도하거나 큰 자금 합산 매수가 확인될 때",
        "무조건 추가매수 신호가 아니라 매도 강도를 낮추는 근거와 회복 확인 조건으로 설명합니다.",
        ["foreignNetVolume", "institutionNetVolume", "individualNetVolume", "investorFlowPsychology"],
    ),
    RelationRuleDefinition(
        "holding.investor_flow.retail_dip_buying_risk.v1",
        "외국인·기관 매도 + 개인 순매수 -> 물타기 위험",
        "v1",
        "AVERAGING_DOWN_RISK",
        "flow_psychology",
        "외국인과 기관이 같이 팔고 개인이 순매수할 때",
        "개인 저가매수가 성공 신호인지보다, 큰 자금 매도 물량을 개인이 받아내는 위험인지 먼저 설명합니다.",
        ["foreignNetVolume", "institutionNetVolume", "individualNetVolume", "investorFlowPsychology"],
    ),
    RelationRuleDefinition(
        "holding.investor_flow.smart_money_outflow_risk.v1",
        "큰 자금 순매도 심리 -> 수급 리스크",
        "v1",
        "FLOW_RISK",
        "flow_psychology",
        "외국인·기관 합산 또는 동반 순매도 흐름이 확인될 때",
        "가격 방향 단정이 아니라 수급 부담과 분할 실행 기준을 확인해야 하는 근거로 설명합니다.",
        ["foreignNetVolume", "institutionNetVolume", "investorFlowPsychology"],
    ),
    RelationRuleDefinition(
        "cross_listing.adr_premium_risk.v1",
        "본주 + ADR 가격 괴리 -> 교차 시장 리스크",
        "v1",
        "MARKET_STRUCTURE",
        "market_structure",
        "ADR 환산 가격이 본주보다 크게 비싸거나 싸고 전환·차익거래 제약이 남아 있을 때",
        "본주 가격만 보지 말고 ADR 프리미엄, 전환 가능일, 환율, 해외 투자자 수요가 만든 괴리를 함께 설명합니다.",
        ["adrPremiumPct", "adrRatio", "usdKrwRate", "conversionStartDate", "listingDate"],
    ),
    RelationRuleDefinition(
        "security_line.leveraged_flow_amplification.v1",
        "단일종목 레버리지 ETF + 거래 신호 -> 수급 증폭 리스크",
        "v1",
        "MARKET_STRUCTURE",
        "market_structure",
        "기초 ADR을 추종하는 2x/-2x 단일종목 ETF 가격이나 거래량이 관측될 때",
        "레버리지 ETF를 매수·매도 지시로 해석하지 않고, 일일 리셋과 파생 헤지 수급이 본주 변동성을 키울 수 있는 구조로 설명합니다.",
        ["leverageFactor", "etfSymbol", "underlyingSymbol", "volume", "latestTradingDay"],
    ),
    RelationRuleDefinition(
        "security_line.coverage_gap.v1",
        "ADR·레버리지 라인 시세 부족 -> 시장 구조 데이터 보강",
        "v1",
        "DATA_CONFLICT",
        "data_quality",
        "보유 종목의 ADR, 환율, 본주, 레버리지 ETF 중 하나라도 없어 가격 괴리나 수급 증폭을 계산하지 못할 때",
        "방향 판단보다 어떤 라인의 시세와 거래량을 추가 수집해야 하는지 AI가 사용자에게 피드백합니다.",
        ["adrPrice", "usdKrwRate", "localSharePrice", "leveragedEtfQuote"],
    ),
    RelationRuleDefinition(
        "holding.loss_smart_money.reversal_watch.v1",
        "손실 보유 + 동반 순매수 + 회복 일부 -> 추가매수 관찰",
        "v1",
        "ADD_BUY_WATCH",
        "add_buy_watch",
        "손실 보유, 외국인·기관 동반 순매수, 회복 확인 신호 일부가 함께 있을 때",
        "추가매수 결론이 아니라 어떤 조건이 더 채워지면 검토 단계로 올라가는지 분리해서 설명합니다.",
        ["profitLossRate", "lossRecoverySignalCount", "addBuyEligibilityStage", "investmentStrategyProfile"],
    ),
    RelationRuleDefinition(
        "holding.loss_smart_money.add_buy_review.v1",
        "손실 보유 + 동반 순매수 + 회복 확인 -> 조건부 추가매수 검토",
        "v1",
        "ADD_BUY_ELIGIBILITY",
        "add_buy_review",
        "투자 성향별 회복 확인 기준, 악재 뉴스, 비중 한도를 통과했을 때",
        "즉시 몰아서 사는 판단이 아니라 소액 분할 추가매수 검토와 무효화 조건을 함께 설명합니다.",
        ["profitLossRate", "lossRecoverySignalCount", "addBuyEligibilityStage", "positionAccountWeight", "directRiskNewsCount"],
    ),
    RelationRuleDefinition(
        "holding.winner_momentum.add_buy_review.v1",
        "수익 보유 + 상승 추세 확인 -> 조건부 추가매수 검토",
        "v1",
        "ADD_BUY_ELIGIBILITY",
        "add_buy_review",
        "보유 종목이 수익 구간이고 5일·20일·60일 평균 가격 위에서 거래 확인이 붙을 때",
        "오르는 종목을 무조건 팔지 않고, 비중 한도와 무효화 조건을 전제로 소액 분할 추가매수 가능성을 검토합니다.",
        ["profitLossRate", "ma5Distance", "ma20Distance", "ma60Distance", "volumeRatio", "positionAccountWeight"],
    ),
    RelationRuleDefinition(
        "trend.support_retest.v1",
        "단기선 이탈 + 60일선 지지 -> 지지선 재확인",
        "v1",
        "SUPPORT_RETEST",
        "trend_context",
        "현재가가 20일선 아래로 크게 밀렸지만 60일선 부근 또는 위에서 버틸 때",
        "손절 결론을 바로 내리지 말고 60일선 지지 유지, 반등 시도, 거래량 동반 여부를 함께 검토합니다.",
        ["currentPrice", "ma20", "ma60", "ma20Distance", "ma60Distance", "priceChangeRate"],
    ),
    RelationRuleDefinition(
        "trend.recovery_attempt.v1",
        "손실/눌림 + 반등 커브 -> 회복 확인",
        "v1",
        "RECOVERY_ATTEMPT",
        "trend_recovery",
        "20일선 아래 또는 손실 구간에서 가격 모멘텀·단기 기울기·커브가 회복 쪽으로 돌아설 때",
        "회복 시도와 단순 낙폭 과대를 분리하고, 추가매수보다 확인 조건을 먼저 제시합니다.",
        ["profitLossRate", "priceChangeRate", "ma20Slope", "ma60Slope", "trendCurve"],
    ),
    RelationRuleDefinition(
        "trend.breakdown_acceleration.v1",
        "추세 훼손 + 하락 가속 -> 리스크 강화",
        "v1",
        "BREAKDOWN_ACCELERATION",
        "trend_acceleration",
        "20일선 이탈 상태에서 가격 하락, 단기 기울기 하락, 하락 커브 확대 또는 중기선 동반 약화가 겹칠 때",
        "현재 위치만 보지 말고 하락 속도와 커브 확대를 AI가 별도 위험 요인으로 검토합니다.",
        ["currentPrice", "ma20", "ma60", "priceChangeRate", "ma20Slope", "ma60Slope", "trendCurve"],
    ),
    RelationRuleDefinition(
        "breakout.failure.v1",
        "회복/돌파 후 재이탈 -> 실패 리스크",
        "v1",
        "FAILED_BREAKOUT",
        "trend_failure",
        "이전에는 20일선 위 또는 회복 상태였으나 현재 20일선을 재이탈하고 하락/거래량/매도 압력이 붙을 때",
        "단순 하락보다 회복 실패를 더 강한 경고로 보고, 재진입/추가매수보다 무효화 조건을 먼저 검토합니다.",
        ["previousMa20Distance", "ma20Distance", "priceChangeRate", "volumeRatio", "sellShare"],
    ),
    RelationRuleDefinition(
        "support.retest.failed.v1",
        "60일선 재시험 실패 -> 지지 실패",
        "v1",
        "SUPPORT_FAILURE",
        "trend_failure",
        "60일선 부근 재시험 후 현재 60일선 아래로 밀리거나 하락 커브가 확대될 때",
        "60일선 방어가 깨진 상태인지, 일시 이탈인지, 다음 확인 가격대를 분리해서 판단합니다.",
        ["previousMa60Distance", "ma60Distance", "trendCurve", "volumeRatio"],
    ),
    RelationRuleDefinition(
        "support.retest.confirmed.v1",
        "지지 재확인 + 매수 압력 -> 방어 확인",
        "v1",
        "SUPPORT_CONFIRMED",
        "confirmation",
        "60일선 부근에서 버티고 가격/체결/호가/수급 중 2개 이상이 회복 쪽일 때",
        "방어 확인은 매수 지시가 아니라 보유/관심 유지 근거이며, 다음 재확인 조건을 함께 제시합니다.",
        ["ma60Distance", "priceChangeRate", "tradeStrength", "bidAskImbalance", "investorFlow"],
    ),
    RelationRuleDefinition(
        "entry.pullback.supported.v1",
        "눌림목 + 단기 회복 + 거시 확인 -> 소액 진입 후보",
        "v1",
        "ENTRY_OPPORTUNITY",
        "entry_timing",
        "20일선보다 낮아졌지만 60일선 지지, 5일선 회복, 거래량·체결·투자자 수급, 금리·환율 부담이 함께 통과할 때",
        "싸졌다는 이유만으로 매수하지 말고 5일선 타이밍, 지지선, 수급 회복, 금리·환율, 뉴스·공시 리스크를 함께 비교합니다.",
        ["currentPrice", "ma5", "ma20", "ma60", "volumeRatio", "tradeStrength", "investorFlow", "macro", "fxRatePair"],
    ),
    RelationRuleDefinition(
        "entry.momentum.confirmed.v1",
        "5/20/60일선 회복 + 거래 증가 + 거시 확인 -> 신규 진입 후보",
        "v1",
        "ENTRY_OPPORTUNITY",
        "entry_timing",
        "관심종목이 5일·20일·60일 평균 가격을 회복하고 거래량과 금리·환율 조건도 통과할 때",
        "회복 확인 전 추격 매수를 피하고, 거래량·뉴스 품질·금리·환율 조건이 유지되는지 함께 확인합니다.",
        ["currentPrice", "ma5", "ma20", "ma60", "volumeRatio", "macro", "fxRatePair"],
    ),
    RelationRuleDefinition(
        "entry.wait_for_confirmation.v1",
        "관심종목 + 확인 부족/거시 부담 -> 신규 진입 대기",
        "v1",
        "ENTRY_WAIT",
        "entry_risk",
        "관심종목의 일부 가격 신호는 있으나 5일선·60일선·거래량·금리·환율·뉴스 품질 중 확인이 부족할 때",
        "매수보다 대기를 우선하고 어떤 조건이 채워지면 진입 검토로 바뀌는지 명확히 설명합니다.",
        ["source", "ma5", "ma20", "ma60", "volumeRatio", "macro", "fxRatePair", "newsHeadlines"],
    ),
    RelationRuleDefinition(
        "entry.add_buy.blocked.v1",
        "보유 종목 + 추세 훼손 -> 추가매수 보류",
        "v1",
        "ENTRY_RISK",
        "entry_risk",
        "보유 중인 종목이 20일선·60일선 아래에 있거나 공시/뉴스 리스크와 손실 상태가 겹칠 때",
        "추가매수보다 손실 기준, 회복 조건, 비중 한도를 먼저 확인하도록 AI에게 요청합니다.",
        ["profitLossRate", "currentPrice", "ma20", "ma60", "dartDisclosure", "newsHeadlines"],
    ),
    RelationRuleDefinition(
        "averaging_down.block.v1",
        "손실 + 20일선 하회 + 확인 부족 -> 물타기 차단",
        "v1",
        "AVERAGING_DOWN_BLOCK",
        "entry_risk",
        "손실 상태에서 단기 추세 아래이고 수급/거래량/체결 확인이 부족할 때",
        "평균단가 낮추기보다 보유 이유와 손절 기준을 먼저 확인하도록 AI에게 요청합니다.",
        ["profitLossRate", "ma20Distance", "volumeRatio", "tradeStrength", "investorFlow"],
    ),
    RelationRuleDefinition(
        "holding.averaging_down.risk_guard.v1",
        "손실 보유 + 회복 확인 부족 -> 추가매수 차단",
        "v1",
        "AVERAGING_DOWN_GUARD",
        "entry_risk",
        "손실 상태에서 외국인·기관 동반 순매수나 회복 확인이 부족할 때",
        "평균단가를 낮추는 행동보다 회복 신호, 뉴스 리스크, 비중 한도를 먼저 확인하도록 설명합니다.",
        ["profitLossRate", "jointSmartMoneyInflow", "lossRecoverySignalCount", "addBuyBlockedReasons"],
    ),
    RelationRuleDefinition(
        "distribution.detected.v1",
        "가격 버팀 + 매도 수급/거래량 -> 분산매도 의심",
        "v1",
        "DISTRIBUTION_RISK",
        "flow_risk",
        "가격은 크게 무너지지 않았지만 거래량 증가, 외국인·기관 순매도, 매도 호가/체결 우위가 겹칠 때",
        "가격만 보고 안심하지 말고 공급 우위와 다음 이탈 조건을 분리합니다.",
        ["priceChangeRate", "volumeRatio", "investorFlow", "sellShare", "bidAskImbalance"],
    ),
    RelationRuleDefinition(
        "profit.protection.volatility.v1",
        "수익 + 변동성 확대 + 둔화 -> 수익 보호",
        "v1",
        "PROFIT_PROTECTION",
        "exit_timing",
        "수익 구간에서 거래량/변동성이 커지고 단기 기울기 또는 커브가 둔화될 때",
        "전량 매도보다 분할 익절, 추세 회복 유지 조건, 재진입 조건을 함께 제시합니다.",
        ["profitLossRate", "volumeRatio", "ma20Slope", "trendCurve"],
    ),
    RelationRuleDefinition(
        "liquidity.exit_capacity.v1",
        "포지션 규모 + 거래대금 제약 -> 분할 실행",
        "v1",
        "LIQUIDITY_CONSTRAINT",
        "execution_risk",
        "포지션 평가액이 거래대금 대비 크거나 매도 가능 수량/호가가 실행을 제한할 때",
        "투자 판단과 실제 실행 가능성을 분리하고, 분할 실행·시장가 회피 기준을 제시합니다.",
        ["marketValue", "tradingValue", "sellableQuantity", "bidAskImbalance"],
    ),
    RelationRuleDefinition(
        "factor.crowding.v1",
        "섹터/팩터 집중 + 동방향 리스크 -> 포트폴리오 과밀",
        "v1",
        "FACTOR_CROWDING",
        "portfolio_risk",
        "섹터 비중이 높고 해당 종목도 같은 팩터에 노출되어 개별 리스크가 포트폴리오 리스크로 전파될 때",
        "개별 종목 신호와 포트폴리오 팩터 리스크를 분리해 설명합니다.",
        ["sectorRatio", "positionWeight", "market", "currency"],
    ),
    RelationRuleDefinition(
        "data.conflict.v1",
        "데이터 출처 충돌/신선도 저하 -> 확신도 상한",
        "v1",
        "DATA_CONFLICT",
        "data_quality",
        "핵심 가격/수급 출처가 비었거나 외부 신호 품질이 낮아 관계 결론의 확신도를 제한해야 할 때",
        "없는 데이터를 추정하지 말고 판단 강도 상한과 복구해야 할 데이터만 말합니다.",
        ["dataQualityScore", "externalSignalQuality", "missingData"],
    ),
    RelationRuleDefinition(
        "macro.regime.shift.v1",
        "금리/크립토/환율 레짐 변화 -> 팩터 민감도 점검",
        "v1",
        "MACRO_REGIME_SHIFT",
        "macro_risk",
        "금리, 스프레드, 크립토 유동성 또는 환율 변화가 성장주/반도체/디지털자산 민감 종목에 영향을 줄 때",
        "개별 가격 신호와 레짐 신호를 섞지 말고 민감도와 후속 확인 지표를 분리합니다.",
        ["macro", "btcChange24h", "btcChange7d", "currency"],
    ),
    RelationRuleDefinition(
        "rates.interest_rate.sensitivity.v1",
        "금리 변화 + 민감 섹터 -> 할인율 점검",
        "v1",
        "RATE_REGIME_SENSITIVITY",
        "macro_rate_risk",
        "미국 10년 금리나 10Y-2Y 스프레드가 이전값 대비 변화폭 기준을 넘고 성장주/반도체/디지털자산 같은 민감 섹터에 노출될 때",
        "금리는 주가 방향 예측값이 아니라 밸류에이션과 위험 선호를 흔드는 배경 변수로 설명합니다.",
        ["macroDgs10", "macroDgs10DeltaBp", "macroDgs2", "macroYieldSpreadDeltaBp", "sector", "currency"],
    ),
    RelationRuleDefinition(
        "fx.usd_krw.exposure.v1",
        "환율 변화 + 외화 노출 -> 환율 민감도 점검",
        "v1",
        "FX_REGIME_EXPOSURE",
        "fx_risk",
        "USD/KRW가 이전값 대비 변화폭 기준을 넘고 외화 보유 비중이 높아 원화 기준 평가액과 실제 종목 흐름을 분리해야 할 때",
        "주가 변화와 환율 효과를 분리하고, 외화 노출 비중과 환율 기준값을 함께 확인하도록 안내합니다.",
        ["fxRatePair", "fxRateToKrw", "usdKrwDeltaKrw", "usdKrwDeltaPct", "fxExposureRatio", "currency"],
    ),
    RelationRuleDefinition(
        "external.crypto.btc_sensitivity.v1",
        "비트코인 급변 + 민감 종목 -> 연동 점검",
        "v1",
        "EXTERNAL_SENSITIVITY",
        "cross_asset",
        "BTC가 24시간 또는 7일 기준을 넘고 MSTR/STRC 같은 민감 종목을 보유할 때",
        "BTC 가격 변화와 보유 종목 가격 변화의 시차, 과민반응 여부를 묻습니다.",
        ["btcChange24h", "btcChange7d"],
    ),
    RelationRuleDefinition(
        "disclosure.material_event.v1",
        "신규 공시 + 보유 종목 -> 이벤트 리스크 점검",
        "v1",
        "DISCLOSURE_EVENT",
        "event_risk",
        "OpenDART 신규 공시가 보유 종목에 연결될 때",
        "공시 제목만으로 결론 내리지 말고 공시 성격, 반복 여부, 가격 반응 확인점을 묻습니다.",
        ["dartDisclosure"],
    ),
    RelationRuleDefinition(
        "news.direct_risk.price_confirmed.v1",
        "직접 부정 뉴스 + 가격·수급 확인 -> 이벤트 리스크 점검",
        "v1",
        "NEWS_RISK_EVENT",
        "event_risk",
        "대상 종목 직접 뉴스가 부정 성격이고 가격 하락, 거래량 증가, 추세 훼손 중 하나 이상으로 확인될 때",
        "뉴스 제목만으로 결론 내리지 말고 직접 관련성, 출처 신뢰도, 가격·수급 동조 여부, 반대 신호를 함께 검토합니다.",
        ["researchEvidence", "directRiskNewsCount", "averageNewsRelevanceScore", "averageNewsMaterialityScore", "topNewsEventTypes", "priceChangeRate", "volumeRatio", "ma20Distance"],
    ),
    RelationRuleDefinition(
        "news.direct_risk.new_material.v1",
        "새 직접 부정 뉴스 -> 뉴스 리스크 점검",
        "v1",
        "NEWS_RISK_EVENT",
        "event_risk",
        "대상 종목 직접 뉴스가 새롭고 관련성·중요도 기준을 넘으면 가격 확인 전이라도 뉴스 리스크로 승격할 때",
        "새 뉴스 자체를 알림 트리거로 보되, 가격·수급 확인 전에는 실행 강도를 낮추고 원문·후속 반응을 확인하게 합니다.",
        ["researchEvidence", "directRiskNewsCount", "averageNewsRelevanceScore", "averageNewsMaterialityScore", "latestDirectNewsAgeMinutes"],
    ),
    RelationRuleDefinition(
        "news.direct_support.price_confirmed.v1",
        "직접 우호 뉴스 + 가격·수급 확인 -> 우호 이벤트 확인",
        "v1",
        "NEWS_SUPPORT_EVENT",
        "event_confirmation",
        "대상 종목 직접 뉴스가 우호 성격이고 가격 상승, 거래량 증가, 체결강도 개선 중 하나 이상으로 확인될 때",
        "우호 뉴스도 매수 지시가 아니라 가격·수급 확인과 무효화 조건을 분리해 검토합니다.",
        ["researchEvidence", "directSupportNewsCount", "averageNewsRelevanceScore", "averageNewsMaterialityScore", "topNewsEventTypes", "priceChangeRate", "volumeRatio", "tradeStrength"],
    ),
    RelationRuleDefinition(
        "news.direct_support.new_material.v1",
        "새 직접 우호 뉴스 -> 우호 이벤트 확인",
        "v1",
        "NEWS_SUPPORT_EVENT",
        "event_confirmation",
        "대상 종목 직접 우호 뉴스가 새롭고 관련성·중요도 기준을 넘으면 가격 확인 전이라도 우호 이벤트로 승격할 때",
        "우호 뉴스 자체를 알림 트리거로 보되, 바로 매수 판단이 아니라 가격·수급 동조 확인 조건을 분리합니다.",
        ["researchEvidence", "directSupportNewsCount", "averageNewsRelevanceScore", "averageNewsMaterialityScore", "latestDirectNewsAgeMinutes"],
    ),
    RelationRuleDefinition(
        "news.direct_material.new.v1",
        "새 직접 중요 뉴스 -> 뉴스 영향 확인",
        "v1",
        "NEWS_MATERIAL_EVENT",
        "event_confirmation",
        "대상 종목 직접 뉴스가 새롭고 관련성·중요도 기준을 넘지만 방향성이 중립이거나 아직 불명확할 때",
        "방향성이 애매한 뉴스도 사용자가 확인할 수 있게 알리되, 가격 방향 판단은 보류합니다.",
        ["researchEvidence", "directNewsCount", "averageNewsRelevanceScore", "averageNewsMaterialityScore", "latestDirectNewsAgeMinutes"],
    ),
    RelationRuleDefinition(
        "news.sector_peer_context.v1",
        "섹터·피어 뉴스 + 대상 종목 노출 -> 맥락 영향 점검",
        "v1",
        "SECTOR_NEWS_CONTEXT",
        "sector_context",
        "직접 뉴스는 아니지만 피어, 섹터, 시장 뉴스가 대상 종목의 팩터·섹터 노출과 연결될 때",
        "직접 기사와 섹터 맥락을 구분하고, 대상 가격·수급이 동조하는 경우에만 판단 강도를 높입니다.",
        ["researchEvidence", "sectorNewsCount", "peerNewsCount", "marketNewsCount", "topNewsEventTypes", "averageNewsMaterialityScore"],
    ),
    RelationRuleDefinition(
        "instrument.profile.strategy_fit.v1",
        "종목 타입 + 투자 성향 일치 -> 보유/진입 가설 보강",
        "v1",
        "STRATEGY_FIT",
        "instrument_profile",
        "종목의 투자 타입, 포지션 의도, 추가매수/축소 정책이 계정 투자 성향과 맞고 비중 한도 안에 있을 때",
        "종목 타입이 맞아도 바로 매수 결론을 내리지 않고 가격 회복, 수급 확인, 비중 여유를 함께 봅니다.",
        ["instrumentProfile", "instrumentArchetypes", "investmentStrategyProfile", "positionAccountWeight", "strategyMaxPositionWeightPct"],
    ),
    RelationRuleDefinition(
        "strategy.profile.loss_tolerance_breach.v1",
        "투자 성향 손실 한도 초과 -> 손실 관리 강화",
        "v1",
        "STRATEGY_RISK_TOLERANCE",
        "investor_profile",
        "보유 손실률이 계정 성향의 손실 허용 기준을 넘고 비중 또는 추세 부담이 함께 있을 때",
        "모든 계정에 같은 기준을 쓰지 않고, 공격형/균형형/보수형의 손실 허용폭과 비중 한도를 반영합니다.",
        ["profitLossRate", "strategyLossTolerancePct", "positionAccountWeight", "strategyMaxPositionWeightPct", "ma20Distance"],
    ),
    RelationRuleDefinition(
        "price.recovery.flow_confirmed.v1",
        "가격 회복 + 거래·수급 확인 -> 회복 신뢰도 보강",
        "v1",
        "RECOVERY_CONFIRM",
        "price_recovery",
        "5일선 또는 20일선을 회복하고 가격 상승, 거래량, 체결강도, 외국인·기관 수급 중 복수 근거가 붙을 때",
        "단순 반등과 확인된 회복을 구분하고, 매도 강도 완화 또는 추가매수 후보로 이어지는 조건을 분리합니다.",
        ["ma5Distance", "ma20Distance", "priceChangeRate", "timeAdjustedVolumeRatio", "tradeStrength", "smartMoneyNetVolume"],
    ),
    RelationRuleDefinition(
        "flow.psychology.price_divergence.v1",
        "가격 변화 + 수급 심리 불일치 -> 지속성 점검",
        "v1",
        "FLOW_DIVERGENCE",
        "flow_psychology",
        "가격은 오르지만 외국인·기관이 빠지거나 개인 저가매수가 위험 신호로 잡힐 때",
        "가격 상승만 보고 추격하지 않고 큰 자금 흐름과 개인 수급 심리가 같은 방향인지 확인합니다.",
        ["priceChangeRate", "foreignNetVolume", "institutionNetVolume", "individualNetVolume", "investorFlowPsychology", "bidAskImbalance"],
    ),
    RelationRuleDefinition(
        "news.disclosure.price_reaction.v1",
        "뉴스·공시 + 가격·거래 반응 -> 이벤트 영향 확인",
        "v1",
        "EVENT_IMPACT_CONFIRMATION",
        "event_confirmation",
        "직접 뉴스나 공시가 관련성·중요도 기준을 넘고 가격, 거래량, 수급 반응으로 확인될 때",
        "뉴스/공시 존재와 실제 시장 반응을 분리하고, 오래됐거나 방향이 애매한 근거는 확인 과제로 낮춥니다.",
        ["researchEvidence", "dartDisclosure", "secFiling", "priceChangeRate", "timeAdjustedVolumeRatio", "ma5Distance", "ma20Distance"],
    ),
    RelationRuleDefinition(
        "data.quality.guard.v1",
        "핵심 데이터 부족 -> 판단 보류",
        "v1",
        "DATA_QUALITY_GUARD",
        "data_quality",
        "현재가, 이동평균 또는 해당 시장에 적용 가능한 수급·체결 데이터가 빠졌을 때",
        "없는 데이터는 추정하지 말고 부족 데이터와 판단 영향만 설명합니다.",
        ["currentPrice", "ma20", "ma60", "tradeStrength", "investorFlow"],
    ),
]
