from dataclasses import asdict, dataclass
from typing import Dict, List, Optional


@dataclass(frozen=True)
class TBoxBoundedContext:
    key: str
    label: str
    description: str


@dataclass(frozen=True)
class TBoxClassDef:
    name: str
    bounded_context: str
    label: str = ""
    parent: str = ""
    description: str = ""


@dataclass(frozen=True)
class TBoxRelationDef:
    name: str
    bounded_context: str
    source_context: str = ""
    target_context: str = ""
    description: str = ""


@dataclass(frozen=True)
class TBoxRuleDef:
    text: str
    bounded_context: str
    description: str = ""


BOUNDED_CONTEXTS: List[TBoxBoundedContext] = [
    TBoxBoundedContext(
        "investment-core",
        "투자 핵심",
        "계좌, 포트폴리오, 투자 대상, 보유/관심 상태, 현금과 노출을 정의합니다.",
    ),
    TBoxBoundedContext(
        "observation-data",
        "관측 데이터",
        "가격, 수급, 기술 지표, 외부 이벤트, 데이터 출처와 신선도를 정의합니다.",
    ),
    TBoxBoundedContext(
        "strategy-thesis",
        "전략 가설",
        "투자 가설, 진입·청산·리밸런싱·비중 규칙과 상태 전이 조건을 정의합니다.",
    ),
    TBoxBoundedContext(
        "risk-exposure",
        "리스크 노출",
        "시장, 유동성, 집중, 통화, 이벤트, 데이터 품질, 모델, 실행 리스크를 분류합니다.",
    ),
    TBoxBoundedContext(
        "reasoning-insight",
        "추론 인사이트",
        "신호, 근거, 판단 근거, 의견, 모순, 기회, 인사이트와 AI 리뷰를 정의합니다.",
    ),
    TBoxBoundedContext(
        "operations-dispatch",
        "운영과 알림",
        "데이터 수집, 분석 실행, 추론 주기, 알림 디스패치와 억제 정책을 정의합니다.",
    ),
]


CLASS_DEFS: List[TBoxClassDef] = [
    TBoxClassDef("Portfolio", "investment-core", "포트폴리오", description="투자 계좌의 전체 자산과 노출 집합입니다."),
    TBoxClassDef("Account", "investment-core", "계좌", description="데이터와 주문 권한이 연결되는 투자 계좌입니다."),
    TBoxClassDef("Instrument", "investment-core", "투자 대상", description="주식, ETF, 크립토, 현금성 자산 등 투자 가능한 대상입니다."),
    TBoxClassDef("Company", "investment-core", "회사", description="증권을 발행하고 뉴스·공시·실세계 노출의 주체가 되는 법인입니다."),
    TBoxClassDef("Security", "investment-core", "증권", parent="Instrument", description="회사가 발행한 거래 가능 증권입니다."),
    TBoxClassDef("Equity", "investment-core", "주식", parent="Instrument"),
    TBoxClassDef("ETF", "investment-core", "ETF", parent="Instrument"),
    TBoxClassDef("MarketProxyInstrument", "investment-core", "시장 흐름 확인용 종목", parent="Instrument", description="경제 흐름, 시장 심리, 금리, 신용시장, 원자재, 업종 흐름을 관찰하기 위한 대표 거래 대상입니다."),
    TBoxClassDef("MarketProxyETF", "investment-core", "시장 프록시 ETF", parent="ETF", description="실시간 또는 준실시간 가격으로 시장 상태를 대변하는 ETF 센서입니다."),
    TBoxClassDef("MarketProxyIndex", "investment-core", "시장 프록시 지수", parent="Index", description="거래 대상이 아니어도 시장 레짐을 대변하는 지수형 센서입니다."),
    TBoxClassDef("SecurityLine", "investment-core", "상장 라인", parent="Security", description="본주, ADR, 단일종목 ETF처럼 같은 경제적 노출과 연결된 거래 라인입니다."),
    TBoxClassDef("LocalOrdinaryShare", "investment-core", "본주", parent="Stock", description="국내 또는 원 발행 시장의 보통주 거래 라인입니다."),
    TBoxClassDef("DepositaryReceipt", "investment-core", "예탁증서", parent="Security", description="해외 시장에서 원주 경제적 권리를 대표하는 증권입니다."),
    TBoxClassDef("ADR", "investment-core", "ADR", parent="DepositaryReceipt", description="미국 시장에서 거래되는 예탁증서 라인입니다."),
    TBoxClassDef("LeveragedETF", "investment-core", "레버리지 ETF", parent="ETF", description="기초 증권 또는 지수의 일일 수익률을 배수로 추종하는 ETF입니다."),
    TBoxClassDef("InverseETF", "investment-core", "인버스 ETF", parent="ETF", description="기초 증권 또는 지수의 반대 방향 일일 성과를 추종하는 ETF입니다."),
    TBoxClassDef("SingleStockETF", "investment-core", "단일종목 ETF", parent="ETF", description="단일 종목을 기초자산으로 삼는 ETF 거래 라인입니다."),
    TBoxClassDef("DailyResetLeverage", "investment-core", "일일 리셋 구조", parent="ETF", description="일별 재조정 때문에 기초자산 수급과 변동성에 영향을 줄 수 있는 상품 구조입니다."),
    TBoxClassDef("CryptoAsset", "investment-core", "크립토 자산", parent="Instrument"),
    TBoxClassDef("CashAsset", "investment-core", "현금성 자산", parent="Instrument"),
    TBoxClassDef("Derivative", "investment-core", "파생상품", parent="Instrument"),
    TBoxClassDef("Index", "investment-core", "지수", parent="Instrument"),
    TBoxClassDef("FXPair", "investment-core", "환율쌍", parent="Instrument"),
    TBoxClassDef("Stock", "investment-core", "종목", parent="Equity"),
    TBoxClassDef("Position", "investment-core", "포지션", description="보유 또는 관찰 중인 투자 대상의 계좌상 행입니다."),
    TBoxClassDef("Watchlist", "investment-core", "관심 목록"),
    TBoxClassDef("WatchlistCandidate", "investment-core", "관심 후보", parent="Position"),
    TBoxClassDef("Sector", "investment-core", "섹터"),
    TBoxClassDef("Industry", "investment-core", "산업"),
    TBoxClassDef("PeerGroup", "investment-core", "피어 그룹"),
    TBoxClassDef("Market", "investment-core", "시장"),
    TBoxClassDef("Currency", "investment-core", "통화"),
    TBoxClassDef("Cash", "investment-core", "대기 현금", parent="CashAsset"),
    TBoxClassDef("MarketExposure", "investment-core", "시장 노출"),
    TBoxClassDef("Observation", "observation-data", "관측값", description="특정 시점과 출처에서 들어온 사실입니다."),
    TBoxClassDef("FactChange", "observation-data", "사실 변경", parent="Observation"),
    TBoxClassDef("TemporalWindow", "observation-data", "기간 구간", parent="Observation", description="종목별 1D, 3D, 5D, 20D 같은 기간 단위 관측 묶음입니다."),
    TBoxClassDef("IntradayWindow", "observation-data", "장중 구간", parent="TemporalWindow"),
    TBoxClassDef("DailyWindow", "observation-data", "일간 구간", parent="TemporalWindow"),
    TBoxClassDef("MultiDayWindow", "observation-data", "다일 구간", parent="TemporalWindow"),
    TBoxClassDef("TemporalMateriality", "observation-data", "기간 중요도", parent="Observation", description="단일 스냅샷보다 기간 묶음으로 봤을 때 판단을 바꿀 만큼 중요한 변화입니다."),
    TBoxClassDef("TemporalCoverageGap", "observation-data", "기간 히스토리 부족", parent="CoverageGap", description="기간 판단에 필요한 스냅샷 수가 부족한 데이터 공백입니다."),
    TBoxClassDef("PriceObservation", "observation-data", "가격 관측", parent="Observation"),
    TBoxClassDef("VolumeObservation", "observation-data", "거래량 관측", parent="Observation"),
    TBoxClassDef("TechnicalObservation", "observation-data", "기술 지표 관측", parent="Observation"),
    TBoxClassDef("FlowObservation", "observation-data", "수급 관측", parent="Observation"),
    TBoxClassDef("FundamentalObservation", "observation-data", "펀더멘털 관측", parent="Observation"),
    TBoxClassDef("ExternalObservation", "observation-data", "외부 관측", parent="Observation"),
    TBoxClassDef("PriceMetric", "observation-data", "가격 지표", parent="PriceObservation"),
    TBoxClassDef("MarketProxyObservation", "observation-data", "시장 프록시 관측", parent="PriceObservation", description="SPY, QQQ, IPO, VIXY, TLT, HYG, SOXX 같은 시장 센서의 현재 가격·추세·거래량 관측입니다."),
    TBoxClassDef("PricePathPattern", "observation-data", "가격 경로 패턴", parent="PriceObservation", description="기간 동안의 하락 지속, 둔화, 반등 시도, 회복 실패 같은 가격 경로입니다."),
    TBoxClassDef("CrossMarketPremium", "observation-data", "교차 시장 프리미엄", parent="PriceObservation", description="본주와 ADR·GDR·해외 라인 사이의 환산 가격 괴리입니다."),
    TBoxClassDef("ADRPremium", "observation-data", "ADR 프리미엄", parent="CrossMarketPremium", description="ADR 가격을 환율과 교환비율로 본주 가치에 환산한 프리미엄 또는 할인입니다."),
    TBoxClassDef("TechnicalIndicator", "observation-data", "기술 지표", parent="TechnicalObservation"),
    TBoxClassDef("TradeFlow", "observation-data", "거래/수급", parent="FlowObservation"),
    TBoxClassDef("FlowPattern", "observation-data", "기간 수급 패턴", parent="FlowObservation", description="기간 동안 외국인·기관·개인 수급이 가격 흐름과 어떻게 맞물렸는지 나타냅니다."),
    TBoxClassDef("RebalancingFlow", "observation-data", "리밸런싱 수급", parent="FlowObservation", description="일일 리셋 상품, ETF, 파생 포지션 재조정에서 생기는 수급 관측입니다."),
    TBoxClassDef("DataQuality", "observation-data", "데이터 품질", parent="Observation"),
    TBoxClassDef("DataSource", "observation-data", "데이터 출처"),
    TBoxClassDef("DataFreshness", "observation-data", "데이터 신선도"),
    TBoxClassDef("DataLatency", "observation-data", "데이터 지연 특성", parent="DataQuality"),
    TBoxClassDef("MissingData", "observation-data", "부족 데이터"),
    TBoxClassDef("CoverageGap", "observation-data", "온톨로지 커버리지 부족", parent="DataQuality", description="투자 판단에 필요한 가격, 경로, 수급, 외부 근거, 밸류에이션, 매크로 같은 범주 중 현재 ABox가 채우지 못한 공백입니다."),
    TBoxClassDef("Provenance", "observation-data", "출처 이력"),
    TBoxClassDef("SourceReliability", "observation-data", "출처 신뢰도", parent="Provenance"),
    TBoxClassDef("ObservationDataState", "observation-data", "관측 자료 상태", parent="DataQuality", description="관측값을 판단에 충분히 쓸 수 있는지 충분·일부·부족·사용 불가로 나타냅니다."),
    TBoxClassDef("TimeWindow", "observation-data", "시간 구간"),
    TBoxClassDef("ObservationTime", "observation-data", "관측 시점"),
    TBoxClassDef("SignalHorizon", "observation-data", "신호 기간"),
    TBoxClassDef("HoldingPeriod", "observation-data", "보유 기간"),
    TBoxClassDef("ValidityInterval", "observation-data", "유효 기간"),
    TBoxClassDef("Staleness", "observation-data", "노후화"),
    TBoxClassDef("ValidationRule", "observation-data", "검증 규칙"),
    TBoxClassDef("PriceBar", "observation-data", "가격 봉", parent="PriceObservation"),
    TBoxClassDef("PricePath", "observation-data", "가격 경로", parent="PriceObservation"),
    TBoxClassDef("VolumeProfile", "observation-data", "거래량 프로파일", parent="VolumeObservation"),
    TBoxClassDef("KeyLevel", "observation-data", "주요 가격대", parent="TechnicalObservation"),
    TBoxClassDef("SupportLevel", "observation-data", "지지선", parent="KeyLevel"),
    TBoxClassDef("ResistanceLevel", "observation-data", "저항선", parent="KeyLevel"),
    TBoxClassDef("Breakout", "observation-data", "돌파", parent="TechnicalObservation"),
    TBoxClassDef("FailedBreakout", "observation-data", "돌파 실패", parent="Breakout"),
    TBoxClassDef("Retest", "observation-data", "재시험", parent="TechnicalObservation"),
    TBoxClassDef("ResearchEvidence", "observation-data", "리서치 근거", parent="ExternalObservation"),
    TBoxClassDef("ExternalSignal", "observation-data", "외부 신호", parent="ExternalObservation"),
    TBoxClassDef("MarketStructureSignal", "observation-data", "시장 구조 신호", parent="ExternalSignal", description="교차 상장, 예탁증서, 단일종목 ETF, 차익거래 제약처럼 시장 구조에서 발생하는 신호입니다."),
    TBoxClassDef("NewsEvent", "observation-data", "뉴스 이벤트", parent="ExternalSignal"),
    TBoxClassDef("NewsArticle", "observation-data", "뉴스 기사", parent="NewsEvent"),
    TBoxClassDef("ArticleAIAnalysis", "observation-data", "기사 AI 분석", parent="NewsEvent"),
    TBoxClassDef("NewsTopic", "observation-data", "뉴스 토픽", parent="NewsEvent"),
    TBoxClassDef("NewsEventType", "observation-data", "뉴스 이벤트 유형", parent="NewsEvent"),
    TBoxClassDef("EventCluster", "observation-data", "이벤트 묶음", parent="ExternalObservation", description="뉴스, 공시, 외부 신호가 같은 기간에 묶여 만든 사건군입니다."),
    TBoxClassDef("EventDrivenRiskCluster", "observation-data", "이벤트 리스크 집중", parent="EventCluster"),
    TBoxClassDef("SupportiveEventCluster", "observation-data", "우호 이벤트 묶음", parent="EventCluster"),
    TBoxClassDef("MixedEventCluster", "observation-data", "혼합 이벤트 묶음", parent="EventCluster"),
    TBoxClassDef("QuietPeriod", "observation-data", "이벤트 공백 구간", parent="EventCluster"),
    TBoxClassDef("PeerCompanyMention", "observation-data", "피어 회사 언급", parent="ExternalObservation"),
    TBoxClassDef("DisclosureEvent", "observation-data", "공시 이벤트", parent="ExternalSignal"),
    TBoxClassDef("DisclosureFiling", "observation-data", "공시 문서", parent="DisclosureEvent"),
    TBoxClassDef("MacroIndicator", "observation-data", "거시 지표", parent="ExternalSignal"),
    TBoxClassDef("MacroPrint", "observation-data", "거시 발표값", parent="MacroIndicator"),
    TBoxClassDef("MacroRegime", "observation-data", "거시 레짐", parent="MacroIndicator", description="금리 수준, 금리 변화, 수익률곡선, 환율 환경을 묶어 투자 대상에 전파하는 시장 환경입니다."),
    TBoxClassDef("RateSignal", "observation-data", "금리 신호", parent="ExternalSignal"),
    TBoxClassDef("InterestRate", "observation-data", "금리", parent="RateSignal"),
    TBoxClassDef("YieldCurve", "observation-data", "수익률곡선", parent="RateSignal"),
    TBoxClassDef("FXRateSignal", "observation-data", "환율 신호", parent="ExternalSignal"),
    TBoxClassDef("CreditSpreadSignal", "observation-data", "크레딧 스프레드 신호", parent="ExternalSignal"),
    TBoxClassDef("CryptoMarketSignal", "observation-data", "크립토 시장 신호", parent="ExternalSignal"),
    TBoxClassDef("EarningsEvent", "observation-data", "실적 이벤트", parent="ExternalSignal"),
    TBoxClassDef("EarningsCalendarEvent", "observation-data", "실적 일정 이벤트", parent="EarningsEvent"),
    TBoxClassDef("AnalystRevision", "observation-data", "애널리스트 추정 변경", parent="ExternalSignal"),
    TBoxClassDef("CorporateAction", "observation-data", "기업 액션", parent="ExternalSignal"),
    TBoxClassDef("RegulatoryEvent", "observation-data", "규제 이벤트", parent="ExternalSignal"),
    TBoxClassDef("ProductLine", "observation-data", "제품/서비스 라인", parent="ExternalObservation"),
    TBoxClassDef("SupplyChainExposure", "observation-data", "공급망 노출", parent="ExternalObservation"),
    TBoxClassDef("CustomerExposure", "observation-data", "고객 노출", parent="ExternalObservation"),
    TBoxClassDef("RevenueExposure", "observation-data", "매출 노출", parent="ExternalObservation"),
    TBoxClassDef("Factor", "strategy-thesis", "투자 팩터"),
    TBoxClassDef("FactorExposure", "strategy-thesis", "팩터 노출"),
    TBoxClassDef("MarketProxyTheme", "strategy-thesis", "시장 프록시 테마", parent="Factor", description="프록시 종목이 대변하는 위험선호, 금리, 크레딧, IPO, 달러, 원자재, 섹터 사이클 같은 시장 상태입니다."),
    TBoxClassDef("BenchmarkIndex", "strategy-thesis", "벤치마크 지수"),
    TBoxClassDef("HedgeCandidate", "strategy-thesis", "헤지 후보"),
    TBoxClassDef("Strategy", "strategy-thesis", "투자전략"),
    TBoxClassDef("InvestmentStrategyProposal", "strategy-thesis", "투자 전략 제안", parent="Strategy", description="AI와 온톨로지 실험이 만든 전략 가설, 조건, 리스크 통제, 검증 상태를 추적합니다."),
    TBoxClassDef("StrategyValidation", "strategy-thesis", "전략 검증", parent="Strategy", description="후보 전략이 ABox, TypeDB schema function preview, InferenceBox 검증을 통과했는지 기록합니다."),
    TBoxClassDef("StrategyDeployment", "strategy-thesis", "전략 배포", parent="Strategy", description="승인된 전략 제안이 운영 RuleBox/InferenceBox 경로에 반영된 이력을 기록합니다."),
    TBoxClassDef("InvestorProfile", "strategy-thesis", "투자자 성향", description="계정별 손실 허용도, 수익 보호 기준, 비중 한도, 행동 범위를 정의합니다."),
    TBoxClassDef("InvestmentStrategyProfile", "strategy-thesis", "투자 전략 성향", parent="InvestorProfile"),
    TBoxClassDef("InstrumentProfile", "strategy-thesis", "종목 투자 성격", description="종목별 투자 성격, 민감도, 추가매수·축소 원칙을 정의합니다."),
    TBoxClassDef("InvestmentArchetype", "strategy-thesis", "종목 성격", description="성장주, 우선주, 비트코인 민감주, 반도체 업황 민감주처럼 종목별 판단 방식을 바꾸는 성격입니다."),
    TBoxClassDef("CrossListedSecurity", "strategy-thesis", "해외 교차상장 종목", parent="InvestmentArchetype", description="본주와 ADR·GDR처럼 여러 시장에서 거래되어 가격 차이와 환율 영향을 함께 받는 종목입니다."),
    TBoxClassDef("DailyLeveragedProduct", "strategy-thesis", "매일 수익률이 재조정되는 레버리지 상품", parent="InvestmentArchetype", description="매일 수익률을 다시 맞추므로 장기 보유보다 단기 거래와 가격 변동 확인이 중요한 상품입니다."),
    TBoxClassDef("InverseProduct", "strategy-thesis", "가격 하락에 투자하는 상품", parent="InvestmentArchetype", description="기초자산과 반대 방향의 성과를 추구하는 상품입니다."),
    TBoxClassDef("BroadMarketProxy", "strategy-thesis", "전체 시장 흐름 지표", parent="InvestmentArchetype"),
    TBoxClassDef("CommodityProxy", "strategy-thesis", "원자재 가격 흐름 지표", parent="InvestmentArchetype"),
    TBoxClassDef("CreditStressProxy", "strategy-thesis", "신용시장 불안 지표", parent="InvestmentArchetype"),
    TBoxClassDef("CryptoLiquidityProxy", "strategy-thesis", "가상자산 거래 활력 지표", parent="InvestmentArchetype"),
    TBoxClassDef("CurrencyProxy", "strategy-thesis", "환율과 달러 흐름 지표", parent="InvestmentArchetype"),
    TBoxClassDef("DurationProxy", "strategy-thesis", "채권 가격의 금리 민감도 지표", parent="InvestmentArchetype"),
    TBoxClassDef("ForeignMarketProxy", "strategy-thesis", "해외 시장 흐름 지표", parent="InvestmentArchetype"),
    TBoxClassDef("GrowthMarketProxy", "strategy-thesis", "성장주 시장 흐름 지표", parent="InvestmentArchetype"),
    TBoxClassDef("IPOCycleProxy", "strategy-thesis", "신규 상장 시장 흐름 지표", parent="InvestmentArchetype"),
    TBoxClassDef("KoreaMarketProxy", "strategy-thesis", "한국 시장 흐름 지표", parent="InvestmentArchetype"),
    TBoxClassDef("RateSensitivityProxy", "strategy-thesis", "금리 변화 영향 지표", parent="InvestmentArchetype"),
    TBoxClassDef("RiskAppetiteProxy", "strategy-thesis", "위험자산 선호 지표", parent="InvestmentArchetype"),
    TBoxClassDef("RiskOffProxy", "strategy-thesis", "안전자산 선호 지표", parent="InvestmentArchetype"),
    TBoxClassDef("SectorCycleProxy", "strategy-thesis", "업종 경기 흐름 지표", parent="InvestmentArchetype"),
    TBoxClassDef("SmallCapRiskProxy", "strategy-thesis", "소형주 투자심리 지표", parent="InvestmentArchetype"),
    TBoxClassDef("VolatilityProxy", "strategy-thesis", "시장 변동성 지표", parent="InvestmentArchetype"),
    TBoxClassDef("GrowthStock", "strategy-thesis", "성장주", parent="InvestmentArchetype"),
    TBoxClassDef("AIGrowth", "strategy-thesis", "인공지능 성장주", parent="GrowthStock"),
    TBoxClassDef("HighVolatilityGrowth", "strategy-thesis", "가격 변동이 큰 성장주", parent="GrowthStock"),
    TBoxClassDef("MegaCapQuality", "strategy-thesis", "대형 우량주", parent="InvestmentArchetype"),
    TBoxClassDef("PlatformGrowth", "strategy-thesis", "플랫폼 성장주", parent="GrowthStock"),
    TBoxClassDef("DividendIncome", "strategy-thesis", "배당형 종목", parent="InvestmentArchetype"),
    TBoxClassDef("PreferredIncome", "strategy-thesis", "배당 중심 우선주", parent="DividendIncome"),
    TBoxClassDef("BitcoinProxy", "strategy-thesis", "비트코인 가격에 민감한 주식", parent="InvestmentArchetype"),
    TBoxClassDef("BitcoinSensitiveIncome", "strategy-thesis", "비트코인에 민감한 배당형 종목", parent="PreferredIncome"),
    TBoxClassDef("CryptoAssetProfile", "strategy-thesis", "가상자산", parent="InvestmentArchetype"),
    TBoxClassDef("SemiconductorCyclical", "strategy-thesis", "반도체 업황 민감주", parent="InvestmentArchetype"),
    TBoxClassDef("SemiconductorHBM", "strategy-thesis", "HBM 반도체 성장주", parent="SemiconductorCyclical"),
    TBoxClassDef("CyclicalGrowth", "strategy-thesis", "경기 흐름에 민감한 성장주", parent="GrowthStock"),
    TBoxClassDef("EquityGeneral", "strategy-thesis", "일반 주식", parent="InvestmentArchetype"),
    TBoxClassDef("PositionIntent", "strategy-thesis", "계좌에서의 역할", description="종목을 핵심 보유, 성장 투자, 기회 대응, 배당·현금흐름, 시장 흐름 확인 중 어떤 목적으로 관리할지 정의합니다."),
    TBoxClassDef("FactorSensitivity", "strategy-thesis", "시장 요인 민감도", parent="FactorExposure", description="금리, 환율, 경기 흐름, 비트코인, 인공지능 같은 요인에 대한 종목별 민감도입니다."),
    TBoxClassDef("RiskBudget", "strategy-thesis", "손실 허용 기준", parent="RiskManagementRule"),
    TBoxClassDef("ProfitPolicy", "strategy-thesis", "수익 보호 기준", parent="RiskManagementRule"),
    TBoxClassDef("PositionRole", "strategy-thesis", "포지션 역할", parent="PositionSizingRule"),
    TBoxClassDef("InvestmentThesis", "strategy-thesis", "투자 가설"),
    TBoxClassDef("EntryCondition", "strategy-thesis", "진입 조건"),
    TBoxClassDef("ExitCondition", "strategy-thesis", "청산 조건"),
    TBoxClassDef("RiskManagementRule", "strategy-thesis", "위험 관리 규칙"),
    TBoxClassDef("RebalancingRule", "strategy-thesis", "리밸런싱 규칙"),
    TBoxClassDef("PositionSizingRule", "strategy-thesis", "비중 규칙"),
    TBoxClassDef("Scenario", "strategy-thesis", "시나리오"),
    TBoxClassDef("StrategyExperiment", "strategy-thesis", "전략 실험"),
    TBoxClassDef("StrategySignal", "strategy-thesis", "전략 신호"),
    TBoxClassDef("Threshold", "strategy-thesis", "기준값"),
    TBoxClassDef("RuntimeSetting", "strategy-thesis", "런타임 설정"),
    TBoxClassDef("AlertRule", "strategy-thesis", "알림 규칙", parent="RuntimeSetting"),
    TBoxClassDef("PromptTemplate", "strategy-thesis", "프롬프트 템플릿", parent="RuntimeSetting"),
    TBoxClassDef("ValuationAssumption", "strategy-thesis", "밸류에이션 가정"),
    TBoxClassDef("AIValuationProposal", "strategy-thesis", "AI 밸류에이션 제안", parent="ValuationAssumption", description="사용자 입력이나 외부 적정가가 부족할 때 AI가 만든 임시 적정가 가정입니다. 승인 전 초안으로 표시되어야 합니다."),
    TBoxClassDef("ValuationModel", "strategy-thesis", "밸류에이션 모델", parent="ValuationAssumption", description="종목 타입별로 어떤 방식으로 적정가 초안을 계산했는지 나타내는 모델입니다."),
    TBoxClassDef("ActiveValuation", "strategy-thesis", "활성 밸류에이션", parent="ValuationAssumption", description="현재 투자 판단에 적용 중인 밸류에이션입니다. AI 제안은 검토 전이라도 자동 적용 상태를 명확히 표시합니다."),
    TBoxClassDef("UserValuationReview", "strategy-thesis", "사용자 밸류에이션 검토", parent="ValuationAssumption", description="AI 밸류에이션 제안에 대한 사용자 승인, 수정, 거절 상태입니다."),
    TBoxClassDef("ValuationEvidence", "observation-data", "밸류에이션 근거", parent="FundamentalObservation", description="적정가 계산에 사용된 가격, 실적, 배당, BTC, 금리, 업황 같은 근거입니다."),
    TBoxClassDef("ValuationMetric", "observation-data", "밸류에이션 지표", parent="FundamentalObservation", description="PER, PEG, 배당수익률, 예상 EPS처럼 적정가 판단에 쓰는 원천 지표입니다."),
    TBoxClassDef("FairValueEstimate", "strategy-thesis", "적정가 추정", parent="ValuationAssumption", description="사용자 공식, 애널리스트 목표가, 상대평가 등으로 만든 적정 가격 추정입니다."),
    TBoxClassDef("FairValueRange", "strategy-thesis", "적정가 범위", parent="FairValueEstimate", description="보수적·기준·낙관 시나리오로 계산한 주당 적정가 범위입니다."),
    TBoxClassDef("ValuationDataState", "strategy-thesis", "밸류에이션 자료 상태", parent="ValuationAssumption", description="출처, 입력값, 기준일, 기간 일치 여부를 확인해 계산 자료를 충분·일부·부족·사용 불가로 나타냅니다."),
    TBoxClassDef("ValuationConsensus", "strategy-thesis", "밸류에이션 모델 합의", parent="ValuationAssumption", description="여러 평가 모델의 적정가 차이와 투자 판단 사용 가능 여부를 나타냅니다."),
    TBoxClassDef("ValuationScenario", "strategy-thesis", "밸류에이션 시나리오", parent="Scenario", description="실적과 배수 가정을 보수적·기준·낙관으로 나눈 평가 시나리오입니다."),
    TBoxClassDef("MarginOfSafety", "strategy-thesis", "안전마진", parent="ValuationAssumption", description="현재가가 적정가보다 얼마나 낮거나 높은지 나타내는 밸류에이션 여유입니다."),
    TBoxClassDef("RelativeValuation", "strategy-thesis", "상대 밸류에이션", parent="ValuationAssumption", description="동종 기업, 과거 밴드, 시장 평균과 비교한 가격 수준입니다."),
    TBoxClassDef("HistoricalValuationBand", "strategy-thesis", "과거 밸류에이션 밴드", parent="RelativeValuation"),
    TBoxClassDef("PeerMultiple", "strategy-thesis", "피어 멀티플", parent="RelativeValuation"),
    TBoxClassDef("EarningsYield", "observation-data", "이익수익률", parent="ValuationMetric"),
    TBoxClassDef("DCFValuation", "strategy-thesis", "현금흐름 할인 평가", parent="FairValueEstimate"),
    TBoxClassDef("Risk", "risk-exposure", "리스크"),
    TBoxClassDef("MarketRisk", "risk-exposure", "시장 리스크", parent="Risk"),
    TBoxClassDef("MarketStructureRisk", "risk-exposure", "시장 구조 리스크", parent="MarketRisk", description="상장 라인, 전환 창구, 차익거래 제약, 레버리지 상품 구조에서 생기는 리스크입니다."),
    TBoxClassDef("ArbitrageFriction", "risk-exposure", "차익거래 제약", parent="MarketStructureRisk", description="본주와 ADR·GDR 같은 교차 상장 라인 사이 가격 괴리가 쉽게 해소되지 않을 수 있는 제약입니다."),
    TBoxClassDef("FlowAmplificationRisk", "risk-exposure", "수급 증폭 리스크", parent="MarketStructureRisk", description="단일종목 레버리지·인버스 상품의 일일 재조정이 기초자산 변동성과 수급을 키울 수 있는 위험입니다."),
    TBoxClassDef("LiquidityRisk", "risk-exposure", "유동성 리스크", parent="Risk"),
    TBoxClassDef("LiquidityProfile", "risk-exposure", "유동성 프로파일", parent="LiquidityRisk"),
    TBoxClassDef("ExitCapacity", "risk-exposure", "청산 가능 용량", parent="LiquidityRisk"),
    TBoxClassDef("ExecutionMetric", "observation-data", "실행 지표", parent="FlowObservation", description="보유 규모, 거래대금, 호가잔량, 청산 일수처럼 주문 실행 가능성을 판단하는 원천 관측값입니다."),
    TBoxClassDef("ExecutionCapacity", "risk-exposure", "실행 가능 용량", parent="ExecutionRisk", description="현재 보유 수량을 실제 시장 유동성 안에서 실행할 수 있는 여유입니다."),
    TBoxClassDef("PositionExitExposure", "risk-exposure", "포지션 청산 노출", parent="LiquidityRisk", description="보유 규모가 거래량·거래대금·호가잔량 대비 얼마나 큰지 나타내는 노출입니다."),
    TBoxClassDef("SlippageEstimate", "risk-exposure", "슬리피지 추정", parent="ExecutionRisk"),
    TBoxClassDef("ConcentrationRisk", "risk-exposure", "집중 리스크", parent="Risk"),
    TBoxClassDef("CurrencyRisk", "risk-exposure", "통화 리스크", parent="Risk"),
    TBoxClassDef("VolatilityRisk", "risk-exposure", "변동성 리스크", parent="Risk"),
    TBoxClassDef("CryptoExposure", "risk-exposure", "크립토 노출", parent="VolatilityRisk", description="비트코인·이더리움 등 디지털 자산 가격 경로가 종목 또는 포트폴리오에 전달되는 노출입니다."),
    TBoxClassDef("EventRisk", "risk-exposure", "이벤트 리스크", parent="Risk"),
    TBoxClassDef("DataQualityRisk", "risk-exposure", "데이터 품질 리스크", parent="Risk"),
    TBoxClassDef("ArticleQualityRisk", "risk-exposure", "기사 품질 리스크", parent="DataQualityRisk", description="뉴스 본문 부재, 종목 직접성 미확인, 분석 충돌처럼 기사 근거의 판단 신뢰도를 낮추는 리스크입니다."),
    TBoxClassDef("ModelRisk", "risk-exposure", "모델 리스크", parent="Risk"),
    TBoxClassDef("ValuationRisk", "risk-exposure", "밸류에이션 리스크", parent="Risk", description="현재가가 적정가나 핵심 지표 대비 비싸다고 볼 수 있는 위험입니다."),
    TBoxClassDef("ExecutionRisk", "risk-exposure", "실행 리스크", parent="Risk"),
    TBoxClassDef("CorrelationRisk", "risk-exposure", "상관 리스크", parent="Risk"),
    TBoxClassDef("RegimeRisk", "risk-exposure", "레짐 리스크", parent="Risk"),
    TBoxClassDef("Signal", "reasoning-insight", "신호"),
    TBoxClassDef("PriceSignal", "reasoning-insight", "가격 신호", parent="Signal"),
    TBoxClassDef("TrendSignal", "reasoning-insight", "추세 신호", parent="Signal"),
    TBoxClassDef("FlowSignal", "reasoning-insight", "수급 신호", parent="Signal"),
    TBoxClassDef("InvestorFlowSentiment", "reasoning-insight", "투자자별 수급 심리", parent="FlowSignal"),
    TBoxClassDef("SmartMoneyFlow", "reasoning-insight", "외국인·기관 수급", parent="FlowSignal"),
    TBoxClassDef("SmartMoneyJointInflow", "reasoning-insight", "외국인·기관 동반 순매수", parent="SmartMoneyFlow"),
    TBoxClassDef("SmartMoneyJointOutflow", "reasoning-insight", "외국인·기관 동반 순매도", parent="SmartMoneyFlow"),
    TBoxClassDef("SmartMoneyAccumulation", "reasoning-insight", "외국인·기관 매집", parent="SmartMoneyFlow"),
    TBoxClassDef("PartialSmartMoneySupport", "reasoning-insight", "외국인·기관 일부 순매수", parent="SmartMoneyFlow"),
    TBoxClassDef("PartialSmartMoneyRisk", "reasoning-insight", "외국인·기관 일부 순매도", parent="SmartMoneyFlow"),
    TBoxClassDef("RetailFlowPsychology", "reasoning-insight", "개인 수급 심리", parent="FlowSignal"),
    TBoxClassDef("RetailDipBuyingRisk", "reasoning-insight", "개인 저가매수 위험", parent="RetailFlowPsychology"),
    TBoxClassDef("PsychologyObservation", "observation-data", "시장 심리 관측", parent="Observation", description="가격 행동, 투자자별 수급, 옵션 포지셔닝, 검증된 뉴스, 커뮤니티 원천을 출처와 시각별로 분리한 관측값입니다."),
    TBoxClassDef("BehaviorSentiment", "observation-data", "가격·거래 행동 심리", parent="PsychologyObservation"),
    TBoxClassDef("PositioningSentiment", "observation-data", "옵션 포지셔닝 심리", parent="PsychologyObservation"),
    TBoxClassDef("NewsSentiment", "observation-data", "검증된 뉴스 심리", parent="PsychologyObservation"),
    TBoxClassDef("CrowdSentiment", "observation-data", "커뮤니티 군중심리", parent="PsychologyObservation"),
    TBoxClassDef("MarketPsychologyState", "reasoning-insight", "시장 심리 상태", parent="Signal", description="신선도와 출처 신뢰도로 가중한 여러 심리 관측의 종합 상태입니다."),
    TBoxClassDef("EuphoriaState", "reasoning-insight", "과열된 낙관", parent="MarketPsychologyState"),
    TBoxClassDef("OptimisticPsychologyState", "reasoning-insight", "낙관 우세", parent="MarketPsychologyState"),
    TBoxClassDef("MixedPsychologyState", "reasoning-insight", "중립·혼조", parent="MarketPsychologyState"),
    TBoxClassDef("NeutralPsychologyState", "reasoning-insight", "방향 중립", parent="MarketPsychologyState"),
    TBoxClassDef("CautiousPsychologyState", "reasoning-insight", "주의 우세", parent="MarketPsychologyState"),
    TBoxClassDef("FearfulPsychologyState", "reasoning-insight", "경계 우세", parent="MarketPsychologyState"),
    TBoxClassDef("PanicState", "reasoning-insight", "공포 확대", parent="MarketPsychologyState"),
    TBoxClassDef("InsufficientPsychologyEvidence", "reasoning-insight", "심리 근거 부족", parent="MarketPsychologyState"),
    TBoxClassDef("PsychologyShadowState", "reasoning-insight", "심리 Shadow 상태", parent="MarketPsychologyState", description="실제 투자 판단과 발송에는 영향을 주지 않고 비교·검증만 하는 심리 상태입니다."),
    TBoxClassDef("PsychologyShadowComparison", "reasoning-insight", "심리 Shadow 비교", parent="ActionabilityAssessment", description="기존 TypeDB 판단과 심리 후보 영향의 차이를 운영 검증용으로 기록합니다."),
    TBoxClassDef("ValuationSignal", "reasoning-insight", "밸류에이션 신호", parent="Signal"),
    TBoxClassDef("MacroSignal", "reasoning-insight", "거시 신호", parent="Signal"),
    TBoxClassDef("DisclosureSignal", "reasoning-insight", "공시 신호", parent="Signal"),
    TBoxClassDef("CryptoSignal", "reasoning-insight", "크립토 신호", parent="Signal"),
    TBoxClassDef("DataQualitySignal", "reasoning-insight", "데이터 품질 신호", parent="Signal"),
    TBoxClassDef("Evidence", "reasoning-insight", "근거"),
    TBoxClassDef("Belief", "reasoning-insight", "판단 근거"),
    TBoxClassDef("RelationStateSnapshot", "reasoning-insight", "관계 상태 스냅샷"),
    TBoxClassDef("SignalTransition", "reasoning-insight", "신호 상태 전이"),
    TBoxClassDef("TrendPhase", "reasoning-insight", "추세 국면", parent="Signal"),
    TBoxClassDef("TrendTransition", "reasoning-insight", "추세 국면 전이", parent="SignalTransition"),
    TBoxClassDef("TrendEpisode", "reasoning-insight", "기간 추세 에피소드", parent="SignalTransition", description="기간 구간의 가격, 수급, 이벤트 묶음이 만든 투자 판단용 상태입니다."),
    TBoxClassDef("DecisionEpisode", "reasoning-insight", "기간 판단 에피소드", parent="ActionabilityAssessment", description="기간 흐름 때문에 보유, 축소, 매도, 추가매수 검토 강도가 어떻게 바뀌는지 나타냅니다."),
    TBoxClassDef("TemporalObservation", "reasoning-insight", "기간 관찰", parent="TrendEpisode"),
    TBoxClassDef("PersistentDecline", "reasoning-insight", "하락 지속", parent="TrendEpisode"),
    TBoxClassDef("DeclineDeceleration", "reasoning-insight", "하락 둔화", parent="TrendEpisode"),
    TBoxClassDef("RecoveryAttempt", "reasoning-insight", "반등 시도", parent="TrendEpisode"),
    TBoxClassDef("FailedRecovery", "reasoning-insight", "회복 실패", parent="TrendEpisode"),
    TBoxClassDef("AccumulationDuringWeakness", "reasoning-insight", "약세 중 매집", parent="TrendEpisode"),
    TBoxClassDef("DistributionDuringBounce", "reasoning-insight", "반등 중 매도", parent="TrendEpisode"),
    TBoxClassDef("CrossMarketDivergence", "reasoning-insight", "교차 시장 괴리", parent="TrendEpisode"),
    TBoxClassDef("LeverageFlowAmplification", "reasoning-insight", "레버리지 수급 증폭", parent="TrendEpisode"),
    TBoxClassDef("ReversalSignal", "reasoning-insight", "반전 신호", parent="TrendTransition"),
    TBoxClassDef("ConsolidationBreak", "reasoning-insight", "횡보 이탈", parent="TrendTransition"),
    TBoxClassDef("AccelerationSignal", "reasoning-insight", "가속 신호", parent="TrendTransition"),
    TBoxClassDef("DecelerationSignal", "reasoning-insight", "둔화 신호", parent="TrendTransition"),
    TBoxClassDef("MaterialityAssessment", "reasoning-insight", "중요 변경 평가"),
    TBoxClassDef("WhyNow", "reasoning-insight", "지금 볼 이유", parent="MaterialityAssessment", description="이전 상태와 현재 추론 세대의 차이로 지금 다시 봐야 하는 이유를 설명합니다."),
    TBoxClassDef("ThresholdCrossing", "reasoning-insight", "기준선 통과"),
    TBoxClassDef("ExposureAssessment", "reasoning-insight", "노출 영향 평가"),
    TBoxClassDef("ValidationAssessment", "reasoning-insight", "검증 상태 평가", description="근거와 반대 근거, 자료 상태를 확인해 AI 판단을 검증 완료·조건부 사용·판단 보류로 나눕니다."),
    TBoxClassDef("ActionabilityAssessment", "reasoning-insight", "행동 가능성 평가"),
    TBoxClassDef("LossDefenseEvidence", "reasoning-insight", "손실 구간 방어 근거", parent="ActionabilityAssessment"),
    TBoxClassDef("AddBuyEligibility", "reasoning-insight", "추가매수 검토 가능성", parent="ActionabilityAssessment"),
    TBoxClassDef("AveragingDownRisk", "reasoning-insight", "물타기 위험", parent="Risk"),
    TBoxClassDef("RecoveryConfirmation", "reasoning-insight", "회복 확인", parent="ActionabilityAssessment"),
    TBoxClassDef("ReboundFailureRisk", "risk-exposure", "반등 실패 위험", parent="Risk", description="단기 반등이 있지만 주요 평균 가격과 수급 확인이 부족해 회복으로 보기 어려운 위험입니다."),
    TBoxClassDef("MomentumConfirmation", "reasoning-insight", "상승 흐름 확인", parent="ActionabilityAssessment"),
    TBoxClassDef("FlowConfirmation", "reasoning-insight", "수급 확인", parent="ActionabilityAssessment", description="가격 신호가 거래량, 체결강도, 외국인·기관 수급과 같은 방향으로 확인된 상태입니다."),
    TBoxClassDef("ProfitProtection", "reasoning-insight", "수익 보호", parent="ActionabilityAssessment"),
    TBoxClassDef("InvestorFlowRisk", "risk-exposure", "투자자 수급 위험", parent="Risk"),
    TBoxClassDef("InvestorProfilePolicy", "strategy-thesis", "투자 성향 정책", parent="ActionPolicy"),
    TBoxClassDef("StrategyFitAssessment", "reasoning-insight", "투자 성향 적합 판단", parent="ActionabilityAssessment", description="종목 타입, 계정 성향, 비중 한도가 서로 맞는지 판단한 추론입니다."),
    TBoxClassDef("StrategyMismatchRisk", "risk-exposure", "투자 성향 부적합 위험", parent="Risk", description="종목 타입이나 현재 상태가 계정 성향, 손실 허용폭, 비중 정책과 맞지 않는 위험입니다."),
    TBoxClassDef("NewsImpactConfirmation", "reasoning-insight", "뉴스 영향 확인", parent="ActionabilityAssessment", description="뉴스·공시가 실제 가격, 거래량, 수급 반응으로 확인됐는지 나타내는 추론입니다."),
    TBoxClassDef("DisclosureDilutionRisk", "risk-exposure", "공시 희석/자금조달 위험", parent="EventRisk", description="증자, 전환사채, 자기주식 처분 등으로 주주 가치나 수급 부담을 확인해야 하는 공시 위험입니다."),
    TBoxClassDef("PreviousInsight", "reasoning-insight", "이전 인사이트", parent="Insight"),
    TBoxClassDef("Opinion", "reasoning-insight", "AI 의견"),
    TBoxClassDef("InvestmentOpinion", "reasoning-insight", "투자 의견", parent="Opinion"),
    TBoxClassDef("ActiveInvestmentOpinion", "reasoning-insight", "실행 투자 의견", parent="Opinion"),
    TBoxClassDef("ExecutionPlan", "reasoning-insight", "실행 계획"),
    TBoxClassDef("DecisionDriver", "reasoning-insight", "판단 근거 축"),
    TBoxClassDef("DecisionStage", "reasoning-insight", "판단 단계"),
    TBoxClassDef("PeerContext", "reasoning-insight", "피어 맥락", description="동종 기업, 섹터, 경쟁사 뉴스나 밸류에이션 비교가 전달되는 맥락입니다."),
    TBoxClassDef("TargetRole", "reasoning-insight", "판단 대상 역할", description="보유종목과 관심종목처럼 실행 가능한 행동 범위를 나누는 역할입니다."),
    TBoxClassDef("ActionPolicy", "reasoning-insight", "행동 정책", description="대상 역할별로 허용되는 투자 행동과 차단되는 행동을 정의합니다."),
    TBoxClassDef("ActionCandidate", "reasoning-insight", "행동 후보"),
    TBoxClassDef("AllowedAction", "reasoning-insight", "허용 행동", parent="ActionCandidate"),
    TBoxClassDef("BlockedAction", "reasoning-insight", "보류 행동", parent="ActionCandidate"),
    TBoxClassDef("InvalidationCondition", "reasoning-insight", "무효화 조건"),
    TBoxClassDef("NextCheck", "reasoning-insight", "다음 확인"),
    TBoxClassDef("AIValidation", "reasoning-insight", "AI 판단 검증"),
    TBoxClassDef("ValidatedOpinion", "reasoning-insight", "AI 최종 의견", parent="Opinion"),
    TBoxClassDef("AIJudgmentAudit", "reasoning-insight", "AI 판단 감사 로그"),
    TBoxClassDef("InvestmentQuestion", "reasoning-insight", "투자 질문", description="사용자 또는 시스템이 투자 대상과 기간을 지정해 온톨로지에 묻는 질문입니다."),
    TBoxClassDef("SelfQuestion", "reasoning-insight", "자체 확인 질문", parent="InvestmentQuestion", description="근거 충돌과 데이터 공백을 해소하기 위해 시스템이 스스로 생성한 후속 질문입니다."),
    TBoxClassDef("ResearchInquiry", "reasoning-insight", "근거 조사 질의", parent="InvestmentQuestion", description="가설의 필수 근거와 반증 자료를 찾기 위한 제한된 조사 질의입니다."),
    TBoxClassDef("ResearchPlan", "reasoning-insight", "조사 계획", description="투자 질문을 답하기 위해 필요한 근거와 확인 순서를 구조화한 계획입니다."),
    TBoxClassDef("ResearchTask", "reasoning-insight", "조사 작업", parent="ResearchPlan"),
    TBoxClassDef("ResearchSourcePolicy", "reasoning-insight", "조사 출처 정책", description="공식 원문 우선순위, 허용 출처, 신선도와 조회 비용 한도를 정의합니다."),
    TBoxClassDef("VerificationRun", "reasoning-insight", "근거 검증 실행", description="조사 문서의 주장 추출, 종목 식별, 출처 검증과 재추론을 묶은 감사 단위입니다."),
    TBoxClassDef("InformationNeed", "reasoning-insight", "필요 정보", parent="MissingData", description="가설 우선순위 또는 행동을 바꿀 수 있어 추가 수집이 필요한 정보입니다."),
    TBoxClassDef("HypothesisTemplate", "reasoning-insight", "투자 가설 템플릿", parent="InvestmentThesis", description="승인된 TypeDB 규칙과 인과 경로에서 상황별 가설을 만드는 재사용 가능한 정의입니다."),
    TBoxClassDef("ApprovedHypothesisTemplate", "reasoning-insight", "승인 투자 가설 템플릿", parent="HypothesisTemplate"),
    TBoxClassDef("NovelHypothesisProposal", "reasoning-insight", "신규 투자 가설 제안", parent="RuleChangeCandidate", description="기존 템플릿으로 설명되지 않는 관계를 AI가 제안한 검토 전 가설입니다."),
    TBoxClassDef("HypothesisSet", "reasoning-insight", "경쟁 가설 집합", description="동일한 투자 질문에 대해 활성 TypeDB 인과 가설과 근거 충분성·반사실 안전 가설을 비교하는 단위입니다."),
    TBoxClassDef("CompetingHypothesis", "reasoning-insight", "경쟁 투자 가설", parent="InvestmentThesis", description="지지 근거, 반대 근거, 가정과 무효화 조건을 가진 잠정 투자 가설입니다."),
    TBoxClassDef("BeliefState", "reasoning-insight", "잠정 믿음 상태", parent="Belief", description="경쟁 가설 비교 결과이며 최종 투자 의견과 분리해 추적합니다."),
    TBoxClassDef("Assumption", "reasoning-insight", "판단 가정", description="가설이 성립하기 위해 참이어야 하는 전제입니다."),
    TBoxClassDef("RetrievedDocument", "observation-data", "조사 원문", parent="ResearchEvidence", description="온디맨드 조사에서 확보한 원문과 조회 시각, 해시, 사용 범위를 가진 문서입니다."),
    TBoxClassDef("ExtractedClaim", "observation-data", "추출 주장", parent="Evidence", description="원문에서 추출했지만 아직 사실로 확정되지 않은 단일 주장입니다."),
    TBoxClassDef("VerifiedClaim", "observation-data", "검증 주장", parent="ExtractedClaim"),
    TBoxClassDef("DisputedClaim", "observation-data", "상충 주장", parent="ExtractedClaim"),
    TBoxClassDef("RejectedClaim", "observation-data", "기각 주장", parent="ExtractedClaim"),
    TBoxClassDef("EntityResolution", "observation-data", "대상 식별 결과", parent="Evidence", description="문서의 회사명, 종목, 증권 라인과 실제 온톨로지 대상을 연결한 검증 결과입니다."),
    TBoxClassDef("EvidenceAssessment", "observation-data", "근거 품질 평가", parent="Evidence", description="출처 신뢰도, 관련성, 신선도, 독립성과 원문 범위를 평가합니다."),
    TBoxClassDef("ObservedOutcome", "reasoning-insight", "판단 후 관측 결과", parent="Observation", description="판단 이후 가격, 손익, 관계 전이를 관측해 가설을 사후 평가한 결과입니다."),
    TBoxClassDef("HypothesisCalibration", "reasoning-insight", "가설 결과 보정", description="서로 다른 판단 에피소드의 확인·반증 결과를 가설 템플릿별로 집계한 검토용 보정 정보입니다."),
    TBoxClassDef("DecisionPerformance", "reasoning-insight", "판단 성과 평가"),
    TBoxClassDef("RulePerformance", "reasoning-insight", "규칙 성과 평가", parent="DecisionPerformance"),
    TBoxClassDef("HypothesisPerformance", "reasoning-insight", "가설 성과 평가", parent="DecisionPerformance"),
    TBoxClassDef("PredictionError", "reasoning-insight", "예측 오차", parent="Contradiction", description="선택 가설과 이후 관측 결과 사이의 차이입니다."),
    TBoxClassDef("LearningProposal", "reasoning-insight", "학습 변경 제안", parent="RuleChangeCandidate", description="반복된 사후 결과에서 만든 규칙·프롬프트·데이터 수집 변경 후보입니다."),
    TBoxClassDef("PromotionDecision", "reasoning-insight", "변경 승격 결정", parent="RuleBoxGovernance", description="학습 제안을 검토, 실험, 승인, 배포 또는 거절한 결정입니다."),
    TBoxClassDef("AIContextPacket", "reasoning-insight", "AI 컨텍스트 패킷", parent="AIJudgmentAudit"),
    TBoxClassDef("EvidenceSubgraph", "reasoning-insight", "근거 서브그래프", parent="InferencePath"),
    TBoxClassDef("GraphNeighborhood", "reasoning-insight", "그래프 이웃 관계", parent="EvidenceSubgraph"),
    TBoxClassDef("Opportunity", "reasoning-insight", "기회"),
    TBoxClassDef("UndervaluationOpportunity", "reasoning-insight", "저평가 기회", parent="Opportunity", description="안전마진이 충분하지만 추가 확인이 필요한 저평가 후보 신호입니다."),
    TBoxClassDef("Contradiction", "reasoning-insight", "모순"),
    TBoxClassDef("SignalConflict", "reasoning-insight", "신호 충돌", parent="Contradiction", description="위험 신호와 지지 신호가 동시에 강할 때 판단 강도를 조절하기 위한 충돌 상태입니다."),
    TBoxClassDef("Insight", "reasoning-insight", "인사이트"),
    TBoxClassDef("InsightType", "reasoning-insight", "인사이트 타입"),
    TBoxClassDef("InsightPolicy", "reasoning-insight", "인사이트 정책"),
    TBoxClassDef("MessageDeliveryProfile", "reasoning-insight", "메시지 전달 수준"),
    TBoxClassDef("ReasoningRule", "reasoning-insight", "추론 규칙"),
    TBoxClassDef("RuleRegistry", "reasoning-insight", "규칙 레지스트리"),
    TBoxClassDef("RelationRuleRegistry", "reasoning-insight", "투자 관계 규칙 레지스트리", parent="RuleRegistry"),
    TBoxClassDef("GraphInferenceRule", "reasoning-insight", "그래프 추론 규칙", parent="ReasoningRule"),
    TBoxClassDef("RelationReasoningRule", "reasoning-insight", "투자 관계 추론 규칙", parent="ReasoningRule"),
    TBoxClassDef("RuleCondition", "reasoning-insight", "규칙 조건", parent="ReasoningRule"),
    TBoxClassDef("RelationRuleCondition", "reasoning-insight", "투자 관계 규칙 조건", parent="RuleCondition"),
    TBoxClassDef("RelationTemplate", "reasoning-insight", "파생 관계 템플릿", parent="ReasoningRule"),
    TBoxClassDef("RelationRuleTemplate", "reasoning-insight", "투자 관계 파생 템플릿", parent="RelationTemplate"),
    TBoxClassDef("RuleDecisionPolicy", "reasoning-insight", "규칙 판단 단계 정책", parent="RelationTemplate"),
    TBoxClassDef("RulePriorityPolicy", "reasoning-insight", "규칙 우선순위 정책", parent="RelationTemplate"),
    TBoxClassDef("RuleBoxGovernance", "reasoning-insight", "RuleBox 운영 거버넌스"),
    TBoxClassDef("RuleBoxVersion", "reasoning-insight", "RuleBox 저장 버전", parent="RuleBoxGovernance"),
    TBoxClassDef("RuleChangeCandidate", "reasoning-insight", "규칙 변경 후보", parent="RuleBoxGovernance"),
    TBoxClassDef("LanguageRegistryVersion", "operations-dispatch", "보편언어 사전 버전", description="사용자에게 보여줄 투자 용어와 수준별 표현의 승인 버전입니다."),
    TBoxClassDef("DomainTerm", "operations-dispatch", "투자 도메인 용어", description="안정적인 내부 식별자와 승인된 사용자 표현을 연결합니다."),
    TBoxClassDef("TermRendering", "operations-dispatch", "사용자 수준별 표현", description="왕초보, 초보, 중수, 고수에게 보여줄 용어 표현입니다."),
    TBoxClassDef("TermAlias", "operations-dispatch", "용어 별칭", description="입력과 과거 문구에서 같은 뜻으로 인식할 표현입니다."),
    TBoxClassDef("ForbiddenExpression", "operations-dispatch", "사용 금지 표현", description="알림과 화면에서 승인된 표현으로 바꿔야 하는 내부 또는 어려운 용어입니다."),
    TBoxClassDef("LanguageChangeProposal", "operations-dispatch", "보편언어 변경 제안", description="자동 적용하지 않고 검토와 승인을 기다리는 용어 변경 제안입니다."),
    TBoxClassDef("DerivedAssertion", "reasoning-insight", "파생 어설션"),
    TBoxClassDef("InferenceTrace", "reasoning-insight", "추론 경로"),
    TBoxClassDef("InferencePath", "reasoning-insight", "추론 패스", parent="InferenceTrace"),
    TBoxClassDef("InferenceTimeline", "reasoning-insight", "추론 타임라인", parent="InferencePath", description="이전 관측, 현재 사실, 현재 추론 세대를 시간 순서로 묶은 판단 맥락입니다."),
    TBoxClassDef("InferenceGeneration", "reasoning-insight", "추론 세대"),
    TBoxClassDef("CandidateGeneration", "reasoning-insight", "검증 대기 추론 세대", parent="InferenceGeneration"),
    TBoxClassDef("ActiveGeneration", "reasoning-insight", "활성 추론 세대", parent="InferenceGeneration"),
    TBoxClassDef("GraphReasoner", "reasoning-insight", "그래프 추론기"),
    TBoxClassDef("GraphStoreNativeReasoner", "reasoning-insight", "그래프 저장소 네이티브 추론기", parent="GraphReasoner"),
    TBoxClassDef("TypeDBNativeReasoner", "reasoning-insight", "TypeDB 네이티브 추론기", parent="GraphReasoner"),
    TBoxClassDef("ReasoningCard", "reasoning-insight", "추론 카드"),
    TBoxClassDef("AIValidationState", "reasoning-insight", "AI 검증 상태"),
    TBoxClassDef("SourceTrustState", "reasoning-insight", "출처 확인 상태"),
    TBoxClassDef("AIReview", "reasoning-insight", "AI 리뷰"),
    TBoxClassDef("DataPipeline", "operations-dispatch", "데이터 파이프라인"),
    TBoxClassDef("DataPipelineHealth", "operations-dispatch", "데이터 파이프라인 건강 상태"),
    TBoxClassDef("CollectionSchedule", "operations-dispatch", "수집 주기"),
    TBoxClassDef("CollectionPolicy", "operations-dispatch", "수집 정책"),
    TBoxClassDef("MarketSnapshot", "operations-dispatch", "시장 스냅샷", parent="DataPipeline"),
    TBoxClassDef("WatchlistSnapshot", "operations-dispatch", "관심 스냅샷", parent="DataPipeline"),
    TBoxClassDef("ExternalSignalCollection", "operations-dispatch", "외부 신호 수집", parent="DataPipeline"),
    TBoxClassDef("AnalysisJob", "operations-dispatch", "분석 작업"),
    TBoxClassDef("ReasoningCycle", "operations-dispatch", "추론 주기"),
    TBoxClassDef("NotificationPolicy", "operations-dispatch", "알림 정책"),
    TBoxClassDef("NotificationDispatch", "operations-dispatch", "알림 디스패치"),
    TBoxClassDef("NotificationIntent", "operations-dispatch", "알림 의도"),
    TBoxClassDef("AlertCandidate", "operations-dispatch", "알림 후보", parent="NotificationIntent"),
    TBoxClassDef("ImportanceGate", "operations-dispatch", "중요도 게이트", parent="NotificationPolicy"),
    TBoxClassDef("CooldownPolicy", "operations-dispatch", "쿨다운 정책", parent="NotificationPolicy"),
    TBoxClassDef("NoveltyPolicy", "operations-dispatch", "신규성 정책", parent="NotificationPolicy"),
    TBoxClassDef("SuppressionPolicy", "operations-dispatch", "억제 정책", parent="NotificationPolicy"),
    TBoxClassDef("MarketSession", "operations-dispatch", "시장 세션"),
    TBoxClassDef("OperationalEvent", "operations-dispatch", "운영 이벤트"),
]


RELATION_DEFS: List[TBoxRelationDef] = [
    TBoxRelationDef("DEFINES_BOUNDED_CONTEXT", "operations-dispatch", "operations-dispatch", "operations-dispatch"),
    TBoxRelationDef("DEFINES_CLASS", "operations-dispatch", "operations-dispatch", "operations-dispatch"),
    TBoxRelationDef("DEFINES_RELATION", "operations-dispatch", "operations-dispatch", "operations-dispatch"),
    TBoxRelationDef("CONSTRAINS_ASSERTIONS", "operations-dispatch", "operations-dispatch", "operations-dispatch"),
    TBoxRelationDef("CONSTRAINS_RULES", "reasoning-insight", "operations-dispatch", "reasoning-insight"),
    TBoxRelationDef("DERIVES_ASSERTIONS", "reasoning-insight", "reasoning-insight", "reasoning-insight"),
    TBoxRelationDef("IS_A", "investment-core", "investment-core", "investment-core"),
    TBoxRelationDef("HOLDS", "investment-core", "investment-core", "investment-core"),
    TBoxRelationDef("WATCHES", "investment-core", "investment-core", "investment-core"),
    TBoxRelationDef("HOLDS_CASH", "investment-core", "investment-core", "investment-core"),
    TBoxRelationDef("MANAGES_PORTFOLIO", "investment-core", "investment-core", "investment-core"),
    TBoxRelationDef("HAS_POSITION", "investment-core", "investment-core", "investment-core"),
    TBoxRelationDef("HAS_WATCHLIST", "investment-core", "investment-core", "investment-core"),
    TBoxRelationDef("ISSUES", "investment-core", "investment-core", "investment-core"),
    TBoxRelationDef("ISSUES_SECURITY_LINE", "investment-core", "investment-core", "investment-core", "회사가 특정 본주, ADR, 레버리지 ETF 같은 거래 라인을 발행 또는 연결합니다."),
    TBoxRelationDef("HAS_SECURITY_LINE", "investment-core", "investment-core", "investment-core", "종목이 투자 판단에 영향을 줄 수 있는 거래 라인과 연결됩니다."),
    TBoxRelationDef("REPRESENTS_ECONOMIC_CLAIM", "investment-core", "investment-core", "investment-core", "ADR·GDR 등 예탁증서가 본주 경제적 권리를 대표합니다."),
    TBoxRelationDef("TRACKS_UNDERLYING", "investment-core", "investment-core", "investment-core", "ETF나 파생 거래 라인이 기초 거래 라인을 추종합니다."),
    TBoxRelationDef("COMPETES_WITH", "investment-core", "investment-core", "investment-core"),
    TBoxRelationDef("SUPPLIES_TO", "observation-data", "investment-core", "investment-core"),
    TBoxRelationDef("SELLS_TO", "observation-data", "investment-core", "investment-core"),
    TBoxRelationDef("HAS_PRODUCT_EXPOSURE", "observation-data", "investment-core", "observation-data"),
    TBoxRelationDef("HAS_SUPPLY_CHAIN_EXPOSURE", "observation-data", "investment-core", "observation-data"),
    TBoxRelationDef("HAS_CUSTOMER_EXPOSURE", "observation-data", "investment-core", "observation-data"),
    TBoxRelationDef("HAS_REVENUE_EXPOSURE", "observation-data", "investment-core", "observation-data"),
    TBoxRelationDef("REPRESENTS_STOCK", "investment-core", "investment-core", "investment-core"),
    TBoxRelationDef("REPRESENTS_INSTRUMENT", "investment-core", "investment-core", "investment-core"),
    TBoxRelationDef("HAS_MARKET_EXPOSURE", "investment-core", "investment-core", "investment-core"),
    TBoxRelationDef("BELONGS_TO", "investment-core", "investment-core", "investment-core"),
    TBoxRelationDef("TRADED_IN", "investment-core", "investment-core", "investment-core"),
    TBoxRelationDef("DENOMINATED_IN", "investment-core", "investment-core", "investment-core"),
    TBoxRelationDef("EXPOSED_TO", "risk-exposure", "investment-core", "risk-exposure"),
    TBoxRelationDef("HAS_FX_EXPOSURE", "risk-exposure", "investment-core", "risk-exposure"),
    TBoxRelationDef("HAS_RATE_SENSITIVITY", "risk-exposure", "investment-core", "risk-exposure"),
    TBoxRelationDef("HAS_MACRO_REGIME", "risk-exposure", "investment-core", "risk-exposure", "투자 대상이 현재 금리·환율·수익률곡선 레짐에 노출됩니다."),
    TBoxRelationDef("HAS_CRYPTO_EXPOSURE", "risk-exposure", "investment-core", "risk-exposure", "투자 대상이 크립토 가격 경로와 변동성에 노출됩니다."),
    TBoxRelationDef("HAS_ARBITRAGE_FRICTION", "risk-exposure", "investment-core", "risk-exposure", "투자 대상이 교차 상장 라인의 차익거래 제약에 노출됩니다."),
    TBoxRelationDef("HAS_LEVERAGED_PRODUCT", "risk-exposure", "investment-core", "investment-core", "투자 대상과 연결된 단일종목 레버리지 상품을 표시합니다."),
    TBoxRelationDef("HAS_ADR_PREMIUM", "observation-data", "investment-core", "observation-data", "ADR과 본주의 환산 가격 괴리를 관측값으로 연결합니다."),
    TBoxRelationDef("HAS_LEVERAGED_FLOW_SIGNAL", "observation-data", "investment-core", "observation-data", "단일종목 레버리지 상품 가격·거래량을 수급 증폭 신호로 연결합니다."),
    TBoxRelationDef("AMPLIFIES_DAILY_RETURN", "risk-exposure", "investment-core", "risk-exposure", "레버리지·인버스 상품이 기초자산의 일일 수익률 변동을 증폭합니다."),
    TBoxRelationDef("CREATES_REBALANCING_FLOW", "risk-exposure", "investment-core", "observation-data", "일일 리셋 상품이 기초자산 주변의 재조정 수급을 만들 수 있습니다."),
    TBoxRelationDef("HAS_OBSERVATION", "observation-data", "investment-core", "observation-data"),
    TBoxRelationDef("OBSERVED_FROM", "observation-data", "investment-core", "observation-data"),
    TBoxRelationDef("HAS_PRICE", "observation-data", "investment-core", "observation-data"),
    TBoxRelationDef("HAS_PRICE_PATH", "observation-data", "investment-core", "observation-data"),
    TBoxRelationDef("HAS_TECHNICAL_INDICATOR", "observation-data", "investment-core", "observation-data"),
    TBoxRelationDef("HAS_TRADE_FLOW", "observation-data", "investment-core", "observation-data"),
    TBoxRelationDef("HAS_INVESTOR_FLOW_SENTIMENT", "observation-data", "investment-core", "observation-data", "외국인·기관·개인 수급을 투자자 심리 관계로 해석합니다."),
    TBoxRelationDef("HAS_PSYCHOLOGY_OBSERVATION", "observation-data", "investment-core", "observation-data", "종목에 가격 행동, 수급, 옵션, 뉴스, 군중심리 관측을 출처별로 연결합니다."),
    TBoxRelationDef("HAS_MARKET_PSYCHOLOGY_STATE", "reasoning-insight", "investment-core", "reasoning-insight", "신선한 심리 관측을 종합한 현재 상태를 종목에 연결합니다."),
    TBoxRelationDef("COMPOSED_FROM_PSYCHOLOGY", "reasoning-insight", "reasoning-insight", "observation-data", "종합 심리 상태를 구성한 개별 관측 근거를 연결합니다."),
    TBoxRelationDef("HAS_PSYCHOLOGY_SHADOW", "reasoning-insight", "investment-core", "reasoning-insight", "TypeDB가 심리 상태를 Shadow 전용 추론으로 확인했음을 기록하며 실제 판단에는 사용하지 않습니다."),
    TBoxRelationDef("HAS_LIQUIDITY_PROFILE", "observation-data", "investment-core", "risk-exposure"),
    TBoxRelationDef("HAS_EXECUTION_METRIC", "observation-data", "investment-core", "observation-data"),
    TBoxRelationDef("HAS_DATA_QUALITY", "observation-data", "investment-core", "observation-data"),
    TBoxRelationDef("HAS_COVERAGE_GAP", "observation-data", "investment-core", "observation-data", "ABox가 투자 판단 필수 범주를 채우지 못한 공백을 명시합니다."),
    TBoxRelationDef("HAS_EXTERNAL_SIGNAL", "observation-data", "investment-core", "observation-data"),
    TBoxRelationDef("HAS_PROVENANCE", "observation-data", "observation-data", "observation-data"),
    TBoxRelationDef("HAS_ANALYSIS", "observation-data", "observation-data", "observation-data"),
    TBoxRelationDef("EXPLAINS", "observation-data", "observation-data", "observation-data"),
    TBoxRelationDef("HAS_SOURCE_RELIABILITY", "observation-data", "observation-data", "observation-data"),
    TBoxRelationDef("WEIGHTED_BY_DATA_STATE", "observation-data", "observation-data", "reasoning-insight"),
    TBoxRelationDef("STALE_AFTER", "observation-data", "observation-data", "observation-data"),
    TBoxRelationDef("CONFLICTS_WITH_SOURCE", "observation-data", "observation-data", "observation-data"),
    TBoxRelationDef("PRODUCES_OBSERVATION", "observation-data", "operations-dispatch", "observation-data"),
    TBoxRelationDef("MEASURED_AT", "observation-data", "observation-data", "observation-data"),
    TBoxRelationDef("VALID_DURING", "observation-data", "observation-data", "observation-data"),
    TBoxRelationDef("PRECEDES", "observation-data", "observation-data", "observation-data"),
    TBoxRelationDef("HAS_TEMPORAL_WINDOW", "observation-data", "investment-core", "observation-data", "종목이 기간 단위 관측 구간과 연결됩니다."),
    TBoxRelationDef("WINDOW_CONTAINS_OBSERVATION", "observation-data", "observation-data", "observation-data", "기간 구간이 가격, 수급, 뉴스, 공시 관측을 포함합니다."),
    TBoxRelationDef("HAS_PRICE_PATH_PATTERN", "observation-data", "observation-data", "observation-data", "기간 구간이 가격 경로 패턴을 갖습니다."),
    TBoxRelationDef("HAS_FLOW_PATTERN", "observation-data", "observation-data", "observation-data", "기간 구간이 수급 패턴을 갖습니다."),
    TBoxRelationDef("HAS_EVENT_CLUSTER", "observation-data", "observation-data", "observation-data", "기간 구간이 뉴스·공시·외부 이벤트 묶음을 갖습니다."),
    TBoxRelationDef("CHANGES_OVER_WINDOW", "reasoning-insight", "observation-data", "reasoning-insight", "값이 특정 기간 동안 의미 있게 바뀌었음을 나타냅니다."),
    TBoxRelationDef("CONFIRMED_ACROSS_WINDOW", "reasoning-insight", "observation-data", "reasoning-insight", "가격, 수급, 이벤트 신호가 기간 안에서 같은 방향으로 확인됩니다."),
    TBoxRelationDef("DIVERGES_ACROSS_WINDOW", "reasoning-insight", "observation-data", "reasoning-insight", "가격, 수급, 이벤트 신호가 기간 안에서 서로 어긋납니다."),
    TBoxRelationDef("CHANGED_FROM", "reasoning-insight", "reasoning-insight", "reasoning-insight"),
    TBoxRelationDef("CONFIRMED_OVER", "reasoning-insight", "observation-data", "reasoning-insight"),
    TBoxRelationDef("FAILED_AFTER", "reasoning-insight", "observation-data", "reasoning-insight"),
    TBoxRelationDef("HAS_TREND_PHASE", "reasoning-insight", "observation-data", "reasoning-insight"),
    TBoxRelationDef("HAS_TREND_TRANSITION", "reasoning-insight", "investment-core", "reasoning-insight"),
    TBoxRelationDef("DERIVES_TREND_EPISODE", "reasoning-insight", "investment-core", "reasoning-insight", "기간 구간의 가격·수급·이벤트 묶음으로 추세 에피소드를 추론합니다."),
    TBoxRelationDef("AFFECTS_DECISION_EPISODE", "reasoning-insight", "reasoning-insight", "reasoning-insight", "추세 에피소드가 투자 판단 강도와 실행 전 확인 항목을 바꿉니다."),
    TBoxRelationDef("INDICATES_REVERSAL", "reasoning-insight", "reasoning-insight", "reasoning-insight"),
    TBoxRelationDef("BREAKS_CONSOLIDATION", "reasoning-insight", "reasoning-insight", "reasoning-insight"),
    TBoxRelationDef("INDICATES_ACCELERATION", "reasoning-insight", "reasoning-insight", "reasoning-insight"),
    TBoxRelationDef("INDICATES_DECELERATION", "reasoning-insight", "reasoning-insight", "reasoning-insight"),
    TBoxRelationDef("INDICATES_WEAKENING", "reasoning-insight", "reasoning-insight", "reasoning-insight"),
    TBoxRelationDef("RETESTS_LEVEL", "observation-data", "investment-core", "observation-data"),
    TBoxRelationDef("BREAKS_LEVEL", "observation-data", "investment-core", "observation-data"),
    TBoxRelationDef("RECLAIMS_LEVEL", "observation-data", "investment-core", "observation-data"),
    TBoxRelationDef("MENTIONS_INSTRUMENT", "observation-data", "observation-data", "investment-core"),
    TBoxRelationDef("MENTIONS_PEER", "observation-data", "observation-data", "investment-core"),
    TBoxRelationDef("HAS_TOPIC", "observation-data", "observation-data", "observation-data"),
    TBoxRelationDef("HAS_EVENT_TYPE", "observation-data", "observation-data", "observation-data"),
    TBoxRelationDef("AFFECTS_SECTOR", "observation-data", "observation-data", "investment-core"),
    TBoxRelationDef(
        "NEWS_CONTEXT_FOR",
        "observation-data",
        "observation-data",
        "investment-core",
        "뉴스가 투자 대상의 직접/간접 맥락 근거로 연결됩니다.",
    ),
    TBoxRelationDef(
        "NEWS_RISK_FOR",
        "risk-exposure",
        "observation-data",
        "investment-core",
        "뉴스가 투자 대상의 이벤트 리스크 근거로 연결됩니다.",
    ),
    TBoxRelationDef(
        "NEWS_SUPPORTS_ENTRY",
        "strategy-thesis",
        "observation-data",
        "investment-core",
        "뉴스가 투자 대상의 진입/유지 가설을 지지하는 근거로 연결됩니다.",
    ),
    TBoxRelationDef(
        "NEWS_PROPAGATES_CONTEXT",
        "observation-data",
        "observation-data",
        "investment-core",
        "섹터, 피어, 시장 뉴스가 투자 대상에 간접 맥락으로 전파됩니다.",
    ),
    TBoxRelationDef("MATERIAL_TO", "observation-data", "observation-data", "strategy-thesis"),
    TBoxRelationDef("DECAYS_AFTER", "observation-data", "observation-data", "observation-data"),
    TBoxRelationDef("HAS_TIME_HORIZON", "observation-data", "investment-core", "observation-data"),
    TBoxRelationDef("APPLIES_TO_HORIZON", "observation-data", "strategy-thesis", "observation-data"),
    TBoxRelationDef("HAS_VALUATION", "strategy-thesis", "investment-core", "strategy-thesis"),
    TBoxRelationDef("HAS_AI_VALUATION_PROPOSAL", "strategy-thesis", "investment-core", "strategy-thesis", "종목이 사용자 검토 전 AI 적정가 제안과 연결됩니다."),
    TBoxRelationDef("USES_VALUATION_MODEL", "strategy-thesis", "investment-core", "strategy-thesis", "종목 또는 밸류에이션 제안이 어떤 종목 타입별 평가 모델을 쓰는지 연결합니다."),
    TBoxRelationDef("HAS_ACTIVE_VALUATION", "strategy-thesis", "investment-core", "strategy-thesis", "현재 투자 판단에 적용 중인 밸류에이션을 연결합니다."),
    TBoxRelationDef("DERIVED_FROM_AI_VALUATION_PROPOSAL", "strategy-thesis", "strategy-thesis", "strategy-thesis", "활성 밸류에이션이 AI 제안에서 자동 적용됐음을 연결합니다."),
    TBoxRelationDef("DERIVED_FROM_VALUATION_ASSUMPTION", "strategy-thesis", "strategy-thesis", "strategy-thesis", "활성 밸류에이션이 사용자 입력 또는 외부 가정에서 왔음을 연결합니다."),
    TBoxRelationDef("AWAITS_USER_REVIEW", "strategy-thesis", "strategy-thesis", "strategy-thesis", "자동 적용된 AI 밸류에이션이 사용자 검토를 기다리는 상태임을 연결합니다."),
    TBoxRelationDef("HAS_VALUATION_METRIC", "observation-data", "investment-core", "observation-data", "종목이 PER, 예상 EPS, 목표 PER 같은 밸류에이션 원천 지표와 연결됩니다."),
    TBoxRelationDef("HAS_FAIR_VALUE_ESTIMATE", "strategy-thesis", "investment-core", "strategy-thesis", "종목이 사용자 공식 또는 외부 근거로 계산한 적정가 추정과 연결됩니다."),
    TBoxRelationDef("HAS_FAIR_VALUE_RANGE", "strategy-thesis", "investment-core", "strategy-thesis", "종목이 보수적·기준·낙관 적정가 범위와 연결됩니다."),
    TBoxRelationDef("HAS_VALUATION_DATA_STATE", "strategy-thesis", "investment-core", "strategy-thesis", "종목이 밸류에이션 자료의 충분·일부·부족·사용 불가 상태와 연결됩니다."),
    TBoxRelationDef("HAS_VALUATION_CONSENSUS", "strategy-thesis", "investment-core", "strategy-thesis", "종목이 여러 밸류에이션 모델의 합의 또는 충돌 상태와 연결됩니다."),
    TBoxRelationDef("HAS_MARGIN_OF_SAFETY", "strategy-thesis", "investment-core", "strategy-thesis", "종목이 현재가와 적정가의 차이인 안전마진과 연결됩니다."),
    TBoxRelationDef("COMPARES_WITH_PEER_MULTIPLE", "strategy-thesis", "investment-core", "strategy-thesis", "종목 밸류에이션을 피어 멀티플 또는 과거 밴드와 비교합니다."),
    TBoxRelationDef("HAS_VALUATION_RISK", "risk-exposure", "investment-core", "risk-exposure", "밸류에이션 근거가 현재가 부담 또는 고평가 위험을 만들었는지 연결합니다."),
    TBoxRelationDef("HAS_VALUATION_OPPORTUNITY", "reasoning-insight", "investment-core", "reasoning-insight", "안전마진과 확인 조건이 저평가 기회 후보를 만들었는지 연결합니다."),
    TBoxRelationDef("HAS_THRESHOLD", "strategy-thesis", "strategy-thesis", "strategy-thesis"),
    TBoxRelationDef("HAS_RUNTIME_SETTING", "strategy-thesis", "investment-core", "strategy-thesis"),
    TBoxRelationDef("HAS_ALERT_RULE", "strategy-thesis", "strategy-thesis", "strategy-thesis"),
    TBoxRelationDef("HAS_PROMPT_TEMPLATE", "strategy-thesis", "strategy-thesis", "strategy-thesis"),
    TBoxRelationDef("USES_STRATEGY", "strategy-thesis", "investment-core", "strategy-thesis"),
    TBoxRelationDef("HAS_STRATEGY_PROPOSAL", "strategy-thesis", "reasoning-insight", "strategy-thesis"),
    TBoxRelationDef("VALIDATES_STRATEGY", "strategy-thesis", "reasoning-insight", "strategy-thesis"),
    TBoxRelationDef("DEPLOYS_STRATEGY", "strategy-thesis", "reasoning-insight", "strategy-thesis"),
    TBoxRelationDef("HAS_INVESTOR_PROFILE", "strategy-thesis", "investment-core", "strategy-thesis"),
    TBoxRelationDef("USES_INVESTMENT_STRATEGY_PROFILE", "strategy-thesis", "investment-core", "strategy-thesis"),
    TBoxRelationDef("HAS_RISK_BUDGET", "strategy-thesis", "strategy-thesis", "strategy-thesis"),
    TBoxRelationDef("HAS_PROFIT_POLICY", "strategy-thesis", "strategy-thesis", "strategy-thesis"),
    TBoxRelationDef("HAS_POSITION_ROLE", "strategy-thesis", "investment-core", "strategy-thesis"),
    TBoxRelationDef("HAS_INSTRUMENT_PROFILE", "strategy-thesis", "investment-core", "strategy-thesis"),
    TBoxRelationDef("HAS_MARKET_PROXY_PROFILE", "strategy-thesis", "investment-core", "strategy-thesis", "투자 대상이 시장 프록시 프로필과 연결되어 배경 시장 신호로 해석됩니다."),
    TBoxRelationDef("OBSERVES_MARKET_PROXY", "strategy-thesis", "investment-core", "strategy-thesis", "포트폴리오가 보유하지 않은 대표 시장 센서를 지속 관찰합니다."),
    TBoxRelationDef("PROXIES_THEME", "strategy-thesis", "investment-core", "strategy-thesis", "시장 프록시 종목이 위험선호, 금리, 크레딧, IPO, 달러 같은 테마를 대변합니다."),
    TBoxRelationDef("SENSITIVE_TO", "strategy-thesis", "investment-core", "strategy-thesis", "시장 프록시 또는 종목 프로필이 특정 팩터 변화에 민감합니다."),
    TBoxRelationDef("HAS_ARCHETYPE", "strategy-thesis", "strategy-thesis", "strategy-thesis"),
    TBoxRelationDef("HAS_FACTOR_SENSITIVITY", "strategy-thesis", "strategy-thesis", "strategy-thesis"),
    TBoxRelationDef("HAS_POSITION_INTENT", "strategy-thesis", "strategy-thesis", "strategy-thesis"),
    TBoxRelationDef("USES_INSTRUMENT_POLICY", "strategy-thesis", "strategy-thesis", "strategy-thesis"),
    TBoxRelationDef("EVALUATED_UNDER_STRATEGY", "strategy-thesis", "investment-core", "strategy-thesis"),
    TBoxRelationDef("BASED_ON_THESIS", "strategy-thesis", "investment-core", "strategy-thesis"),
    TBoxRelationDef("HAS_ENTRY_CONDITION", "strategy-thesis", "strategy-thesis", "strategy-thesis"),
    TBoxRelationDef("HAS_EXIT_CONDITION", "strategy-thesis", "strategy-thesis", "strategy-thesis"),
    TBoxRelationDef("HAS_RISK_MANAGEMENT_RULE", "strategy-thesis", "strategy-thesis", "strategy-thesis"),
    TBoxRelationDef("HAS_POSITION_SIZING_RULE", "strategy-thesis", "strategy-thesis", "strategy-thesis"),
    TBoxRelationDef("HAS_REBALANCING_RULE", "strategy-thesis", "strategy-thesis", "strategy-thesis"),
    TBoxRelationDef("HAS_FACTOR_EXPOSURE", "strategy-thesis", "investment-core", "strategy-thesis"),
    TBoxRelationDef("HAS_BETA_TO", "strategy-thesis", "investment-core", "strategy-thesis"),
    TBoxRelationDef("CORRELATED_WITH", "risk-exposure", "investment-core", "investment-core"),
    TBoxRelationDef("OFFSETS_RISK", "risk-exposure", "strategy-thesis", "risk-exposure"),
    TBoxRelationDef("SUPPORTS_THESIS", "strategy-thesis", "reasoning-insight", "strategy-thesis"),
    TBoxRelationDef("WEAKENS_THESIS", "strategy-thesis", "risk-exposure", "strategy-thesis"),
    TBoxRelationDef("INVALIDATES_THESIS", "strategy-thesis", "reasoning-insight", "strategy-thesis"),
    TBoxRelationDef("ASKS_ABOUT", "reasoning-insight", "reasoning-insight", "investment-core", "투자 질문이 어떤 종목, 포지션 또는 포트폴리오를 대상으로 하는지 연결합니다."),
    TBoxRelationDef("HAS_RESEARCH_PLAN", "reasoning-insight", "reasoning-insight", "reasoning-insight"),
    TBoxRelationDef("DECOMPOSES_INTO", "reasoning-insight", "reasoning-insight", "reasoning-insight", "질문이나 조사 계획을 검증 가능한 조사 작업으로 나눕니다."),
    TBoxRelationDef("USES_SOURCE_POLICY", "reasoning-insight", "reasoning-insight", "reasoning-insight", "조사 작업을 승인 출처와 비용·신선도 정책에 연결합니다."),
    TBoxRelationDef("TESTS_HYPOTHESIS", "reasoning-insight", "reasoning-insight", "strategy-thesis", "조사 작업이 어떤 경쟁 가설을 검증하거나 반박하는지 연결합니다."),
    TBoxRelationDef("REQUIRES_EVIDENCE", "reasoning-insight", "reasoning-insight", "observation-data", "가설 또는 조사 작업이 필요로 하는 근거 범주를 연결합니다."),
    TBoxRelationDef("HAS_HYPOTHESIS_SET", "reasoning-insight", "reasoning-insight", "reasoning-insight"),
    TBoxRelationDef("CONTAINS_HYPOTHESIS", "reasoning-insight", "reasoning-insight", "strategy-thesis"),
    TBoxRelationDef("INSTANTIATES_HYPOTHESIS_TEMPLATE", "reasoning-insight", "strategy-thesis", "strategy-thesis", "현재 가설 인스턴스를 승인된 TypeDB 가설 템플릿과 연결합니다."),
    TBoxRelationDef("APPLICABLE_TO", "reasoning-insight", "strategy-thesis", "investment-core", "승인 가설 템플릿이 어떤 종목과 현재 상황에 적용 가능한지 연결합니다."),
    TBoxRelationDef("COMPETES_WITH_HYPOTHESIS", "reasoning-insight", "strategy-thesis", "strategy-thesis", "동일 질문에 대한 서로 다른 설명 가설을 경쟁 관계로 연결합니다."),
    TBoxRelationDef("DEPENDS_ON_ASSUMPTION", "reasoning-insight", "strategy-thesis", "reasoning-insight"),
    TBoxRelationDef("ANSWERED_BY", "reasoning-insight", "reasoning-insight", "reasoning-insight", "투자 질문을 최종 판단 에피소드와 연결합니다."),
    TBoxRelationDef("HAS_DECISION_EPISODE", "reasoning-insight", "investment-core", "reasoning-insight", "종목과 포트폴리오가 과거 판단 에피소드 기억을 갖습니다."),
    TBoxRelationDef("SELECTS_HYPOTHESIS", "reasoning-insight", "reasoning-insight", "strategy-thesis", "최종 판단이 경쟁 가설 중 어떤 가설을 잠정 선택했는지 연결합니다."),
    TBoxRelationDef("HAS_UNRESOLVED_QUESTION", "reasoning-insight", "reasoning-insight", "reasoning-insight"),
    TBoxRelationDef("HAS_VERIFICATION_RUN", "reasoning-insight", "reasoning-insight", "reasoning-insight", "질문과 판단 에피소드를 온디맨드 근거 검증 실행에 연결합니다."),
    TBoxRelationDef("PRODUCES_VERIFICATION_RESULT", "reasoning-insight", "reasoning-insight", "observation-data", "근거 검증 실행이 투자 판단에 사용할 수 있는 검증 주장을 생성했음을 연결합니다."),
    TBoxRelationDef("PROPOSES_HYPOTHESIS_FOR", "reasoning-insight", "reasoning-insight", "investment-core", "검토 전 신규 가설 제안을 대상 종목과 연결합니다."),
    TBoxRelationDef("RETRIEVED_FROM", "reasoning-insight", "observation-data", "observation-data", "조사 원문을 실제 데이터 출처와 연결합니다."),
    TBoxRelationDef("ASSERTS", "reasoning-insight", "observation-data", "observation-data", "문서가 포함한 개별 주장을 연결합니다."),
    TBoxRelationDef("RESOLVES_TO", "reasoning-insight", "observation-data", "investment-core", "추출된 엔티티 언급을 실제 회사나 증권에 연결합니다."),
    TBoxRelationDef("VERIFIED_BY", "reasoning-insight", "observation-data", "observation-data", "주장을 근거 품질 평가와 검증 결과에 연결합니다."),
    TBoxRelationDef("CORROBORATED_BY", "reasoning-insight", "observation-data", "observation-data", "독립 출처에서 같은 주장을 교차 확인합니다."),
    TBoxRelationDef("RESULTED_IN_OUTCOME", "reasoning-insight", "reasoning-insight", "reasoning-insight", "판단 에피소드와 이후 관측 결과를 연결합니다."),
    TBoxRelationDef("OBSERVES_OUTCOME", "reasoning-insight", "investment-core", "reasoning-insight"),
    TBoxRelationDef("CALIBRATED_BY_OUTCOME", "reasoning-insight", "strategy-thesis", "reasoning-insight", "가설 템플릿을 독립 판단 에피소드의 사후 결과 집계와 연결합니다."),
    TBoxRelationDef("HAS_HYPOTHESIS_CALIBRATION", "reasoning-insight", "investment-core", "reasoning-insight", "포트폴리오가 현재 판단에 참고할 가설 결과 보정을 갖습니다."),
    TBoxRelationDef("HAS_DECISION_PERFORMANCE", "reasoning-insight", "investment-core", "reasoning-insight"),
    TBoxRelationDef("HAS_PERFORMANCE_SLICE", "reasoning-insight", "reasoning-insight", "reasoning-insight"),
    TBoxRelationDef("EVALUATES_RULE", "reasoning-insight", "reasoning-insight", "reasoning-insight"),
    TBoxRelationDef("EVALUATES_HYPOTHESIS", "reasoning-insight", "reasoning-insight", "strategy-thesis"),
    TBoxRelationDef("LEARNED_FROM", "reasoning-insight", "reasoning-insight", "reasoning-insight"),
    TBoxRelationDef("PROPOSES_CHANGE", "reasoning-insight", "reasoning-insight", "reasoning-insight"),
    TBoxRelationDef("TESTED_IN", "reasoning-insight", "reasoning-insight", "strategy-thesis"),
    TBoxRelationDef("SUPERSEDES", "reasoning-insight", "reasoning-insight", "reasoning-insight"),
    TBoxRelationDef("TRIGGERS_ENTRY", "strategy-thesis", "reasoning-insight", "strategy-thesis"),
    TBoxRelationDef("TRIGGERS_EXIT", "strategy-thesis", "risk-exposure", "strategy-thesis"),
    TBoxRelationDef("REQUIRES_CONFIRMATION", "strategy-thesis", "strategy-thesis", "observation-data"),
    TBoxRelationDef("CONFIGURES", "strategy-thesis", "investment-core", "strategy-thesis"),
    TBoxRelationDef("DERIVES_SIGNAL", "reasoning-insight", "observation-data", "reasoning-insight"),
    TBoxRelationDef("DEFINES_RULE", "reasoning-insight", "reasoning-insight", "reasoning-insight"),
    TBoxRelationDef("HAS_CONDITION", "reasoning-insight", "reasoning-insight", "reasoning-insight"),
    TBoxRelationDef("DERIVES_RELATION", "reasoning-insight", "reasoning-insight", "reasoning-insight"),
    TBoxRelationDef("HAS_RULEBOX_VERSION", "reasoning-insight", "reasoning-insight", "reasoning-insight"),
    TBoxRelationDef("HAS_RULE_CHANGE_CANDIDATE", "reasoning-insight", "reasoning-insight", "reasoning-insight"),
    TBoxRelationDef("TRIGGERED_INFERENCE", "reasoning-insight", "reasoning-insight", "reasoning-insight"),
    TBoxRelationDef("EXECUTES_RULEBOX", "reasoning-insight", "reasoning-insight", "reasoning-insight"),
    TBoxRelationDef("MATERIALIZES_INFERENCE", "reasoning-insight", "reasoning-insight", "reasoning-insight"),
    TBoxRelationDef("HAS_INFERENCE_TRACE", "reasoning-insight", "investment-core", "reasoning-insight"),
    TBoxRelationDef("EXPLAINED_BY_TRACE", "reasoning-insight", "reasoning-insight", "reasoning-insight"),
    TBoxRelationDef("HAS_INFERRED_RISK", "risk-exposure", "investment-core", "risk-exposure"),
    TBoxRelationDef("HAS_INFERRED_SUPPORT", "strategy-thesis", "investment-core", "reasoning-insight"),
    TBoxRelationDef("HAS_INFERRED_ENTRY_OPPORTUNITY", "strategy-thesis", "investment-core", "reasoning-insight"),
    TBoxRelationDef("MATCHES_INVESTOR_PROFILE", "strategy-thesis", "investment-core", "reasoning-insight", "종목 타입과 계정 투자 성향이 맞는지 추론합니다."),
    TBoxRelationDef("FITS_INVESTOR_RISK_PROFILE", "strategy-thesis", "investment-core", "reasoning-insight", "투자 성향의 손실·비중 허용 범위 안에서 행동 후보가 가능한지 추론합니다."),
    TBoxRelationDef("VIOLATES_STRATEGY_FIT", "risk-exposure", "investment-core", "risk-exposure", "종목 타입이나 현재 흐름이 계정 전략과 맞지 않는 위험을 추론합니다."),
    TBoxRelationDef("VIOLATES_RISK_TOLERANCE", "risk-exposure", "investment-core", "risk-exposure", "보유 손익과 비중이 계정 투자 성향의 손실 허용 기준을 넘었는지 추론합니다."),
    TBoxRelationDef("CONFIRMS_RECOVERY", "reasoning-insight", "investment-core", "reasoning-insight", "가격 회복이 거래·수급 확인으로 보강됐는지 추론합니다."),
    TBoxRelationDef("FAILS_RECOVERY", "risk-exposure", "investment-core", "risk-exposure", "단기 반등이 주요 평균 가격과 수급 확인을 통과하지 못했는지 추론합니다."),
    TBoxRelationDef("CONFIRMS_WITH_FLOW", "reasoning-insight", "investment-core", "reasoning-insight", "가격 신호가 투자자별 수급 심리와 같은 방향인지 추론합니다."),
    TBoxRelationDef("DIVERGES_FROM_FLOW", "risk-exposure", "investment-core", "risk-exposure", "가격 변화와 외국인·기관·개인 수급 심리가 어긋나는지 추론합니다."),
    TBoxRelationDef("CONFIRMS_EVENT_IMPACT", "reasoning-insight", "investment-core", "reasoning-insight", "뉴스·공시 영향이 가격·거래 반응으로 확인됐는지 추론합니다."),
    TBoxRelationDef("HAS_DILUTION_RISK", "risk-exposure", "investment-core", "risk-exposure", "공시가 자금조달, 지분 희석, 수급 부담 위험을 만들었는지 추론합니다."),
    TBoxRelationDef("HAS_ACTION_CANDIDATE", "reasoning-insight", "investment-core", "reasoning-insight"),
    TBoxRelationDef("USED_AS_EVIDENCE", "reasoning-insight", "reasoning-insight", "reasoning-insight"),
    TBoxRelationDef("CONFIRMS_SIGNAL", "reasoning-insight", "reasoning-insight", "reasoning-insight"),
    TBoxRelationDef("DIVERGES_FROM", "reasoning-insight", "reasoning-insight", "reasoning-insight"),
    TBoxRelationDef("DERIVES", "reasoning-insight", "reasoning-insight", "reasoning-insight"),
    TBoxRelationDef("AFFECTS", "reasoning-insight", "observation-data", "reasoning-insight"),
    TBoxRelationDef("IMPACTS_OPINION", "reasoning-insight", "reasoning-insight", "reasoning-insight"),
    TBoxRelationDef("CONTRIBUTES_TO", "reasoning-insight", "reasoning-insight", "strategy-thesis"),
    TBoxRelationDef("SUPPORTED_BY", "reasoning-insight", "investment-core", "reasoning-insight"),
    TBoxRelationDef("CONTRADICTS", "reasoning-insight", "reasoning-insight", "reasoning-insight"),
    TBoxRelationDef("USES_EVIDENCE_FROM", "reasoning-insight", "investment-core", "reasoning-insight"),
    TBoxRelationDef("REQUESTS_OPINION_FROM", "reasoning-insight", "investment-core", "reasoning-insight"),
    TBoxRelationDef("HAS_EVIDENCE", "reasoning-insight", "investment-core", "reasoning-insight"),
    TBoxRelationDef("HAS_BELIEF", "reasoning-insight", "investment-core", "reasoning-insight"),
    TBoxRelationDef("HAS_OPINION", "reasoning-insight", "investment-core", "reasoning-insight"),
    TBoxRelationDef("HAS_EXECUTION_PLAN", "reasoning-insight", "investment-core", "reasoning-insight"),
    TBoxRelationDef("HAS_MESSAGE_DELIVERY_PROFILE", "reasoning-insight", "investment-core", "reasoning-insight"),
    TBoxRelationDef("USES_MESSAGE_DELIVERY_PROFILE", "reasoning-insight", "investment-core", "reasoning-insight"),
    TBoxRelationDef("HAS_AI_CONTEXT_PACKET", "reasoning-insight", "reasoning-insight", "reasoning-insight"),
    TBoxRelationDef("HAS_EVIDENCE_SUBGRAPH", "reasoning-insight", "reasoning-insight", "reasoning-insight"),
    TBoxRelationDef("INCLUDES_EVIDENCE_RELATION", "reasoning-insight", "reasoning-insight", "reasoning-insight"),
    TBoxRelationDef("HAS_DECISION_DRIVER", "reasoning-insight", "reasoning-insight", "reasoning-insight"),
    TBoxRelationDef("HAS_TARGET_ROLE", "reasoning-insight", "investment-core", "reasoning-insight"),
    TBoxRelationDef("USES_ACTION_POLICY", "reasoning-insight", "investment-core", "reasoning-insight"),
    TBoxRelationDef("ALLOWS_ACTION", "reasoning-insight", "reasoning-insight", "reasoning-insight"),
    TBoxRelationDef("HAS_PRIMARY_ACTION", "reasoning-insight", "reasoning-insight", "reasoning-insight"),
    TBoxRelationDef("BLOCKS_ACTION", "reasoning-insight", "reasoning-insight", "reasoning-insight"),
    TBoxRelationDef("LIMITED_BY_LIQUIDITY", "risk-exposure", "reasoning-insight", "risk-exposure"),
    TBoxRelationDef("HAS_EXIT_CAPACITY", "risk-exposure", "reasoning-insight", "risk-exposure"),
    TBoxRelationDef("HAS_EXECUTION_CAPACITY", "risk-exposure", "reasoning-insight", "risk-exposure"),
    TBoxRelationDef("HAS_SLIPPAGE_RISK", "risk-exposure", "reasoning-insight", "risk-exposure"),
    TBoxRelationDef("STRENGTHENS_ACTION_IF", "reasoning-insight", "reasoning-insight", "reasoning-insight"),
    TBoxRelationDef("WEAKENS_ACTION_IF", "reasoning-insight", "reasoning-insight", "reasoning-insight"),
    TBoxRelationDef("REQUIRES_NEXT_CHECK", "reasoning-insight", "reasoning-insight", "reasoning-insight"),
    TBoxRelationDef("VALIDATES_OPINION", "reasoning-insight", "reasoning-insight", "reasoning-insight"),
    TBoxRelationDef("VALIDATES_DATA", "reasoning-insight", "reasoning-insight", "observation-data"),
    TBoxRelationDef("HAS_SOURCE_DATA_STATE", "observation-data", "observation-data", "observation-data", "데이터 출처를 충분·일부·부족·사용 불가 상태와 연결합니다."),
    TBoxRelationDef("HAS_DECISION_AUDIT", "reasoning-insight", "reasoning-insight", "reasoning-insight"),
    TBoxRelationDef("PRODUCES_AI_DECISION", "reasoning-insight", "reasoning-insight", "reasoning-insight"),
    TBoxRelationDef("PRODUCES_VALIDATED_MESSAGE", "operations-dispatch", "reasoning-insight", "operations-dispatch"),
    TBoxRelationDef("HAS_REASONING_CARD", "reasoning-insight", "investment-core", "reasoning-insight"),
    TBoxRelationDef("HAS_VALIDATION_STATE", "reasoning-insight", "reasoning-insight", "reasoning-insight"),
    TBoxRelationDef("CHANGES_FACT", "observation-data", "observation-data", "observation-data"),
    TBoxRelationDef("TRIGGERS_MATERIALITY_ASSESSMENT", "reasoning-insight", "observation-data", "reasoning-insight"),
    TBoxRelationDef("HAS_THRESHOLD_CROSSING", "reasoning-insight", "reasoning-insight", "reasoning-insight"),
    TBoxRelationDef("HAS_EXPOSURE_ASSESSMENT", "reasoning-insight", "reasoning-insight", "reasoning-insight"),
    TBoxRelationDef("HAS_VALIDATION_ASSESSMENT", "reasoning-insight", "reasoning-insight", "reasoning-insight"),
    TBoxRelationDef("HAS_ACTIONABILITY_ASSESSMENT", "reasoning-insight", "reasoning-insight", "reasoning-insight"),
    TBoxRelationDef("BLOCKS_VALIDATION_OF", "reasoning-insight", "risk-exposure", "reasoning-insight", "자료 부족이나 출처 문제가 검증 완료를 막고 조건부 사용 또는 판단 보류로 연결됩니다."),
    TBoxRelationDef("AMPLIFIES_RISK", "risk-exposure", "reasoning-insight", "risk-exposure"),
    TBoxRelationDef("MITIGATES_RISK", "risk-exposure", "reasoning-insight", "risk-exposure"),
    TBoxRelationDef("HAS_PIPELINE", "operations-dispatch", "investment-core", "operations-dispatch"),
    TBoxRelationDef("COLLECTS_DATA_FROM", "operations-dispatch", "operations-dispatch", "observation-data"),
    TBoxRelationDef("RUNS_ON_SCHEDULE", "operations-dispatch", "operations-dispatch", "operations-dispatch"),
    TBoxRelationDef("RUNS_AFTER_EVENT", "operations-dispatch", "operations-dispatch", "operations-dispatch"),
    TBoxRelationDef("USES_COLLECTION_POLICY", "operations-dispatch", "operations-dispatch", "operations-dispatch"),
    TBoxRelationDef("HAS_DATA_FRESHNESS", "operations-dispatch", "operations-dispatch", "observation-data"),
    TBoxRelationDef("HAS_PIPELINE_HEALTH", "operations-dispatch", "operations-dispatch", "operations-dispatch"),
    TBoxRelationDef("UPDATES_GRAPH", "operations-dispatch", "operations-dispatch", "investment-core"),
    TBoxRelationDef("TRIGGERS_REASONING", "operations-dispatch", "operations-dispatch", "operations-dispatch"),
    TBoxRelationDef("HAS_REASONING_CYCLE", "operations-dispatch", "investment-core", "operations-dispatch"),
    TBoxRelationDef("SCHEDULES_ANALYSIS", "operations-dispatch", "operations-dispatch", "operations-dispatch"),
    TBoxRelationDef("PRODUCES_INSIGHT", "operations-dispatch", "operations-dispatch", "reasoning-insight"),
    TBoxRelationDef("HAS_INSIGHT_TYPE", "reasoning-insight", "reasoning-insight", "reasoning-insight"),
    TBoxRelationDef("CREATED_FROM_RELATION", "reasoning-insight", "investment-core", "reasoning-insight"),
    TBoxRelationDef("EVALUATED_BY", "reasoning-insight", "reasoning-insight", "reasoning-insight"),
    TBoxRelationDef("USES_INSIGHT_POLICY", "operations-dispatch", "operations-dispatch", "reasoning-insight"),
    TBoxRelationDef("USES_IMPORTANCE_GATE", "operations-dispatch", "operations-dispatch", "operations-dispatch"),
    TBoxRelationDef("HAS_NOTIFICATION_POLICY", "operations-dispatch", "investment-core", "operations-dispatch"),
    TBoxRelationDef("HAS_NOTIFICATION_DISPATCH", "operations-dispatch", "investment-core", "operations-dispatch"),
    TBoxRelationDef("PASSES_IMPORTANCE_GATE", "operations-dispatch", "reasoning-insight", "operations-dispatch"),
    TBoxRelationDef("BLOCKED_BY_IMPORTANCE_GATE", "operations-dispatch", "reasoning-insight", "operations-dispatch"),
    TBoxRelationDef("CREATES_NOTIFICATION_INTENT", "operations-dispatch", "reasoning-insight", "operations-dispatch"),
    TBoxRelationDef("CREATES_ALERT_CANDIDATE", "operations-dispatch", "reasoning-insight", "operations-dispatch"),
    TBoxRelationDef("DISPATCHED_BY", "operations-dispatch", "reasoning-insight", "operations-dispatch"),
    TBoxRelationDef("SUPPRESSED_BY_POLICY", "operations-dispatch", "operations-dispatch", "operations-dispatch"),
    TBoxRelationDef("HAS_COOLDOWN_POLICY", "operations-dispatch", "operations-dispatch", "operations-dispatch"),
    TBoxRelationDef("HAS_NOVELTY_POLICY", "operations-dispatch", "operations-dispatch", "operations-dispatch"),
    TBoxRelationDef("OBSERVES_MARKET_SESSION", "operations-dispatch", "investment-core", "operations-dispatch"),
    TBoxRelationDef("TRIGGERS_ALERT", "operations-dispatch", "reasoning-insight", "operations-dispatch"),
    TBoxRelationDef("GOVERNS_TERM", "operations-dispatch", "operations-dispatch", "operations-dispatch", "보편언어 사전 버전이 승인 상태와 함께 용어를 관리합니다."),
    TBoxRelationDef("HAS_TERM_RENDERING", "operations-dispatch", "operations-dispatch", "operations-dispatch", "투자 도메인 용어를 사용자 수준별 표현과 연결합니다."),
    TBoxRelationDef("HAS_TERM_ALIAS", "operations-dispatch", "operations-dispatch", "operations-dispatch", "투자 도메인 용어를 같은 뜻의 과거 표현과 연결합니다."),
    TBoxRelationDef("FORBIDS_EXPRESSION", "operations-dispatch", "operations-dispatch", "operations-dispatch", "사용자 화면에 노출하면 안 되는 표현을 승인된 용어에 연결합니다."),
    TBoxRelationDef("PROPOSES_TERM_CHANGE", "operations-dispatch", "operations-dispatch", "operations-dispatch", "검사나 AI가 만든 변경 제안을 용어와 연결하며 자동 적용을 금지합니다."),
]


RULE_DEFS: List[TBoxRuleDef] = [
    TBoxRuleDef("portfolio exposure, position weight, and sector concentration create risk beliefs", "risk-exposure"),
    TBoxRuleDef("price, trend, volume, and smart-money flow observations derive investable signals", "observation-data"),
    TBoxRuleDef("signals support, weaken, or invalidate an investment thesis before AI forms an opinion", "strategy-thesis"),
    TBoxRuleDef("raw facts and semantic states replace aggregate investment scores", "strategy-thesis"),
    TBoxRuleDef("risk, support, counter, and context evidence create an explicit conflict state", "reasoning-insight"),
    TBoxRuleDef("data quality, freshness, provenance, and missing data determine AI validation state", "observation-data"),
    TBoxRuleDef("watchlist candidates create observation assertions and entry checks, not sell decisions", "investment-core"),
    TBoxRuleDef("all runtime concepts become ABox nodes before AI receives an opinion packet", "operations-dispatch"),
    TBoxRuleDef("relations with evidenceRole, reviewLevel, dataState, and polarity define decision evidence state", "reasoning-insight"),
    TBoxRuleDef("execution plans are ABox nodes derived from facts, active relation rules, counter signals, and missing data before notification rendering", "reasoning-insight"),
    TBoxRuleDef("AI validation validates an active investment opinion and execution plan before notification dispatch", "reasoning-insight"),
    TBoxRuleDef("data collection, analysis, reasoning, and notification dispatch are first-class ontology concepts", "operations-dispatch"),
    TBoxRuleDef("notification dispatch is driven by meaningful ontology insights, not by alert-type polling alone", "operations-dispatch"),
    TBoxRuleDef("fact changes must pass a materiality assessment before they trigger ontology reasoning or notification intent", "reasoning-insight"),
    TBoxRuleDef("materiality combines factual threshold crossings, new evidence, exposure, data state, and actionability before dispatch", "reasoning-insight"),
    TBoxRuleDef("collection schedules describe data freshness targets while cooldown, novelty, and suppression policies control delivery noise", "operations-dispatch"),
    TBoxRuleDef("price-bar sequence, key levels, and relation-state transitions distinguish confirmation, failure, and acceleration", "observation-data"),
    TBoxRuleDef("price path transitions such as falling-to-rebound, sideways breakout, sideways breakdown, and rising-to-distribution can change thesis validation state", "reasoning-insight"),
    TBoxRuleDef("individual news, disclosure, macro, earnings, and analyst events are ABox evidence objects that can support, weaken, or invalidate a thesis", "observation-data"),
    TBoxRuleDef("news relevance state separates direct instrument evidence from peer, sector, market, and unrelated context before rules use it", "observation-data"),
    TBoxRuleDef("factor exposure, benchmark beta, and correlation clusters transmit market-regime risk across positions", "risk-exposure"),
    TBoxRuleDef("liquidity profile, exit capacity, and slippage risk constrain execution plans before alert dispatch", "risk-exposure"),
    TBoxRuleDef("source trust and observation data state qualify evidence before AI receives the graph", "observation-data"),
    TBoxRuleDef("coverage gaps are ABox data-quality facts that block ready validation before an AI opinion can be used", "observation-data"),
    TBoxRuleDef("crypto assets must carry price, price path, liquidity, data quality, and exposure relations before they can alter a stock thesis", "risk-exposure"),
    TBoxRuleDef("macro regimes combine rates, yield curve, FX, and rate-sensitive position context before deriving risk or support", "risk-exposure"),
    TBoxRuleDef("news body availability and subject confirmation are data-quality facts that can make validation conditional independently from headline polarity", "observation-data"),
    TBoxRuleDef("fundamental and valuation evidence affects validation state only after provenance and coverage gates are visible in ABox", "strategy-thesis"),
    TBoxRuleDef("RuleBox stores executable graph inference rules as first-class ontology nodes linked to their conditions and derived relation templates", "reasoning-insight"),
    TBoxRuleDef("InferenceBox stores derived assertions, inference traces, matched conditions, and source relation ids so new ABox facts can immediately affect opinions", "reasoning-insight"),
    TBoxRuleDef("The active graph store projection preserves TBox, RuleBox, ABox, and InferenceBox as queryable ontology layers instead of flattening rule output into text", "operations-dispatch"),
    TBoxRuleDef("TypeDB executes RuleBox conditions and materializes InferenceBox facts, traces, evidence, beliefs, and derived relations after graph persistence", "reasoning-insight"),
    TBoxRuleDef("companies issue securities, securities represent tradable instruments, and peer groups transmit sector and competitive context before AI forms an opinion", "investment-core"),
    TBoxRuleDef("market-data changes become FactChange and MaterialityAssessment ABox nodes before any alert candidate is created", "observation-data"),
    TBoxRuleDef("trend transitions remain ABox facts in the active graph store even when local Python opinions are disabled for production projection", "reasoning-insight"),
    TBoxRuleDef("temporal windows group repeated market, flow, event, and cross-market observations before RuleBox derives risk or support episodes", "reasoning-insight"),
    TBoxRuleDef("AI receives a compact evidence subgraph built from InferenceBox relations, traces, current facts, missing data, and source freshness instead of an undifferentiated raw dump", "reasoning-insight"),
    TBoxRuleDef("RuleBox graph conditions can filter ABox fact values such as trade strength, volume ratio, orderbook imbalance, materiality state, event type, and relation scope before deriving opinions", "reasoning-insight"),
    TBoxRuleDef("material direct news, disclosures, trade-flow pressure, trend transitions, and fact-change gates can each independently create InferenceBox relations that alter AI investment opinions", "reasoning-insight"),
    TBoxRuleDef("RuleBox relation templates own decisionStage and reviewLevel so graph-store policy, not rule-id code maps, controls AI decision routing", "reasoning-insight"),
    TBoxRuleDef("RuleBox relation templates and InferenceBox assertions carry targetRole, actionPolicy, allowedActions, and blockedActions so watchlist candidates stay entry-only before AI validation", "reasoning-insight"),
    TBoxRuleDef("loss-position smart-money inflow first weakens sell pressure, and only investor-profile-gated recovery confirmation can open conditional add-buy review", "reasoning-insight"),
    TBoxRuleDef("foreign, institutional, and retail investor flow psychology derives accumulation, absorption, or retail-dip-buying risk before add-buy and trim opinions are formed", "reasoning-insight"),
    TBoxRuleDef("instrument profiles classify each security into archetypes, sensitivities, position intent, and action policies before RuleBox decides add, hold, trim, or sell", "strategy-thesis"),
    TBoxRuleDef("market proxy instruments observe risk appetite, IPO cycle, rates, credit, volatility, currency, commodities, crypto liquidity, and sector cycles before position opinions are formed", "strategy-thesis"),
    TBoxRuleDef("cross-listed ADRs, local shares, and single-stock leveraged ETFs are separate SecurityLine ABox nodes whose premiums, conversion windows, and daily-reset flows can change AI opinions", "risk-exposure"),
    TBoxRuleDef("RuleBox changes must produce governance versions and reviewable rule-change candidates before candidate rules affect InferenceBox decisions", "reasoning-insight"),
    TBoxRuleDef("active TypeDB native rules are approved hypothesis templates, and each matched inference trace instantiates a situation-specific competing hypothesis", "reasoning-insight"),
    TBoxRuleDef("research tasks retrieve only decision-relevant evidence through approved source policies, then verified claims enter ABox before TypeDB re-runs inference", "reasoning-insight"),
    TBoxRuleDef("unverified or disputed claims can trigger further research but cannot independently strengthen a buy, trim, or sell opinion", "reasoning-insight"),
    TBoxRuleDef("novel hypotheses remain review-required proposals until evidence replay and governance approval promote them into active TypeDB rules", "reasoning-insight"),
    TBoxRuleDef("user-facing investment terms keep stable internal identifiers while approved level-specific renderings are managed as TypeDB language-governance concepts", "operations-dispatch"),
    TBoxRuleDef("forbidden or unregistered expressions create review-required language proposals and never mutate approved terminology automatically", "operations-dispatch"),
]


TBOX_CLASSES = [item.name for item in CLASS_DEFS]
TBOX_RELATION_TYPES = [item.name for item in RELATION_DEFS]
TBOX_REASONING_RULES = [item.text for item in RULE_DEFS]

_CLASS_BY_NAME: Dict[str, TBoxClassDef] = {item.name: item for item in CLASS_DEFS}
_RELATION_BY_NAME: Dict[str, TBoxRelationDef] = {item.name: item for item in RELATION_DEFS}

_ABSTRACT_CLASS_NAMES = {
    "Instrument",
    "Security",
    "Equity",
    "Observation",
    "ExternalObservation",
    "ExternalSignal",
    "Risk",
    "Signal",
    "Evidence",
    "Belief",
    "Opinion",
    "ReasoningRule",
    "RuleRegistry",
    "RuleCondition",
    "RelationTemplate",
}

_SOURCE_BACKED_CLASS_NAMES = {
    "Portfolio",
    "Account",
    "Company",
    "Stock",
    "ETF",
    "MarketProxyInstrument",
    "MarketProxyETF",
    "MarketProxyIndex",
    "SecurityLine",
    "LocalOrdinaryShare",
    "DepositaryReceipt",
    "ADR",
    "LeveragedETF",
    "InverseETF",
    "SingleStockETF",
    "DailyResetLeverage",
    "CryptoAsset",
    "CashAsset",
    "Derivative",
    "Index",
    "FXPair",
    "Position",
    "Watchlist",
    "WatchlistCandidate",
    "Sector",
    "Industry",
    "PeerGroup",
    "Market",
    "Currency",
    "Cash",
    "MarketExposure",
    "FactChange",
    "TemporalWindow",
    "IntradayWindow",
    "DailyWindow",
    "MultiDayWindow",
    "TemporalMateriality",
    "TemporalCoverageGap",
    "PriceObservation",
    "VolumeObservation",
    "TechnicalObservation",
    "FlowObservation",
    "FundamentalObservation",
    "PriceMetric",
    "MarketProxyObservation",
    "PricePathPattern",
    "CrossMarketPremium",
    "ADRPremium",
    "TechnicalIndicator",
    "TradeFlow",
    "FlowPattern",
    "RebalancingFlow",
    "DataQuality",
    "DataSource",
    "DataFreshness",
    "DataLatency",
    "MissingData",
    "CoverageGap",
    "Provenance",
    "SourceReliability",
    "ObservationDataState",
    "TimeWindow",
    "ObservationTime",
    "SignalHorizon",
    "HoldingPeriod",
    "ValidityInterval",
    "Staleness",
    "ValidationRule",
    "PriceBar",
    "PricePath",
    "VolumeProfile",
    "KeyLevel",
    "SupportLevel",
    "ResistanceLevel",
    "Breakout",
    "FailedBreakout",
    "Retest",
    "ResearchEvidence",
    "MarketStructureSignal",
    "NewsEvent",
    "NewsArticle",
    "ArticleAIAnalysis",
    "NewsTopic",
    "NewsEventType",
    "EventCluster",
    "EventDrivenRiskCluster",
    "SupportiveEventCluster",
    "MixedEventCluster",
    "QuietPeriod",
    "PeerCompanyMention",
    "DisclosureEvent",
    "DisclosureFiling",
    "MacroIndicator",
    "MacroPrint",
    "MacroRegime",
    "RateSignal",
    "InterestRate",
    "YieldCurve",
    "FXRateSignal",
    "CreditSpreadSignal",
    "CryptoMarketSignal",
    "EarningsEvent",
    "EarningsCalendarEvent",
    "AnalystRevision",
    "CorporateAction",
    "RegulatoryEvent",
    "ProductLine",
    "SupplyChainExposure",
    "CustomerExposure",
    "RevenueExposure",
    "Factor",
    "FactorExposure",
    "MarketProxyTheme",
    "FactorSensitivity",
    "BenchmarkIndex",
    "HedgeCandidate",
    "Strategy",
    "InstrumentProfile",
    "InvestmentArchetype",
    "CrossListedSecurity",
    "DailyLeveragedProduct",
    "InverseProduct",
    "BroadMarketProxy",
    "CommodityProxy",
    "CreditStressProxy",
    "CryptoLiquidityProxy",
    "CurrencyProxy",
    "DurationProxy",
    "ForeignMarketProxy",
    "GrowthMarketProxy",
    "IPOCycleProxy",
    "KoreaMarketProxy",
    "RateSensitivityProxy",
    "RiskAppetiteProxy",
    "RiskOffProxy",
    "SectorCycleProxy",
    "SmallCapRiskProxy",
    "VolatilityProxy",
    "GrowthStock",
    "AIGrowth",
    "HighVolatilityGrowth",
    "MegaCapQuality",
    "PlatformGrowth",
    "DividendIncome",
    "PreferredIncome",
    "BitcoinProxy",
    "BitcoinSensitiveIncome",
    "CryptoAssetProfile",
    "SemiconductorCyclical",
    "SemiconductorHBM",
    "CyclicalGrowth",
    "EquityGeneral",
    "PositionIntent",
    "InvestmentThesis",
    "EntryCondition",
    "ExitCondition",
    "RiskManagementRule",
    "RebalancingRule",
    "PositionSizingRule",
    "Scenario",
    "StrategyExperiment",
    "StrategySignal",
    "Threshold",
    "RuntimeSetting",
    "AlertRule",
    "PromptTemplate",
    "ValuationAssumption",
    "AIValuationProposal",
    "ValuationModel",
    "ActiveValuation",
    "UserValuationReview",
    "ValuationEvidence",
    "ValuationMetric",
    "FairValueEstimate",
    "MarginOfSafety",
    "RelativeValuation",
    "HistoricalValuationBand",
    "PeerMultiple",
    "EarningsYield",
    "DCFValuation",
    "MarketRisk",
    "MarketStructureRisk",
    "ArbitrageFriction",
    "FlowAmplificationRisk",
    "LiquidityRisk",
    "LiquidityProfile",
    "ExitCapacity",
    "ExecutionMetric",
    "ExecutionCapacity",
    "PositionExitExposure",
    "SlippageEstimate",
    "ConcentrationRisk",
    "CurrencyRisk",
    "VolatilityRisk",
    "CryptoExposure",
    "EventRisk",
    "DataQualityRisk",
    "ArticleQualityRisk",
    "ModelRisk",
    "ValuationRisk",
    "ExecutionRisk",
    "CorrelationRisk",
    "RegimeRisk",
}

_INFERRED_CLASS_NAMES = {
    "PriceSignal",
    "TrendSignal",
    "FlowSignal",
    "ValuationSignal",
    "MacroSignal",
    "DisclosureSignal",
    "CryptoSignal",
    "DataQualitySignal",
    "RelationStateSnapshot",
    "SignalTransition",
    "TrendPhase",
    "TrendTransition",
    "TrendEpisode",
    "DecisionEpisode",
    "TemporalObservation",
    "PersistentDecline",
    "DeclineDeceleration",
    "RecoveryAttempt",
    "FailedRecovery",
    "AccumulationDuringWeakness",
    "DistributionDuringBounce",
    "CrossMarketDivergence",
    "LeverageFlowAmplification",
    "ReversalSignal",
    "ConsolidationBreak",
    "AccelerationSignal",
    "DecelerationSignal",
    "MaterialityAssessment",
    "WhyNow",
    "ThresholdCrossing",
    "ExposureAssessment",
    "ValidationAssessment",
    "ActionabilityAssessment",
    "PreviousInsight",
    "InvestmentOpinion",
    "ActiveInvestmentOpinion",
    "ExecutionPlan",
    "DecisionDriver",
    "DecisionStage",
    "PeerContext",
    "ActionCandidate",
    "BlockedAction",
    "InvalidationCondition",
    "NextCheck",
    "AIValidation",
    "ValidatedOpinion",
    "AIJudgmentAudit",
    "AIContextPacket",
    "EvidenceSubgraph",
    "GraphNeighborhood",
    "Opportunity",
    "UndervaluationOpportunity",
    "Contradiction",
    "SignalConflict",
    "Insight",
    "InsightType",
    "InsightPolicy",
    "MessageDeliveryProfile",
    "DerivedAssertion",
    "InferenceTrace",
    "InferencePath",
    "InferenceTimeline",
    "InferenceGeneration",
    "CandidateGeneration",
    "ActiveGeneration",
    "DecisionPerformance",
    "RulePerformance",
    "HypothesisPerformance",
    "GraphReasoner",
    "GraphStoreNativeReasoner",
    "TypeDBNativeReasoner",
    "ReasoningCard",
    "AIValidationState",
    "SourceTrustState",
    "AIReview",
}

_RULEBOX_CLASS_NAMES = {
    "RelationRuleRegistry",
    "GraphInferenceRule",
    "RelationReasoningRule",
    "RelationRuleCondition",
    "RelationRuleTemplate",
    "RuleDecisionPolicy",
    "RulePriorityPolicy",
}

_GOVERNANCE_CLASS_NAMES = {
    "RuleBoxGovernance",
    "RuleBoxVersion",
    "RuleChangeCandidate",
}

_LANGUAGE_GOVERNANCE_CLASS_NAMES = {
    "LanguageRegistryVersion",
    "DomainTerm",
    "TermRendering",
    "TermAlias",
    "ForbiddenExpression",
    "LanguageChangeProposal",
}

_OPERATIONAL_CLASS_NAMES = {
    "DataPipeline",
    "DataPipelineHealth",
    "CollectionSchedule",
    "CollectionPolicy",
    "MarketSnapshot",
    "WatchlistSnapshot",
    "ExternalSignalCollection",
    "AnalysisJob",
    "ReasoningCycle",
    "NotificationPolicy",
    "NotificationDispatch",
    "NotificationIntent",
    "AlertCandidate",
    "ImportanceGate",
    "CooldownPolicy",
    "NoveltyPolicy",
    "SuppressionPolicy",
    "MarketSession",
    "OperationalEvent",
}

_SCHEMA_RELATION_NAMES = {
    "DEFINES_BOUNDED_CONTEXT",
    "DEFINES_CLASS",
    "DEFINES_RELATION",
    "CONSTRAINS_ASSERTIONS",
    "CONSTRAINS_RULES",
    "DERIVES_ASSERTIONS",
    "IS_A",
}

_RULEBOX_RELATION_NAMES = {
    "HAS_RULE_CONDITION",
    "USES_RULE_TEMPLATE",
    "MATCHES_CONDITION",
    "PRODUCES_DERIVED_ASSERTION",
    "DERIVES_RELATION",
    "GOVERNED_BY",
    "PROPOSES_RULE_CHANGE",
    "SUPERSEDES_RULE_VERSION",
}

_LANGUAGE_GOVERNANCE_RELATION_NAMES = {
    "GOVERNS_TERM",
    "HAS_TERM_RENDERING",
    "HAS_TERM_ALIAS",
    "FORBIDS_EXPRESSION",
    "PROPOSES_TERM_CHANGE",
}


def tbox_class_def(name: str) -> Optional[TBoxClassDef]:
    return _CLASS_BY_NAME.get(str(name or ""))


def tbox_relation_def(name: str) -> Optional[TBoxRelationDef]:
    return _RELATION_BY_NAME.get(str(name or "").upper())


def tbox_class_materialization_policy(name: str) -> str:
    value = str(name or "")
    if value in _LANGUAGE_GOVERNANCE_CLASS_NAMES:
        return "language-governance"
    if value in _GOVERNANCE_CLASS_NAMES:
        return "governance"
    if value in _RULEBOX_CLASS_NAMES:
        return "rulebox"
    if value in _INFERRED_CLASS_NAMES:
        return "inferred"
    if value in _OPERATIONAL_CLASS_NAMES:
        return "operational"
    if value in _SOURCE_BACKED_CLASS_NAMES:
        return "source-backed"
    if value in _ABSTRACT_CLASS_NAMES:
        return "abstract"
    return "source-backed"


def tbox_materialization_box(policy: str) -> str:
    value = str(policy or "")
    if value in {"abstract", "schema"}:
        return "TBox"
    if value == "rulebox":
        return "RuleBox"
    if value == "governance":
        return "RuleBoxGovernance"
    if value == "language-governance":
        return "LanguageGovernance"
    if value == "inferred":
        return "InferenceBox"
    return "ABox"


def tbox_relation_materialization_policy(name: str) -> str:
    value = str(name or "").upper()
    if value in _LANGUAGE_GOVERNANCE_RELATION_NAMES:
        return "language-governance"
    if value in _SCHEMA_RELATION_NAMES:
        return "schema"
    if value in _RULEBOX_RELATION_NAMES:
        return "rulebox"
    definition = tbox_relation_def(value)
    if definition and definition.bounded_context in {"reasoning-insight", "operations-dispatch"}:
        return "inferred-or-operational"
    return "source-backed"


def bounded_contexts_payload() -> List[Dict[str, object]]:
    return [asdict(item) for item in BOUNDED_CONTEXTS]


def class_definitions_payload() -> List[Dict[str, object]]:
    rows: List[Dict[str, object]] = []
    for item in CLASS_DEFS:
        payload = asdict(item)
        policy = tbox_class_materialization_policy(item.name)
        payload["materializationPolicy"] = policy
        payload["materializationBox"] = tbox_materialization_box(policy)
        rows.append(payload)
    return rows


def relation_definitions_payload() -> List[Dict[str, object]]:
    rows: List[Dict[str, object]] = []
    for item in RELATION_DEFS:
        payload = asdict(item)
        policy = tbox_relation_materialization_policy(item.name)
        payload["materializationPolicy"] = policy
        payload["materializationBox"] = tbox_materialization_box(policy)
        rows.append(payload)
    return rows


def rule_definitions_payload() -> List[Dict[str, object]]:
    return [asdict(item) for item in RULE_DEFS]
