from typing import List

from .ontology_rulebox_contracts import GraphInferenceRule, GraphRuleCondition, GraphRuleDerivation


def default_graph_inference_rules() -> List[GraphInferenceRule]:
    return [
        GraphInferenceRule(
            rule_id="graph.loss_guard.breakdown.v1",
            label="손실 보유 + 기준선 이탈 -> 손실 방어 추론",
            version="v1",
            source_kind="stock",
            action_group="lossControl",
            action_level="review",
            prompt_hint="손실률과 기준선 이탈이 동시에 보이면 손절 결론보다 회복 조건, 60일선, 거래량 동반 여부를 분리해 설명합니다.",
            conditions=[
                GraphRuleCondition(
                    "holding-source",
                    "subject_property",
                    "보유 종목입니다.",
                    field="source",
                    operator="==",
                    value="holding",
                ),
                GraphRuleCondition(
                    "holding-loss",
                    "subject_property",
                    "보유 종목 손익률이 -8% 이하입니다.",
                    field="profitLossRate",
                    operator="<=",
                    value=-8,
                ),
                GraphRuleCondition(
                    "ma-break",
                    "relation",
                    "20일선 또는 60일선 기준을 이탈했습니다.",
                    relation_type="BREAKS_LEVEL",
                    target_kind="key-level",
                    target_property_filters={"levelType": ["ma20", "ma60"]},
                    min_weight=0.5,
                ),
            ],
            derivations=[
                GraphRuleDerivation(
                    relation_type="HAS_INFERRED_RISK",
                    target_kind="risk",
                    target_key="{symbol}:loss-guard-breakdown",
                    target_label="{displayName} 손실 방어 리스크",
                    tbox_class="MarketRisk",
                    tbox_classes=["Risk", "MarketRisk", "ThresholdCrossing"],
                    polarity="risk",
                    risk_impact=13.0,
                    weight=0.86,
                    belief_label="손실 구간에서 기준선 이탈이 겹쳐 손실 방어 판단이 필요합니다.",
                    ai_influence_label="손실 방어 추론",
                ),
                GraphRuleDerivation(
                    relation_type="REQUIRES_NEXT_CHECK",
                    target_kind="next-check",
                    target_key="{symbol}:loss-guard-recheck",
                    target_label="{displayName} 회복 조건 재확인",
                    tbox_class="NextCheck",
                    tbox_classes=["NextCheck", "ActionabilityAssessment"],
                    polarity="context",
                    weight=0.78,
                    belief_label="다음 갱신에서 60일선과 거래량 확인이 필요합니다.",
                    ai_influence_label="회복 조건 재확인",
                    action_group="lossControl",
                    action_level="watch",
                ),
            ],
        ),
        GraphInferenceRule(
            rule_id="graph.profit_protect.trend_break.v1",
            label="수익 보유 + 추세 이탈 -> 수익 보호 추론",
            version="v1",
            source_kind="stock",
            action_group="profitTake",
            action_level="review",
            prompt_hint="수익 상태에서 단기 추세가 무너지면 보유 유지 조건과 분할 익절 조건을 함께 검토합니다.",
            conditions=[
                GraphRuleCondition(
                    "holding-source",
                    "subject_property",
                    "보유 종목입니다.",
                    field="source",
                    operator="==",
                    value="holding",
                ),
                GraphRuleCondition(
                    "holding-profit",
                    "subject_property",
                    "보유 종목 손익률이 +12% 이상입니다.",
                    field="profitLossRate",
                    operator=">=",
                    value=12,
                ),
                GraphRuleCondition(
                    "ma20-break",
                    "relation",
                    "20일선 기준을 이탈했습니다.",
                    relation_type="BREAKS_LEVEL",
                    target_kind="key-level",
                    target_property_filters={"levelType": "ma20"},
                    min_weight=0.5,
                ),
            ],
            derivations=[
                GraphRuleDerivation(
                    relation_type="HAS_ACTION_CANDIDATE",
                    target_kind="action-candidate",
                    target_key="{symbol}:profit-protect",
                    target_label="{displayName} 수익 보호 점검",
                    tbox_class="ActionCandidate",
                    tbox_classes=["ActionCandidate", "ExecutionPlan"],
                    polarity="risk",
                    risk_impact=8.0,
                    weight=0.76,
                    belief_label="수익 구간에서 20일선 이탈이 생겨 수익 보호 기준을 점검합니다.",
                    ai_influence_label="수익 보호 추론",
                    action_group="profitTake",
                    action_level="review",
                )
            ],
        ),
        GraphInferenceRule(
            rule_id="graph.watchlist.pullback.entry.v1",
            label="관심 종목 + 기준선 재시험 -> 진입 관찰 추론",
            version="v1",
            source_kind="stock",
            action_group="entry",
            action_level="watch",
            prompt_hint="관심 종목은 매도 판단이 아니라 진입 조건, 확인 가격대, 반대 신호를 중심으로 설명합니다.",
            conditions=[
                GraphRuleCondition(
                    "watchlist-source",
                    "subject_property",
                    "관심 종목입니다.",
                    field="source",
                    operator="==",
                    value="watchlist",
                ),
                GraphRuleCondition(
                    "level-retest",
                    "relation",
                    "주요 기준선을 재시험 중입니다.",
                    relation_type="RETESTS_LEVEL",
                    target_kind="key-level",
                    min_weight=0.5,
                ),
            ],
            derivations=[
                GraphRuleDerivation(
                    relation_type="HAS_INFERRED_SUPPORT",
                    target_kind="opportunity",
                    target_key="{symbol}:watchlist-entry-retest",
                    target_label="{displayName} 진입 관찰 기회",
                    tbox_class="Opportunity",
                    tbox_classes=["Opportunity", "EntryCondition", "ActionabilityAssessment"],
                    polarity="support",
                    support_impact=7.0,
                    weight=0.72,
                    belief_label="관심 종목이 주요 기준선을 재시험해 진입 관찰 후보가 됩니다.",
                    ai_influence_label="관심 종목 진입 관찰",
                    action_group="entry",
                    action_level="watch",
                )
            ],
        ),
        GraphInferenceRule(
            rule_id="graph.liquidity.execution_guard.v1",
            label="유동성 제약 + 실행 리스크 -> 분할 실행 추론",
            version="v1",
            source_kind="stock",
            action_group="executionRisk",
            action_level="review",
            prompt_hint="유동성·슬리피지 관계가 강하면 투자 의견과 실제 실행 가능성을 분리합니다.",
            conditions=[
                GraphRuleCondition(
                    "liquidity-limited",
                    "relation",
                    "유동성 제한 관계가 의미 있는 강도입니다.",
                    relation_type="LIMITED_BY_LIQUIDITY",
                    target_kind="liquidity-profile",
                    min_weight=0.55,
                )
            ],
            derivations=[
                GraphRuleDerivation(
                    relation_type="HAS_INFERRED_RISK",
                    target_kind="risk",
                    target_key="{symbol}:execution-liquidity",
                    target_label="{displayName} 실행 유동성 리스크",
                    tbox_class="LiquidityRisk",
                    tbox_classes=["Risk", "LiquidityRisk", "ExecutionRisk"],
                    polarity="risk",
                    risk_impact=9.0,
                    weight=0.74,
                    belief_label="유동성 제약이 있어 의견과 실행 계획을 분리해야 합니다.",
                    ai_influence_label="실행 유동성 추론",
                    action_group="executionRisk",
                    action_level="review",
                )
            ],
        ),
        GraphInferenceRule(
            rule_id="graph.materiality.alert_candidate.v1",
            label="중요 시장 데이터 변경 -> 알림 후보 추론",
            version="v1",
            source_kind="stock",
            action_group="alertReview",
            action_level="watch",
            prompt_hint="단순 최신값이 아니라 이전 상태 대비 의미 있는 변경인지, 어떤 필드가 바뀌었는지 먼저 설명합니다.",
            conditions=[
                GraphRuleCondition(
                    "material-fact-change",
                    "relation",
                    "시장 데이터 변경이 중요도 게이트 기준을 넘었습니다.",
                    relation_type="HAS_OBSERVATION",
                    target_kind="fact-change",
                    min_weight=0.65,
                )
            ],
            derivations=[
                GraphRuleDerivation(
                    relation_type="CREATES_NOTIFICATION_INTENT",
                    target_kind="alert-candidate",
                    target_key="{symbol}:material-market-change",
                    target_label="{displayName} 중요 변경 알림 후보",
                    tbox_class="AlertCandidate",
                    tbox_classes=["NotificationIntent", "AlertCandidate", "MaterialityAssessment"],
                    polarity="context",
                    weight=0.74,
                    belief_label="이전 상태 대비 중요한 시장 데이터 변경이 있어 알림 후보로 승격합니다.",
                    ai_influence_label="중요 변경 알림 후보",
                    action_group="alertReview",
                    action_level="watch",
                )
            ],
        ),
        GraphInferenceRule(
            rule_id="graph.holding.trend_transition.risk.v1",
            label="보유 종목 + 위험 추세 전이 -> 리스크 재점검 추론",
            version="v1",
            source_kind="stock",
            action_group="lossControl",
            action_level="review",
            prompt_hint="현재 손익률 하나보다 하락 가속, 횡보 후 하방 이탈, 상승 탄력 둔화 같은 전이 맥락을 우선 설명합니다.",
            conditions=[
                GraphRuleCondition(
                    "holding-source",
                    "subject_property",
                    "보유 종목입니다.",
                    field="source",
                    operator="==",
                    value="holding",
                ),
                GraphRuleCondition(
                    "risk-transition",
                    "relation",
                    "위험 방향의 추세 전이가 감지됐습니다.",
                    relation_type="HAS_TREND_TRANSITION",
                    target_kind="trend-transition",
                    relation_property_filters={"polarity": "risk"},
                    min_weight=0.60,
                ),
            ],
            derivations=[
                GraphRuleDerivation(
                    relation_type="HAS_INFERRED_RISK",
                    target_kind="risk",
                    target_key="{symbol}:trend-transition-risk",
                    target_label="{displayName} 추세 전이 리스크",
                    tbox_class="RegimeRisk",
                    tbox_classes=["Risk", "MarketRisk", "RegimeRisk", "TrendTransition"],
                    polarity="risk",
                    risk_impact=11.0,
                    weight=0.80,
                    belief_label="보유 종목의 가격 경로가 위험 방향으로 전이되어 리스크 재점검이 필요합니다.",
                    ai_influence_label="추세 전이 리스크",
                    action_group="lossControl",
                    action_level="review",
                )
            ],
        ),
        GraphInferenceRule(
            rule_id="graph.watchlist.trend_transition.support.v1",
            label="관심 종목 + 우호 추세 전이 -> 진입 관찰 추론",
            version="v1",
            source_kind="stock",
            action_group="entry",
            action_level="review",
            prompt_hint="관심 종목은 가격 경로가 하락 후 반등하거나 횡보 후 상방 이탈했는지와 거래량 확인 여부를 분리해 설명합니다.",
            conditions=[
                GraphRuleCondition(
                    "watchlist-source",
                    "subject_property",
                    "관심 종목입니다.",
                    field="source",
                    operator="==",
                    value="watchlist",
                ),
                GraphRuleCondition(
                    "support-transition",
                    "relation",
                    "우호 방향의 추세 전이가 감지됐습니다.",
                    relation_type="HAS_TREND_TRANSITION",
                    target_kind="trend-transition",
                    relation_property_filters={"polarity": "support"},
                    min_weight=0.60,
                ),
            ],
            derivations=[
                GraphRuleDerivation(
                    relation_type="HAS_INFERRED_ENTRY_OPPORTUNITY",
                    target_kind="opportunity",
                    target_key="{symbol}:trend-transition-entry",
                    target_label="{displayName} 추세 전이 진입 관찰",
                    tbox_class="Opportunity",
                    tbox_classes=["Opportunity", "EntryCondition", "TrendTransition", "ActionabilityAssessment"],
                    polarity="support",
                    support_impact=10.0,
                    weight=0.78,
                    belief_label="관심 종목의 가격 경로가 우호적으로 전이되어 진입 관찰 후보가 됩니다.",
                    ai_influence_label="추세 전이 진입 관찰",
                    action_group="entry",
                    action_level="review",
                )
            ],
        ),
    ]
