from typing import List

from .ontology_rulebox_contracts import (
    WATCHLIST_ACTION_POLICY,
    WATCHLIST_ALLOWED_ACTIONS,
    WATCHLIST_BLOCKED_ACTIONS,
    WATCHLIST_TARGET_ROLE,
    GraphInferenceRule,
    GraphRuleCondition,
    GraphRuleDerivation,
)


WATCHLIST_ENTRY_POLICY = {
    "target_role": WATCHLIST_TARGET_ROLE,
    "action_policy": WATCHLIST_ACTION_POLICY,
    "allowed_actions": WATCHLIST_ALLOWED_ACTIONS,
    "blocked_actions": WATCHLIST_BLOCKED_ACTIONS,
}


def default_graph_inference_rules() -> List[GraphInferenceRule]:
    return [
        GraphInferenceRule(
            rule_id="graph.loss_guard.breakdown.v1",
            label="손실 보유 + 기준선 이탈 -> 손실 방어 추론",
            version="v1",
            source_kind="stock",
            action_group="lossControl",
            action_level="review",
            prompt_hint="손실률과 기준선 이탈이 동시에 보이면 손절 결론보다 회복 조건, 60일선, 거래량 동반 여부를 분리해 설명합니다.",
            conditions=[
                GraphRuleCondition(
                    "holding-source",
                    "subject_property",
                    "보유 종목입니다.",
                    field="source",
                    operator="==",
                    value="holding",
                ),
                GraphRuleCondition(
                    "holding-loss",
                    "subject_property",
                    "보유 종목 손익률이 -8% 이하입니다.",
                    field="profitLossRate",
                    operator="<=",
                    value=-8,
                ),
                GraphRuleCondition(
                    "ma-break",
                    "relation",
                    "20일선 또는 60일선 기준을 이탈했습니다.",
                    relation_type="BREAKS_LEVEL",
                    target_kind="key-level",
                    target_property_filters={"levelType": ["ma20", "ma60"]},
                    min_weight=0.5,
                ),
            ],
            derivations=[
                GraphRuleDerivation(
                    relation_type="HAS_INFERRED_RISK",
                    target_kind="risk",
                    target_key="{symbol}:loss-guard-breakdown",
                    target_label="{displayName} 손실 방어 리스크",
                    tbox_class="MarketRisk",
                    tbox_classes=["Risk", "MarketRisk", "ThresholdCrossing"],
                    polarity="risk",
                    risk_impact=13.0,
                    weight=0.86,
                    belief_label="손실 구간에서 기준선 이탈이 겹쳐 손실 방어 판단이 필요합니다.",
                    ai_influence_label="손실 방어 추론",
                ),
                GraphRuleDerivation(
                    relation_type="REQUIRES_NEXT_CHECK",
                    target_kind="next-check",
                    target_key="{symbol}:loss-guard-recheck",
                    target_label="{displayName} 회복 조건 재확인",
                    tbox_class="NextCheck",
                    tbox_classes=["NextCheck", "ActionabilityAssessment"],
                    polarity="context",
                    weight=0.78,
                    belief_label="다음 갱신에서 60일선과 거래량 확인이 필요합니다.",
                    ai_influence_label="회복 조건 재확인",
                    action_group="lossControl",
                    action_level="watch",
                ),
            ],
        ),
        GraphInferenceRule(
            rule_id="graph.profit_protect.trend_break.v1",
            label="수익 보유 + 추세 이탈 -> 수익 보호 추론",
            version="v1",
            source_kind="stock",
            action_group="profitTake",
            action_level="review",
            prompt_hint="수익 상태에서 단기 추세가 무너지면 보유 유지 조건과 분할 익절 조건을 함께 검토합니다.",
            conditions=[
                GraphRuleCondition(
                    "holding-source",
                    "subject_property",
                    "보유 종목입니다.",
                    field="source",
                    operator="==",
                    value="holding",
                ),
                GraphRuleCondition(
                    "holding-profit",
                    "subject_property",
                    "보유 종목 손익률이 +12% 이상입니다.",
                    field="profitLossRate",
                    operator=">=",
                    value=12,
                ),
                GraphRuleCondition(
                    "ma20-break",
                    "relation",
                    "20일선 기준을 이탈했습니다.",
                    relation_type="BREAKS_LEVEL",
                    target_kind="key-level",
                    target_property_filters={"levelType": "ma20"},
                    min_weight=0.5,
                ),
            ],
            derivations=[
                GraphRuleDerivation(
                    relation_type="HAS_ACTION_CANDIDATE",
                    target_kind="action-candidate",
                    target_key="{symbol}:profit-protect",
                    target_label="{displayName} 수익 보호 점검",
                    tbox_class="ActionCandidate",
                    tbox_classes=["ActionCandidate", "ExecutionPlan"],
                    polarity="risk",
                    risk_impact=8.0,
                    weight=0.76,
                    belief_label="수익 구간에서 20일선 이탈이 생겨 수익 보호 기준을 점검합니다.",
                    ai_influence_label="수익 보호 추론",
                    action_group="profitTake",
                    action_level="review",
                )
            ],
        ),
        GraphInferenceRule(
            rule_id="graph.watchlist.pullback.entry.v1",
            label="관심 종목 + 기준선 재시험 -> 진입 관찰 추론",
            version="v1",
            source_kind="stock",
            action_group="entry",
            action_level="watch",
            prompt_hint="관심 종목은 매도 판단이 아니라 진입 조건, 확인 가격대, 반대 신호를 중심으로 설명합니다.",
            conditions=[
                GraphRuleCondition(
                    "watchlist-source",
                    "subject_property",
                    "관심 종목입니다.",
                    field="source",
                    operator="==",
                    value="watchlist",
                ),
                GraphRuleCondition(
                    "level-retest",
                    "relation",
                    "주요 기준선을 재시험 중입니다.",
                    relation_type="RETESTS_LEVEL",
                    target_kind="key-level",
                    min_weight=0.5,
                ),
            ],
            derivations=[
                GraphRuleDerivation(
                    relation_type="HAS_INFERRED_SUPPORT",
                    target_kind="opportunity",
                    target_key="{symbol}:watchlist-entry-retest",
                    target_label="{displayName} 진입 관찰 기회",
                    tbox_class="Opportunity",
                    tbox_classes=["Opportunity", "EntryCondition", "ActionabilityAssessment"],
                    polarity="support",
                    support_impact=7.0,
                    weight=0.72,
                    belief_label="관심 종목이 주요 기준선을 재시험해 진입 관찰 후보가 됩니다.",
                    ai_influence_label="관심 종목 진입 관찰",
                    action_group="entry",
                    action_level="watch",
                    **WATCHLIST_ENTRY_POLICY,
                )
            ],
        ),
        GraphInferenceRule(
            rule_id="graph.liquidity.execution_guard.v1",
            label="유동성 제약 + 실행 리스크 -> 분할 실행 추론",
            version="v1",
            source_kind="stock",
            action_group="executionRisk",
            action_level="review",
            prompt_hint="유동성·슬리피지 관계가 강하면 투자 의견과 실제 실행 가능성을 분리합니다.",
            conditions=[
                GraphRuleCondition(
                    "liquidity-limited",
                    "relation",
                    "유동성 제한 관계가 의미 있는 강도입니다.",
                    relation_type="LIMITED_BY_LIQUIDITY",
                    target_kind="liquidity-profile",
                    min_weight=0.55,
                )
            ],
            derivations=[
                GraphRuleDerivation(
                    relation_type="HAS_INFERRED_RISK",
                    target_kind="risk",
                    target_key="{symbol}:execution-liquidity",
                    target_label="{displayName} 실행 유동성 리스크",
                    tbox_class="LiquidityRisk",
                    tbox_classes=["Risk", "LiquidityRisk", "ExecutionRisk"],
                    polarity="risk",
                    risk_impact=9.0,
                    weight=0.74,
                    belief_label="유동성 제약이 있어 의견과 실행 계획을 분리해야 합니다.",
                    ai_influence_label="실행 유동성 추론",
                    action_group="executionRisk",
                    action_level="review",
                )
            ],
        ),
        GraphInferenceRule(
            rule_id="graph.data_quality.microstructure_gap.v1",
            label="체결·호가·투자자 수급 결측 -> 데이터 품질 리스크 추론",
            version="v1",
            source_kind="stock",
            action_group="alertReview",
            action_level="watch",
            prompt_hint="체결강도, 호가, 투자자별 수급 같은 미시구조 데이터가 빠지면 방향 판단보다 결론 확신도와 다음 수집 과제를 먼저 설명합니다.",
            conditions=[
                GraphRuleCondition(
                    "microstructure-missing",
                    "relation",
                    "체결·호가·투자자별 수급 결측이 판단 확신도를 낮춥니다.",
                    relation_type="HAS_DATA_QUALITY",
                    target_kind="missing-data",
                    target_property_filters={"dataScope": "market-microstructure"},
                    relation_property_filters={"minRiskImpact": 2.4},
                    min_weight=0.1,
                )
            ],
            derivations=[
                GraphRuleDerivation(
                    relation_type="HAS_INFERRED_RISK",
                    target_kind="risk",
                    target_key="{symbol}:microstructure-data-gap",
                    target_label="{displayName} 미시구조 데이터 결측 리스크",
                    tbox_class="DataQualityRisk",
                    tbox_classes=["Risk", "DataQualityRisk", "MissingData", "DataQualitySignal"],
                    polarity="risk",
                    risk_impact=7.0,
                    weight=0.68,
                    belief_label="체결·호가·투자자별 수급 일부가 없어 투자 의견 확신도를 제한합니다.",
                    ai_influence_label="미시구조 데이터 결측 추론",
                    action_group="alertReview",
                    action_level="watch",
                ),
                GraphRuleDerivation(
                    relation_type="LOWERS_CONFIDENCE_OF",
                    target_kind="confidence-assessment",
                    target_key="{symbol}:microstructure-confidence-limit",
                    target_label="{displayName} 미시구조 결측 신뢰도 제한",
                    tbox_class="ConfidenceAssessment",
                    tbox_classes=["ConfidenceAssessment", "DataQualityRisk", "MissingData"],
                    polarity="risk",
                    risk_impact=5.5,
                    weight=0.64,
                    belief_label="체결·호가·투자자 수급 결측 때문에 매수·매도 판단 신뢰도를 낮춥니다.",
                    ai_influence_label="데이터 결측 신뢰도 제한",
                    action_group="dataQuality",
                    action_level="review",
                    decision_stage="DATA_CONFLICT",
                    stage_priority=34,
                )
            ],
        ),
        GraphInferenceRule(
            rule_id="graph.flow.sell_pressure.v1",
            label="보유 종목 + 매도 호가 압력 + 거래량 증가 -> 수급 리스크 추론",
            version="v1",
            source_kind="stock",
            action_group="executionRisk",
            action_level="review",
            prompt_hint="이동평균보다 체결강도, 호가 불균형, 거래량 배율이 실제 매도 압력인지 먼저 설명하고 실행 리스크와 분할 대응 기준을 분리합니다.",
            conditions=[
                GraphRuleCondition(
                    "holding-source",
                    "subject_property",
                    "보유 종목입니다.",
                    field="source",
                    operator="==",
                    value="holding",
                ),
                GraphRuleCondition(
                    "ask-pressure",
                    "relation",
                    "매도 호가 잔량 우위가 의미 있는 수준입니다.",
                    relation_type="HAS_TRADE_FLOW",
                    target_kind="flow-metric",
                    target_property_filters={"field": "bidAskImbalance", "maxValue": -15},
                    min_weight=0.5,
                ),
                GraphRuleCondition(
                    "volume-confirmation",
                    "relation",
                    "거래량 배율이 단기 수급 변화를 확인합니다.",
                    relation_type="HAS_TRADE_FLOW",
                    target_kind="flow-metric",
                    target_property_filters={"field": "volumeRatio", "minValue": 1.2},
                    min_weight=0.5,
                ),
            ],
            derivations=[
                GraphRuleDerivation(
                    relation_type="HAS_INFERRED_RISK",
                    target_kind="risk",
                    target_key="{symbol}:flow-sell-pressure",
                    target_label="{displayName} 매도 수급 압력",
                    tbox_class="LiquidityRisk",
                    tbox_classes=["Risk", "LiquidityRisk", "ExecutionRisk", "TradeFlow"],
                    polarity="risk",
                    risk_impact=10.5,
                    weight=0.81,
                    belief_label="보유 종목에서 거래량 증가와 매도 호가 압력이 함께 나타나 실행 리스크 점검이 필요합니다.",
                    ai_influence_label="매도 수급 압력 추론",
                    action_group="executionRisk",
                    action_level="review",
                )
            ],
        ),
        GraphInferenceRule(
            rule_id="graph.flow.accumulation.entry.v1",
            label="관심 종목 + 체결강도 + 매수 호가 우위 -> 진입 후보 추론",
            version="v1",
            source_kind="stock",
            action_group="entry",
            action_level="review",
            prompt_hint="관심 종목은 가격 위치만 보지 않고 체결강도와 호가 우위가 실제 매집 후보인지 확인 조건을 제시합니다.",
            conditions=[
                GraphRuleCondition(
                    "watchlist-source",
                    "subject_property",
                    "관심 종목입니다.",
                    field="source",
                    operator="==",
                    value="watchlist",
                ),
                GraphRuleCondition(
                    "trade-strength",
                    "relation",
                    "체결강도가 매수 우위 구간입니다.",
                    relation_type="HAS_TRADE_FLOW",
                    target_kind="flow-metric",
                    target_property_filters={"field": "tradeStrength", "minValue": 115},
                    min_weight=0.5,
                ),
                GraphRuleCondition(
                    "bid-pressure",
                    "relation",
                    "매수 호가 우위가 진입 후보를 보강합니다.",
                    relation_type="HAS_TRADE_FLOW",
                    target_kind="flow-metric",
                    target_property_filters={"field": "bidAskImbalance", "minValue": 8},
                    min_weight=0.5,
                ),
            ],
            derivations=[
                GraphRuleDerivation(
                    relation_type="HAS_INFERRED_ENTRY_OPPORTUNITY",
                    target_kind="opportunity",
                    target_key="{symbol}:flow-accumulation-entry",
                    target_label="{displayName} 수급 매집 진입 후보",
                    tbox_class="Opportunity",
                    tbox_classes=["Opportunity", "EntryCondition", "TradeFlow", "ActionabilityAssessment"],
                    polarity="support",
                    support_impact=10.0,
                    weight=0.79,
                    belief_label="관심 종목에서 체결강도와 호가 우위가 함께 나타나 진입 후보로 점검할 수 있습니다.",
                    ai_influence_label="수급 매집 진입 후보",
                    action_group="entry",
                    action_level="review",
                    **WATCHLIST_ENTRY_POLICY,
                )
            ],
        ),
        GraphInferenceRule(
            rule_id="graph.news.direct_material_risk.v1",
            label="보유 종목 + 직접 중요 리스크 뉴스 -> 이벤트 리스크 추론",
            version="v1",
            source_kind="stock",
            action_group="lossControl",
            action_level="review",
            prompt_hint="뉴스 존재 여부가 아니라 종목 직접성, 중요도, 신뢰도, 이벤트 유형을 분리하고 가격·수급 반응과 함께 설명합니다.",
            conditions=[
                GraphRuleCondition(
                    "holding-source",
                    "subject_property",
                    "보유 종목입니다.",
                    field="source",
                    operator="==",
                    value="holding",
                ),
                GraphRuleCondition(
                    "direct-material-risk",
                    "relation",
                    "직접 관련 중요 리스크 뉴스나 공시가 있습니다.",
                    relation_type="HAS_EXTERNAL_SIGNAL",
                    target_kind="research-evidence",
                    target_property_filters={
                        "relationScope": "direct",
                        "polarity": "risk",
                        "materialityPassed": True,
                        "minMaterialityScore": 65,
                    },
                    min_weight=0.55,
                ),
            ],
            derivations=[
                GraphRuleDerivation(
                    relation_type="HAS_INFERRED_RISK",
                    target_kind="risk",
                    target_key="{symbol}:direct-news-risk",
                    target_label="{displayName} 직접 뉴스 이벤트 리스크",
                    tbox_class="EventRisk",
                    tbox_classes=["Risk", "EventRisk", "ResearchEvidence", "NewsEvent"],
                    polarity="risk",
                    risk_impact=12.0,
                    weight=0.83,
                    belief_label="직접 관련 중요 리스크 뉴스가 보유 판단을 약화시키므로 이벤트 리스크 점검이 필요합니다.",
                    ai_influence_label="직접 뉴스 이벤트 리스크",
                    action_group="lossControl",
                    action_level="review",
                ),
                GraphRuleDerivation(
                    relation_type="WEAKENS_THESIS",
                    target_kind="investment-thesis",
                    target_key="{symbol}:news-risk-thesis",
                    target_label="{displayName} 직접 리스크 뉴스로 약화된 투자 가설",
                    tbox_class="InvestmentThesis",
                    tbox_classes=["InvestmentThesis", "NewsEvent", "EventRisk"],
                    polarity="risk",
                    risk_impact=10.0,
                    weight=0.74,
                    belief_label="직접 중요 리스크 뉴스가 기존 보유 논리를 약화합니다.",
                    ai_influence_label="뉴스 기반 가설 약화",
                    action_group="lossControl",
                    action_level="review",
                    decision_stage="NEWS_RISK",
                    stage_priority=36,
                )
            ],
        ),
        GraphInferenceRule(
            rule_id="graph.news.ai_direct_risk.v1",
            label="기사 AI 분석 직접 위험 신호 -> 뉴스 이벤트 리스크 추론",
            version="v1",
            source_kind="stock",
            action_group="eventRisk",
            action_level="review",
            prompt_hint="기사 AI 분석은 매수·매도 결론이 아니라 뉴스 문맥 메타데이터입니다. 직접 위험 신호, 원문 확보 여부, 반대 신호를 분리해 설명합니다.",
            conditions=[
                GraphRuleCondition(
                    "holding-source",
                    "subject_property",
                    "보유 종목입니다.",
                    field="source",
                    operator="==",
                    value="holding",
                ),
                GraphRuleCondition(
                    "ai-direct-risk",
                    "relation",
                    "기사 AI 분석이 직접 관련 위험 신호를 감지했습니다.",
                    relation_type="AFFECTS",
                    direction="in",
                    target_kind="article-ai-analysis",
                    target_property_filters={
                        "relationScope": "direct",
                        "impactPolarity": "risk",
                        "minMaterialityScore": 65,
                        "confidence": {"operator": ">=", "value": 0.55},
                    },
                    min_weight=0.4,
                ),
            ],
            derivations=[
                GraphRuleDerivation(
                    relation_type="HAS_INFERRED_RISK",
                    target_kind="risk",
                    target_key="{symbol}:ai-news-risk",
                    target_label="{displayName} 기사 AI 분석 이벤트 리스크",
                    tbox_class="EventRisk",
                    tbox_classes=["Risk", "EventRisk", "NewsEvent", "ArticleAIAnalysis"],
                    polarity="risk",
                    risk_impact=10.5,
                    weight=0.79,
                    belief_label="기사 AI 분석이 직접 위험 문맥을 감지해 이벤트 리스크 점검이 필요합니다.",
                    ai_influence_label="기사 AI 직접 위험 분석",
                    action_group="eventRisk",
                    action_level="review",
                    decision_stage="NEWS_RISK",
                    stage_priority=37,
                )
            ],
        ),
        GraphInferenceRule(
            rule_id="graph.news.ai_body_missing_review.v1",
            label="기사 AI 분석 본문 미수집 -> 원문 확인 필요 추론",
            version="v1",
            source_kind="stock",
            action_group="dataQuality",
            action_level="watch",
            prompt_hint="본문 없이 제목/RSS 요약으로 분석한 뉴스는 방향 판단보다 원문 확보, 재수집, 가격 반응 확인을 우선합니다.",
            conditions=[
                GraphRuleCondition(
                    "ai-direct-review",
                    "relation",
                    "직접 뉴스 AI 분석이 본문 없이 수행되어 검토가 필요합니다.",
                    relation_type="AFFECTS",
                    direction="in",
                    target_kind="article-ai-analysis",
                    target_property_filters={
                        "relationScope": "direct",
                        "readScope": "title+rss-summary",
                        "needsReview": True,
                    },
                    min_weight=0.4,
                ),
            ],
            derivations=[
                GraphRuleDerivation(
                    relation_type="REQUIRES_NEXT_CHECK",
                    target_kind="next-check",
                    target_key="{symbol}:ai-news-body-check",
                    target_label="{displayName} 뉴스 원문 확보 확인",
                    tbox_class="NextCheck",
                    tbox_classes=["NextCheck", "ArticleAIAnalysis", "DataQualitySignal"],
                    polarity="context",
                    risk_impact=2.5,
                    weight=0.66,
                    belief_label="본문 없이 제목/RSS 요약으로 분석된 직접 뉴스라 원문 확보와 가격 반응 확인이 먼저 필요합니다.",
                    ai_influence_label="뉴스 본문 미수집 확인",
                    action_group="dataQuality",
                    action_level="watch",
                    decision_stage="DATA_CONFLICT",
                    stage_priority=26,
                ),
                GraphRuleDerivation(
                    relation_type="LOWERS_CONFIDENCE_OF",
                    target_kind="confidence-assessment",
                    target_key="{symbol}:ai-news-body-confidence-limit",
                    target_label="{displayName} 뉴스 분석 신뢰도 제한",
                    tbox_class="ConfidenceAssessment",
                    tbox_classes=["ConfidenceAssessment", "ArticleAIAnalysis", "DataQualitySignal"],
                    polarity="risk",
                    risk_impact=3.5,
                    weight=0.61,
                    belief_label="뉴스 본문 부재 때문에 기사 영향 분석 신뢰도를 제한합니다.",
                    ai_influence_label="뉴스 본문 부재 신뢰도 제한",
                    action_group="dataQuality",
                    action_level="review",
                    decision_stage="DATA_CONFLICT",
                    stage_priority=28,
                )
            ],
        ),
        GraphInferenceRule(
            rule_id="graph.news.direct_material_support.v1",
            label="직접 중요 우호 뉴스 + 의미 있는 시장 변화 -> 우호 이벤트 추론",
            version="v1",
            source_kind="stock",
            action_group="entry",
            action_level="review",
            prompt_hint="우호 뉴스는 단독 매수 근거가 아니라 가격·거래량 변화가 확인되는지와 반대 리스크가 있는지 함께 설명합니다.",
            conditions=[
                GraphRuleCondition(
                    "direct-material-support",
                    "relation",
                    "직접 관련 중요 우호 뉴스가 있습니다.",
                    relation_type="HAS_EXTERNAL_SIGNAL",
                    target_kind="research-evidence",
                    target_property_filters={
                        "relationScope": "direct",
                        "polarity": "support",
                        "materialityPassed": True,
                        "minMaterialityScore": 65,
                    },
                    min_weight=0.55,
                ),
                GraphRuleCondition(
                    "market-reaction",
                    "relation",
                    "시장 데이터 변경이 중요도 게이트를 통과했습니다.",
                    relation_type="HAS_OBSERVATION",
                    target_kind="fact-change",
                    target_property_filters={"materialityPassed": True},
                    min_weight=0.65,
                ),
            ],
            derivations=[
                GraphRuleDerivation(
                    relation_type="HAS_INFERRED_ENTRY_OPPORTUNITY",
                    target_kind="opportunity",
                    target_key="{symbol}:direct-news-support",
                    target_label="{displayName} 직접 뉴스 우호 이벤트",
                    tbox_class="Opportunity",
                    tbox_classes=["Opportunity", "EntryCondition", "ResearchEvidence", "NewsEvent"],
                    polarity="support",
                    support_impact=9.0,
                    weight=0.77,
                    belief_label="직접 우호 뉴스와 시장 반응이 함께 확인되어 진입 또는 보유 근거를 재점검할 수 있습니다.",
                    ai_influence_label="직접 뉴스 우호 이벤트",
                    action_group="entry",
                    action_level="review",
                ),
                GraphRuleDerivation(
                    relation_type="SUPPORTS_THESIS",
                    target_kind="investment-thesis",
                    target_key="{symbol}:news-support-thesis",
                    target_label="{displayName} 직접 우호 뉴스로 강화된 투자 가설",
                    tbox_class="InvestmentThesis",
                    tbox_classes=["InvestmentThesis", "NewsEvent", "EntryCondition"],
                    polarity="support",
                    support_impact=8.5,
                    weight=0.70,
                    belief_label="직접 우호 뉴스와 시장 반응이 기존 투자 가설을 보강합니다.",
                    ai_influence_label="뉴스 기반 가설 강화",
                    action_group="entry",
                    action_level="review",
                    decision_stage="NEWS_CONFIRMATION",
                    stage_priority=31,
                )
            ],
        ),
        GraphInferenceRule(
            rule_id="graph.news.direct_material_context.v1",
            label="직접 중요 맥락 뉴스 -> 다음 확인 추론",
            version="v1",
            source_kind="stock",
            action_group="alertReview",
            action_level="watch",
            prompt_hint="방향성이 뚜렷하지 않은 직접 중요 뉴스는 매수·매도 결론보다 가격, 거래량, 후속 공시, 반대 신호 확인 과제로 분리합니다.",
            conditions=[
                GraphRuleCondition(
                    "direct-material-context",
                    "relation",
                    "직접 관련 중요 맥락 뉴스가 있어 다음 확인이 필요합니다.",
                    relation_type="HAS_EXTERNAL_SIGNAL",
                    target_kind="research-evidence",
                    target_property_filters={
                        "relationScope": "direct",
                        "polarity": "context",
                        "materialityPassed": True,
                        "minMaterialityScore": 60,
                    },
                    min_weight=0.55,
                ),
            ],
            derivations=[
                GraphRuleDerivation(
                    relation_type="REQUIRES_NEXT_CHECK",
                    target_kind="next-check",
                    target_key="{symbol}:direct-news-context-check",
                    target_label="{displayName} 직접 뉴스 후속 확인",
                    tbox_class="NextCheck",
                    tbox_classes=["NextCheck", "NewsEvent", "ActionabilityAssessment"],
                    polarity="context",
                    risk_impact=3.5,
                    weight=0.71,
                    belief_label="직접 중요 뉴스가 방향성 결론이 아니라 후속 확인 과제를 만듭니다.",
                    ai_influence_label="직접 중요 맥락 뉴스 확인",
                    action_group="alertReview",
                    action_level="watch",
                )
            ],
        ),
        GraphInferenceRule(
            rule_id="graph.disclosure.event_risk.v1",
            label="보유 종목 + 공시/신고 이벤트 -> 공시 이벤트 리스크 추론",
            version="v1",
            source_kind="stock",
            action_group="lossControl",
            action_level="review",
            prompt_hint="공시나 신고는 제목만 반복하지 않고 이벤트 유형, 기존 보유 논리와의 충돌, 다음 확인 자료를 분리해 설명합니다.",
            conditions=[
                GraphRuleCondition(
                    "holding-source",
                    "subject_property",
                    "보유 종목입니다.",
                    field="source",
                    operator="==",
                    value="holding",
                ),
                GraphRuleCondition(
                    "symbol-disclosure-signal",
                    "relation",
                    "종목 단위 공시/신고 신호가 갱신됐습니다.",
                    relation_type="HAS_EXTERNAL_SIGNAL",
                    target_kind="external-signal",
                    target_property_filters={"group": ["dartDisclosures", "secFilings"]},
                    min_weight=0.5,
                ),
            ],
            derivations=[
                GraphRuleDerivation(
                    relation_type="HAS_INFERRED_RISK",
                    target_kind="risk",
                    target_key="{symbol}:disclosure-event-risk",
                    target_label="{displayName} 공시 이벤트 리스크",
                    tbox_class="EventRisk",
                    tbox_classes=["Risk", "EventRisk", "DisclosureEvent", "DisclosureFiling"],
                    polarity="risk",
                    risk_impact=9.5,
                    weight=0.76,
                    belief_label="보유 종목에 공시/신고 이벤트가 갱신되어 보유 논리와 실행 계획을 재확인해야 합니다.",
                    ai_influence_label="공시 이벤트 리스크",
                    action_group="lossControl",
                    action_level="review",
                )
            ],
        ),
        GraphInferenceRule(
            rule_id="graph.materiality.alert_candidate.v1",
            label="중요 시장 데이터 변경 -> 알림 후보 추론",
            version="v1",
            source_kind="stock",
            action_group="alertReview",
            action_level="watch",
            prompt_hint="단순 최신값이 아니라 이전 상태 대비 의미 있는 변경인지, 어떤 필드가 바뀌었는지 먼저 설명합니다.",
            conditions=[
                GraphRuleCondition(
                    "material-fact-change",
                    "relation",
                    "시장 데이터 변경이 중요도 게이트 기준을 넘었습니다.",
                    relation_type="HAS_OBSERVATION",
                    target_kind="fact-change",
                    target_property_filters={"materialityPassed": True},
                    min_weight=0.65,
                )
            ],
            derivations=[
                GraphRuleDerivation(
                    relation_type="CREATES_NOTIFICATION_INTENT",
                    target_kind="alert-candidate",
                    target_key="{symbol}:material-market-change",
                    target_label="{displayName} 중요 변경 알림 후보",
                    tbox_class="AlertCandidate",
                    tbox_classes=["NotificationIntent", "AlertCandidate", "MaterialityAssessment"],
                    polarity="context",
                    weight=0.74,
                    belief_label="이전 상태 대비 중요한 시장 데이터 변경이 있어 알림 후보로 승격합니다.",
                    ai_influence_label="중요 변경 알림 후보",
                    action_group="alertReview",
                    action_level="watch",
                )
            ],
        ),
        GraphInferenceRule(
            rule_id="graph.holding.trend_transition.risk.v1",
            label="보유 종목 + 위험 추세 전이 -> 리스크 재점검 추론",
            version="v1",
            source_kind="stock",
            action_group="lossControl",
            action_level="review",
            prompt_hint="현재 손익률 하나보다 하락 가속, 횡보 후 하방 이탈, 상승 탄력 둔화 같은 전이 맥락을 우선 설명합니다.",
            conditions=[
                GraphRuleCondition(
                    "holding-source",
                    "subject_property",
                    "보유 종목입니다.",
                    field="source",
                    operator="==",
                    value="holding",
                ),
                GraphRuleCondition(
                    "risk-transition",
                    "relation",
                    "위험 방향의 추세 전이가 감지됐습니다.",
                    relation_type="HAS_TREND_TRANSITION",
                    target_kind="trend-transition",
                    relation_property_filters={"polarity": "risk"},
                    min_weight=0.60,
                ),
            ],
            derivations=[
                GraphRuleDerivation(
                    relation_type="HAS_INFERRED_RISK",
                    target_kind="risk",
                    target_key="{symbol}:trend-transition-risk",
                    target_label="{displayName} 추세 전이 리스크",
                    tbox_class="RegimeRisk",
                    tbox_classes=["Risk", "MarketRisk", "RegimeRisk", "TrendTransition"],
                    polarity="risk",
                    risk_impact=11.0,
                    weight=0.80,
                    belief_label="보유 종목의 가격 경로가 위험 방향으로 전이되어 리스크 재점검이 필요합니다.",
                    ai_influence_label="추세 전이 리스크",
                    action_group="lossControl",
                    action_level="review",
                ),
                GraphRuleDerivation(
                    relation_type="WEAKENS_THESIS",
                    target_kind="investment-thesis",
                    target_key="{symbol}:trend-risk-thesis",
                    target_label="{displayName} 위험 추세 전이로 약화된 투자 가설",
                    tbox_class="InvestmentThesis",
                    tbox_classes=["InvestmentThesis", "TrendTransition", "RegimeRisk"],
                    polarity="risk",
                    risk_impact=9.0,
                    weight=0.72,
                    belief_label="위험 방향 추세 전이가 기존 보유 가설의 신뢰도를 낮춥니다.",
                    ai_influence_label="추세 기반 가설 약화",
                    action_group="lossControl",
                    action_level="review",
                    decision_stage="FLOW_DEFENSE",
                    stage_priority=35,
                )
            ],
        ),
        GraphInferenceRule(
            rule_id="graph.watchlist.trend_transition.support.v1",
            label="관심 종목 + 우호 추세 전이 -> 진입 관찰 추론",
            version="v1",
            source_kind="stock",
            action_group="entry",
            action_level="review",
            prompt_hint="관심 종목은 가격 경로가 하락 후 반등하거나 횡보 후 상방 이탈했는지와 거래량 확인 여부를 분리해 설명합니다.",
            conditions=[
                GraphRuleCondition(
                    "watchlist-source",
                    "subject_property",
                    "관심 종목입니다.",
                    field="source",
                    operator="==",
                    value="watchlist",
                ),
                GraphRuleCondition(
                    "support-transition",
                    "relation",
                    "우호 방향의 추세 전이가 감지됐습니다.",
                    relation_type="HAS_TREND_TRANSITION",
                    target_kind="trend-transition",
                    relation_property_filters={"polarity": "support"},
                    min_weight=0.60,
                ),
            ],
            derivations=[
                GraphRuleDerivation(
                    relation_type="HAS_INFERRED_ENTRY_OPPORTUNITY",
                    target_kind="opportunity",
                    target_key="{symbol}:trend-transition-entry",
                    target_label="{displayName} 추세 전이 진입 관찰",
                    tbox_class="Opportunity",
                    tbox_classes=["Opportunity", "EntryCondition", "TrendTransition", "ActionabilityAssessment"],
                    polarity="support",
                    support_impact=10.0,
                    weight=0.78,
                    belief_label="관심 종목의 가격 경로가 우호적으로 전이되어 진입 관찰 후보가 됩니다.",
                    ai_influence_label="추세 전이 진입 관찰",
                    action_group="entry",
                    action_level="review",
                    **WATCHLIST_ENTRY_POLICY,
                ),
                GraphRuleDerivation(
                    relation_type="SUPPORTS_THESIS",
                    target_kind="investment-thesis",
                    target_key="{symbol}:trend-support-thesis",
                    target_label="{displayName} 우호 추세 전이로 강화된 투자 가설",
                    tbox_class="InvestmentThesis",
                    tbox_classes=["InvestmentThesis", "TrendTransition", "EntryCondition"],
                    polarity="support",
                    support_impact=8.0,
                    weight=0.70,
                    belief_label="우호 방향 추세 전이가 관심 종목의 진입 가설을 보강합니다.",
                    ai_influence_label="추세 기반 가설 강화",
                    action_group="entry",
                    action_level="review",
                    decision_stage="ENTRY_SPLIT_BUY",
                    stage_priority=31,
                    **WATCHLIST_ENTRY_POLICY,
                )
            ],
        ),
        GraphInferenceRule(
            rule_id="graph.data_quality.action_block.v1",
            label="심각한 미시구조 결측 -> 신규 행동 차단",
            version="v1",
            source_kind="stock",
            action_group="entryRisk",
            action_level="review",
            prompt_hint="데이터 결측이 심하면 매수·매도 결론을 만들기보다 판단 차단과 수집 과제를 먼저 설명합니다.",
            conditions=[
                GraphRuleCondition(
                    "severe-microstructure-gap",
                    "relation",
                    "미시구조 결측의 리스크 영향이 커서 신규 행동을 막습니다.",
                    relation_type="HAS_DATA_QUALITY",
                    target_kind="missing-data",
                    target_property_filters={"dataScope": "market-microstructure"},
                    relation_property_filters={"minRiskImpact": 4.0},
                    min_weight=0.1,
                )
            ],
            derivations=[
                GraphRuleDerivation(
                    relation_type="BLOCKS_ACTION",
                    target_kind="blocked-action",
                    target_key="{symbol}:data-quality-action-block",
                    target_label="{displayName} 데이터 결측 행동 차단",
                    tbox_class="BlockedAction",
                    tbox_classes=["BlockedAction", "DataQualityRisk", "ActionabilityAssessment"],
                    polarity="risk",
                    risk_impact=8.0,
                    weight=0.76,
                    belief_label="미시구조 데이터가 부족해 신규 매수·매도 판단을 보류합니다.",
                    ai_influence_label="데이터 품질 행동 차단",
                    action_group="entryRisk",
                    action_level="review",
                    decision_stage="ADD_BUY_BLOCKED",
                    stage_priority=38,
                ),
                GraphRuleDerivation(
                    relation_type="LOWERS_CONFIDENCE_OF",
                    target_kind="confidence-assessment",
                    target_key="{symbol}:data-quality-confidence-block",
                    target_label="{displayName} 데이터 결측 신뢰도 차단",
                    tbox_class="ConfidenceAssessment",
                    tbox_classes=["ConfidenceAssessment", "DataQualityRisk", "MissingData"],
                    polarity="risk",
                    risk_impact=7.0,
                    weight=0.72,
                    belief_label="필수 미시구조 데이터 결측이 판단 신뢰도를 강하게 낮춥니다.",
                    ai_influence_label="데이터 품질 신뢰도 차단",
                    action_group="dataQuality",
                    action_level="review",
                    decision_stage="DATA_CONFLICT",
                    stage_priority=36,
                ),
            ],
        ),
        GraphInferenceRule(
            rule_id="graph.execution.liquidity_or_slippage_block.v1",
            label="보유 종목 + 유동성 또는 슬리피지 위험 -> 실행 차단",
            version="v1",
            source_kind="stock",
            action_group="executionRisk",
            action_level="action",
            prompt_hint="투자 의견과 실제 주문 가능성을 분리하고, 유동성이나 슬리피지가 강하면 분할 실행 또는 행동 보류를 우선합니다.",
            any_condition_min_count=1,
            conditions=[
                GraphRuleCondition(
                    "holding-source",
                    "subject_property",
                    "보유 종목입니다.",
                    field="source",
                    operator="==",
                    value="holding",
                ),
                GraphRuleCondition(
                    "liquidity-limited",
                    "relation",
                    "유동성 제한이 강합니다.",
                    relation_type="LIMITED_BY_LIQUIDITY",
                    target_kind="liquidity-profile",
                    min_weight=0.55,
                    role="any",
                ),
                GraphRuleCondition(
                    "slippage-risk",
                    "relation",
                    "슬리피지 리스크가 강합니다.",
                    relation_type="HAS_SLIPPAGE_RISK",
                    target_kind="slippage-estimate",
                    min_weight=0.55,
                    role="any",
                ),
            ],
            derivations=[
                GraphRuleDerivation(
                    relation_type="HAS_INFERRED_RISK",
                    target_kind="risk",
                    target_key="{symbol}:execution-block-risk",
                    target_label="{displayName} 실행 차단 리스크",
                    tbox_class="ExecutionRisk",
                    tbox_classes=["Risk", "ExecutionRisk", "LiquidityRisk"],
                    polarity="risk",
                    risk_impact=12.0,
                    weight=0.82,
                    belief_label="유동성 또는 슬리피지 리스크가 강해 의견과 주문 실행을 분리해야 합니다.",
                    ai_influence_label="실행 차단 리스크",
                    action_group="executionRisk",
                    action_level="action",
                    decision_stage="LIQUIDITY_ACTION",
                    stage_priority=41,
                ),
                GraphRuleDerivation(
                    relation_type="BLOCKS_ACTION",
                    target_kind="blocked-action",
                    target_key="{symbol}:execution-action-block",
                    target_label="{displayName} 실행 리스크 행동 차단",
                    tbox_class="BlockedAction",
                    tbox_classes=["BlockedAction", "ExecutionRisk", "LiquidityRisk"],
                    polarity="risk",
                    risk_impact=10.0,
                    weight=0.78,
                    belief_label="주문 실행 리스크가 커서 시장가·일괄 주문을 차단하고 분할 기준을 요구합니다.",
                    ai_influence_label="실행 행동 차단",
                    action_group="executionRisk",
                    action_level="action",
                    decision_stage="LIQUIDITY_ACTION",
                    stage_priority=42,
                ),
            ],
        ),
        GraphInferenceRule(
            rule_id="graph.factor.position_crowding.v1",
            label="보유 종목 + 의미 있는 팩터 노출 -> thesis 약화 점검",
            version="v1",
            source_kind="stock",
            action_group="factorRisk",
            action_level="review",
            prompt_hint="종목 단독 신호가 좋아도 같은 팩터에 이미 노출되어 있으면 포트폴리오 리스크와 함께 설명합니다.",
            conditions=[
                GraphRuleCondition(
                    "holding-source",
                    "subject_property",
                    "보유 종목입니다.",
                    field="source",
                    operator="==",
                    value="holding",
                ),
                GraphRuleCondition(
                    "factor-exposure",
                    "relation",
                    "포트폴리오 내에서 의미 있는 팩터 노출입니다.",
                    relation_type="HAS_FACTOR_EXPOSURE",
                    target_kind="factor",
                    min_weight=0.10,
                ),
            ],
            derivations=[
                GraphRuleDerivation(
                    relation_type="REQUIRES_NEXT_CHECK",
                    target_kind="next-check",
                    target_key="{symbol}:factor-crowding-review",
                    target_label="{displayName} 팩터 과밀 점검",
                    tbox_class="NextCheck",
                    tbox_classes=["NextCheck", "ExposureAssessment", "FactorExposure"],
                    polarity="context",
                    risk_impact=5.0,
                    weight=0.68,
                    belief_label="팩터 노출이 커서 종목 판단을 포트폴리오 집중 리스크와 함께 확인합니다.",
                    ai_influence_label="팩터 과밀 점검",
                    action_group="factorRisk",
                    action_level="review",
                    decision_stage="FACTOR_CROWDING",
                    stage_priority=32,
                ),
                GraphRuleDerivation(
                    relation_type="WEAKENS_THESIS",
                    target_kind="investment-thesis",
                    target_key="{symbol}:factor-crowding-thesis",
                    target_label="{displayName} 팩터 과밀로 약화된 투자 가설",
                    tbox_class="InvestmentThesis",
                    tbox_classes=["InvestmentThesis", "FactorExposure", "ConcentrationRisk"],
                    polarity="risk",
                    risk_impact=6.5,
                    weight=0.66,
                    belief_label="동일 팩터 노출이 커질수록 신규 비중 확대 가설은 약해집니다.",
                    ai_influence_label="팩터 기반 가설 약화",
                    action_group="factorRisk",
                    action_level="review",
                    decision_stage="FACTOR_CROWDING",
                    stage_priority=33,
                ),
            ],
        ),
        GraphInferenceRule(
            rule_id="graph.benchmark.beta.context.v1",
            label="보유 종목 + 벤치마크 베타 -> 시장 민감도 점검",
            version="v1",
            source_kind="stock",
            action_group="factorRisk",
            action_level="review",
            prompt_hint="개별 종목 판단 전에 벤치마크 베타와 시장 방향 민감도를 분리해 설명합니다.",
            conditions=[
                GraphRuleCondition(
                    "holding-source",
                    "subject_property",
                    "보유 종목입니다.",
                    field="source",
                    operator="==",
                    value="holding",
                ),
                GraphRuleCondition(
                    "benchmark-beta",
                    "relation",
                    "시장 벤치마크 베타가 판단 컨텍스트에 필요합니다.",
                    relation_type="HAS_BETA_TO",
                    target_kind="benchmark-index",
                    min_weight=0.60,
                ),
            ],
            derivations=[
                GraphRuleDerivation(
                    relation_type="REQUIRES_NEXT_CHECK",
                    target_kind="next-check",
                    target_key="{symbol}:benchmark-beta-review",
                    target_label="{displayName} 벤치마크 베타 점검",
                    tbox_class="NextCheck",
                    tbox_classes=["NextCheck", "ExposureAssessment", "BenchmarkIndex"],
                    polarity="context",
                    risk_impact=4.5,
                    weight=0.62,
                    belief_label="시장 베타가 있어 종목 신호를 시장 방향성과 함께 확인합니다.",
                    ai_influence_label="벤치마크 베타 점검",
                    action_group="factorRisk",
                    action_level="review",
                    decision_stage="FACTOR_CROWDING",
                    stage_priority=28,
                )
            ],
        ),
        GraphInferenceRule(
            rule_id="graph.price.reclaim.thesis_support.v1",
            label="가격 기준 회복 + 심각 결측 없음 -> thesis 지지",
            version="v1",
            source_kind="stock",
            action_group="entry",
            action_level="review",
            prompt_hint="기준선 회복은 데이터 품질 차단이 없을 때만 진입 또는 보유 thesis 지지로 설명합니다.",
            conditions=[
                GraphRuleCondition(
                    "level-reclaim",
                    "relation",
                    "주요 기준선을 회복했습니다.",
                    relation_type="RECLAIMS_LEVEL",
                    target_kind="key-level",
                    min_weight=0.70,
                ),
                GraphRuleCondition(
                    "no-severe-microstructure-gap",
                    "relation",
                    "심각한 미시구조 결측이 없어야 합니다.",
                    relation_type="HAS_DATA_QUALITY",
                    target_kind="missing-data",
                    target_property_filters={"dataScope": "market-microstructure"},
                    relation_property_filters={"minRiskImpact": 4.0},
                    min_weight=0.1,
                    role="not",
                ),
            ],
            derivations=[
                GraphRuleDerivation(
                    relation_type="HAS_INFERRED_SUPPORT",
                    target_kind="opportunity",
                    target_key="{symbol}:level-reclaim-support",
                    target_label="{displayName} 기준선 회복 지지",
                    tbox_class="Opportunity",
                    tbox_classes=["Opportunity", "EntryCondition", "TechnicalObservation"],
                    polarity="support",
                    support_impact=7.5,
                    weight=0.71,
                    belief_label="주요 기준선 회복이 진입 또는 보유 thesis를 지지합니다.",
                    ai_influence_label="기준선 회복 지지",
                    action_group="entry",
                    action_level="review",
                    decision_stage="RECOVERY_CONFIRM",
                    stage_priority=30,
                ),
                GraphRuleDerivation(
                    relation_type="SUPPORTS_THESIS",
                    target_kind="investment-thesis",
                    target_key="{symbol}:level-reclaim-thesis",
                    target_label="{displayName} 기준선 회복으로 강화된 투자 가설",
                    tbox_class="InvestmentThesis",
                    tbox_classes=["InvestmentThesis", "TechnicalObservation", "EntryCondition"],
                    polarity="support",
                    support_impact=7.0,
                    weight=0.68,
                    belief_label="가격 기준 회복이 기존 투자 가설을 보강합니다.",
                    ai_influence_label="가격 회복 가설 강화",
                    action_group="entry",
                    action_level="review",
                    decision_stage="RECOVERY_CONFIRM",
                    stage_priority=30,
                ),
            ],
        ),
        GraphInferenceRule(
            rule_id="graph.portfolio.concentration.review.v1",
            label="포트폴리오 집중 노출 -> 리밸런싱 점검",
            version="v1",
            source_kind="portfolio",
            action_group="rebalance",
            action_level="review",
            prompt_hint="계좌 단위 집중 노출은 개별 종목 매수·매도보다 리밸런싱, 현금 비중, 상관 리스크 점검으로 설명합니다.",
            any_condition_min_count=1,
            conditions=[
                GraphRuleCondition(
                    "sector-concentration-risk",
                    "relation",
                    "섹터 또는 상관 집중 리스크가 있습니다.",
                    relation_type="EXPOSED_TO",
                    target_kind="risk",
                    target_property_filters={"tboxClasses": "ConcentrationRisk"},
                    min_weight=0.25,
                    role="any",
                ),
                GraphRuleCondition(
                    "currency-concentration-risk",
                    "relation",
                    "통화 노출 리스크가 있습니다.",
                    relation_type="EXPOSED_TO",
                    target_kind="risk",
                    target_property_filters={"tboxClasses": "CurrencyRisk"},
                    min_weight=0.25,
                    role="any",
                ),
            ],
            derivations=[
                GraphRuleDerivation(
                    relation_type="REQUIRES_NEXT_CHECK",
                    target_kind="next-check",
                    target_key="{subjectId}:portfolio-concentration-review",
                    target_label="{displayName} 집중 노출 리밸런싱 점검",
                    tbox_class="NextCheck",
                    tbox_classes=["NextCheck", "ExposureAssessment", "ConcentrationRisk"],
                    polarity="context",
                    risk_impact=8.5,
                    weight=0.74,
                    belief_label="포트폴리오 집중 노출이 커서 리밸런싱과 현금 비중 점검이 필요합니다.",
                    ai_influence_label="포트폴리오 집중 노출 점검",
                    action_group="rebalance",
                    action_level="review",
                    decision_stage="REBALANCE_REVIEW",
                    stage_priority=35,
                )
            ],
        ),
    ]
