SENSITIVE_SETTING_TOKENS = ("secret", "token", "password", "clientid", "client_id", "accountseq", "account_seq", "chatid", "chat_id", "key")

METRIC_CONCEPTS = [
    ("quantity", "수량", "Position", "HAS_POSITION", "position", "quantity"),
    ("sellable_quantity", "매도 가능 수량", "Position", "HAS_POSITION", "position", "sellableQuantity"),
    ("average_price", "평단", "PriceMetric", "HAS_PRICE", "price", "averagePrice"),
    ("current_price", "현재가", "PriceMetric", "HAS_PRICE", "price", "currentPrice"),
    ("market_value", "평가액", "PriceMetric", "HAS_PRICE", "price", "marketValue"),
    ("profit_loss", "평가손익", "PriceMetric", "HAS_PRICE", "price", "profitLoss"),
    ("profit_loss_rate", "손익률", "PriceMetric", "HAS_PRICE", "price", "profitLossRate"),
    ("change_rate", "가격 변화율", "PriceMetric", "HAS_PRICE", "price", "changeRate"),
    ("volume", "거래량", "TradeFlow", "HAS_TRADE_FLOW", "flow", "volume"),
    ("volume_ratio", "거래량 배율", "TradeFlow", "HAS_TRADE_FLOW", "flow", "volumeRatio"),
    ("trade_strength", "체결강도", "TradeFlow", "HAS_TRADE_FLOW", "flow", "tradeStrength"),
    ("trading_value", "거래대금", "TradeFlow", "HAS_TRADE_FLOW", "flow", "tradingValue"),
    ("buy_volume", "매수 체결량", "TradeFlow", "HAS_TRADE_FLOW", "flow", "buyVolume"),
    ("sell_volume", "매도 체결량", "TradeFlow", "HAS_TRADE_FLOW", "flow", "sellVolume"),
    ("orderbook_bid_volume", "매수호가 잔량", "TradeFlow", "HAS_TRADE_FLOW", "flow", "orderbookBidVolume"),
    ("orderbook_ask_volume", "매도호가 잔량", "TradeFlow", "HAS_TRADE_FLOW", "flow", "orderbookAskVolume"),
    ("bid_ask_imbalance", "호가 불균형", "TradeFlow", "HAS_TRADE_FLOW", "flow", "bidAskImbalance"),
    ("foreign_net_volume", "외국인 순매수", "TradeFlow", "HAS_TRADE_FLOW", "flow", "foreignNetVolume"),
    ("foreign_net_amount", "외국인 순매수 금액", "TradeFlow", "HAS_TRADE_FLOW", "flow", "foreignNetAmount"),
    ("institution_net_volume", "기관 순매수", "TradeFlow", "HAS_TRADE_FLOW", "flow", "institutionNetVolume"),
    ("institution_net_amount", "기관 순매수 금액", "TradeFlow", "HAS_TRADE_FLOW", "flow", "institutionNetAmount"),
    ("individual_net_volume", "개인 순매수", "TradeFlow", "HAS_TRADE_FLOW", "flow", "individualNetVolume"),
    ("individual_net_amount", "개인 순매수 금액", "TradeFlow", "HAS_TRADE_FLOW", "flow", "individualNetAmount"),
    ("ma5", "5일선", "TechnicalIndicator", "HAS_TECHNICAL_INDICATOR", "technical", "ma5"),
    ("ma20", "20일선", "TechnicalIndicator", "HAS_TECHNICAL_INDICATOR", "technical", "ma20"),
    ("ma60", "60일선", "TechnicalIndicator", "HAS_TECHNICAL_INDICATOR", "technical", "ma60"),
    ("ma120", "120일선", "TechnicalIndicator", "HAS_TECHNICAL_INDICATOR", "technical", "ma120"),
    ("ma200", "200일선", "TechnicalIndicator", "HAS_TECHNICAL_INDICATOR", "technical", "ma200"),
    ("ma20_slope", "20일선 기울기", "TechnicalIndicator", "HAS_TECHNICAL_INDICATOR", "technical", "ma20Slope"),
    ("ma60_slope", "60일선 기울기", "TechnicalIndicator", "HAS_TECHNICAL_INDICATOR", "technical", "ma60Slope"),
    ("ma20_distance", "20일선 괴리", "TechnicalIndicator", "HAS_TECHNICAL_INDICATOR", "technical", "ma20Distance"),
    ("ma60_distance", "60일선 괴리", "TechnicalIndicator", "HAS_TECHNICAL_INDICATOR", "technical", "ma60Distance"),
]

SETTING_CONCEPT_TYPES = {
    "ontologyRelationRules": ("AlertRule", "HAS_ALERT_RULE"),
    "aiPromptTemplates": ("PromptTemplate", "HAS_PROMPT_TEMPLATE"),
    "aiPromptPolicy": ("NotificationPolicy", "HAS_NOTIFICATION_POLICY"),
    "instrumentProfiles": ("InstrumentProfile", "HAS_INSTRUMENT_PROFILE"),
    "alertThresholds": ("Threshold", "HAS_THRESHOLD"),
    "relationRuleThresholds": ("Threshold", "HAS_THRESHOLD"),
    "modelDecisionThresholds": ("Threshold", "HAS_THRESHOLD"),
    "formulaWeights": ("Threshold", "HAS_THRESHOLD"),
    "alertCadenceMinutes": ("CooldownPolicy", "HAS_COOLDOWN_POLICY"),
    "externalApiFetchIntervalMinutes": ("CollectionSchedule", "RUNS_ON_SCHEDULE"),
    "marketSnapshotIntervalMinutes": ("CollectionSchedule", "RUNS_ON_SCHEDULE"),
    "watchlistSnapshotIntervalMinutes": ("CollectionSchedule", "RUNS_ON_SCHEDULE"),
    "externalSignalsIntervalMinutes": ("CollectionSchedule", "RUNS_ON_SCHEDULE"),
    "notificationNoveltyThreshold": ("NoveltyPolicy", "HAS_NOVELTY_POLICY"),
    "notificationCooldownMinutes": ("CooldownPolicy", "HAS_COOLDOWN_POLICY"),
    "buyScoreFormula": ("StrategySignal", "CONFIGURES"),
    "sellScoreFormula": ("StrategySignal", "CONFIGURES"),
    "customBuyModelFormula": ("StrategySignal", "CONFIGURES"),
    "customSellModelFormula": ("StrategySignal", "CONFIGURES"),
    "profitTakeScoreFormula": ("StrategySignal", "CONFIGURES"),
    "lossCutScoreFormula": ("StrategySignal", "CONFIGURES"),
    "notificationScoreFormula": ("NotificationPolicy", "HAS_NOTIFICATION_POLICY"),
    "messageDeliveryLevel": ("MessageDeliveryProfile", "HAS_MESSAGE_DELIVERY_PROFILE"),
    "newsCollectionMinRelevanceScore": ("Threshold", "HAS_THRESHOLD"),
}

OPERATIONAL_PIPELINES = [
    {
        "key": "marketSnapshot",
        "label": "marketSnapshot",
        "tboxClasses": ["DataPipeline", "MarketSnapshot"],
        "sourceKey": "account-market-data",
        "sourceLabel": "계좌·보유·시세 데이터",
        "scheduleKey": "marketSnapshotIntervalMinutes",
        "defaultMinutes": 3,
        "dataKinds": ["portfolio", "positions", "quotes", "cash"],
        "description": "보유 잔고, 현재가, 현금, 포트폴리오 노출을 갱신합니다.",
    },
    {
        "key": "watchlistSnapshot",
        "label": "watchlistSnapshot",
        "tboxClasses": ["DataPipeline", "WatchlistSnapshot"],
        "sourceKey": "watchlist-market-data",
        "sourceLabel": "관심종목 시세 데이터",
        "scheduleKey": "watchlistSnapshotIntervalMinutes",
        "defaultMinutes": 5,
        "dataKinds": ["watchlist", "quotes", "technicalIndicators"],
        "description": "관심 종목의 시세, 추세, 진입 관찰 데이터를 갱신합니다.",
    },
    {
        "key": "externalSignals",
        "label": "externalSignals",
        "tboxClasses": ["DataPipeline", "ExternalSignalCollection"],
        "sourceKey": "external-signal-data",
        "sourceLabel": "뉴스·공시·거시·크립토 외부 신호",
        "scheduleKey": "externalSignalsIntervalMinutes",
        "fallbackSettingKey": "externalApiFetchIntervalMinutes",
        "defaultMinutes": 30,
        "dataKinds": ["news", "disclosures", "macro", "fx", "crypto", "foreignMarket"],
        "description": "외부 신호를 수집해 종목과 포트폴리오 관계에 연결합니다.",
    },
]

INSIGHT_TYPES = [
    ("riskIncrease", "리스크 증가"),
    ("opportunityDetected", "기회 포착"),
    ("contradictionDetected", "관계 충돌"),
    ("dataQualityWarning", "데이터 품질 경고"),
    ("portfolioExposureShift", "포트폴리오 노출 변화"),
    ("watchlistEntrySignal", "관심종목 진입 관찰"),
]

FACTOR_BENCHMARKS = {
    "KR": ("benchmark:KOSPI", "KOSPI"),
    "KOSPI": ("benchmark:KOSPI", "KOSPI"),
    "KOSDAQ": ("benchmark:KOSDAQ", "KOSDAQ"),
    "US": ("benchmark:NASDAQ", "NASDAQ/US Growth"),
    "USA": ("benchmark:NASDAQ", "NASDAQ/US Growth"),
    "NASDAQ": ("benchmark:NASDAQ", "NASDAQ/US Growth"),
    "NYSE": ("benchmark:SP500", "S&P 500"),
    "CRYPTO": ("benchmark:BTC", "Bitcoin/Crypto Liquidity"),
}

SECTOR_FACTORS = {
    "반도체": ["AI 인프라", "HBM/메모리 사이클", "반도체 사이클", "수출 민감"],
    "AI/플랫폼": ["AI/플랫폼 성장", "금리 민감 성장주", "광고·클라우드 수요"],
    "모빌리티": ["전기차 수요", "경기 민감 소비재"],
    "디지털자산": ["크립토 유동성", "위험자산 심리"],
}
