"""Compatibility exports; repository capabilities live with their owners."""

from digital_twin.modules.market_data.contracts import MarketDataProviderFactory

from digital_twin.modules.accounts.contracts import AccountRepository
from digital_twin.modules.decisions.contracts import DecisionEpisodeRepository
from digital_twin.modules.model_registry.contracts import HypothesisLifecycleRepository
from digital_twin.modules.investment_calendar.contracts import InvestmentCalendarRepository
from digital_twin.modules.portfolio.contracts import InvestmentDomainRepository
from digital_twin.modules.news_intelligence.contracts import InvestmentResearchRepository
from digital_twin.modules.market_data.contracts import MarketDataProvider
from digital_twin.modules.market_data.contracts import MarketQuoteRepository
from digital_twin.modules.market_data.contracts import MarketTimeSeriesRepository
from digital_twin.modules.portfolio.contracts import MonitorAccountJob
from digital_twin.modules.portfolio.contracts import MonitorAccountJobRepository
from digital_twin.modules.portfolio.contracts import MonitorSnapshotReader
from digital_twin.modules.portfolio.contracts import MonitorStateRepository
from digital_twin.modules.portfolio.contracts import MonitoringCycleRecordResult
from digital_twin.modules.portfolio.contracts import MonitoringCycleRecorder
from digital_twin.modules.notifications.contracts import NotificationGateway
from digital_twin.modules.reasoning.contracts import ONTOLOGY_GRAPH_REPOSITORY_CONTRACT
from digital_twin.modules.reasoning.contracts import OntologyGraphRepository
from digital_twin.modules.reasoning.contracts import OntologyProjectionAuditRepository
from digital_twin.modules.reasoning.contracts import OntologyProjectionRecorder
from digital_twin.modules.news_intelligence.contracts import ResearchEvidenceGateway
from digital_twin.modules.news_intelligence.contracts import ResearchEvidenceRepository
from digital_twin.modules.portfolio.contracts import SnapshotMonitor
from digital_twin.modules.portfolio.contracts import SnapshotProvider
from digital_twin.modules.instruments.contracts import SymbolSourceGateway
from digital_twin.modules.instruments.contracts import SymbolUniverseRepository
from digital_twin.modules.reasoning.contracts import ensure_ontology_graph_repository_contract
from digital_twin.modules.reasoning.contracts import ontology_graph_repository_contract_errors
