"""Explicit lazy store exports; selecting one adapter does not load every store."""

from digital_twin.modules._exports import resolve_export


_EXPORTS = {'MYSQL_SCHEMA': ('digital_twin.infrastructure.mysql_operational_connection', 'MYSQL_SCHEMA'),
 'MySQLAIInferenceQueueStore': ('digital_twin.infrastructure.mysql_ai_inference_queue',
                                'MySQLAIInferenceQueueStore'),
 'MySQLAccountRegistry': ('digital_twin.infrastructure.account_transactions', 'MySQLAccountRegistry'),
 'MySQLAppStore': ('digital_twin.infrastructure.mysql_operational_core_stores', 'MySQLAppStore'),
 'MySQLCompanyKnowledgeCache': ('digital_twin.infrastructure.mysql_operational_core_stores',
                                'MySQLCompanyKnowledgeCache'),
 'MySQLConnectionProxy': ('digital_twin.infrastructure.mysql_operational_connection', 'MySQLConnectionProxy'),
 'MySQLCryptoMarketSignalCache': ('digital_twin.infrastructure.mysql_operational_core_stores',
                                  'MySQLCryptoMarketSignalCache'),
 'MySQLDataPipelineHealthStore': ('digital_twin.infrastructure.mysql_operational_core_stores',
                                  'MySQLDataPipelineHealthStore'),
 'MySQLEventLog': ('digital_twin.infrastructure.mysql_monitoring_stores', 'MySQLEventLog'),
 'MySQLExternalDataStore': ('digital_twin.infrastructure.external_api.mysql_stores',
                            'MySQLExternalDataStore'),
 'MySQLExternalEvidenceProjectionStateStore': ('digital_twin.infrastructure.mysql_operational_core_stores',
                                               'MySQLExternalEvidenceProjectionStateStore'),
 'MySQLExternalSignalCache': ('digital_twin.infrastructure.mysql_operational_core_stores',
                              'MySQLExternalSignalCache'),
 'MySQLHistoricalReplayJobStore': ('digital_twin.modules.outcomes.infrastructure.mysql_historical_replay_jobs',
                                   'MySQLHistoricalReplayJobStore'),
 'MySQLHypothesisDevelopmentStore': ('digital_twin.modules.model_registry.infrastructure.mysql_hypothesis_development',
                                     'MySQLHypothesisDevelopmentStore'),
 'MySQLHypothesisLifecycleStore': ('digital_twin.modules.model_registry.infrastructure.mysql_hypothesis_lifecycle',
                                   'MySQLHypothesisLifecycleStore'),
 'MySQLInvestmentCalendarCandidateStore': ('digital_twin.modules.investment_calendar.infrastructure.mysql_investment_calendar_candidates',
                                           'MySQLInvestmentCalendarCandidateStore'),
 'MySQLInvestmentCalendarStore': ('digital_twin.modules.investment_calendar.infrastructure.mysql_investment_calendar',
                                  'MySQLInvestmentCalendarStore'),
 'MySQLInvestmentDecisionEpisodeStore': ('digital_twin.infrastructure.mysql_investment_decision_episodes',
                                         'MySQLInvestmentDecisionEpisodeStore'),
 'MySQLInvestmentDomainStore': ('digital_twin.infrastructure.mysql_investment_domain',
                                'MySQLInvestmentDomainStore'),
 'MySQLInvestmentReasoningCaseStore': ('digital_twin.modules.reasoning.infrastructure.mysql_investment_reasoning_cases',
                                       'MySQLInvestmentReasoningCaseStore'),
 'MySQLInvestmentResearchStore': ('digital_twin.modules.news_intelligence.infrastructure.mysql_investment_research',
                                  'MySQLInvestmentResearchStore'),
 'MySQLInvestmentStrategyProposalStore': ('digital_twin.modules.model_registry.infrastructure.mysql_investment_strategy_proposals',
                                          'MySQLInvestmentStrategyProposalStore'),
 'MySQLMarketObservationReasoningAnchorStore': ('digital_twin.infrastructure.mysql_monitoring_stores',
                                                'MySQLMarketObservationReasoningAnchorStore'),
 'MySQLMarketQuoteCache': ('digital_twin.modules.market_data.infrastructure.mysql_market_quotes',
                           'MySQLMarketQuoteCache'),
 'MySQLMarketTimeSeriesStore': ('digital_twin.modules.market_data.infrastructure.mysql_market_time_series',
                                'MySQLMarketTimeSeriesStore'),
 'MySQLModelReviewJobStore': ('digital_twin.modules.model_registry.infrastructure.mysql_model_review_jobs',
                              'MySQLModelReviewJobStore'),
 'MySQLMonitorStore': ('digital_twin.infrastructure.mysql_monitoring_stores', 'MySQLMonitorStore'),
 'MySQLMonitoringCycleRecorder': ('digital_twin.infrastructure.mysql_monitoring_stores',
                                  'MySQLMonitoringCycleRecorder'),
 'MySQLNewsDigestReconciliationStateStore': ('digital_twin.infrastructure.mysql_operational_core_stores',
                                             'MySQLNewsDigestReconciliationStateStore'),
 'MySQLNotificationJobStore': ('digital_twin.modules.notifications.infrastructure.mysql_notification_jobs',
                               'MySQLNotificationJobStore'),
 'MySQLNotificationRuleStore': ('digital_twin.modules.notifications.infrastructure.mysql_notification_config',
                                'MySQLNotificationRuleStore'),
 'MySQLNotificationTemplateStore': ('digital_twin.modules.notifications.infrastructure.mysql_notification_config',
                                    'MySQLNotificationTemplateStore'),
 'MySQLOntologyExperimentStore': ('digital_twin.modules.model_registry.infrastructure.mysql_hypothesis_development',
                                  'MySQLOntologyExperimentStore'),
 'MySQLOntologyGraphAssemblyCacheStore': ('digital_twin.modules.reasoning.infrastructure.mysql_ontology_graph_assembly_cache',
                                          'MySQLOntologyGraphAssemblyCacheStore'),
 'MySQLOntologyInferenceDetailOutboxStore': ('digital_twin.modules.reasoning.infrastructure.mysql_ontology_inference_detail_outbox',
                                             'MySQLOntologyInferenceDetailOutboxStore'),
 'MySQLOntologyInferenceDetailStateStore': ('digital_twin.infrastructure.mysql_operational_core_stores',
                                            'MySQLOntologyInferenceDetailStateStore'),
 'MySQLOntologyMaintenanceStateStore': ('digital_twin.infrastructure.mysql_operational_core_stores',
                                        'MySQLOntologyMaintenanceStateStore'),
 'MySQLOntologyProjectionRunStore': ('digital_twin.modules.reasoning.infrastructure.mysql_ontology_projection_runs',
                                     'MySQLOntologyProjectionRunStore'),
 'MySQLOntologyQualitySampleStore': ('digital_twin.modules.reasoning.infrastructure.mysql_ontology_quality',
                                     'MySQLOntologyQualitySampleStore'),
 'MySQLOntologyReasoningCursorStore': ('digital_twin.infrastructure.mysql_operational_core_stores',
                                       'MySQLOntologyReasoningCursorStore'),
 'MySQLOntologyReasoningMailboxStore': ('digital_twin.modules.reasoning.infrastructure.mysql_reasoning_mailbox',
                                        'MySQLOntologyReasoningMailboxStore'),
 'MySQLOntologyReasoningMonitorStore': ('digital_twin.infrastructure.mysql_monitoring_stores',
                                        'MySQLOntologyReasoningMonitorStore'),
 'MySQLOntologyWorldProjectionOutboxStore': ('digital_twin.modules.reasoning.infrastructure.mysql_ontology_world_projection_outbox',
                                             'MySQLOntologyWorldProjectionOutboxStore'),
 'MySQLOntologyWorldProjectionStateStore': ('digital_twin.infrastructure.mysql_operational_core_stores',
                                            'MySQLOntologyWorldProjectionStateStore'),
 'MySQLOperationalConnection': ('digital_twin.infrastructure.mysql_operational_connection',
                                'MySQLOperationalConnection'),
 'MySQLOperationalStorageCapacityStateStore': ('digital_twin.infrastructure.mysql_operational_core_stores',
                                               'MySQLOperationalStorageCapacityStateStore'),
 'MySQLReasoningEngineComparisonStore': ('digital_twin.infrastructure.mysql_versioned_runtime',
                                         'MySQLReasoningEngineComparisonStore'),
 'MySQLReasoningEngineJobStore': ('digital_twin.infrastructure.mysql_versioned_runtime',
                                  'MySQLReasoningEngineJobStore'),
 'MySQLReasoningEngineRegistryStore': ('digital_twin.infrastructure.mysql_versioned_runtime',
                                       'MySQLReasoningEngineRegistryStore'),
 'MySQLReasoningShadowJobStore': ('digital_twin.infrastructure.mysql_versioned_runtime',
                                  'MySQLReasoningShadowJobStore'),
 'MySQLReasoningSourceFactStore': ('digital_twin.modules.reasoning.infrastructure.mysql_reasoning_source_facts',
                                   'MySQLReasoningSourceFactStore'),
 'MySQLResearchEvidenceStore': ('digital_twin.modules.news_intelligence.infrastructure.mysql_research_evidence',
                                'MySQLResearchEvidenceStore'),
 'MySQLRuntimeCheckpointStore': ('digital_twin.infrastructure.mysql_runtime_checkpoints',
                                 'MySQLRuntimeCheckpointStore'),
 'MySQLRuntimeSettingsStore': ('digital_twin.infrastructure.mysql_operational_core_stores',
                               'MySQLRuntimeSettingsStore'),
 'MySQLSharedInstrumentInferenceStore': ('digital_twin.modules.reasoning.infrastructure.mysql_shared_instrument_inference',
                                         'MySQLSharedInstrumentInferenceStore'),
 'MySQLStatisticalModelSignalStore': ('digital_twin.modules.model_registry.infrastructure.mysql_statistical_signals',
                                      'MySQLStatisticalModelSignalStore'),
 'MySQLSubjectDecisionCaseStore': ('digital_twin.modules.decisions.infrastructure.mysql_subject_decision_cases',
                                   'MySQLSubjectDecisionCaseStore'),
 'MySQLSymbolUniverseStore': ('digital_twin.modules.instruments.infrastructure.mysql_symbol_universe',
                              'MySQLSymbolUniverseStore'),
 'MySQLTemporalFeatureSnapshotStore': ('digital_twin.infrastructure.mysql_versioned_runtime',
                                       'MySQLTemporalFeatureSnapshotStore'),
 'MySQLTimeSeriesBackendRegistryStore': ('digital_twin.infrastructure.mysql_versioned_runtime',
                                         'MySQLTimeSeriesBackendRegistryStore'),
 'MySQLTimeSeriesProjectionOutboxStore': ('digital_twin.infrastructure.mysql_versioned_runtime',
                                          'MySQLTimeSeriesProjectionOutboxStore'),
 '_is_duplicate_key_error': ('digital_twin.infrastructure.mysql_operational_helpers',
                             '_is_duplicate_key_error'),
 '_json_loads': ('digital_twin.infrastructure.mysql_operational_helpers', '_json_loads'),
 '_sent_key_hash': ('digital_twin.infrastructure.mysql_operational_helpers', '_sent_key_hash'),
 'insert_domain_event_with_connection': ('digital_twin.infrastructure.mysql_operational_events',
                                         'insert_domain_event_with_connection'),
 'research_evidence_change_payload': ('digital_twin.infrastructure.mysql_operational_helpers',
                                      'research_evidence_change_payload')}

__all__ = list(_EXPORTS)


def __getattr__(name):
    return resolve_export(__name__, _EXPORTS, name)
