"""Lazy runtime entry points. Implementations live in infrastructure.composition."""

from digital_twin.modules._exports import resolve_export


_EXPORTS = {'ActiveDeploymentWorldProjectionSink': ('digital_twin.infrastructure.composition.reasoning_shadow',
                                         'ActiveDeploymentWorldProjectionSink'),
 'FrozenReasoningSnapshotSource': ('digital_twin.infrastructure.composition.reasoning_shadow',
                                   'FrozenReasoningSnapshotSource'),
 'ShadowNotificationSink': ('digital_twin.infrastructure.composition.reasoning_shadow',
                            'ShadowNotificationSink'),
 'ShadowWorldProjectionSink': ('digital_twin.infrastructure.composition.reasoning_shadow',
                               'ShadowWorldProjectionSink'),
 'V2InferenceDetailReceiptSink': ('digital_twin.infrastructure.composition.reasoning_shadow',
                                  'V2InferenceDetailReceiptSink'),
 'active_versioned_reasoning_queue_state': ('digital_twin.infrastructure.composition.reasoning_health',
                                            'active_versioned_reasoning_queue_state'),
 'build_ai_inference_queue_runner': ('digital_twin.infrastructure.composition.decisions',
                                     'build_ai_inference_queue_runner'),
 'build_decision_action_planning_service': ('digital_twin.infrastructure.composition.portfolio',
                                            'build_decision_action_planning_service'),
 'build_decision_episode_reconciliation_service': ('digital_twin.infrastructure.composition.decisions',
                                                   'build_decision_episode_reconciliation_service'),
 'build_external_data_collection_runner': ('digital_twin.infrastructure.composition.market_data',
                                           'build_external_data_collection_runner'),
 'build_flow_lens_service': ('digital_twin.infrastructure.composition.read_models',
                             'build_flow_lens_service'),
 'build_historical_decision_replay_service': ('digital_twin.infrastructure.composition.outcomes',
                                              'build_historical_decision_replay_service'),
 'build_historical_replay_job_service': ('digital_twin.infrastructure.composition.outcomes',
                                         'build_historical_replay_job_service'),
 'build_hypothesis_development_service': ('digital_twin.infrastructure.composition.model_registry',
                                          'build_hypothesis_development_service'),
 'build_hypothesis_lifecycle_service': ('digital_twin.infrastructure.composition.outcomes',
                                        'build_hypothesis_lifecycle_service'),
 'build_hypothesis_proposal_service': ('digital_twin.infrastructure.composition.model_registry',
                                       'build_hypothesis_proposal_service'),
 'build_hypothesis_research_planning_service': ('digital_twin.infrastructure.composition.news_intelligence',
                                                'build_hypothesis_research_planning_service'),
 'build_instrument_timeline_query_service': ('digital_twin.infrastructure.composition.read_models',
                                             'build_instrument_timeline_query_service'),
 'build_instrument_valuation_query_service': ('digital_twin.infrastructure.composition.read_models',
                                              'build_instrument_valuation_query_service'),
 'build_investment_analysis_service': ('digital_twin.infrastructure.composition.read_models',
                                       'build_investment_analysis_service'),
 'build_investment_brain_service': ('digital_twin.infrastructure.composition.decisions',
                                    'build_investment_brain_service'),
 'build_investment_calendar_candidate_service': ('digital_twin.infrastructure.composition.investment_calendar',
                                                 'build_investment_calendar_candidate_service'),
 'build_investment_calendar_discovery_service': ('digital_twin.infrastructure.composition.investment_calendar',
                                                 'build_investment_calendar_discovery_service'),
 'build_investment_calendar_research_service': ('digital_twin.infrastructure.composition.investment_calendar',
                                                'build_investment_calendar_research_service'),
 'build_investment_calendar_runner': ('digital_twin.infrastructure.composition.investment_calendar',
                                      'build_investment_calendar_runner'),
 'build_investment_calendar_service': ('digital_twin.infrastructure.composition.investment_calendar',
                                       'build_investment_calendar_service'),
 'build_investment_domain_service': ('digital_twin.infrastructure.composition.portfolio',
                                     'build_investment_domain_service'),
 'build_investment_research_orchestrator': ('digital_twin.infrastructure.composition.news_intelligence',
                                            'build_investment_research_orchestrator'),
 'build_investment_research_queue_runner': ('digital_twin.infrastructure.composition.news_intelligence',
                                            'build_investment_research_queue_runner'),
 'build_investment_strategy_proposal_service': ('digital_twin.infrastructure.composition.model_registry',
                                                'build_investment_strategy_proposal_service'),
 'build_kis_realtime_websocket_runner': ('digital_twin.infrastructure.composition.market_data',
                                         'build_kis_realtime_websocket_runner'),
 'build_market_data_collection_runner': ('digital_twin.infrastructure.composition.market_data',
                                         'build_market_data_collection_runner'),
 'build_model_review_runner': ('digital_twin.infrastructure.composition.model_registry',
                               'build_model_review_runner'),
 'build_monitor_runner': ('digital_twin.infrastructure.composition.market_data',
                          'build_monitor_runner'),
 'build_news_analysis_enrichment_runner': ('digital_twin.infrastructure.composition.news_intelligence',
                                           'build_news_analysis_enrichment_runner'),
 'build_news_collection_runner': ('digital_twin.infrastructure.composition.news_intelligence',
                                  'build_news_collection_runner'),
 'build_news_pipeline_repair_service': ('digital_twin.infrastructure.composition.news_intelligence',
                                        'build_news_pipeline_repair_service'),
 'build_notification_queue_runner': ('digital_twin.infrastructure.composition.notifications',
                                     'build_notification_queue_runner'),
 'build_official_calendar_sync_service': ('digital_twin.infrastructure.composition.investment_calendar',
                                          'build_official_calendar_sync_service'),
 'build_ontology_inference_detail_runner': ('digital_twin.infrastructure.composition.reasoning_projection',
                                            'build_ontology_inference_detail_runner'),
 'build_ontology_lab_service': ('digital_twin.infrastructure.composition.model_registry',
                                'build_ontology_lab_service'),
 'build_ontology_maintenance_runner': ('digital_twin.infrastructure.composition.reasoning_projection',
                                       'build_ontology_maintenance_runner'),
 'build_ontology_portfolio_rebuild_runner': ('digital_twin.infrastructure.composition.reasoning_projection',
                                             'build_ontology_portfolio_rebuild_runner'),
 'build_ontology_reasoning_proof_service': ('digital_twin.infrastructure.composition.reasoning_projection',
                                            'build_ontology_reasoning_proof_service'),
 'build_ontology_reasoning_queue_probe': ('digital_twin.infrastructure.composition.reasoning_health',
                                          'build_ontology_reasoning_queue_probe'),
 'build_ontology_reasoning_runner': ('digital_twin.infrastructure.composition.reasoning_monitor',
                                     'build_ontology_reasoning_runner'),
 'build_ontology_world_projection_runner': ('digital_twin.infrastructure.composition.reasoning_projection',
                                            'build_ontology_world_projection_runner'),
 'build_operational_storage_capacity_service': ('digital_twin.infrastructure.composition.operations',
                                                'build_operational_storage_capacity_service'),
 'build_reasoning_engine_shadow_runner': ('digital_twin.infrastructure.composition.reasoning_shadow',
                                          'build_reasoning_engine_shadow_runner'),
 'build_rule_change_candidate_service': ('digital_twin.infrastructure.composition.model_registry',
                                         'build_rule_change_candidate_service'),
 'build_symbol_universe_service': ('digital_twin.infrastructure.composition.instruments',
                                   'build_symbol_universe_service'),
 'build_trade_execution_service': ('digital_twin.infrastructure.composition.portfolio',
                                   'build_trade_execution_service'),
 'build_v2_reasoning_engine': ('digital_twin.infrastructure.composition.reasoning',
                               'build_v2_reasoning_engine'),
 'build_v2_reasoning_job_runner': ('digital_twin.infrastructure.composition.reasoning',
                                   'build_v2_reasoning_job_runner'),
 'data_pipeline_health_event_bus': ('digital_twin.infrastructure.composition.events',
                                    'data_pipeline_health_event_bus'),
 'flow_lens_snapshot': ('digital_twin.infrastructure.composition.read_models', 'flow_lens_snapshot'),
 'investment_analysis_snapshot': ('digital_twin.infrastructure.composition.read_models',
                                  'investment_analysis_snapshot'),
 'monitor_account_job_store_from_settings': ('digital_twin.infrastructure.composition.market_data',
                                             'monitor_account_job_store_from_settings'),
 'monitor_event_bus': ('digital_twin.infrastructure.composition.events', 'monitor_event_bus'),
 'news_event_bus': ('digital_twin.infrastructure.composition.events', 'news_event_bus'),
 'observe_operational_storage_capacity': ('digital_twin.infrastructure.composition.operations',
                                          'observe_operational_storage_capacity'),
 'ontology_graph_single_writer_enabled': ('digital_twin.infrastructure.composition.runtime_support',
                                          'ontology_graph_single_writer_enabled'),
 'ontology_graph_store_epoch': ('digital_twin.infrastructure.composition.runtime_support',
                                'ontology_graph_store_epoch'),
 'ontology_reasoning_event_bus': ('digital_twin.infrastructure.composition.events',
                                  'ontology_reasoning_event_bus'),
 'ontology_reasoning_priority_symbols': ('digital_twin.infrastructure.composition.instruments',
                                         'ontology_reasoning_priority_symbols'),
 'operational_storage_event_bus': ('digital_twin.infrastructure.composition.events',
                                   'operational_storage_event_bus'),
 'prepare_v2_rulebox_release': ('digital_twin.infrastructure.composition.reasoning_release',
                                'prepare_v2_rulebox_release'),
 'resolve_v2_reasoning_worker_deployment': ('digital_twin.infrastructure.composition.reasoning',
                                            'resolve_v2_reasoning_worker_deployment'),
 'setting_truthy': ('digital_twin.infrastructure.composition.runtime_support', 'setting_truthy'),
 'typedb_capacity_guard': ('digital_twin.infrastructure.composition.runtime_support',
                           'typedb_capacity_guard'),
 'typedb_projection_recovery_health': ('digital_twin.infrastructure.composition.reasoning_health',
                                       'typedb_projection_recovery_health'),
 'v2_model_signal_release_contract': ('digital_twin.infrastructure.composition.reasoning_release',
                                      'v2_model_signal_release_contract'),
 'DISABLED_SETTING_VALUES': ('digital_twin.infrastructure.composition.runtime_support',
                             'DISABLED_SETTING_VALUES')}

_EXPORTS.update({
    "build_account_service": ("digital_twin.infrastructure.composition.accounts", "build_account_service"),
    "build_account_watchlist_service": ("digital_twin.infrastructure.composition.instruments", "build_account_watchlist_service"),
})

__all__ = list(_EXPORTS)


def __getattr__(name):
    return resolve_export(__name__, _EXPORTS, name)
