"""Only the graph I/O capabilities needed to publish an inference generation."""

from dataclasses import dataclass
from typing import Any, Callable, ContextManager, Dict, Iterable, List, Optional, Protocol, Tuple, TypeVar

from digital_twin.domain.ontology_contracts import PortfolioOntology


Row = Dict[str, object]
DriverImports = Tuple[Optional[Tuple[Any, Any, Any, Any, Any]], object]
T = TypeVar("T")


class QueryResult(Protocol):
    def resolve(self) -> Any: ...


class Transaction(Protocol):
    def query(self, query: str, given_rows: Optional[List[Row]] = None) -> QueryResult: ...
    def commit(self) -> None: ...


class Driver(Protocol):
    def transaction(self, database: str, transaction_type: object, options: object = None) -> ContextManager[Transaction]: ...


@dataclass(frozen=True)
class PublicationRuntime:
    settings: Callable[[], Row]
    now: Callable[[], str]
    timeout: Callable[[float, str], ContextManager[None]]
    error_code: Callable[[object], str]


class PublicationStore(Protocol):
    address: str
    database: str

    def driver_imports(self) -> DriverImports: ...
    def open_driver(self, imported: DriverImports) -> Driver: ...
    def close_driver(self, driver: Driver) -> None: ...
    def ensure_database(self, driver: Driver) -> None: ...
    def ensure_schema(self, driver: Driver, imported: DriverImports) -> None: ...
    def with_typedb_retries(self, operation: Callable[[], T]) -> T: ...
    def write_operation_timeout_seconds(self) -> float: ...
    def write_transaction_options(self) -> object: ...
    def read_transaction_options(self) -> object: ...
    def inferencebox_write_transaction_query_count(self) -> int: ...
    def write_query_max_bytes(self, settings: Optional[Row] = None) -> int: ...
    def inferencebox_relation_batch_size(self, settings: Optional[Row] = None) -> int: ...
    def inferencebox_given_relation_batch_size(self, settings: Optional[Row] = None) -> int: ...
    def node_rows(self, graph: PortfolioOntology) -> List[Row]: ...
    def rows_for_relations(self, graph: PortfolioOntology) -> List[Row]: ...
    def support_relation_rows(self, graph: PortfolioOntology) -> List[Row]: ...
    def node_insert_query(self, row: Row, updated_at: str) -> str: ...

    def batched_node_insert_queries(
        self, rows: Iterable[Row], updated_at: str, batch_size: int, max_query_bytes: int,
    ) -> List[str]: ...

    def batched_relation_insert_queries(
        self, rows: Iterable[Row], updated_at: str, batch_size: int, max_query_bytes: int,
    ) -> List[str]: ...

    def inferencebox_given_relation_insert_plans(
        self, rows: Iterable[Row], updated_at: str, settings: Optional[Row] = None,
    ) -> List[Row]: ...

    def read_rows_in_transaction(
        self, tx: Transaction, query: str, columns: List[str], label: str = "",
    ) -> List[Row]: ...

    def active_abox_snapshot_id(self, world_id: str = "") -> str: ...

    def read_inference_generation_records(
        self, published_only: bool = True, world_id: str = "",
    ) -> List[Row]: ...

    def inference_generation_candidate_summary(self, generation_id: str, world_id: str = "") -> Row: ...

    def validate_inference_generation_candidate(
        self, graph: PortfolioOntology, generation_id: str,
        expected_entity_count: int, expected_relation_count: int, world_id: str = "",
    ) -> Row: ...

    def activate_inference_generation(
        self, graph: PortfolioOntology, node_rows: Iterable[Row],
        relation_rows: Iterable[Row], world_id: str = "",
    ) -> Row: ...
