"""Public contracts for one end-to-end investment reasoning case."""

from digital_twin.modules.decisions.domain.investment_reasoning.case import CASE_AI_COMPLETED, CASE_AI_PENDING, CASE_BLOCKED, CASE_COMPLETED, CASE_CREATED, CASE_DEFERRED, CASE_DECISION_SYNTHESIZED, CASE_FAILED, CASE_EXPIRED, CASE_HYPOTHESES_READY, CASE_INFERENCE_COMPLETED, CASE_INPUT_READY, CASE_PUBLISHED, CASE_SUPPRESSED, CASE_SUPERSEDED, CASE_TERMINAL_STAGES, CASE_VALIDATED, ReasoningCase
from digital_twin.modules.decisions.domain.investment_reasoning.contracts import AIJudgmentResult, ActionAlternative, ConditionEvidence, DataGap, DecisionSynthesis, FactDelta, FinalDecision, HypothesisRecord, InferenceResult, PremiseLineage, RuleEvaluationRecord, RuleMatchProof, rule_evaluation_records_from_projection_results
from digital_twin.modules.decisions.domain.investment_reasoning.hypotheses import GraphHypothesisManager
from digital_twin.modules.decisions.domain.investment_reasoning.decision_delta import DECISION_DELTA_VERSION, DecisionDelta
from digital_twin.modules.decisions.domain.investment_reasoning.disposition import ACTIONABLE_DECISION, AI_JUDGEMENT_DISPOSITIONS, CONTEXT_OBSERVATION, DATA_SOURCE_FAILURE, HYPOTHESIS_COMPARISON_REQUIRED, HYPOTHESIS_QUALIFICATION_PENDING, HYPOTHESIS_RESEARCH_ONLY, INTERNAL_ONLY_DISPOSITIONS, JUDGEMENT_BLOCKED, NO_MATERIAL_PREDICTIVE_RULE_MATCH, RULE_COVERAGE_GAP_CANDIDATE, WAITING_FOR_SCHEDULED_SOURCE, decision_synthesis_payload, disposition_code_from_context, reasoning_disposition_delivery, reasoning_disposition_requires_ai
from digital_twin.modules.decisions.domain.investment_reasoning.synthesis import decision_data_gaps_from_relation_context, decision_synthesis_from_relation_context
from digital_twin.modules.decisions.domain.investment_reasoning.rule_inventory import reasoning_rule_inventory
from digital_twin.modules.decisions.domain.investment_reasoning.subject_case import ABSTAIN, FINAL_DECISION, OBSERVATION, REVIEW_ONLY, SUPPRESSED, CandidateSetSnapshot, DecisionAbstention, DecisionPublication, SubjectDecisionCase, publication_for_subject_case
from digital_twin.modules.decisions.domain.investment_reasoning.ai_insight import AI_INSIGHT_EPISODE_VERSION, AI_INSIGHT_HANDOFF_VERSION, DECISION_RECONCILIATION_VERSION, SUBJECT_DECISION_ORIGIN, AIInsightEpisode, AIInsightHandoff, ai_insight_handoff, decision_reconciliation, reconciliation_after_delivery
from digital_twin.modules.decisions.domain.investment_reasoning.dispatch import ARCHIVE, HANDOFF_AI, INFERENCE_DISPATCH_VERSION, INVALID, PUBLISH_TYPEDB, InferenceDispatchDecision, inference_dispatch_decision
from digital_twin.modules.reasoning.contracts import FactEnvelope, FactRevisionVector, FactSlice, SemanticChangeSet

__all__ = [
    "AIJudgmentResult",
    "ActionAlternative",
    "ConditionEvidence",
    "DataGap",
    "CASE_AI_COMPLETED",
    "CASE_AI_PENDING",
    "CASE_BLOCKED",
    "CASE_COMPLETED",
    "CASE_CREATED",
    "CASE_DEFERRED",
    "CASE_DECISION_SYNTHESIZED",
    "CASE_FAILED",
    "CASE_EXPIRED",
    "CASE_HYPOTHESES_READY",
    "CASE_INFERENCE_COMPLETED",
    "CASE_INPUT_READY",
    "CASE_PUBLISHED",
    "CASE_SUPPRESSED",
    "CASE_SUPERSEDED",
    "CASE_TERMINAL_STAGES",
    "CASE_VALIDATED",
    "FactDelta",
    "DecisionSynthesis",
    "DECISION_DELTA_VERSION",
    "DecisionDelta",
    "ACTIONABLE_DECISION",
    "AI_JUDGEMENT_DISPOSITIONS",
    "CONTEXT_OBSERVATION",
    "DATA_SOURCE_FAILURE",
    "HYPOTHESIS_COMPARISON_REQUIRED",
    "HYPOTHESIS_QUALIFICATION_PENDING",
    "HYPOTHESIS_RESEARCH_ONLY",
    "INTERNAL_ONLY_DISPOSITIONS",
    "JUDGEMENT_BLOCKED",
    "NO_MATERIAL_PREDICTIVE_RULE_MATCH",
    "RULE_COVERAGE_GAP_CANDIDATE",
    "WAITING_FOR_SCHEDULED_SOURCE",
    "decision_synthesis_payload",
    "disposition_code_from_context",
    "reasoning_disposition_delivery",
    "reasoning_disposition_requires_ai",
    "FinalDecision",
    "GraphHypothesisManager",
    "HypothesisRecord",
    "InferenceResult",
    "PremiseLineage",
    "RuleEvaluationRecord",
    "RuleMatchProof",
    "ReasoningCase",
    "decision_synthesis_from_relation_context",
    "decision_data_gaps_from_relation_context",
    "reasoning_rule_inventory",
    "rule_evaluation_records_from_projection_results",
    "ABSTAIN",
    "FINAL_DECISION",
    "OBSERVATION",
    "REVIEW_ONLY",
    "SUPPRESSED",
    "CandidateSetSnapshot",
    "DecisionAbstention",
    "DecisionPublication",
    "SubjectDecisionCase",
    "publication_for_subject_case",
    "AI_INSIGHT_EPISODE_VERSION",
    "AI_INSIGHT_HANDOFF_VERSION",
    "DECISION_RECONCILIATION_VERSION",
    "SUBJECT_DECISION_ORIGIN",
    "AIInsightEpisode",
    "AIInsightHandoff",
    "ai_insight_handoff",
    "decision_reconciliation",
    "reconciliation_after_delivery",
    "ARCHIVE",
    "HANDOFF_AI",
    "INFERENCE_DISPATCH_VERSION",
    "INVALID",
    "PUBLISH_TYPEDB",
    "InferenceDispatchDecision",
    "inference_dispatch_decision",
    "FactEnvelope",
    "FactRevisionVector",
    "FactSlice",
    "SemanticChangeSet",
]
