"""Capabilities for candidate mapping, readback and guarded recovery."""

from typing import Callable, Dict, Iterable, List, Protocol, Tuple, TypeVar

from digital_twin.domain.ontology_contracts import PortfolioOntology


Row = Dict[str, object]
T = TypeVar("T")


class CandidateRowMapper(Protocol):
    def node_rows(self, graph: PortfolioOntology) -> List[Row]: ...
    def rows_for_relations(self, graph: PortfolioOntology) -> List[Row]: ...
    def support_relation_rows(self, graph: PortfolioOntology) -> List[Row]: ...


class CandidateValidationStore(Protocol):
    def scoped_abox_storage_identity(self, row: Row, owner_kind: str) -> Dict[str, str]: ...
    def scoped_abox_storage_rows_unique(self, rows: Iterable[Row], owner_kind: str) -> Tuple[List[Row], List[Row]]: ...
    def scoped_abox_storage_rows_by_id(self, node_storage_ids: Iterable[str], relation_storage_ids: Iterable[str]) -> Row: ...
    def scoped_abox_storage_reuse_plan(self, node_rows: Iterable[Row], relation_rows: Iterable[Row], assume_missing_storage: bool = False) -> Row: ...


class CandidateRecoveryStore(Protocol):
    address: str

    def pending_abox_activation(self, world_id: str = "") -> Row: ...
    def active_abox_metadata(self, world_id: str = "") -> Row: ...
    def inferencebox_recovery_metadata(self, world_id: str = "") -> Row: ...
    def inferencebox_matches_pending_abox_activation(self, inferencebox: Row, candidate_snapshot_id: str, target_symbols: Iterable[str] = None) -> bool: ...
    def activate_abox_generation(self, snapshot_id: str, world_id: str = "") -> Row: ...
    def finalize_abox_generation(self, active_snapshot_id: str, previous_snapshot_id: str = "", world_id: str = "") -> Row: ...


class CandidateRetryStore(Protocol):
    def with_typedb_retries(self, operation: Callable[[], T], retry_if: Callable[[Exception], bool] = None) -> T: ...
