"""Explicit, lazy contracts surface for the reasoning module."""

from digital_twin.modules._exports import resolve_export


_EXPORTS = {}

_EXPORTS['ONTOLOGY_GRAPH_REPOSITORY_CONTRACT'] = ('digital_twin.modules.reasoning.domain.repositories', 'ONTOLOGY_GRAPH_REPOSITORY_CONTRACT')
_EXPORTS['OntologyGraphRepository'] = ('digital_twin.modules.reasoning.domain.repositories', 'OntologyGraphRepository')
_EXPORTS['ontology_graph_repository_contract_errors'] = ('digital_twin.modules.reasoning.domain.repositories', 'ontology_graph_repository_contract_errors')
_EXPORTS['ensure_ontology_graph_repository_contract'] = ('digital_twin.modules.reasoning.domain.repositories', 'ensure_ontology_graph_repository_contract')
_EXPORTS['OntologyProjectionRecorder'] = ('digital_twin.modules.reasoning.domain.repositories', 'OntologyProjectionRecorder')
_EXPORTS['OntologyProjectionAuditRepository'] = ('digital_twin.modules.reasoning.domain.repositories', 'OntologyProjectionAuditRepository')


_EXPORTS.update({
    'ACTION_ENVELOPE_STATUS_LABELS': ('digital_twin.modules.reasoning.domain.ontology_decision_state', 'ACTION_ENVELOPE_STATUS_LABELS'),
    'ALERT_COVERAGE_CONTRACT_VERSION': ('digital_twin.modules.reasoning.domain.investment_alert_coverage', 'ALERT_COVERAGE_CONTRACT_VERSION'),
    'CATEGORY_LABELS': ('digital_twin.modules.reasoning.domain.portfolio_ontology_coverage', 'CATEGORY_LABELS'),
    'CATEGORY_RELATIONS': ('digital_twin.modules.reasoning.domain.portfolio_ontology_coverage', 'CATEGORY_RELATIONS'),
    'CHANGE_STATES': ('digital_twin.modules.reasoning.domain.ontology_decision_state', 'CHANGE_STATES'),
    'CHANGE_STATE_LABELS': ('digital_twin.modules.reasoning.domain.ontology_decision_state', 'CHANGE_STATE_LABELS'),
    'CONFLICT_STATES': ('digital_twin.modules.reasoning.domain.ontology_decision_state', 'CONFLICT_STATES'),
    'CONFLICT_STATE_LABELS': ('digital_twin.modules.reasoning.domain.ontology_decision_state', 'CONFLICT_STATE_LABELS'),
    'DATA_STATES': ('digital_twin.modules.reasoning.domain.ontology_decision_state', 'DATA_STATES'),
    'DATA_STATE_LABELS': ('digital_twin.modules.reasoning.domain.ontology_decision_state', 'DATA_STATE_LABELS'),
    'DECISION_EFFECTS': ('digital_twin.modules.reasoning.domain.ontology_decision_state', 'DECISION_EFFECTS'),
    'EXECUTION_GRAINS': ('digital_twin.modules.reasoning.domain.ontology_execution_units', 'EXECUTION_GRAINS'),
    'FactEnvelope': ('digital_twin.modules.reasoning.domain.semantic_fact_plane', 'FactEnvelope'),
    'FactRevisionVector': ('digital_twin.modules.reasoning.domain.semantic_fact_plane', 'FactRevisionVector'),
    'FactSlice': ('digital_twin.modules.reasoning.domain.semantic_fact_plane', 'FactSlice'),
    'GraphActionAuthorization': ('digital_twin.modules.reasoning.domain.graph_action_authorization', 'GraphActionAuthorization'),
    'INVESTMENT_ALERT_COVERAGE_CHANGED': ('digital_twin.modules.reasoning.domain.event_types', 'INVESTMENT_ALERT_COVERAGE_CHANGED'),
    'ONTOLOGY_PROMPT_VERSION': ('digital_twin.modules.reasoning.domain.ontology_prompting', 'ONTOLOGY_PROMPT_VERSION'),
    'ONTOLOGY_REASONING_COMPLETED': ('digital_twin.modules.reasoning.domain.event_types', 'ONTOLOGY_REASONING_COMPLETED'),
    'OntologyEntity': ('digital_twin.modules.reasoning.domain.ontology_contracts', 'OntologyEntity'),
    'OntologyQualitySample': ('digital_twin.modules.reasoning.domain.ontology_quality', 'OntologyQualitySample'),
    'OntologyRelation': ('digital_twin.modules.reasoning.domain.ontology_contracts', 'OntologyRelation'),
    'PORTFOLIO_WORLD_TYPE': ('digital_twin.modules.reasoning.domain.ontology_worlds', 'PORTFOLIO_WORLD_TYPE'),
    'PortfolioOntology': ('digital_twin.modules.reasoning.domain.ontology_contracts', 'PortfolioOntology'),
    'RETIRED_AGGREGATE_FIELDS': ('digital_twin.modules.reasoning.domain.ontology_decision_state', 'RETIRED_AGGREGATE_FIELDS'),
    'REVIEW_LEVELS': ('digital_twin.modules.reasoning.domain.ontology_decision_state', 'REVIEW_LEVELS'),
    'REVIEW_LEVEL_LABELS': ('digital_twin.modules.reasoning.domain.ontology_decision_state', 'REVIEW_LEVEL_LABELS'),
    'REVIEW_LEVEL_RANK': ('digital_twin.modules.reasoning.domain.ontology_decision_state', 'REVIEW_LEVEL_RANK'),
    'RULE_EXECUTION_UNIT_VERSION': ('digital_twin.modules.reasoning.domain.ontology_execution_units', 'RULE_EXECUTION_UNIT_VERSION'),
    'SemanticChangeSet': ('digital_twin.modules.reasoning.domain.semantic_fact_plane', 'SemanticChangeSet'),
    'VALIDATION_STATES': ('digital_twin.modules.reasoning.domain.ontology_decision_state', 'VALIDATION_STATES'),
    'VALIDATION_STATE_LABELS': ('digital_twin.modules.reasoning.domain.ontology_decision_state', 'VALIDATION_STATE_LABELS'),
    'VERIFIED_MONITOR_SNAPSHOT_QUEUED': ('digital_twin.modules.reasoning.domain.ontology_projection_status', 'VERIFIED_MONITOR_SNAPSHOT_QUEUED'),
    'VERIFIED_MONITOR_SNAPSHOT_VERSION': ('digital_twin.modules.reasoning.domain.verified_snapshot_reasoning', 'VERIFIED_MONITOR_SNAPSHOT_VERSION'),
    'abox_relation_properties': ('digital_twin.modules.reasoning.domain.ontology_schema', 'abox_relation_properties'),
    'add_entity': ('digital_twin.modules.reasoning.domain.ontology_schema', 'add_entity'),
    'add_relation': ('digital_twin.modules.reasoning.domain.ontology_schema', 'add_relation'),
    'build_investment_insight_events': ('digital_twin.modules.reasoning.domain.ontology_insights', 'build_investment_insight_events'),
    'build_ontology_decision_quality_snapshot': ('digital_twin.modules.reasoning.domain.ontology_decision_quality', 'build_ontology_decision_quality_snapshot'),
    'build_ontology_quality_sample': ('digital_twin.modules.reasoning.domain.ontology_quality', 'build_ontology_quality_sample'),
    'build_portfolio_ontology': ('digital_twin.modules.reasoning.domain.portfolio_ontology_builder', 'build_portfolio_ontology'),
    'compact_monitor_state_for_ontology': ('digital_twin.modules.reasoning.domain.ontology_projection_input', 'compact_monitor_state_for_ontology'),
    'compact_snapshot_event_metadata': ('digital_twin.modules.reasoning.domain.event_payloads', 'compact_snapshot_event_metadata'),
    'conflict_state_from_roles': ('digital_twin.modules.reasoning.domain.ontology_decision_state', 'conflict_state_from_roles'),
    'data_state_is_usable': ('digital_twin.modules.reasoning.domain.ontology_decision_state', 'data_state_is_usable'),
    'dedupe_temporal_rows': ('digital_twin.modules.reasoning.domain.portfolio_ontology_temporal_concepts', 'dedupe_temporal_rows'),
    'default_tbox_metadata': ('digital_twin.modules.reasoning.domain.ontology_schema', 'default_tbox_metadata'),
    'derive_coverage_outcome': ('digital_twin.modules.reasoning.domain.investment_alert_coverage', 'derive_coverage_outcome'),
    'derive_delivery_eligibility': ('digital_twin.modules.reasoning.domain.investment_alert_coverage', 'derive_delivery_eligibility'),
    'entity_id': ('digital_twin.modules.reasoning.domain.ontology_contracts', 'entity_id'),
    'evaluate_alert_coverage_health': ('digital_twin.modules.reasoning.domain.investment_alert_coverage', 'evaluate_alert_coverage_health'),
    'fact_change_contract': ('digital_twin.modules.reasoning.domain.fact_changes', 'fact_change_contract'),
    'fact_revision_id': ('digital_twin.modules.reasoning.domain.fact_changes', 'fact_revision_id'),
    'fact_signature': ('digital_twin.modules.reasoning.domain.fact_changes', 'fact_signature'),
    'follow_up_field_fact_types': ('digital_twin.modules.reasoning.domain.fact_changes', 'follow_up_field_fact_types'),
    'frozen_monitor_state_for_reasoning': ('digital_twin.modules.reasoning.domain.ontology_projection_input', 'frozen_monitor_state_for_reasoning'),
    'inference_trace_ledger_payload': ('digital_twin.modules.reasoning.domain.ontology_inference_ledger', 'inference_trace_ledger_payload'),
    'inferencebox_from_snapshot': ('digital_twin.modules.reasoning.domain.ontology_inference_context', 'inferencebox_from_snapshot'),
    'inferencebox_source_name': ('digital_twin.modules.reasoning.domain.ontology_inference_context', 'inferencebox_source_name'),
    'investment_alert_coverage_changed_event': ('digital_twin.modules.reasoning.domain.events', 'investment_alert_coverage_changed_event'),
    'investment_calendar_source_fact': ('digital_twin.modules.reasoning.domain.reasoning_source_facts', 'investment_calendar_source_fact'),
    'market_fact_change': ('digital_twin.modules.reasoning.domain.fact_changes', 'market_fact_change'),
    'market_world': ('digital_twin.modules.reasoning.domain.ontology_worlds', 'market_world'),
    'material_event_assessment': ('digital_twin.modules.reasoning.domain.investment_alert_coverage', 'material_event_assessment'),
    'ontology_projection_from_metadata': ('digital_twin.modules.reasoning.domain.ontology_inference_context', 'ontology_projection_from_metadata'),
    'ontology_reasoning_requested_event': ('digital_twin.modules.reasoning.domain.events', 'ontology_reasoning_requested_event'),
    'ontology_tbox': ('digital_twin.modules.reasoning.domain.ontology_schema', 'ontology_tbox'),
    'parse_temporal_windows': ('digital_twin.modules.reasoning.domain.portfolio_ontology_temporal_concepts', 'parse_temporal_windows'),
    'portfolio_relation_context_from_snapshot': ('digital_twin.modules.reasoning.domain.ontology_inference_context', 'portfolio_relation_context_from_snapshot'),
    'portfolio_world': ('digital_twin.modules.reasoning.domain.ontology_worlds', 'portfolio_world'),
    'portfolio_world_id': ('digital_twin.modules.reasoning.domain.ontology_worlds', 'portfolio_world_id'),
    'position_observation_profiles': ('digital_twin.modules.reasoning.domain.ontology_observation_quality', 'position_observation_profiles'),
    'profile_for_domain': ('digital_twin.modules.reasoning.domain.ontology_observation_quality', 'profile_for_domain'),
    'projection_reuses_unchanged_inference': ('digital_twin.modules.reasoning.domain.ontology_projection_status', 'projection_reuses_unchanged_inference'),
    'projection_waits_for_reasoning_worker': ('digital_twin.modules.reasoning.domain.ontology_projection_status', 'projection_waits_for_reasoning_worker'),
    'reasoning_source_fact': ('digital_twin.modules.reasoning.domain.reasoning_source_facts', 'reasoning_source_fact'),
    'reasoning_source_snapshot_id': ('digital_twin.modules.reasoning.domain.reasoning_source_snapshot', 'reasoning_source_snapshot_id'),
    'relation_context_from_inferencebox': ('digital_twin.modules.reasoning.domain.ontology_inference_context', 'relation_context_from_inferencebox'),
    'relation_contexts_from_snapshot': ('digital_twin.modules.reasoning.domain.ontology_inference_context', 'relation_contexts_from_snapshot'),
    'relation_news_event_key_suffix': ('digital_twin.modules.reasoning.domain.ontology_insights', 'relation_news_event_key_suffix'),
    'relation_rule_context_summary_lines': ('digital_twin.modules.reasoning.domain.ontology_relation_reasoning', 'relation_rule_context_summary_lines'),
    'requested_scope_families_for_event_fact_types': ('digital_twin.modules.reasoning.domain.ontology_change_impact', 'requested_scope_families_for_event_fact_types'),
    'research_evidence_fact_payload': ('digital_twin.modules.reasoning.domain.fact_changes', 'research_evidence_fact_payload'),
    'review_level_at_least': ('digital_twin.modules.reasoning.domain.ontology_decision_state', 'review_level_at_least'),
    'review_level_for': ('digital_twin.modules.reasoning.domain.ontology_decision_state', 'review_level_for'),
    'rule_condition_dependency_profile': ('digital_twin.modules.reasoning.domain.ontology_change_impact', 'rule_condition_dependency_profile'),
    'rule_dependency_profile': ('digital_twin.modules.reasoning.domain.ontology_change_impact', 'rule_dependency_profile'),
    'rule_execution_unit': ('digital_twin.modules.reasoning.domain.ontology_execution_units', 'rule_execution_unit'),
    'scoped_abox_maintenance_health': ('digital_twin.modules.reasoning.domain.ontology_runtime_operations', 'scoped_abox_maintenance_health'),
    'scoped_abox_maintenance_policy': ('digital_twin.modules.reasoning.domain.ontology_runtime_operations', 'scoped_abox_maintenance_policy'),
    'scoped_abox_maintenance_yield_status': ('digital_twin.modules.reasoning.domain.ontology_runtime_operations', 'scoped_abox_maintenance_yield_status'),
    'split_operational_and_investment_events': ('digital_twin.modules.reasoning.domain.ontology_insights', 'split_operational_and_investment_events'),
    'symbol_key': ('digital_twin.modules.reasoning.domain.portfolio_ontology_market_concepts', 'symbol_key'),
    'tbox_entities': ('digital_twin.modules.reasoning.domain.ontology_schema', 'tbox_entities'),
    'tbox_fingerprint': ('digital_twin.modules.reasoning.domain.ontology_schema', 'tbox_fingerprint'),
    'tbox_relations': ('digital_twin.modules.reasoning.domain.ontology_schema', 'tbox_relations'),
    'temporal_window_values': ('digital_twin.modules.reasoning.domain.portfolio_ontology_temporal_concepts', 'temporal_window_values'),
    'trim_to_recent_sessions': ('digital_twin.modules.reasoning.domain.portfolio_ontology_temporal_concepts', 'trim_to_recent_sessions'),
    'validation_state_for': ('digital_twin.modules.reasoning.domain.ontology_decision_state', 'validation_state_for'),
    'valuation_assumption_rows': ('digital_twin.modules.reasoning.domain.portfolio_ontology_runtime_concepts', 'valuation_assumption_rows'),
    'window_rows': ('digital_twin.modules.reasoning.domain.portfolio_ontology_temporal_concepts', 'window_rows'),
    'without_portfolio_assessment': ('digital_twin.modules.reasoning.domain.ontology_decision_assessments', 'without_portfolio_assessment'),
    'world_type_from_id': ('digital_twin.modules.reasoning.domain.ontology_worlds', 'world_type_from_id'),
})

__all__ = list(_EXPORTS)


def __getattr__(name):
    return resolve_export(__name__, _EXPORTS, name)
