"""Explicit, lazy public surface for the notifications module."""

from digital_twin.modules._exports import resolve_export


_EXPORTS = {'AIInsightNotificationProjectionService': ('digital_twin.modules.notifications.application.ai_insight_notification_projection',
                                            'AIInsightNotificationProjectionService'),
 'CompositeNotificationContextEnricher': ('digital_twin.modules.notifications.application.notification.workflow',
                                          'CompositeNotificationContextEnricher'),
 'DisclosureAnalysisNotificationEnricher': ('digital_twin.modules.notifications.application.notification.workflow',
                                            'DisclosureAnalysisNotificationEnricher'),
 'NotificationAIOpinionEnricher': ('digital_twin.modules.notifications.application.notification.workflow',
                                   'NotificationAIOpinionEnricher'),
 'NotificationAdmissionPolicy': ('digital_twin.modules.notifications.application.notification.admission',
                                 'NotificationAdmissionPolicy'),
 'NotificationFeedbackService': ('digital_twin.modules.notifications.application.notification_feedback_service',
                                 'NotificationFeedbackService'),
 'NotificationHoldingSnapshotEnricher': ('digital_twin.modules.notifications.application.notification.workflow',
                                         'NotificationHoldingSnapshotEnricher'),
 'NotificationHypothesisResearchEnricher': ('digital_twin.modules.notifications.application.notification.workflow',
                                            'NotificationHypothesisResearchEnricher'),
 'NotificationIngressService': ('digital_twin.modules.notifications.application.notification.intake',
                                'NotificationIngressService'),
 'NotificationInstrumentIdentityEnricher': ('digital_twin.modules.notifications.application.notification.workflow',
                                            'NotificationInstrumentIdentityEnricher'),
 'NotificationQueueRunner': ('digital_twin.modules.notifications.application.notification.workflow',
                             'NotificationQueueRunner'),
 'NotificationRenderingService': ('digital_twin.modules.notifications.application.notification.rendering',
                                  'NotificationRenderingService'),
 'NotificationReplayService': ('digital_twin.modules.notifications.application.notification_replay_service',
                               'NotificationReplayService'),
 'NotificationTraceQueryService': ('digital_twin.modules.notifications.application.notification.query',
                                   'NotificationTraceQueryService'),
 '_profit_loss_change_summary': ('digital_twin.modules.notifications.application.notification_message_metrics',
                                 '_profit_loss_change_summary'),
 'apply_ontology_quality_gate_to_response': ('digital_twin.modules.notifications.application.notification.quality',
                                             'apply_ontology_quality_gate_to_response'),
 'notification_heading': ('digital_twin.modules.notifications.application.notification.presentation',
                          'notification_heading'),
 'ontology_quality_gate_context': ('digital_twin.modules.notifications.application.notification.quality',
                                   'ontology_quality_gate_context'),
 'present_notification': ('digital_twin.modules.notifications.application.notification.presentation',
                          'present_notification'),
 'redact_notification_trace_data': ('digital_twin.modules.notifications.application.notification.query',
                                    'redact_notification_trace_data'),
 'render_customer_investment_document': ('digital_twin.modules.notifications.application.customer_investment_message',
                                         'render_customer_investment_document'),
 'typedb_observation_telegram_message': ('digital_twin.modules.notifications.application.typedb_observation_message',
                                         'typedb_observation_telegram_message'),
 'compact_invalidation_line': ('digital_twin.modules.notifications.application.notification_ai_gate_message',
                               'compact_invalidation_line'),
 'compact_next_action_line': ('digital_twin.modules.notifications.application.notification_ai_gate_message',
                              'compact_next_action_line'),
 'decision_transition_presentation': ('digital_twin.modules.notifications.application.notification_ai_gate_message',
                                      'decision_transition_presentation'),
 'execution_headline': ('digital_twin.modules.notifications.application.notification_ai_gate_message',
                        'execution_headline'),
 'execution_telegram_message': ('digital_twin.modules.notifications.application.notification_ai_gate_message',
                                'execution_telegram_message'),
 'prepend_execution_start_badge': ('digital_twin.modules.notifications.application.notification_ai_gate_message',
                                   'prepend_execution_start_badge'),
 'strategy_guide_quality': ('digital_twin.modules.notifications.application.notification_ai_gate_message',
                            'strategy_guide_quality')}

__all__ = list(_EXPORTS)


def __getattr__(name):
    return resolve_export(__name__, _EXPORTS, name)
