"""Explicit capabilities for projection_lock/recovery; no repository or application imports."""

from dataclasses import dataclass
from typing import Any, Callable, Protocol, Dict, List, Tuple


class ProjectionLockRecoveryStore(Protocol):
    address: Any

    def close_driver(self, driver) -> None: ...

    def delete_scoped_abox_write_lease(
        self, driver, imported, lease: Dict[str, object]
    ) -> Dict[str, object]: ...

    def driver_imports(self) -> Tuple[object, object]: ...

    def ensure_database(self, driver) -> None: ...

    def local_process_alive(self, process_id: object) -> bool: ...

    def open_driver(self, imported, request_timeout_seconds: float = None): ...

    def projection_coordinator_token_is_active(self, token: str) -> bool: ...

    def recover_all_dead_local_scoped_abox_write_leases(self) -> Dict[str, object]: ...

    def recover_all_scoped_abox_write_leases_after_server_start(self) -> Dict[str, object]: ...

    def recover_dead_local_scoped_abox_write_lease(
        self, world_id: str = "", recover_untracked_current_process: bool = False
    ) -> Dict[str, object]: ...

    def recover_scoped_abox_write_lease_after_server_start_for_world(
        self, world_id: str = ""
    ) -> Dict[str, object]: ...

    def release_scoped_abox_write_lease(self, lease: Dict[str, object]) -> Dict[str, object]: ...

    def scoped_abox_write_lease_status(self, world_id: str = "") -> Dict[str, object]: ...

    def scoped_abox_write_lease_storage_id(self, world_id: str = "") -> str: ...

    def scoped_abox_write_lease_world_ids(self) -> List[str]: ...

    def with_typedb_retries(self, operation, retry_if=None): ...
