"""Constants for TypeQL, without database execution."""




NATIVE_RULE_EVIDENCE_READ_INDEX_VERSION = "native-rule-evidence-read-index-v3"

NATIVE_RULE_EVIDENCE_READ_INDEX_BATCH_SIZE = 48

# This is a TypeDB query-shape guard, not an investment threshold. Field-index
# hydration splits larger factual reads into this size; an individual native
# predicate remains in the direct TypeQL path when its own evidence set is
# still wider than this bounded shape.
NATIVE_RULE_INDEXED_QUERY_MAX_STORAGE_IDS = NATIVE_RULE_EVIDENCE_READ_INDEX_BATCH_SIZE

TYPEDB_NATIVE_REASONING_PROFILE_VERSION = "typedb-native-rule-profile-v10"

TYPEDB_NATIVE_RULE_ENGINE_VERSION = "typedb-direct-typeql-rule-engine-v6"

TYPEDB_NATIVE_REASONING_LAYER = "typedb-native-rule"

TYPEDB_PROMOTED_NUMERIC_ATTRIBUTES = {
    "currentPrice": "ontology-current-price",
    "averagePrice": "ontology-average-price",
    "marketValue": "ontology-market-value",
    "quantity": "ontology-quantity",
    "sellableQuantity": "ontology-sellable-quantity",
    "positionWeight": "ontology-position-weight-pct",
    "positionAccountWeight": "ontology-position-account-weight-pct",
    "exposureRatio": "ontology-exposure-ratio",
    "policyLimitRatio": "ontology-policy-limit-ratio",
    "policyDeltaRatio": "ontology-policy-delta-ratio",
    "limitValuePct": "ontology-limit-value-pct",
    "minCashWeightPct": "ontology-min-cash-weight-pct",
    "strategyMinCashWeightPct": "ontology-strategy-min-cash-weight-pct",
    "positionCount": "ontology-position-count",
    "changeRate": "ontology-change-rate",
    "priceChangeRate": "ontology-price-change-rate",
    "ma5": "ontology-ma5",
    "ma20": "ontology-ma20",
    "ma60": "ontology-ma60",
    "ma5Distance": "ontology-ma5-distance",
    "ma20Distance": "ontology-ma20-distance",
    "ma60Distance": "ontology-ma60-distance",
    "ma20Slope": "ontology-ma20-slope",
    "ma60Slope": "ontology-ma60-slope",
    "trendCurve": "ontology-trend-curve",
    "volume": "ontology-volume",
    "volumeRatio": "ontology-volume-ratio",
    "rawVolumeRatio": "ontology-raw-volume-ratio",
    "timeAdjustedVolumeRatio": "ontology-time-adjusted-volume-ratio",
    "expectedVolumeRatioNow": "ontology-expected-volume-ratio-now",
    "tradeStrength": "ontology-trade-strength",
    "tradingValue": "ontology-trading-value",
    "reportedTradingValue": "ontology-reported-trading-value",
    "estimatedTradingValue": "ontology-estimated-trading-value",
    "tradingValueMismatchPct": "ontology-trading-value-mismatch-pct",
    "bidAskImbalance": "ontology-bid-ask-imbalance",
    "foreignNetVolume": "ontology-foreign-net-volume",
    "foreignNetAmount": "ontology-foreign-net-amount",
    "institutionNetVolume": "ontology-institution-net-volume",
    "institutionNetAmount": "ontology-institution-net-amount",
    "individualNetVolume": "ontology-individual-net-volume",
    "individualNetAmount": "ontology-individual-net-amount",
    "smartMoneyNetVolume": "ontology-smart-money-net-volume",
    "adrRatio": "ontology-adr-ratio",
    "adrPriceUsd": "ontology-adr-price-usd",
    "adrVolume": "ontology-adr-volume",
    "usdKrwRate": "ontology-usd-krw-rate",
    "localPriceKrw": "ontology-local-price-krw",
    "localEquivalentKrw": "ontology-local-equivalent-krw",
    "leverageFactor": "ontology-leverage-factor",
    "price": "ontology-price",
    "fairValue": "ontology-fair-value",
    "fairValuePrice": "ontology-fair-value-price",
    "fairValueLow": "ontology-fair-value-low",
    "fairValueBase": "ontology-fair-value-base",
    "fairValueHigh": "ontology-fair-value-high",
    "marginOfSafetyPct": "ontology-margin-of-safety-pct",
    "conservativeMarginOfSafetyPct": "ontology-conservative-margin-of-safety-pct",
    "optimisticMarginOfSafetyPct": "ontology-optimistic-margin-of-safety-pct",
    "expensivePremiumPct": "ontology-expensive-premium-pct",
    "minimumMarginOfSafetyPct": "ontology-minimum-margin-of-safety-pct",
    "valuationDecisionEligible": "ontology-valuation-decision-eligible",
    "valuationReferenceOnly": "ontology-valuation-reference-only",
    "valuationModelCount": "ontology-valuation-model-count",
    "valuationConsensusPrice": "ontology-valuation-consensus-price",
    "valuationDisagreementPct": "ontology-valuation-disagreement-pct",
    "analystTargetPrice": "ontology-analyst-target-price",
    "analystTargetMedianPrice": "ontology-analyst-target-median-price",
    "analystTargetLowPrice": "ontology-analyst-target-low-price",
    "analystTargetHighPrice": "ontology-analyst-target-high-price",
    "analystTargetUpsidePct": "ontology-analyst-target-upside-pct",
    "analystOpinionCount": "ontology-analyst-opinion-count",
    "expectedEPS": "ontology-expected-eps",
    "reportedEPS": "ontology-reported-eps",
    "estimatedEPS": "ontology-estimated-eps",
    "targetPER": "ontology-target-per",
    "forwardPE": "ontology-forward-pe",
    "pegRatio": "ontology-peg-ratio",
    "dividendYield": "ontology-dividend-yield",
    "peerPER": "ontology-peer-per",
    "historicalMedianPER": "ontology-historical-median-per",
    "lookbackDays": "ontology-lookback-days",
    "requiredSampleCount": "ontology-required-sample-count",
    "sampleCount": "ontology-sample-count",
    "coverageRatio": "ontology-coverage-ratio",
    "elapsedHours": "ontology-elapsed-hours",
    "startPrice": "ontology-start-price",
    "priceChangePct": "ontology-price-change-pct",
    "relativeReturnPct": "ontology-relative-return-pct",
    "periodReturnPct": "ontology-period-return-pct",
    "activeReturnPct": "ontology-active-return-pct",
    "annualizedVolatilityPct": "ontology-annualized-volatility-pct",
    "maximumDrawdownPct": "ontology-maximum-drawdown-pct",
    "maximumPairwiseCorrelation": "ontology-maximum-pairwise-correlation",
    "volatilityPolicyDeltaPct": "ontology-volatility-policy-delta-pct",
    "drawdownPolicyDeltaPct": "ontology-drawdown-policy-delta-pct",
    "correlationPolicyDelta": "ontology-correlation-policy-delta",
    "estimatedCost": "ontology-estimated-cost",
    "turnoverPct": "ontology-turnover-pct",
    "proxyChangeRate": "ontology-proxy-change-rate",
    "peakPrice": "ontology-peak-price",
    "troughPrice": "ontology-trough-price",
    "peakReturnPct": "ontology-peak-return-pct",
    "troughReturnPct": "ontology-trough-return-pct",
    "drawdownFromPeakPct": "ontology-drawdown-from-peak-pct",
    "reboundFromTroughPct": "ontology-rebound-from-trough-pct",
    "priorPriceChangePct": "ontology-prior-price-change-pct",
    "recentPriceChangePct": "ontology-recent-price-change-pct",
    "priceVelocityChangePct": "ontology-price-velocity-change-pct",
    "consecutiveDeclineCount": "ontology-consecutive-decline-count",
    "consecutiveAdvanceCount": "ontology-consecutive-advance-count",
    "directionChangeCount": "ontology-direction-change-count",
    "validObservationCount": "ontology-valid-observation-count",
    "invalidObservationCount": "ontology-invalid-observation-count",
    "staleObservationCount": "ontology-stale-observation-count",
    "validObservationRatio": "ontology-valid-observation-ratio",
    "profitLossRateStart": "ontology-profit-loss-rate-start",
    "profitLossRateEnd": "ontology-profit-loss-rate-end",
    "profitLossRateChangePct": "ontology-profit-loss-rate-change-pct",
    "ma20DistanceStart": "ontology-ma20-distance-start",
    "ma20DistanceEnd": "ontology-ma20-distance-end",
    "ma20DistanceChange": "ontology-ma20-distance-change",
    "ma20DistancePeak": "ontology-ma20-distance-peak",
    "ma20DistanceTrough": "ontology-ma20-distance-trough",
    "ma20ReclaimCount": "ontology-ma20-reclaim-count",
    "ma20BreakCount": "ontology-ma20-break-count",
    "ma20ObservationCount": "ontology-ma20-observation-count",
    "ma60DistanceStart": "ontology-ma60-distance-start",
    "ma60DistanceEnd": "ontology-ma60-distance-end",
    "volumeRatioEnd": "ontology-volume-ratio-end",
    "tradeStrengthEnd": "ontology-trade-strength-end",
    "bidAskImbalanceEnd": "ontology-bid-ask-imbalance-end",
    "smartMoneyNetLatest": "ontology-smart-money-net-latest",
    "smartMoneyNetChange": "ontology-smart-money-net-change",
    "smartMoneyNetCumulative": "ontology-smart-money-net-cumulative",
    "smartMoneyNetAmountCumulative": "ontology-smart-money-net-amount-cumulative",
    "smartMoneyTradingValueRatioPct": "ontology-smart-money-trading-value-ratio-pct",
    "smartMoneyPositiveSessionRatio": "ontology-smart-money-positive-session-ratio",
    "smartMoneyNegativeSessionRatio": "ontology-smart-money-negative-session-ratio",
    "smartMoneyFlowPersistenceRatio": "ontology-smart-money-flow-persistence-ratio",
    "smartMoneyFlowAcceleration": "ontology-smart-money-flow-acceleration",
    "smartMoneyObservationCount": "ontology-smart-money-observation-count",
    "smartMoneyDistinctObservationCount": "ontology-smart-money-distinct-observation-count",
    "smartMoneyDistinctSessionCount": "ontology-smart-money-distinct-session-count",
    "individualNetLatest": "ontology-individual-net-latest",
    "eventCount": "ontology-event-count",
    "riskEventCount": "ontology-risk-event-count",
    "supportEventCount": "ontology-support-event-count",
    "increaseCount20d": "ontology-position-increase-count-20d",
    # Raw ABox delta fields. These are deliberately promoted so RuleBox native
    # functions, rather than Python materiality code, can evaluate changes.
    "delta": "ontology-delta",
    "deltaPct": "ontology-delta-pct",
    "deltaBp": "ontology-delta-bp",
    "previousValue": "ontology-previous-value",
    "delta1dBp": "ontology-delta-1d-bp",
    "delta5dBp": "ontology-delta-5d-bp",
    "delta20dBp": "ontology-delta-20d-bp",
    "change24h": "ontology-change-24h",
    "change7d": "ontology-change-7d",
    "surprisePercentage": "ontology-surprise-percentage",
    "revenue": "ontology-company-revenue",
    "grossProfit": "ontology-company-gross-profit",
    "operatingIncome": "ontology-company-operating-income",
    "netIncome": "ontology-company-net-income",
    "totalAssets": "ontology-company-total-assets",
    "totalLiabilities": "ontology-company-total-liabilities",
    "equity": "ontology-company-equity",
    "cash": "ontology-company-cash",
    "totalDebt": "ontology-company-total-debt",
    "operatingCashFlow": "ontology-company-operating-cash-flow",
    "capitalExpenditure": "ontology-company-capital-expenditure",
    "freeCashFlow": "ontology-company-free-cash-flow",
    "sharesOutstanding": "ontology-company-shares-outstanding",
    "floatShares": "ontology-company-float-shares",
    "sharesShort": "ontology-company-shares-short",
    "grossMarginPct": "ontology-company-gross-margin-pct",
    "operatingMarginPct": "ontology-company-operating-margin-pct",
    "netMarginPct": "ontology-company-net-margin-pct",
    "cashConversionPct": "ontology-company-cash-conversion-pct",
    "freeCashFlowMarginPct": "ontology-company-free-cash-flow-margin-pct",
    "debtToEquityPct": "ontology-company-debt-to-equity-pct",
    "liabilitiesToAssetsPct": "ontology-company-liabilities-to-assets-pct",
    "revenueGrowthPct": "ontology-company-revenue-growth-pct",
    "operatingIncomeGrowthPct": "ontology-company-operating-income-growth-pct",
    "netIncomeGrowthPct": "ontology-company-net-income-growth-pct",
    "freeCashFlowGrowthPct": "ontology-company-free-cash-flow-growth-pct",
    "sharesOutstandingGrowthPct": "ontology-company-shares-outstanding-growth-pct",
    "pbr": "ontology-price-to-book",
    "bookValue": "ontology-book-value",
    "trailingEPS": "ontology-trailing-eps",
    "returnOnEquity": "ontology-return-on-equity",
    "returnOnAssets": "ontology-return-on-assets",
    "returnOnEquityPct": "ontology-return-on-equity-pct",
    "returnOnAssetsPct": "ontology-return-on-assets-pct",
    "enterpriseToEbitda": "ontology-enterprise-to-ebitda",
    "dividendYieldPct": "ontology-dividend-yield-pct",
    "institutionalOwnershipPct": "ontology-institutional-ownership-pct",
    "insiderOwnershipPct": "ontology-insider-ownership-pct",
    "executiveCount": "ontology-executive-count",
    "score": "ontology-model-signal-score",
    "confidence": "ontology-model-signal-confidence",
    "probability": "ontology-model-signal-probability",
    "probabilityLower": "ontology-model-signal-probability-lower",
    "probabilityUpper": "ontology-model-signal-probability-upper",
    "sourceAgeSeconds": "ontology-model-source-age-seconds",
    "eventAgeMinutes": "ontology-event-age-minutes",
    "eventMaxAgeMinutes": "ontology-event-max-age-minutes",
}

TYPEDB_PROMOTED_TEXT_ATTRIBUTES = {
    "investmentStrategyProfile": "ontology-investment-strategy-profile",
    "investmentStrategyProfileLabel": "ontology-investment-strategy-profile-label",
    "positionRole": "ontology-position-role",
    "targetPositionRole": "ontology-target-position-role",
    "positionIntent": "ontology-position-intent",
    "positionIntentLabel": "ontology-position-intent-label",
    "positionIntentDescription": "ontology-position-intent-description",
    "instrumentArchetype": "ontology-instrument-archetype",
    "instrumentArchetypes": "ontology-instrument-archetype",
    "archetypeLabel": "ontology-instrument-archetype-label",
    "archetypeLabels": "ontology-instrument-archetype-label",
    "instrumentArchetypeLabels": "ontology-instrument-archetype-label",
    "factor": "ontology-factor",
    "sensitivityLevel": "ontology-sensitivity-level",
    "rateSeriesId": "ontology-rate-series-id",
    "observationDate": "ontology-observation-date",
    "previousDate": "ontology-previous-observation-date",
    "sourceAsOf": "ontology-source-as-of",
    "effectiveAt": "ontology-event-effective-at",
    "retrievedAt": "ontology-event-retrieved-at",
    "evaluatedAt": "ontology-event-evaluated-at",
    "validFrom": "ontology-event-valid-from",
    "validUntil": "ontology-event-valid-until",
    "eventLifecycleState": "ontology-event-lifecycle-state",
    "eventFreshnessClass": "ontology-event-freshness-class",
    "eventDecisionEligible": "ontology-event-decision-eligible",
    "eventDecisionReason": "ontology-event-decision-reason",
    "eventTimeContractVersion": "ontology-event-time-contract-version",
    "documentVerificationState": "ontology-document-verification-state",
    "documentAnalysisState": "ontology-document-analysis-state",
    "evidenceEligibilityState": "ontology-evidence-eligibility-state",
    "documentHash": "ontology-document-hash",
    "reportName": "ontology-report-name",
    "receiptDate": "ontology-receipt-date",
    "sourceRevision": "ontology-source-revision",
    "changeBasis": "ontology-change-basis",
    "cryptoSymbol": "ontology-crypto-symbol",
    "pair": "ontology-fx-pair",
    "actionPolicy": "ontology-action-policy",
    "tradingValueQuality": "ontology-trading-value-quality",
    "tradingValueBasis": "ontology-trading-value-basis",
    "securityLineRole": "ontology-security-line-role",
    "localSymbol": "ontology-local-symbol",
    "companyName": "ontology-company-name",
    "market": "ontology-market",
    "currency": "ontology-currency",
    "exchange": "ontology-exchange",
    "adrSymbol": "ontology-adr-symbol",
    "etfSymbol": "ontology-etf-symbol",
    "underlyingSymbol": "ontology-underlying-symbol",
    "conversionStartDate": "ontology-conversion-start-date",
    "listingDate": "ontology-listing-date",
    "sourceUrl": "ontology-source-url",
    "valuationMethod": "ontology-valuation-method",
    "formula": "ontology-formula",
    "epsPeriod": "ontology-eps-period",
    "multiplePeriod": "ontology-multiple-period",
    "valuationAsOf": "ontology-valuation-as-of",
    "valuationFreshnessStatus": "ontology-valuation-freshness-status",
    "valuationDataStateLabel": "ontology-valuation-data-state-label",
    "valuationDataState": "ontology-valuation-data-state",
    "valuationInputState": "ontology-valuation-input-state",
    "valuationReliabilityState": "ontology-valuation-reliability-state",
    "valuationSourceType": "ontology-valuation-source-type",
    "valuationCurrency": "ontology-valuation-currency",
    "valuationReferenceReason": "ontology-valuation-reference-reason",
    "valuationConsensusStatus": "ontology-valuation-consensus-status",
    "perValuationStatus": "ontology-per-valuation-status",
    "perValuationReason": "ontology-per-valuation-reason",
    "preferredValuationMetric": "ontology-preferred-valuation-metric",
    "fundamentalDataSourcePriority": "ontology-fundamental-data-source-priority",
    "windowKey": "ontology-window-key",
    "hasSufficientHistory": "ontology-has-sufficient-history",
    "latestObservationQuality": "ontology-latest-observation-quality",
    "sequenceRole": "ontology-sequence-role",
    "observationQuality": "ontology-observation-quality",
    "observedAt": "ontology-observed-at",
    "provider": "ontology-provider",
    "pricePathPattern": "ontology-price-path-pattern",
    "flowPattern": "ontology-flow-pattern",
    "eventClusterType": "ontology-event-cluster-type",
    "trendEpisodeType": "ontology-trend-episode-type",
    "registryVersion": "ontology-language-registry-version",
    "termId": "ontology-language-term-id",
    "termCategory": "ontology-language-term-category",
    "termStatus": "ontology-language-term-status",
    "termVersion": "ontology-language-term-version",
    "preferredLabel": "ontology-language-preferred-label",
    "deliveryLevel": "ontology-language-delivery-level",
    "deliveryLevelLabel": "ontology-language-delivery-level-label",
    "renderedLabel": "ontology-language-rendered-label",
    "smartMoneyDirection": "ontology-smart-money-direction",
    "smartMoneyFlowDirection": "ontology-smart-money-flow-direction",
    "smartMoneyFlowBasis": "ontology-smart-money-flow-basis",
    "investorFlowPsychology": "ontology-investor-flow-psychology",
    "investorFlowEvidenceRole": "ontology-investor-flow-evidence-role",
    "investorFlowDataState": "ontology-investor-flow-data-state",
    "investorFlowReviewLevel": "ontology-investor-flow-review-level",
    "investorFlowMeasurementType": "ontology-investor-flow-measurement-type",
    "investorFlowIsEstimate": "ontology-investor-flow-is-estimate",
    "investorFlowSourceAsOf": "ontology-investor-flow-source-as-of",
    "investorFlowProviderUpdateSlot": "ontology-investor-flow-provider-update-slot",
    "investorFlowFreshnessStatus": "ontology-investor-flow-freshness-status",
    "trendRiskState": "ontology-trend-risk-state",
    "trendReviewLevel": "ontology-trend-review-level",
    "trendEvidenceRole": "ontology-trend-evidence-role",
    "trendDataState": "ontology-trend-data-state",
    "liquidityState": "ontology-liquidity-state",
    "liquidityReviewLevel": "ontology-liquidity-review-level",
    "liquidityDataState": "ontology-liquidity-data-state",
    "sourceDataState": "ontology-source-data-state",
    "externalSignalDataState": "ontology-external-signal-data-state",
    "relevanceState": "ontology-relevance-state",
    "sourceTrustState": "ontology-source-trust-state",
    "materialityState": "ontology-materiality-state",
    "period": "ontology-reporting-period",
    "reportingFrequency": "ontology-reporting-frequency",
    "companyFactRevision": "ontology-company-fact-revision",
    "companyDataState": "ontology-company-data-state",
    "ceoName": "ontology-ceo-name",
    # Statistical model outputs are first-class ABox evidence. RuleBox
    # functions must bind these immutable release and eligibility fields from
    # TypeDB attributes rather than inspect the JSON display payload.
    "signalType": "ontology-model-signal-type",
    "signalFamily": "ontology-model-signal-family",
    "horizon": "ontology-model-signal-horizon",
    "strengthBand": "ontology-model-signal-strength-band",
    "releaseId": "ontology-model-release-id",
    "validationStatus": "ontology-model-validation-status",
    "decisionEligibility": "ontology-model-decision-eligibility",
    "eligibilityStatus": "ontology-model-eligibility-status",
    "uncertaintyStatus": "ontology-model-uncertainty-status",
    "hypothesisFamilyId": "ontology-hypothesis-family-id",
    "hypothesisContractId": "ontology-hypothesis-contract-id",
    "outcomeMetric": "ontology-model-outcome-metric",
    "knowledgeCutoffAt": "ontology-model-knowledge-cutoff-at",
    "marketSession": "ontology-model-market-session",
    "featureSetVersion": "ontology-model-feature-set-version",
    "materialHash": "ontology-model-signal-material-hash",
    "personName": "ontology-person-name",
    "executiveTitle": "ontology-executive-title",
    "executiveResponsibility": "ontology-executive-responsibility",
    "registeredExecutive": "ontology-registered-executive",
    "tenureEnd": "ontology-tenure-end",
    "classification": "ontology-portfolio-activity-classification",
    "reentered": "ontology-position-reentered",
    "correspondence": "ontology-decision-action-correspondence",
}

TYPEDB_FUNCTION_SUBJECT_FIELDS = {
    "source",
    "symbol",
    "kind",
    "ontologyBox",
    "tboxClass",
    "profitLossRate",
    "value",
    "valueNumber",
} | set(TYPEDB_PROMOTED_NUMERIC_ATTRIBUTES.keys()) | set(TYPEDB_PROMOTED_TEXT_ATTRIBUTES.keys())

TYPEDB_FUNCTION_TARGET_FILTERS = {
    # Normalized ABox observations, including ExecutionMetric, retain their
    # numeric fact in the common ``ontology-value-number`` attribute.  These
    # are physical TypeDB values, not JSON-only filters.
    "value",
    "valueNumber",
    "field",
    "levelType",
    "dataScope",
    "domainScope",
    "relationScope",
    "group",
    "polarity",
    "eventType",
    "materialityPassed",
    "materialityState",
    "relevanceState",
    "sourceTrustState",
    "dataState",
    "valuationDataState",
    "minValue",
    "maxValue",
    "tboxClass",
    "tboxClasses",
    "allowAddOnStrength",
    "trimOnTrendBreak",
    "avoidAveragingDown",
    "impactPolarity",
    "needsReview",
    "readScope",
    "peRatio",
    "beta",
} | set(TYPEDB_PROMOTED_NUMERIC_ATTRIBUTES.keys()) | set(TYPEDB_PROMOTED_TEXT_ATTRIBUTES.keys())

TYPEDB_FUNCTION_RELATION_FILTERS = {
    "weight",
    "field",
    "signalGroup",
    "polarity",
    "transitionType",
    "materialityPassed",
    "materialityState",
    "relevanceState",
    "sourceTrustState",
    "evidenceRole",
    "reviewLevel",
    "dataState",
    "changeState",
    "conflictState",
}

TYPEDB_FUNCTION_OPERATORS = {"==", "eq", "!=", "ne", "<=", "lte", ">=", "gte", "<", "lt", ">", "gt", "exists", "present"}

TYPEDB_STRING_ATTRIBUTES = {
    "ontology-id",
    "ontology-label",
    "ontology-kind",
    "ontology-box",
    "ontology-symbol",
    "ontology-rule-id",
    "ontology-account-id",
    "ontology-tenant-id",
    "ontology-world-id",
    "ontology-world-type",
    "ontology-snapshot-id",
    "ontology-scope-id",
    "ontology-scope-type",
    "ontology-manifest-id",
    "ontology-tbox-class",
    "ontology-relation-type",
    "ontology-updated-at",
    "ontology-json",
    "ontology-source-value",
    "ontology-field",
    "ontology-level-type",
    "ontology-data-scope",
    "ontology-domain-scope",
    "ontology-relation-scope",
    "ontology-group",
    "ontology-polarity",
    "ontology-evidence-role",
    "ontology-review-level",
    "ontology-data-state",
    "ontology-change-state",
    "ontology-conflict-state",
    "ontology-validation-state",
    "ontology-transition-type",
    "ontology-signal-group",
    "ontology-event-type",
    "ontology-materiality-passed",
    "ontology-allow-add-on-strength",
    "ontology-trim-on-trend-break",
    "ontology-avoid-averaging-down",
    "ontology-impact-polarity",
    "ontology-needs-review",
    "ontology-read-scope",
} | set(TYPEDB_PROMOTED_TEXT_ATTRIBUTES.values())

TYPEDB_NUMERIC_ATTRIBUTES = {
    "ontology-weight",
    "ontology-value-number",
    "ontology-profit-loss-rate",
    "ontology-pe-ratio",
    "ontology-beta",
} | set(TYPEDB_PROMOTED_NUMERIC_ATTRIBUTES.values())

# Only identity and lifecycle attributes belong on the universal node root.
# Investment facts queried by the active RuleBox are owned by narrow bounded-
# context roots below.  This prevents every one of the hundreds of semantic
# classes from inheriting every promoted display attribute at TypeDB startup.
TYPEDB_COMMON_NODE_ATTRIBUTES = {
    "ontology-id",
    "ontology-storage-id",
    "ontology-content-fingerprint",
    "ontology-label",
    "ontology-kind",
    "ontology-box",
    "ontology-symbol",
    "ontology-rule-id",
    "ontology-account-id",
    "ontology-tenant-id",
    "ontology-world-id",
    "ontology-world-type",
    "ontology-snapshot-id",
    "ontology-scope-id",
    "ontology-scope-type",
    "ontology-manifest-id",
    "ontology-tbox-class",
    "ontology-semantic-type",
    "ontology-updated-at",
    "ontology-json",
}
