"""Separate capabilities for physical fact writes and active-generation control."""

from dataclasses import dataclass
from typing import Any, Callable, ContextManager, Dict, Iterable, List, Optional, Protocol, Tuple, TypeVar

from digital_twin.domain.ontology_contracts import PortfolioOntology


Row = Dict[str, object]
DriverImports = Tuple[Optional[Tuple[Any, Any, Any, Any, Any]], object]
T = TypeVar("T")


class QueryResult(Protocol):
    def resolve(self) -> Any: ...


class Transaction(Protocol):
    def query(self, query: str, given_rows: Optional[List[Row]] = None) -> QueryResult: ...
    def commit(self) -> None: ...


class Driver(Protocol):
    def transaction(self, database: str, transaction_type: object, options: object = None) -> ContextManager[Transaction]: ...


@dataclass(frozen=True)
class ABoxRuntime:
    settings: Callable[[], Row]
    now: Callable[[], str]
    timeout: Callable[[float, str], ContextManager[None]]
    error_code: Callable[[object], str]


class WriteIO(Protocol):
    database: str

    def open_driver(self, imported: DriverImports) -> Driver: ...
    def close_driver(self, driver: Driver) -> None: ...
    def ensure_database(self, driver: Driver) -> None: ...
    def with_typedb_retries(self, operation: Callable[[], T]) -> T: ...
    def write_operation_timeout_seconds(self) -> float: ...
    def write_transaction_options(self) -> object: ...


class ABoxRowStore(WriteIO, Protocol):
    def scoped_abox_storage_reuse_plan(
        self, node_rows: Iterable[Row], relation_rows: Iterable[Row], assume_missing_storage: bool = False,
    ) -> Row: ...

    def scoped_abox_counts_by_scope(self, node_rows: Iterable[Row], relation_rows: Iterable[Row]) -> Row: ...
    def scoped_abox_relation_breakdown(self, rows: Iterable[Row]) -> Row: ...
    def abox_node_batch_size(self, settings: Optional[Row] = None) -> int: ...
    def abox_relation_batch_size(self, settings: Optional[Row] = None) -> int: ...
    def abox_write_transaction_query_count(self, settings: Optional[Row] = None) -> int: ...
    def write_query_max_bytes(self, settings: Optional[Row] = None) -> int: ...

    def batched_node_insert_queries(
        self, rows: Iterable[Row], updated_at: str, batch_size: int, max_query_bytes: int,
    ) -> List[str]: ...

    def batched_relation_insert_queries(
        self, rows: Iterable[Row], updated_at: str, batch_size: int, max_query_bytes: int,
    ) -> List[str]: ...

    def given_relation_insert_plans(self, rows: Iterable[Row], updated_at: str, settings: Optional[Row] = None) -> List[Row]: ...

    def current_state_storage_inventory(
        self, driver: Driver, imported: DriverImports,
        node_storage_ids: Optional[Iterable[str]] = None, relation_storage_ids: Optional[Iterable[str]] = None,
    ) -> Row: ...

    def missing_relation_endpoint_storage_ids(self, rows: Iterable[Row], nodes: Row) -> List[str]: ...
    def missing_relation_endpoint_diagnostics(self, rows: Iterable[Row], storage_ids: Iterable[str]) -> List[Row]: ...


class ABoxControlStore(WriteIO, Protocol):
    address: str

    def driver_imports(self) -> DriverImports: ...
    def driver_missing_result(self, error: object, graph: PortfolioOntology) -> Row: ...
    def ensure_schema(self, driver: Driver, imported: DriverImports) -> None: ...
    def scoped_abox_control_delete_query(self, kind: str, world_id: str = "", scope_id: str = "") -> str: ...
    def graph_insert_queries(self, graph: PortfolioOntology) -> List[str]: ...
    def scoped_manifest_metadata(self, manifest_id: str, world_id: str = "") -> Row: ...
    def active_abox_metadata(self, world_id: str = "") -> Row: ...
    def pending_abox_activation(self, world_id: str = "") -> Row: ...
    def scoped_manifest_control_delta(self, metadata: Row, previous_metadata: Optional[Row] = None) -> Row: ...

    def scoped_manifest_control_graph(
        self, metadata: Row, previous_metadata: Optional[Row] = None, pending_activation: bool = False,
        inference_target_symbols: Optional[Iterable[str]] = None, scope_ids: Optional[Iterable[str]] = None,
    ) -> PortfolioOntology: ...

    def replace_scoped_abox_control_graph(
        self, driver: Driver, imported: DriverImports, graph: PortfolioOntology, world_id: str = "",
        scope_ids: Optional[Iterable[str]] = None, replace_all_scope_pointers: bool = False,
    ) -> Row: ...

    def activate_scoped_abox_manifest(
        self, manifest_id: str, previous_metadata: Optional[Row] = None, pending_activation: bool = False,
        inference_target_symbols: Optional[Iterable[str]] = None, world_id: str = "",
    ) -> Row: ...

    def clear_scoped_abox_pending_activation(self, world_id: str = "") -> Row: ...
    def inferencebox_recovery_metadata(self, world_id: str = "") -> Row: ...

    def inferencebox_matches_pending_abox_activation(
        self, inferencebox: Row, candidate_snapshot_id: str, target_symbols: Optional[Iterable[str]] = None,
    ) -> bool: ...
