"""Web configuration boundary."""

from digital_twin.infrastructure import operational_store as stores
from digital_twin.infrastructure.runtime_identity import runtime_identity
from digital_twin.infrastructure.settings import runtime_settings
from digital_twin.infrastructure.settings import save_runtime_settings
from digital_twin.infrastructure.share_access import ShareAccess
from digital_twin.infrastructure.share_access import anonymous_access
from digital_twin.infrastructure.share_access import local_owner_access
from digital_twin.infrastructure.share_access import share_mode_enabled
from digital_twin.infrastructure.web.adapters.share import share_runtime_status_payload
from digital_twin.infrastructure.web.common import configured
from digital_twin.infrastructure.web.events import new_domain_event
from digital_twin.infrastructure.web.telemetry import WEB_PROCESS_STARTED_AT
from digital_twin.modules.market_data.public import ExternalDataConfigurationRecoveryService
from digital_twin.modules.market_data.public import sec_metadata_access_ready
from digital_twin.platform.domain.event_types import SETTINGS_UPDATED
from typing import Dict


def settings_status_payload(access: ShareAccess = None) -> Dict[str, object]:
    settings = runtime_settings()
    from digital_twin.modules.decisions.domain.notification_ai_prompt_release import active_notification_ai_prompt_release

    prompt_release = active_notification_ai_prompt_release(settings).to_public_dict()
    public_keys = [
        "appTheme",
        "appTimezone",
        "watchlistSymbols",
        "mysqlUrl",
        "mysqlHost",
        "mysqlPort",
        "mysqlDatabase",
        "mysqlUser",
        "mysqlUnixSocket",
        "mysqlTablePartitioning",
        "tossApiBaseUrl",
        "kisEnv",
        "kisBaseUrl",
        "kisWebSocketUrl",
        "kisRealtimeWebSocketEnabled",
        "kisRealtimeWebSocketSymbols",
        "kisRealtimeWebSocketIncludeConfiguredInReasoning",
        "kisRealtimeWebSocketMaxSymbols",
        "kisRealtimeWebSocketCollectSeconds",
        "kisRealtimeWebSocketEventIntervalSeconds",
        "kisRealtimeWebSocketReconnectSeconds",
        "kisRealtimeWebSocketTimeoutSeconds",
        "kisMarketSignalsEnabled",
        "kisMarketSignalMaxSymbols",
        "kisMarketSignalCacheMinutes",
        "kisMarketSignalGapSeconds",
        "kisMarketSignalPreferLiveDuringMarketHours",
        "kisMarketSignalLiveRefreshSeconds",
        "kisMarketSignalUnchangedStaleCount",
        "notifyProvider",
        "notifyLinkUrl",
        "fxRates",
        "fairValueFormula",
        "ontologyRelationRules",
        "aiPromptTemplates",
        "aiPromptPolicy",
        "notificationAiGateEnabled",
        "notificationAiGateMessageTypes",
        "notificationAiUseCodex",
        "notificationAiModel",
        "notificationAiReasoningEffort",
        "notificationAiTimeoutSeconds",
        "notificationAiDeliveryDeadlineSeconds",
        "notificationAiAttemptWatchdogSeconds",
        "notificationAiTypeDbFallbackEnabled",
        "notificationAiFallbackOnFirstFailure",
        "notificationAiComparisonRepairReasoningEffort",
        "notificationAiComparisonRepairTimeoutSeconds",
        "notificationAiQueueWorkerCount",
        "localAiMaxConcurrentProcesses",
        "localAiInvestmentReservedProcesses",
        "localAiCapacityWaitSeconds",
        "notificationAiCapacityWaitSeconds",
        "notificationAiQueueBatchSize",
        "notificationAiQueueIntervalSeconds",
        "notificationAiQueueLeaseSeconds",
        "notificationAiQueueHeartbeatSeconds",
        "notificationAiQueueMaxAttempts",
        "notificationAiQueueRetrySeconds",
        "notificationAiQueueMaxPromptBytes",
        "notificationAiQueueRetentionHours",
        "investmentBrainMinimumHypothesisCount",
        "investmentBrainMaximumHypothesisCount",
        "investmentBrainInferenceBoxLimit",
        "investmentBrainResearchEnabled",
        "investmentBrainResearchMaxRounds",
        "investmentBrainResearchEvidenceLimit",
        "investmentBrainResearchMinimumVerifiedCount",
        "investmentBrainResearchMinimumSourceTrustState",
        "researchClaimRequireVerifiedForInvestment",
        "researchClaimOfficialVerificationEnabled",
        "researchClaimMinimumIndependentSources",
        "researchClaimCrossSourceWindowHours",
        "researchClaimSimilarityThreshold",
        "researchClaimSourceRegistry",
        "investmentBrainResearchCooldownMinutes",
        "investmentBrainOutcomeObservationMinutes",
        "investmentBrainOutcomeEpisodeBatchSize",
        "investmentBrainOutcomeMaxDelayMinutes",
        "investmentActionPlanExpiryMinutes",
        "investmentActionPlanSlicePct",
        "investmentActionPlanSliceCount",
        "investmentExecutionQuoteDriftPct",
        "investmentExecutionSnapshotMaxAgeMinutes",
        "investmentBrainNotificationResearchEnabled",
        "investmentBrainNovelHypothesisAiEnabled",
        "investmentBrainNovelHypothesisAiTimeoutSeconds",
        "modelName",
        "modelHypothesis",
        "modelTimingScenario",
        "modelTimingSymbols",
        "operatorReasoningReportEnabled",
        "alertRules",
        "alertThresholds",
        "relationRuleThresholds",
        "alertCadenceMinutes",
        "ontologyTypeDbEnabled",
        "ontologyProjectionGraphCacheEnabled",
        "ontologyProjectionGraphCacheTtlSeconds",
        "ontologyProjectionGraphCacheMaxEntries",
        "ontologyProjectionGraphPersistentCacheEnabled",
        "ontologyProjectionGraphPersistentCacheTtlSeconds",
        "ontologyProjectionGraphPersistentCacheMaxEntries",
        "ontologyProjectionGraphPersistentCacheMaxPayloadBytes",
        "ontologyDecisionEpisodeContextPerSymbolLimit",
        "ontologyDecisionEpisodeContextMaxEpisodes",
        "ontologyDecisionEpisodeContextHypothesisLimit",
        "ontologyDecisionEpisodeContextOutcomeLimit",
        "ontologyMonitorInlineProjectionEnabled",
        "ontologyReasoningEnabled",
        "ontologyReasoningIntervalSeconds",
        "ontologyReasoningBatchSize",
        "ontologyReasoningMaxSymbolsPerRun",
        "ontologyReasoningAdaptiveBatchEnabled",
        "ontologyReasoningAdaptiveBatchSteadySymbols",
        "ontologyReasoningAdaptiveBatchBurstSymbols",
        "ontologyReasoningAdaptiveBatchPendingThreshold",
        "ontologyReasoningAdaptiveBatchAgeSeconds",
        "ontologyReasoningAdaptiveBatchRuntimeGuardSeconds",
        "ontologyReasoningAdaptiveBatchBudgetSeconds",
        "ontologyReasoningAdaptiveBatchBacklogBurstEnabled",
        "ontologyReasoningAdaptiveBatchBacklogBurstAgeSeconds",
        "ontologyReasoningMailboxEnabled",
        "ontologyReasoningMailboxIngressEnabled",
        "ontologyReasoningMailboxBatchSize",
        "ontologyReasoningMailboxRetentionHours",
        "ontologyReasoningWorkLeaseSeconds",
        "ontologyReasoningWorkRetrySeconds",
        "ontologyReasoningQueueProbeCacheSeconds",
        "ontologyReasoningSourceFreshnessEnabled",
        "ontologyReasoningRealtimeEventMaxAgeMinutes",
        "ontologyReasoningResearchEventMaxAgeMinutes",
        "ontologyReasoningTelemetryHistoryLimit",
        "reasoningEngineSharedPremiseInlineRetryCount",
        "reasoningEngineSharedPremiseInlineRetryMaxSeconds",
        "typedbNativeRuleTargetSymbolLimit",
        "typedbNativeRuleTargetParallelism",
        "typedbNativeRuleSubjectFanoutEnabled",
        "typedbNativeRuleSubjectParallelism",
        "typedbNativeRuleTotalReadParallelism",
        "typedbNativeRuleTargetWorkShardingEnabled",
        "typedbNativeRuleAdaptiveTargetShardingEnabled",
        "typedbNativeRuleAdaptiveTargetShardingLookbackRuns",
        "typedbNativeRuleAdaptiveTargetShardingParallelism",
        "typedbNativeRuleSelectionEnabled",
        "typedbIncrementalEquivalenceAuditSamplePct",
        "typedbNativeRuleParallelism",
        "typedbNativeRuleExecutionBudgetSeconds",
        "ontologyReasoningMinIntervalSeconds",
        "ontologyReasoningUrgentMinIntervalSeconds",
        "ontologyReasoningCriticalMinIntervalSeconds",
        "ontologyReasoningMarketMinIntervalSeconds",
        "ontologyReasoningResearchMinIntervalSeconds",
        "ontologyReasoningObservationFollowupTargetLimit",
        "ontologyReasoningVerifiedSnapshotFastDrainEnabled",
        "ontologyReasoningBacklogDrainNoCooldownEnabled",
        "ontologyReasoningBacklogDrainNoCooldownAgeSeconds",
        "ontologyReasoningProjectionRetrySeconds",
        "ontologyProjectionCircuitProbeRetrySeconds",
        "ontologyReasoningBackpressureEnabled",
        "ontologyReasoningBackpressureFactor",
        "ontologyReasoningBackpressureMaxSeconds",
        "ontologyReasoningFairnessMaxWaitSeconds",
        "ontologyReasoningFairnessDrainEnabled",
        "ontologyReasoningFairnessDrainMinIntervalSeconds",
        "ontologyReasoningProcessIsolationEnabled",
        "ontologyReasoningPersistentWorkerEnabled",
        "ontologyReasoningExecutionTimeoutSeconds",
        "ontologyReasoningExecutionTimeoutGraceSeconds",
        "ontologyReasoningExecutionTimeoutBackoffSeconds",
        "ontologyReasoningPreNativeTimeoutBackoffSeconds",
        "ontologyReasoningQueueAlertEnabled",
        "ontologyReasoningQueueWarningAgeMinutes",
        "ontologyReasoningQueueCriticalAgeMinutes",
        "ontologyReasoningQueueWarningPendingCount",
        "ontologyReasoningQueueCriticalPendingCount",
        "ontologyReasoningQueueWarningOverdueSymbols",
        "ontologyReasoningQueueCriticalOverdueSymbols",
        "ontologyReasoningQueueConsecutiveObservations",
        "ontologyReasoningQueueNoProgressMinutes",
        "ontologyReasoningQueueAlertReminderMinutes",
        "investmentAlertCoverageEnabled",
        "investmentAlertCoverageReconcileSeconds",
        "investmentAlertCoverageLookbackHours",
        "investmentAlertCoverageDeadlineSeconds",
        "investmentAlertCoverageStarvationMinCandidates",
        "investmentAlertCoverageConsecutiveObservations",
        "investmentAlertCoverageReminderMinutes",
        "ontologyProjectionAuditStaleAfterSeconds",
        "ontologyReasoningMaintenanceEnabled",
        "ontologyReasoningMaintenanceIntervalSeconds",
        "ontologyAboxMaintenanceEnabled",
        "ontologyAboxMaintenanceIntervalSeconds",
        "ontologyAboxMaintenanceWorldTypes",
        "ontologyAboxMaintenanceMaxManifestsPerRun",
        "ontologyAboxMaintenanceMaxDeleteBatchesPerRun",
        "ontologyAboxMaintenanceDeleteBatchSize",
        "ontologyAboxMaintenanceKeepInactiveManifestCount",
        "ontologyAboxMaintenanceWarningInactiveManifestCount",
        "ontologyAboxMaintenanceCriticalInactiveManifestCount",
        "ontologyAboxMaintenanceAdaptiveDrainEnabled",
        "ontologyAboxMaintenanceAdaptiveDrainMaxDeleteBatchesPerRun",
        "ontologyAboxMaintenanceAdaptiveDrainCriticalRunsBeforeIncrease",
        "ontologyAboxMaintenanceProcessIsolationEnabled",
        "ontologyAboxMaintenanceExecutionTimeoutSeconds",
        "ontologyAboxMaintenanceExecutionTimeoutGraceSeconds",
        "ontologyAboxMaintenanceExecutionReserveSeconds",
        "ontologyAboxMaintenanceSliceSeconds",
        "ontologyAboxMaintenanceEstimatedDeleteBatchSeconds",
        "ontologyAboxMaintenanceMaxReasoningDeferralSeconds",
        "ontologyAboxMaintenanceBusyRetrySeconds",
        "ontologyAboxMaintenancePriorityInactiveManifestCount",
        "ontologyAboxMaintenanceYieldEnabled",
        "ontologyAboxMaintenanceYieldAfterSeconds",
        "ontologyAboxMaintenanceYieldWindowSeconds",
        "ontologyAboxMaintenanceYieldRequestTtlSeconds",
        "ontologyAboxMaintenanceYieldCooldownSeconds",
        "ontologyAboxMaintenanceYieldInventoryMaxAgeSeconds",
        "ontologyWorldProjectionDeferWhenReasoningPending",
        "ontologyInferenceDetailOutboxEnabled",
        "ontologyInferenceDetailIntervalSeconds",
        "ontologyInferenceDetailBatchSize",
        "ontologyInferenceDetailLeaseSeconds",
        "ontologyInferenceDetailDeferWhenReasoningPending",
        "ontologyInferenceDetailMaxAttempts",
        "ontologyInferenceDetailExecutionTimeoutSeconds",
        "ontologyInferenceDetailExecutionTimeoutGraceSeconds",
        "ontologyInferenceDetailProcessIsolationEnabled",
        "ontologyInferenceDetailCompletedRetentionHours",
        "ontologyInferenceDetailMaxResultBytes",
        "ontologyAboxMaintenanceDeferWhenReasoningPending",
        "ontologyRuntimeProjectionSloSeconds",
        "ontologyRuntimeInferenceSloSeconds",
        "ontologyRuntimeSloConsecutiveBreachCount",
        "ontologyRuntimeAuditWindowRuns",
        "ontologyScopeIntegrityAuditEnabled",
        "ontologyScopeIntegrityAuditIntervalMinutes",
        "ontologyScopeIntegrityAuditBatchSize",
        "ontologyScopeRepairRetryMinutes",
        "ontologyScopeRepairVerificationMinutes",
        "ontologyAboxMaintenanceAdaptiveDrainBacklogGrowthRunsBeforeIncrease",
        "ontologyAboxMaintenanceAdaptiveDrainMaxConsecutiveWorldRuns",
        "ontologyReasoningUrgentReviewLevels",
        "temporalWindowPeriods",
        "temporalWindowHistoryLimit",
        "ontologyLabAutoApplyEnabled",
        "ontologyLabAutoApplyValidationStates",
        "ontologyLabAutoApplyNeedsReviewEnabled",
        "ontologyLabNotifyEnabled",
        "ontologyRuleCandidateAiEnabled",
        "ontologyRuleCandidateAiUseCodex",
        "ontologyRuleCandidateAiCommand",
        "ontologyRuleCandidateAiTimeoutSeconds",
        "ontologyRuleCandidateAiIntervalMinutes",
        "ontologyRuleCandidateAiMaxCandidates",
        "ontologyTenantId",
        "ontologySharedMarketTenantId",
        "ontologySharedMarketWorldRetentionHours",
        "ontologySharedMarketWorldMaxSymbols",
        "ontologySharedMarketWorldAsyncProjectionEnabled",
        "materialityGateEnabled",
        "marketMaterialityPriceChangePct",
        "marketMaterialityTrendDistancePct",
        "marketMaterialityTrendDistanceChangePct",
        "marketMaterialityVolumeRatio",
        "marketMaterialityInvestorFlowRatioPct",
        "marketSignalTransitionPolicyEnabled",
        "marketSignalPersistenceObservations",
        "marketSignalPricePersistenceObservations",
        "marketSignalPriceResetPct",
        "marketSignalPriceImmediatePct",
        "marketSignalOrderbookEnterPct",
        "marketSignalOrderbookExitPct",
        "marketSignalTradeStrengthBand",
        "marketSignalTradeStrengthExitBand",
        "marketSignalVolumeEnterRatio",
        "marketSignalVolumeExitRatio",
        "marketSignalInvestorFlowExitPct",
        "marketSignalTrendCrossBufferPct",
        "marketSignalTrendCrossExitPct",
        "marketSignalTrendDistanceExitPct",
        "marketSignalDataStatePersistenceObservations",
        "typedbAddress",
        "typedbUser",
        "typedbAllowDefaultPassword",
        "typedbDatabase",
        "typedbTlsEnabled",
        "typedbTimeoutSeconds",
        "typedbRetryCount",
        "typedbPersistentDriverEnabled",
        "typedbProjectionCoordinatorEnabled",
        "typedbProjectionCoordinatorLeaseSeconds",
        "typedbProjectionCoordinatorRetrySeconds",
        "typedbStaticNodeBatchSize",
        "typedbStaticWriteTransactionQueryCount",
        "symbolUniverseMaxAgeHours",
        "typedbInferenceGenerationKeepCount",
        "typedbAutoResetEnabled",
        "typedbAgeResetEnabled",
        "typedbDataRetentionHours",
        "typedbDataMaxSizeMb",
        "typedbMinimumFreeSpaceMb",
        "typedbCapacityGuardCheckIntervalSeconds",
        "typedbCapacityGuardStaleSeconds",
        "typedbCapacitySharedSampleMaxAgeSeconds",
        "typedbCapacityThrottlePercent",
        "typedbCapacityAutoRotateEnabled",
        "typedbCapacityProactiveRotatePercent",
        "typedbCapacityAutoRotatePercent",
        "typedbCapacityAutoRotateFreeSpaceMb",
        "typedbCapacityCriticalPercent",
        "typedbCapacityAutoRotateCooldownMinutes",
        "typedbCapacityAutoRotateFailureRetrySeconds",
        "typedbBlueGreenMinimumHeadroomMb",
        "typedbBlueGreenEstimatedCandidateMaxMb",
        "typedbCapacityMaintenanceMaxManifests",
        "typedbCapacityMaintenanceMaxDeleteBatches",
        "typedbCapacityMaintenanceDeleteBatchSize",
        "typedbStartupWaitSeconds",
        "externalApiFetchIntervalMinutes",
        "externalAlphaEnabled",
        "externalAlphaDailyRequestBudget",
        "externalAlphaQuotaCooldownMinutes",
        "externalAlphaFundamentalsEnabled",
        "externalAlphaFundamentalsMaxSymbols",
        "externalYFinanceEnabled",
        "externalYFinanceMaxSymbols",
        "externalYFinanceHistoryPeriod",
        "externalYFinanceHistoryInterval",
        "externalYFinanceHistoryRows",
        "externalYFinanceFinancialPeriods",
        "externalYFinanceTabularRows",
        "externalYFinanceOptionExpirations",
        "externalYFinanceOptionsMaxRows",
        "externalYFinanceEarningsLimit",
        "externalYFinanceNewsLimit",
        "externalYFinancePriceMaxAgeMinutes",
        "externalYFinanceOptionsMaxAgeMinutes",
        "externalYFinanceNewsMaxAgeMinutes",
        "externalYFinanceAnalystMaxAgeMinutes",
        "externalYFinanceFundamentalMaxAgeMinutes",
        "externalCoinGeckoEnabled",
        "externalCoinGeckoFetchIntervalMinutes",
        "externalFredEnabled",
        "externalFredSeries",
        "externalFredTimeoutSeconds",
        "externalCryptoIds",
        "externalAlphaMaxSymbols",
        "externalSecEnabled",
        "externalSecMaxSymbols",
        "externalSecCompanyCiks",
        "externalSecContactEmail",
        "externalSecUserAgent",
        "externalSecDocumentTextEnabled",
        "externalSecDocumentTextMaxChars",
        "externalDartEnabled",
        "externalDartLookbackDays",
        "externalDartCorpCodes",
        "externalDartCompanyFundamentalsEnabled",
        "externalDartDocumentTextEnabled",
        "externalDartDocumentTextMaxChars",
        "externalDartDocumentMaxPerSymbol",
        "externalNewsEnabled",
        "externalNewsProvider",
        "externalNewsMaxSymbols",
        "externalNewsLookbackHours",
        "externalResearchEvidenceMaxItems",
        "newsCollectionEnabled",
        "newsCollectionIntervalSeconds",
        "newsCollectionRunBudgetSeconds",
        "newsCollectionMaxSymbols",
        "newsCollectionLookbackMinutes",
        "newsCollectionPerSymbolLimit",
        "newsCollectionProviders",
        "newsCollectionInternationalProviders",
        "newsCollectionKoreanProviders",
        "newsCollectionBoundedParallelEnabled",
        "newsCollectionProviderParallelism",
        "newsCollectionPrimaryProviderCount",
        "newsCollectionPrimaryMinimumItems",
        "newsCollectionGoogleKrEnabled",
        "newsCollectionGoogleUsEnabled",
        "newsCollectionYahooSearchEnabled",
        "newsCollectionYahooRssEnabled",
        "newsCollectionGdeltSyncEnabled",
        "newsCollectionGoogleOriginalUrlResolveEnabled",
        "newsCollectionGoogleOriginalUrlMaxPerTarget",
        "newsCollectionGoogleOriginalUrlMaxPerRun",
        "newsCollectionArticleBodyMinimumChars",
        "newsCollectionArticleBodyCacheMinutes",
        "newsCollectionArticleBodyFailureCacheMinutes",
        "newsCollectionArticleBodyCacheMaxEntries",
        "newsCollectionQualityGateEnabled",
        "newsCollectionMinimumRelevanceState",
        "newsCollectionMinimumMaterialityState",
        "newsCollectionMinimumSourceTrustState",
        "newsCollectionRequireArticleBody",
        "newsDigestMinimumRelevanceState",
        "newsDigestMinimumMaterialityState",
        "newsDigestMinimumNeutralMaterialityState",
        "newsDigestMinimumSourceTrustState",
        "newsDigestRequireKoreanTitleTranslation",
        "newsCollectionRequireArticleBodyForRss",
        "newsCollectionIncludeWatchlist",
        "newsCollectionIncludeHoldings",
        "newsCollectionRateLimitSeconds",
        "newsEvidenceCleanupEnabled",
        "newsEvidenceMaxAgeMinutes",
        "newsEvidenceCleanupBatchSize",
        "newsEvidenceCleanupIntervalSeconds",
        "newsEvidenceKeepUndated",
        "researchEvidenceWriteBatchSize",
        "mysqlDeadlockRetryCount",
        "mysqlDeadlockRetryBaseMilliseconds",
        "mysqlDeadlockRetryMaxMilliseconds",
        "newsArticleBodyFailureWarnRate",
        "newsArticleBodyFailureMinimumCount",
        "dataPipelineHealthDeteriorationConsecutiveRuns",
        "dataPipelineHealthRecoveryConsecutiveRuns",
        "dataPipelineHealthFailureConsecutiveRuns",
        "dataPipelineHealthNormalConsecutiveRuns",
        "newsAiAnalysisEnabled",
        "newsAiAnalysisUseCodex",
        "newsAiAnalysisCommand",
        "newsAiAnalysisTimeoutSeconds",
        "newsAiAnalysisInlineTimeoutSeconds",
        "newsAiAnalysisInlineEnabled",
        "newsAiAnalysisAsyncEnabled",
        "newsAiAnalysisWorkerIntervalSeconds",
        "newsAiAnalysisWorkerBatchSize",
        "newsAiAnalysisWorkerScanLimit",
        "newsAiAnalysisRetryMinutes",
        "researchClaimCorpusLimit",
        "investmentCalendarEnabled",
        "investmentCalendarIntervalSeconds",
        "investmentCalendarDefaultWindowDays",
        "investmentCalendarReminderLookbackMinutes",
        "investmentCalendarAutoExtractEnabled",
        "investmentCalendarAutoExtractRegisterUndated",
        "investmentCalendarAutoExtractReviewEnabled",
        "investmentCalendarCandidateDefaultTime",
        "investmentCalendarAiResearchEnabled",
        "investmentCalendarAiResearchRunCollection",
        "investmentCalendarAiResearchEvidenceLimit",
        "investmentCalendarAiResearchCandidateLimit",
        "investmentCalendarDiscoveryEnabled",
        "investmentCalendarDiscoveryIntervalHours",
        "investmentCalendarDiscoveryMaxSymbols",
        "investmentCalendarDiscoveryHorizonDays",
        "investmentCalendarOfficialMacroSyncEnabled",
        "investmentCalendarOfficialMacroSyncIntervalHours",
        "investmentCalendarOfficialMacroSyncRateLimitSeconds",
        "investmentCalendarOfficialMacroSyncTimeoutSeconds",
        "investmentCalendarOfficialEarningsSyncEnabled",
        "investmentCalendarOfficialEarningsLookbackDays",
        "investmentCalendarOfficialEarningsMaxSymbols",
        "investmentCalendarOfficialEarningsRateLimitSeconds",
        "investmentCalendarBokPolicyDecisionEnabled",
        "investmentCalendarBokPolicyDecisionTimeKst",
        "investmentCalendarBokPolicyDecisionLookaheadYears",
        "investmentCalendarFedFomcEnabled",
        "investmentCalendarFedDecisionTimeEt",
        "investmentCalendarBlsMacroEnabled",
        "investmentCalendarBlsFredFallbackEnabled",
        "investmentCalendarBeaMacroEnabled",
        "dartDisclosureAiAnalysisEnabled",
        "dartDisclosureAiUseCodex",
        "dartDisclosureAiCommand",
        "dartDisclosureAiTimeoutSeconds",
        "notificationQueueIntervalSeconds",
        "notificationQueueBatchSize",
        "notificationSendGapSeconds",
        "notificationProcessingStaleMinutes",
        "monitorAccountQueueEnabled",
        "monitorAccountIntervalSeconds",
        "monitorAccountBatchSize",
        "monitorAccountLockSeconds",
        "marketObservationRawDeliveryMode",
        "marketObservationImmediatePriceChangePct",
        "marketObservationImmediateCadenceMinutes",
        "marketDataMaxAgeMinutes",
        "marketSignalDataCollectionEnabled",
        "marketSignalDataBatchSize",
        "dataFreshnessEnabled",
        "newsDigestFreshnessGateEnabled",
        "dataFreshnessNewsDigestMaxAgeMinutes",
        "dataFreshnessDefaultMaxAgeMinutes",
        "dataFreshnessQuoteMaxAgeMinutes",
        "dataFreshnessKisPriceMaxAgeMinutes",
        "dataFreshnessKisMicrostructureMaxAgeMinutes",
        "dataFreshnessKisInvestorMaxAgeMinutes",
        "dataFreshnessExternalMaxAgeMinutes",
        "dataFreshnessExternalEquityMaxAgeMinutes",
        "dataFreshnessExternalCryptoMaxAgeMinutes",
        "dataFreshnessMacroMaxAgeMinutes",
        "dataFreshnessDisclosureMaxAgeMinutes",
        "externalSignalCacheMaxAgeMinutes",
        "externalPublicDataStockEnabled",
        "externalPublicDataReferenceEnabled",
        "externalPublicDataTimeoutSeconds",
        "externalDataPublicStockCadenceSeconds",
        "externalDataPublicStockFreshnessSeconds",
        "externalDataPublicStockMaxPartitions",
        "externalDataPublicReferenceCadenceSeconds",
        "externalDataPublicReferenceFreshnessSeconds",
        "externalDataPublicReferenceMaxPartitions",
        "aiValuationAutoProposalEnabled",
        "aiValuationCurrentPriceAnchorEnabled",
        "valuationReviewOverrides",
        "aiValuationPreferredParValue",
        "aiValuationPreferredRiskSpreadPct",
        "aiValuationPreferredRequiredYieldPct",
        "aiValuationPreferredMinimumMarginPct",
        "aiValuationBaselineMinimumMarginPct",
    ]
    public = {key: settings.get(key, "") for key in public_keys}
    public.update({
        "tossClientId": "",
        "tossClientSecret": "",
        "tossAccountSeq": "",
        "kisAppKey": "",
        "kisAppSecret": "",
        "telegramBotToken": "",
        "telegramChatId": "",
        "operationsTelegramBotToken": "",
        "operationsTelegramChatId": "",
        "alphaVantageApiKey": "",
        "coingeckoApiKey": "",
        "fredApiKey": "",
        "opendartApiKey": "",
        "publicDataPortalServiceKey": "",
        "typedbPassword": "",
        "mysqlPassword": "",
    })
    for optional_key in ["valuationAssumptions", "marketSignalInputs"]:
        if configured(settings.get(optional_key)):
            public[optional_key] = settings[optional_key]
    resolved_access = access or (anonymous_access() if share_mode_enabled() else local_owner_access())
    return {
        "settings": public,
        "notificationAiPromptRelease": prompt_release,
        "configured": {
            "tossClientId": bool(settings.get("tossClientId")),
            "tossClientSecret": bool(settings.get("tossClientSecret")),
            "tossAccountSeq": bool(settings.get("tossAccountSeq")),
            "kisAppKey": bool(settings.get("kisAppKey")),
            "kisAppSecret": bool(settings.get("kisAppSecret")),
            "telegramBotToken": bool(settings.get("telegramBotToken")),
            "telegramChatId": bool(settings.get("telegramChatId")),
            "operationsTelegramBotToken": bool(settings.get("operationsTelegramBotToken")),
            "operationsTelegramChatId": bool(settings.get("operationsTelegramChatId")),
            "alphaVantageApiKey": bool(settings.get("alphaVantageApiKey")),
            "coingeckoApiKey": bool(settings.get("coingeckoApiKey")),
            "fredApiKey": bool(settings.get("fredApiKey")),
            "opendartApiKey": bool(settings.get("opendartApiKey")),
            "publicDataPortalServiceKey": bool(settings.get("publicDataPortalServiceKey")),
            "externalSecContactEmail": sec_metadata_access_ready(settings),
            "externalSecUserAgent": bool(
                settings.get("externalSecUserAgent")
                and "local-contact" not in str(settings.get("externalSecUserAgent")).lower()
            ),
            "typedbAddress": bool(settings.get("typedbAddress")),
            "typedbPassword": bool(settings.get("typedbPassword")),
            "mysqlPassword": bool(settings.get("mysqlPassword")),
        },
        "locked": bool(resolved_access.shared and not resolved_access.writable),
        "shareAccess": resolved_access.to_public_dict(),
        "shareRuntime": share_runtime_status_payload(resolved_access, settings),
        "runtimeIdentity": {
            **runtime_identity(),
            "startedAt": WEB_PROCESS_STARTED_AT,
        },
    }


def save_settings_payload(payload: Dict[str, object], access: ShareAccess = None) -> Dict[str, object]:
    requested = payload.get("settings") if isinstance(payload.get("settings"), dict) else payload
    previous = runtime_settings()
    saved = save_runtime_settings(requested if isinstance(requested, dict) else {})
    recovery = ExternalDataConfigurationRecoveryService(
        stores.external_data_store(saved)
    ).recover(previous, saved)
    status = settings_status_payload(access)
    status["externalDataRecovery"] = recovery
    new_domain_event(
        SETTINGS_UPDATED,
        "runtime",
        {
            "keys": sorted([str(key) for key in (requested or {}).keys()]) if isinstance(requested, dict) else [],
            "configured": status.get("configured") or {},
            "externalDataRecovery": recovery,
        },
    )
    return status
