"""Explicit, lazy contracts surface for the model_registry module."""

from digital_twin.modules._exports import resolve_export


_EXPORTS = {'MODEL_REVIEW_PROMPT_VERSION': ('digital_twin.modules.model_registry.domain.model_review',
                                 'MODEL_REVIEW_PROMPT_VERSION'),
 'ModelReviewJob': ('digital_twin.modules.model_registry.domain.model_review', 'ModelReviewJob')}

_EXPORTS['HypothesisLifecycleRepository'] = ('digital_twin.modules.model_registry.domain.repositories', 'HypothesisLifecycleRepository')


_EXPORTS.update({
    'observation_requirements': ('digital_twin.modules.model_registry.domain.experiment_observations', 'observation_requirements'),
    'ACCOUNT_FIELDS': ('digital_twin.modules.model_registry.domain.hypothesis_scoping', 'ACCOUNT_FIELDS'),
    'ACCOUNT_ONLY_SCOPE': ('digital_twin.modules.model_registry.domain.hypothesis_scoping', 'ACCOUNT_ONLY_SCOPE'),
    'AI_PROMPT_REGISTRY_VERSION': ('digital_twin.modules.model_registry.domain.ontology_relation_contracts', 'AI_PROMPT_REGISTRY_VERSION'),
    'ASSESSMENT_SCOPES': ('digital_twin.modules.model_registry.domain.ontology_rule_manifest', 'ASSESSMENT_SCOPES'),
    'BOUNDED_CONTEXTS': ('digital_twin.modules.model_registry.domain.ontology_tbox', 'BOUNDED_CONTEXTS'),
    'BTC_SENSITIVE_SYMBOLS': ('digital_twin.modules.model_registry.domain.ontology_relation_contracts', 'BTC_SENSITIVE_SYMBOLS'),
    'CAPITAL_FLOW_SHADOW_RELEASE_ID': ('digital_twin.modules.model_registry.domain.statistical_signals.registry', 'CAPITAL_FLOW_SHADOW_RELEASE_ID'),
    'CLASS_DEFS': ('digital_twin.modules.model_registry.domain.ontology_tbox', 'CLASS_DEFS'),
    'DEFAULT_AUTHORED_THESIS_SIGNAL_RELEASE_ID': ('digital_twin.modules.model_registry.domain.statistical_signals.registry', 'DEFAULT_AUTHORED_THESIS_SIGNAL_RELEASE_ID'),
    'DEFAULT_CROSS_ASSET_SIGNAL_RELEASE_ID': ('digital_twin.modules.model_registry.domain.statistical_signals.registry', 'DEFAULT_CROSS_ASSET_SIGNAL_RELEASE_ID'),
    'DEFAULT_EVENT_SIGNAL_RELEASE_ID': ('digital_twin.modules.model_registry.domain.statistical_signals.registry', 'DEFAULT_EVENT_SIGNAL_RELEASE_ID'),
    'DEFAULT_FLOW_SIGNAL_RELEASE_ID': ('digital_twin.modules.model_registry.domain.statistical_signals.registry', 'DEFAULT_FLOW_SIGNAL_RELEASE_ID'),
    'DEFAULT_PRICE_SIGNAL_RELEASE_ID': ('digital_twin.modules.model_registry.domain.statistical_signals.registry', 'DEFAULT_PRICE_SIGNAL_RELEASE_ID'),
    'DEFAULT_PROMPT_TEMPLATES': ('digital_twin.modules.model_registry.domain.ontology_prompt_registry', 'DEFAULT_PROMPT_TEMPLATES'),
    'DEFAULT_RELATION_THRESHOLDS': ('digital_twin.modules.model_registry.domain.ontology_relation_contracts', 'DEFAULT_RELATION_THRESHOLDS'),
    'DEFAULT_VALUATION_SIGNAL_RELEASE_ID': ('digital_twin.modules.model_registry.domain.statistical_signals.registry', 'DEFAULT_VALUATION_SIGNAL_RELEASE_ID'),
    'DecisionStageDefinition': ('digital_twin.modules.model_registry.domain.ontology_relation_contracts', 'DecisionStageDefinition'),
    'GRAPH_REASONER_VERSION': ('digital_twin.modules.model_registry.domain.ontology_rulebox_contracts', 'GRAPH_REASONER_VERSION'),
    'GraphInferenceRule': ('digital_twin.modules.model_registry.domain.ontology_rulebox_contracts', 'GraphInferenceRule'),
    'GraphRuleCondition': ('digital_twin.modules.model_registry.domain.ontology_rulebox_contracts', 'GraphRuleCondition'),
    'GraphRuleDerivation': ('digital_twin.modules.model_registry.domain.ontology_rulebox_contracts', 'GraphRuleDerivation'),
    'HOLDING_TARGET_ROLE': ('digital_twin.modules.model_registry.domain.ontology_rulebox_contracts', 'HOLDING_TARGET_ROLE'),
    'HYPOTHESIS_LIFECYCLE_KEY_PREFIX': ('digital_twin.modules.model_registry.domain.hypothesis_lifecycle', 'HYPOTHESIS_LIFECYCLE_KEY_PREFIX'),
    'HYPOTHESIS_LIFECYCLE_KEY_VERSION': ('digital_twin.modules.model_registry.domain.hypothesis_lifecycle', 'HYPOTHESIS_LIFECYCLE_KEY_VERSION'),
    'HYPOTHESIS_LIFECYCLE_STATE_LABELS': ('digital_twin.modules.model_registry.domain.hypothesis_lifecycle', 'HYPOTHESIS_LIFECYCLE_STATE_LABELS'),
    'HYPOTHESIS_LIFECYCLE_VERSION': ('digital_twin.modules.model_registry.domain.hypothesis_lifecycle', 'HYPOTHESIS_LIFECYCLE_VERSION'),
    'HYPOTHESIS_SCOPE_VERSION': ('digital_twin.modules.model_registry.domain.hypothesis_scoping', 'HYPOTHESIS_SCOPE_VERSION'),
    'HypothesisLifecyclePolicy': ('digital_twin.modules.model_registry.domain.ontology_rulebox_contracts', 'HypothesisLifecyclePolicy'),
    'HypothesisLifecycleRecord': ('digital_twin.modules.model_registry.domain.hypothesis_lifecycle', 'HypothesisLifecycleRecord'),
    'HypothesisLifecycleSnapshot': ('digital_twin.modules.model_registry.domain.hypothesis_lifecycle', 'HypothesisLifecycleSnapshot'),
    'MARKET_SHARED_SCOPE': ('digital_twin.modules.model_registry.domain.hypothesis_scoping', 'MARKET_SHARED_SCOPE'),
    'MIXED_SCOPE': ('digital_twin.modules.model_registry.domain.hypothesis_scoping', 'MIXED_SCOPE'),
    'MODEL_SIGNAL_BRIDGE_VERSION': ('digital_twin.modules.model_registry.domain.model_signal_interpretation', 'MODEL_SIGNAL_BRIDGE_VERSION'),
    'MODEL_SIGNAL_CONTRACT_VERSION': ('digital_twin.modules.model_registry.domain.statistical_signals.contracts', 'MODEL_SIGNAL_CONTRACT_VERSION'),
    'ModelSignal': ('digital_twin.modules.model_registry.domain.statistical_signals.contracts', 'ModelSignal'),
    'ModelSignalBundle': ('digital_twin.modules.model_registry.domain.statistical_signals.contracts', 'ModelSignalBundle'),
    'ModelSignalOutcome': ('digital_twin.modules.model_registry.domain.statistical_signals.evaluation', 'ModelSignalOutcome'),
    'ONTOLOGY_DOMAIN_TBOX_VERSION': ('digital_twin.modules.model_registry.domain.ontology_domain_tbox', 'ONTOLOGY_DOMAIN_TBOX_VERSION'),
    'ONTOLOGY_RULE_ENGINE_VERSION': ('digital_twin.modules.model_registry.domain.ontology_relation_contracts', 'ONTOLOGY_RULE_ENGINE_VERSION'),
    'OntologyPromptTemplate': ('digital_twin.modules.model_registry.domain.ontology_relation_contracts', 'OntologyPromptTemplate'),
    'OntologyRuleMatch': ('digital_twin.modules.model_registry.domain.ontology_relation_contracts', 'OntologyRuleMatch'),
    'RELATION_DEFS': ('digital_twin.modules.model_registry.domain.ontology_tbox', 'RELATION_DEFS'),
    'RULEBOX_RELEASE_MANIFEST_VERSION': ('digital_twin.modules.model_registry.domain.ontology_rulebox_release_manifest', 'RULEBOX_RELEASE_MANIFEST_VERSION'),
    'RULE_EXECUTION_POLICY_VERSION': ('digital_twin.modules.model_registry.domain.ontology_rule_execution_policy', 'RULE_EXECUTION_POLICY_VERSION'),
    'RelationRuleDefinition': ('digital_twin.modules.model_registry.domain.ontology_relation_contracts', 'RelationRuleDefinition'),
    'RuleClaimContract': ('digital_twin.modules.model_registry.domain.rule_claim_contract', 'RuleClaimContract'),
    'SYSTEM_SAFETY_SCOPE': ('digital_twin.modules.model_registry.domain.hypothesis_scoping', 'SYSTEM_SAFETY_SCOPE'),
    'TBOX_CLASSES': ('digital_twin.modules.model_registry.domain.ontology_tbox', 'TBOX_CLASSES'),
    'TBOX_REASONING_RULES': ('digital_twin.modules.model_registry.domain.ontology_tbox', 'TBOX_REASONING_RULES'),
    'TBOX_RELATION_TYPES': ('digital_twin.modules.model_registry.domain.ontology_tbox', 'TBOX_RELATION_TYPES'),
    'TERMINAL_HYPOTHESIS_LIFECYCLE_STATES': ('digital_twin.modules.model_registry.domain.hypothesis_lifecycle', 'TERMINAL_HYPOTHESIS_LIFECYCLE_STATES'),
    'UNVERIFIED_SCOPE': ('digital_twin.modules.model_registry.domain.hypothesis_scoping', 'UNVERIFIED_SCOPE'),
    'WATCHLIST_ACTION_POLICY': ('digital_twin.modules.model_registry.domain.ontology_rulebox_contracts', 'WATCHLIST_ACTION_POLICY'),
    'WATCHLIST_ALLOWED_ACTIONS': ('digital_twin.modules.model_registry.domain.ontology_rulebox_contracts', 'WATCHLIST_ALLOWED_ACTIONS'),
    'WATCHLIST_BLOCKED_ACTIONS': ('digital_twin.modules.model_registry.domain.ontology_rulebox_contracts', 'WATCHLIST_BLOCKED_ACTIONS'),
    'WATCHLIST_TARGET_ROLE': ('digital_twin.modules.model_registry.domain.ontology_rulebox_contracts', 'WATCHLIST_TARGET_ROLE'),
    '_thresholds': ('digital_twin.modules.model_registry.domain.ontology_relation_settings', '_thresholds'),
    'authored_outcome_contract_complete': ('digital_twin.modules.model_registry.domain.rule_claim_contract', 'authored_outcome_contract_complete'),
    'bounded_contexts_payload': ('digital_twin.modules.model_registry.domain.ontology_tbox', 'bounded_contexts_payload'),
    'class_definitions_payload': ('digital_twin.modules.model_registry.domain.ontology_tbox', 'class_definitions_payload'),
    'condition_scope_profile': ('digital_twin.modules.model_registry.domain.hypothesis_scoping', 'condition_scope_profile'),
    'decision_stage_from_relation': ('digital_twin.modules.model_registry.domain.ontology_relation_decisions', 'decision_stage_from_relation'),
    'default_ai_prompt_policy_text': ('digital_twin.modules.model_registry.domain.ontology_prompt_registry', 'default_ai_prompt_policy_text'),
    'default_ai_prompt_templates_text': ('digital_twin.modules.model_registry.domain.ontology_prompt_registry', 'default_ai_prompt_templates_text'),
    'default_graph_inference_rules': ('digital_twin.modules.model_registry.domain.ontology_rulebox_catalog', 'default_graph_inference_rules'),
    'default_ontology_relation_reasoning_text': ('digital_twin.modules.model_registry.domain.ontology_prompt_registry', 'default_ontology_relation_reasoning_text'),
    'default_ontology_threshold_policy': ('digital_twin.modules.model_registry.domain.ontology_threshold_policy', 'default_ontology_threshold_policy'),
    'governed_graph_inference_rules': ('digital_twin.modules.model_registry.domain.ontology_rulebox_catalog', 'governed_graph_inference_rules'),
    'has_material_delta': ('digital_twin.modules.model_registry.domain.hypothesis_lifecycle', 'has_material_delta'),
    'hypothesis_family_definition': ('digital_twin.modules.model_registry.domain.hypothesis_catalog', 'hypothesis_family_definition'),
    'hypothesis_lifecycle_transitioned_event': ('digital_twin.modules.model_registry.domain.events', 'hypothesis_lifecycle_transitioned_event'),
    'hypothesis_qualification': ('digital_twin.modules.model_registry.domain.rule_claim_contract', 'hypothesis_qualification'),
    'inference_scope_assessment': ('digital_twin.modules.model_registry.domain.hypothesis_scoping', 'inference_scope_assessment'),
    'investment_archetype_label': ('digital_twin.modules.model_registry.domain.investment_ubiquitous_language', 'investment_archetype_label'),
    'investment_archetype_labels': ('digital_twin.modules.model_registry.domain.investment_ubiquitous_language', 'investment_archetype_labels'),
    'investment_language_registry': ('digital_twin.modules.model_registry.domain.investment_ubiquitous_language', 'investment_language_registry'),
    'is_batchable_model_signal_interpretation_rule': ('digital_twin.modules.model_registry.domain.model_signal_interpretation', 'is_batchable_model_signal_interpretation_rule'),
    'is_model_signal_interpretation_rule': ('digital_twin.modules.model_registry.domain.model_signal_interpretation', 'is_model_signal_interpretation_rule'),
    'knowledge_basis_summary': ('digital_twin.modules.model_registry.domain.ontology_rule_knowledge', 'knowledge_basis_summary'),
    'lifecycle_context_summary': ('digital_twin.modules.model_registry.domain.hypothesis_lifecycle', 'lifecycle_context_summary'),
    'lifecycle_key_for_hypothesis': ('digital_twin.modules.model_registry.domain.hypothesis_lifecycle', 'lifecycle_key_for_hypothesis'),
    'lifecycle_snapshots_from_relation_context': ('digital_twin.modules.model_registry.domain.hypothesis_lifecycle', 'lifecycle_snapshots_from_relation_context'),
    'material_delta_values': ('digital_twin.modules.model_registry.domain.hypothesis_lifecycle', 'material_delta_values'),
    'model_registry_payload': ('digital_twin.modules.model_registry.domain.statistical_signals.registry', 'model_registry_payload'),
    'model_release': ('digital_twin.modules.model_registry.domain.statistical_signals.registry', 'model_release'),
    'model_signal_bridge_conditions': ('digital_twin.modules.model_registry.domain.model_signal_interpretation', 'model_signal_bridge_conditions'),
    'model_signal_bridge_source_scope': ('digital_twin.modules.model_registry.domain.model_signal_interpretation', 'model_signal_bridge_source_scope'),
    'model_signal_conditions': ('digital_twin.modules.model_registry.domain.model_signal_interpretation', 'model_signal_conditions'),
    'model_signal_interpretation_contract_id': ('digital_twin.modules.model_registry.domain.model_signal_interpretation', 'model_signal_interpretation_contract_id'),
    'model_signal_residual_conditions': ('digital_twin.modules.model_registry.domain.model_signal_interpretation', 'model_signal_residual_conditions'),
    'normalize_rule_change_candidate': ('digital_twin.modules.model_registry.domain.ontology_rulebox_governance', 'normalize_rule_change_candidate'),
    'parse_ai_prompt_templates_text': ('digital_twin.modules.model_registry.domain.ontology_relation_settings', 'parse_ai_prompt_templates_text'),
    'parse_relation_rule_definitions_text': ('digital_twin.modules.model_registry.domain.ontology_relation_settings', 'parse_relation_rule_definitions_text'),
    'parse_timestamp': ('digital_twin.modules.model_registry.domain.hypothesis_lifecycle', 'parse_timestamp'),
    'position_intent_label': ('digital_twin.modules.model_registry.domain.investment_ubiquitous_language', 'position_intent_label'),
    'position_intent_sentence': ('digital_twin.modules.model_registry.domain.investment_ubiquitous_language', 'position_intent_sentence'),
    'prompt_template': ('digital_twin.modules.model_registry.domain.ontology_relation_settings', 'prompt_template'),
    'prompt_template_for_message_type': ('digital_twin.modules.model_registry.domain.ontology_relation_settings', 'prompt_template_for_message_type'),
    'prompt_templates_from_settings': ('digital_twin.modules.model_registry.domain.ontology_relation_settings', 'prompt_templates_from_settings'),
    'record_for_absent_snapshot': ('digital_twin.modules.model_registry.domain.hypothesis_lifecycle', 'record_for_absent_snapshot'),
    'record_for_snapshot': ('digital_twin.modules.model_registry.domain.hypothesis_lifecycle', 'record_for_snapshot'),
    'relation_definitions_payload': ('digital_twin.modules.model_registry.domain.ontology_tbox', 'relation_definitions_payload'),
    'relation_lifecycle_transition_contract': ('digital_twin.modules.model_registry.domain.hypothesis_lifecycle', 'relation_lifecycle_transition_contract'),
    'relation_rule_definitions_from_settings': ('digital_twin.modules.model_registry.domain.ontology_relation_settings', 'relation_rule_definitions_from_settings'),
    'relation_thresholds_from_settings': ('digital_twin.modules.model_registry.domain.ontology_relation_settings', 'relation_thresholds_from_settings'),
    'resolved_rule_claim_contract': ('digital_twin.modules.model_registry.domain.rule_claim_contract', 'resolved_rule_claim_contract'),
    'resolved_rule_knowledge_basis': ('digital_twin.modules.model_registry.domain.ontology_rule_knowledge', 'resolved_rule_knowledge_basis'),
    'rule_assessment_scope': ('digital_twin.modules.model_registry.domain.ontology_rule_manifest', 'rule_assessment_scope'),
    'rule_claim_coverage': ('digital_twin.modules.model_registry.domain.rule_claim_contract', 'rule_claim_coverage'),
    'rule_definitions_payload': ('digital_twin.modules.model_registry.domain.ontology_tbox', 'rule_definitions_payload'),
    'rule_dependency_reverse_index': ('digital_twin.modules.model_registry.domain.ontology_rule_manifest', 'rule_dependency_reverse_index'),
    'rule_domain_manifest': ('digital_twin.modules.model_registry.domain.ontology_rule_manifest', 'rule_domain_manifest'),
    'rule_execution_profile': ('digital_twin.modules.model_registry.domain.ontology_rule_execution_policy', 'rule_execution_profile'),
    'rule_knowledge_basis_from_rows': ('digital_twin.modules.model_registry.domain.ontology_rule_knowledge', 'rule_knowledge_basis_from_rows'),
    'rulebox_governance_candidates': ('digital_twin.modules.model_registry.domain.ontology_rulebox_governance', 'rulebox_governance_candidates'),
    'rulebox_rules_hash': ('digital_twin.modules.model_registry.domain.ontology_rulebox_governance', 'rulebox_rules_hash'),
    'rulebox_version_payload': ('digital_twin.modules.model_registry.domain.ontology_rulebox_governance', 'rulebox_version_payload'),
    'score_flow_feature_snapshot': ('digital_twin.modules.model_registry.domain.statistical_signals.flow_scoring', 'score_flow_feature_snapshot'),
    'score_graph_hypothesis_contracts': ('digital_twin.modules.model_registry.domain.statistical_signals.graph_scoring', 'score_graph_hypothesis_contracts'),
    'score_temporal_feature_snapshot': ('digital_twin.modules.model_registry.domain.statistical_signals.scoring', 'score_temporal_feature_snapshot'),
    'snapshot_expiry_reason': ('digital_twin.modules.model_registry.domain.hypothesis_lifecycle', 'snapshot_expiry_reason'),
    'tbox_class_def': ('digital_twin.modules.model_registry.domain.ontology_tbox', 'tbox_class_def'),
    'tbox_class_materialization_policy': ('digital_twin.modules.model_registry.domain.ontology_tbox', 'tbox_class_materialization_policy'),
    'tbox_domain_validation': ('digital_twin.modules.model_registry.domain.ontology_domain_tbox', 'tbox_domain_validation'),
    'tbox_materialization_box': ('digital_twin.modules.model_registry.domain.ontology_tbox', 'tbox_materialization_box'),
    'tbox_relation_def': ('digital_twin.modules.model_registry.domain.ontology_tbox', 'tbox_relation_def'),
    'tbox_relation_materialization_policy': ('digital_twin.modules.model_registry.domain.ontology_tbox', 'tbox_relation_materialization_policy'),
    'user_facing_investment_language': ('digital_twin.modules.model_registry.domain.investment_ubiquitous_language', 'user_facing_investment_language'),
})

_EXPORTS['rulebox_semantic_violations'] = ('digital_twin.modules.model_registry.domain.ontology_rulebox_governance', 'rulebox_semantic_violations')
_EXPORTS['validate_evolution_plan'] = ('digital_twin.modules.model_registry.domain.ontology_evolution', 'validate_plan')
_EXPORTS['evolution_fingerprint'] = ('digital_twin.modules.model_registry.domain.ontology_evolution', 'fingerprint')

__all__ = list(_EXPORTS)


def __getattr__(name):
    return resolve_export(__name__, _EXPORTS, name)
